import type { Permission, Role } from '@/domain/security';

const all: Permission[] = [
  'organization.read', 'organization.manage',
  'people.read.directory', 'people.read.private', 'people.manage',
  'positions.read', 'positions.manage',
  'workflow.read', 'workflow.manage', 'workflow.run', 'workflow.act',
  'audit.read', 'audit.export',
  'membership.read', 'membership.invite', 'membership.manage',
  'self.read', 'self.update', 'team.read', 'team.manage',
  'automation.read', 'automation.run', 'notifications.read', 'notifications.manage', 'security.manage',
  'recruiting.read', 'recruiting.manage', 'recruiting.manage.team', 'recruiting.approve', 'recruiting.interview', 'recruiting.offer', 'recruiting.hire',
  'onboarding.read', 'onboarding.manage', 'onboarding.manage.team', 'onboarding.activate',
  'documents.read', 'documents.manage', 'documents.dispose',
  'policies.read', 'policies.manage', 'policies.approve',
  'compliance.read', 'compliance.manage', 'retention.manage',
  'leave.read', 'leave.request', 'leave.approve', 'leave.manage',
  'time.read', 'time.clock', 'time.manage', 'time.manage.team', 'time.approve', 'time.configure', 'payroll.export', 'expense.read', 'expense.request', 'expense.approve', 'expense.manage',
  'separation.read', 'separation.request', 'separation.manage', 'separation.approve', 'separation.close', 'separation.analytics',
  'performance.read', 'performance.manage', 'performance.review', 'performance.calibrate', 'performance.pip', 'performance.pip.team',
  'learning.read', 'learning.manage', 'learning.assign', 'learning.verify', 'learning.verify.team', 'learning.self_assign',
  'career.read', 'career.manage', 'succession.read', 'succession.manage', 'talent.calibrate',
  'compensation.read', 'compensation.manage', 'compensation.approve', 'jobarchitecture.manage', 'payequity.review',
  'er.intake', 'er.read', 'er.manage', 'er.investigate', 'er.findings', 'er.accommodation', 'er.legal_hold', 'er.analytics',
  'safety.report', 'safety.read', 'safety.manage', 'safety.investigate', 'safety.rtw', 'safety.committee', 'safety.analytics',
  'experience.read', 'experience.survey', 'experience.manage', 'service.read', 'service.request', 'service.manage', 'recognition.send', 'recognition.manage',
  'workforce.read', 'workforce.manage', 'workforce.approve', 'peopleanalytics.read', 'peopleanalytics.manage', 'peopleanalytics.approve',
  'ai.use', 'ai.manage', 'ai.approve', 'ai.audit',
  'diagnostic.read', 'diagnostic.manage', 'diagnostic.approve',
  'governance.read', 'governance.manage', 'governance.approve', 'governance.audit',
  'regulatory.read', 'regulatory.manage', 'regulatory.approve', 'regulatory.audit',
  'assurance.read', 'assurance.manage', 'assurance.approve', 'assurance.audit',
  'privacy.read', 'privacy.manage', 'privacy.approve', 'privacy.audit',
  'resilience.read', 'resilience.manage', 'resilience.approve', 'resilience.audit', 'resilience.incident',
  'strategy.read', 'strategy.manage', 'strategy.approve', 'strategy.audit',
  'orgdesign.read', 'orgdesign.manage', 'orgdesign.approve', 'orgdesign.audit',
  'commandcenter.read', 'commandcenter.manage', 'commandcenter.approve', 'commandcenter.audit',
  'integration.read', 'integration.manage', 'integration.approve', 'integration.audit',
  'identity.read', 'identity.manage', 'identity.approve', 'identity.audit',
  'securityops.read', 'securityops.manage', 'securityops.approve', 'securityops.audit',
  'platform.read', 'platform.manage', 'platform.approve', 'platform.audit',
];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  super_admin: all,
  org_admin: all,
  hr_admin: all,
  hr_partner: [
    'organization.read', 'people.read.directory', 'people.read.private', 'people.manage',
    'positions.read', 'positions.manage', 'workflow.read', 'workflow.run', 'workflow.act',
    'audit.read', 'audit.export', 'membership.read', 'membership.invite',
    'self.read', 'self.update', 'team.read', 'team.manage', 'notifications.read',
    'recruiting.read', 'recruiting.manage', 'recruiting.interview', 'recruiting.offer',
    'onboarding.read', 'onboarding.manage',
    'documents.read', 'documents.manage', 'policies.read', 'policies.manage',
    'compliance.read', 'compliance.manage',
    'leave.read', 'leave.request', 'leave.approve', 'leave.manage',
    'time.read', 'time.clock', 'time.manage', 'time.approve', 'expense.read', 'expense.request', 'expense.approve', 'expense.manage',
    'separation.read', 'separation.request', 'separation.manage', 'separation.analytics',
    'performance.read', 'performance.manage', 'performance.review', 'performance.pip',
    'learning.read', 'learning.manage', 'learning.assign', 'learning.verify', 'learning.self_assign',
    'career.read', 'career.manage', 'succession.read', 'succession.manage',
    'compensation.read', 'compensation.manage',
    'er.intake', 'er.read', 'er.manage', 'er.investigate', 'er.accommodation', 'er.analytics',
    'safety.report', 'safety.read', 'safety.manage', 'safety.investigate', 'safety.rtw', 'safety.committee', 'safety.analytics',
    'experience.read', 'experience.survey', 'service.read', 'service.request', 'service.manage', 'recognition.send', 'recognition.manage',
    'workforce.read', 'workforce.manage', 'peopleanalytics.read', 'peopleanalytics.manage',
    'ai.use', 'ai.manage', 'ai.audit',
    'diagnostic.read', 'diagnostic.manage',
    'governance.read', 'governance.manage', 'governance.audit',
    'regulatory.read', 'regulatory.manage', 'regulatory.audit',
    'assurance.read', 'assurance.manage', 'assurance.audit',
    'privacy.read', 'privacy.manage', 'privacy.audit',
    'resilience.read', 'resilience.manage', 'resilience.audit', 'resilience.incident',
    'strategy.read', 'strategy.manage', 'strategy.audit',
    'orgdesign.read', 'orgdesign.manage', 'orgdesign.audit',
    'commandcenter.read', 'commandcenter.manage', 'commandcenter.audit',
    'integration.read', 'integration.manage', 'integration.audit',
    'identity.read', 'identity.manage', 'identity.audit',
    'securityops.read', 'securityops.manage', 'securityops.audit',
    'platform.read', 'platform.manage', 'platform.audit',
  ],
  manager: [
    'organization.read', 'people.read.directory', 'positions.read', 'workflow.read',
    'workflow.run', 'workflow.act', 'self.read', 'self.update', 'team.read', 'team.manage', 'notifications.read',
    'recruiting.read', 'recruiting.manage.team', 'recruiting.interview',
    'onboarding.read', 'onboarding.manage.team',
    'documents.read', 'policies.read', 'compliance.read',
    'leave.read', 'leave.request', 'leave.approve',
    'time.read', 'time.clock', 'time.manage.team', 'time.approve', 'expense.read', 'expense.request', 'expense.approve',
    'separation.read', 'separation.request',
    'performance.read', 'performance.review', 'performance.pip.team',
    'learning.read', 'learning.assign', 'learning.verify.team', 'learning.self_assign',
    'career.read', 'compensation.read', 'er.intake',
    'safety.report', 'safety.read',
    'experience.read', 'service.read', 'service.request', 'recognition.send',
    'resilience.read', 'resilience.incident',
    'ai.use',
  ],
  employee: [
    'organization.read', 'people.read.directory', 'positions.read', 'self.read', 'self.update', 'notifications.read',
    'documents.read', 'policies.read', 'compliance.read',
    'leave.read', 'leave.request', 'time.read', 'time.clock', 'expense.read', 'expense.request',
    'separation.read', 'separation.request',
    'performance.read', 'performance.review',
    'learning.read', 'learning.self_assign',
    'career.read', 'compensation.read', 'er.intake',
    'safety.report',
    'experience.read', 'service.read', 'service.request', 'recognition.send',
  ],
};

export function permissionsForRole(role: Role): Permission[] {
  return ROLE_PERMISSIONS[role] ?? [];
}

export function can(role: Role, permission: Permission): boolean {
  return permissionsForRole(role).includes(permission);
}
