import { createHash, randomUUID } from 'node:crypto';
import type { ActorContext } from '@/domain/security';
import type { GovernanceControl } from '@/domain/governance';
import type { Policy, PolicyAcknowledgement, PolicyVersion } from '@/domain/compliance';
import type { Membership } from '@/domain/security';
import type { Worker } from '@/domain/hr';
import type { LegalReviewQueueItem, PolicyImpactAssessment, PolicyReattestationCampaign, RegulatoryChange, RegulatoryDashboard, RegulatoryObligation, RegulatorySource, RegulatorySourceType } from '@/domain/regulatory';
import { adminDb } from '@/lib/firebase/admin';
import { ApiError } from '@/lib/http/errors';
import { buildAudit } from '@/lib/audit/service';
import { buildDomainEvent } from '@/lib/events/build';
import { systemActor } from '@/lib/automation/system-actor';
import { fetchRegulatorySnapshot, validateRegulatorySourceUrl } from './monitor';
import { legalReviewActionSchema, legalReviewCreateSchema, policyImpactActionSchema, policyImpactCreateSchema, policyImpactRevisionSchema, reattestationCampaignActionSchema, reattestationCampaignCreateSchema, regulatoryChangeActionSchema, regulatoryChangeCreateSchema, regulatoryObligationActionSchema, regulatoryObligationCreateSchema, regulatorySourceActionSchema, regulatorySourceCreateSchema } from './schemas';

const now=()=>new Date().toISOString();
const today=()=>now().slice(0,10);
const hash=(v:string)=>createHash('sha256').update(v).digest('hex');
const addDays=(date:string,days:number)=>{const d=new Date(`${date.slice(0,10)}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);};
const requireRead=(a:ActorContext)=>{if(!a.permissions.includes('regulatory.read'))throw new ApiError(403,'Regulatory change read permission required.','forbidden');};
const requireManage=(a:ActorContext)=>{if(!a.permissions.includes('regulatory.manage'))throw new ApiError(403,'Regulatory change management permission required.','forbidden');};
const requireApprove=(a:ActorContext)=>{if(!a.permissions.includes('regulatory.approve'))throw new ApiError(403,'Regulatory change approval permission required.','forbidden');};
async function all<T>(orgId:string,name:string,limit=1000){const s=await adminDb().collection(`organizations/${orgId}/${name}`).limit(limit).get();return s.docs.map(d=>d.data() as T);}
async function getRecord<T>(orgId:string,name:string,id:string,label:string){const s=await adminDb().doc(`organizations/${orgId}/${name}/${id}`).get();if(!s.exists)throw new ApiError(404,`${label} not found.`,`${name}_not_found`);return s.data() as T;}
function inferredSourceType(url:string):RegulatorySourceType{const h=new URL(url).hostname.toLowerCase();if(h.endsWith('ontario.ca')||h.endsWith('canada.ca'))return 'government_guidance';if(h.includes('payequity')||h.includes('priv.gc.ca'))return 'regulator_guidance';return 'other';}
function authorityFromUrl(url:string){return new URL(url).hostname.replace(/^www\./,'');}
async function addAudit(actor:ActorContext,action:string,entityType:string,entityId:string,before:unknown,after:unknown){const a=buildAudit(actor,{action,entityType,entityId,before,after});await adminDb().doc(`organizations/${actor.orgId}/auditLogs/${a.id}`).create(a);}
async function queueLegalReview(actor:ActorContext,input:{entityType:LegalReviewQueueItem['entityType'];entityId:string;title:string;reason:string;sourceUrl?:string;priority:LegalReviewQueueItem['priority'];dueDate:string},batch?:any){
  const db=adminDb();const existing=await db.collection(`organizations/${actor.orgId}/legalReviewQueue`).where('entityId','==',input.entityId).limit(20).get();const openExisting=existing.docs.map(d=>d.data() as LegalReviewQueueItem).find(r=>r.entityType===input.entityType&&['open','in_review','returned'].includes(r.status));if(openExisting)return openExisting;
  const ts=now(),id=randomUUID(),record:LegalReviewQueueItem={id,...input,status:'open',createdBy:actor.uid,createdAt:ts,updatedAt:ts};const audit=buildAudit(actor,{action:'regulatory.legal_review.create',entityType:'legalReviewQueueItem',entityId:id,after:record});
  if(batch){batch.create(db.doc(`organizations/${actor.orgId}/legalReviewQueue/${id}`),record);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);}else{const b=db.batch();b.create(db.doc(`organizations/${actor.orgId}/legalReviewQueue/${id}`),record);b.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await b.commit();}return record;
}

export async function createRegulatorySource(actor:ActorContext,raw:unknown){
  requireManage(actor);const input=regulatorySourceCreateSchema.parse(raw);await validateRegulatorySourceUrl(input.sourceUrl);const db=adminDb(),dupe=await db.collection(`organizations/${actor.orgId}/regulatorySources`).where('code','==',input.code).limit(1).get();if(!dupe.empty)throw new ApiError(409,'Regulatory source code already exists.','regulatory_source_code_exists');const byUrl=await db.collection(`organizations/${actor.orgId}/regulatorySources`).where('sourceUrl','==',input.sourceUrl).limit(1).get();if(!byUrl.empty)throw new ApiError(409,'This regulatory source URL is already registered.','regulatory_source_url_exists');
  const ts=now(),id=randomUUID(),review=input.lastReviewedAt||today(),record:RegulatorySource={id,...input,status:'active',lastReviewedAt:input.lastReviewedAt,nextReviewDate:addDays(review,input.reviewCadenceDays),nextCheckDate:today(),changePending:false,legalConclusionProhibited:true,createdBy:actor.uid,createdAt:ts,updatedBy:actor.uid,updatedAt:ts};const audit=buildAudit(actor,{action:'regulatory.source.create',entityType:'regulatorySource',entityId:id,after:record}),batch=db.batch();batch.create(db.doc(`organizations/${actor.orgId}/regulatorySources/${id}`),record);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return record;
}

export async function actOnRegulatorySource(actor:ActorContext,id:string,raw:unknown){
  requireManage(actor);const input=regulatorySourceActionSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/regulatorySources/${id}`),before=await getRecord<RegulatorySource>(actor.orgId,'regulatorySources',id,'Regulatory source'),ts=now();let after:RegulatorySource={...before,updatedBy:actor.uid,updatedAt:ts};
  if(input.action==='pause'){after={...after,status:'paused'};}
  if(input.action==='resume'){after={...after,status:'active',nextCheckDate:today()};}
  if(input.action==='retire'){requireApprove(actor);after={...after,status:'retired'};}
  if(input.action==='record_review'){after={...after,lastReviewedAt:input.reviewDate,nextReviewDate:addDays(input.reviewDate,before.reviewCadenceDays),lastReviewNote:input.reviewNote};}
  if(input.action==='accept_observed'){requireApprove(actor);if(!before.changePending)throw new ApiError(409,'No pending source-change signal requires snapshot acceptance.','regulatory_source_no_pending_change');if(!before.observedFingerprint)throw new ApiError(409,'No observed source snapshot is waiting for acceptance.','regulatory_source_no_observed_snapshot');after={...after,lastReviewedAt:input.reviewDate,nextReviewDate:addDays(input.reviewDate,before.reviewCadenceDays),currentFingerprint:before.observedFingerprint,changePending:false,lastReviewNote:input.reviewNote};}
  const audit=buildAudit(actor,{action:`regulatory.source.${input.action}`,entityType:'regulatorySource',entityId:id,before,after}),batch=db.batch();batch.set(ref,after);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return after;
}

export async function checkRegulatorySource(actor:ActorContext,id:string){
  requireManage(actor);const source=await getRecord<RegulatorySource>(actor.orgId,'regulatorySources',id,'Regulatory source');if(source.status!=='active')throw new ApiError(409,'Only active regulatory sources can be checked.','regulatory_source_inactive');const db=adminDb(),ts=now();
  try{
    const snap=await fetchRegulatorySnapshot(source.sourceUrl),snapshotId=randomUUID(),snapshot={id:snapshotId,sourceId:source.id,sourceCode:source.code,url:snap.url,fingerprint:snap.fingerprint,etag:snap.etag,lastModified:snap.lastModified,bytes:snap.bytes,checkedAt:snap.checkedAt,checkedBy:actor.uid};
    const baseline=source.currentFingerprint||snap.fingerprint,changed=Boolean(source.currentFingerprint&&source.currentFingerprint!==snap.fingerprint),patch:Partial<RegulatorySource>={lastCheckedAt:ts,lastCheckStatus:changed?'changed':'ok',observedFingerprint:snap.fingerprint,observedAt:ts,nextCheckDate:addDays(today(),source.monitorCadenceDays),updatedBy:actor.uid,updatedAt:ts};if(!source.currentFingerprint)Object.assign(patch,{currentFingerprint:snap.fingerprint,changePending:false});
    const batch=db.batch();batch.create(db.doc(`organizations/${actor.orgId}/regulatorySourceSnapshots/${snapshotId}`),snapshot);batch.set(db.doc(`organizations/${actor.orgId}/regulatorySources/${source.id}`),patch,{merge:true});
    let change:RegulatoryChange|undefined;
    if(changed){const dedupe=hash(`${source.id}:${snap.fingerprint}`),changeRef=db.doc(`organizations/${actor.orgId}/regulatoryChanges/${dedupe}`),exists=await changeRef.get();Object.assign(patch,{changePending:true});batch.set(db.doc(`organizations/${actor.orgId}/regulatorySources/${source.id}`),{changePending:true},{merge:true});if(!exists.exists){change={id:dedupe,sourceId:source.id,sourceCode:source.code,title:`Potential source change detected — ${source.title}`,changeType:'source_content_changed',materiality:'medium',summary:'Automated monitoring detected a source-content fingerprint change. This is a change signal only; a qualified human must review the source, determine legal significance and assess organizational applicability.',sourceUrl:snap.url,detectedAt:ts,status:'new',legalReviewRequired:true,affectedPolicyIds:[],affectedControlIds:source.linkedGovernanceControlIds,priorFingerprint:baseline,observedFingerprint:snap.fingerprint,createdBy:'system:regulatory-source-monitor',createdAt:ts,updatedAt:ts};batch.create(changeRef,change);const event=buildDomainEvent(systemActor(actor.orgId,'system:regulatory-source-monitor'),'regulatory.change_detected' as any,'regulatoryChange',change.id,{sourceId:source.id,sourceCode:source.code});batch.create(db.doc(`organizations/${actor.orgId}/domainEvents/${event.id}`),event);}}
    const audit=buildAudit(actor,{action:'regulatory.source.check',entityType:'regulatorySource',entityId:source.id,before:source,after:{...source,...patch,changeCreated:Boolean(change)}});batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return{source:{...source,...patch},changed,change:change||null,snapshot:{...snapshot,fingerprint:snapshot.fingerprint.slice(0,16)+'…'}};
  }catch(error){const message=error instanceof Error?error.message:'Regulatory source check failed.';await db.doc(`organizations/${actor.orgId}/regulatorySources/${source.id}`).set({lastCheckedAt:ts,lastCheckStatus:'unreachable',nextCheckDate:addDays(today(),source.monitorCadenceDays),updatedBy:actor.uid,updatedAt:ts},{merge:true});await addAudit(actor,'regulatory.source.check_failed','regulatorySource',source.id,source,{error:message});throw new ApiError(502,message,'regulatory_source_check_failed');}
}

export async function bootstrapRegulatorySources(actor:ActorContext){
  requireApprove(actor);const db=adminDb(),controls=(await all<GovernanceControl>(actor.orgId,'governanceControls')).filter(c=>c.status==='active'&&c.sourceUrl);const groups=new Map<string,GovernanceControl[]>();for(const c of controls){const key=c.sourceUrl!;groups.set(key,[...(groups.get(key)||[]),c]);}let created=0,updated=0;const ts=now();
  for(const [url,rows] of groups){try{await validateRegulatorySourceUrl(url);}catch{continue;}const id=`src_${hash(url).slice(0,28)}`,ref=db.doc(`organizations/${actor.orgId}/regulatorySources/${id}`),existing=await ref.get(),linked=[...new Set(rows.map(r=>r.id))];if(existing.exists){const before=existing.data() as RegulatorySource,merged=[...new Set([...(before.linkedGovernanceControlIds||[]),...linked])];if(merged.length!==before.linkedGovernanceControlIds.length){await ref.set({linkedGovernanceControlIds:merged,updatedBy:actor.uid,updatedAt:ts},{merge:true});updated++;}continue;}const first=rows[0],review=first.sourceReviewedAt||today(),record:RegulatorySource={id,code:`SRC.${hash(url).slice(0,12).toUpperCase()}`,jurisdiction:first.jurisdiction,authority:authorityFromUrl(url),title:first.sourceTitle,sourceUrl:url,sourceType:inferredSourceType(url),ownerRole:first.accountableRole||'hr_admin',status:'active',reviewCadenceDays:90,monitorCadenceDays:1,lastReviewedAt:review,nextReviewDate:addDays(review,90),nextCheckDate:today(),changePending:false,legalConclusionProhibited:true,linkedGovernanceControlIds:linked,createdBy:'system:v2.4-regulatory-bootstrap',createdAt:ts,updatedBy:actor.uid,updatedAt:ts};await ref.create(record);created++;}
  await addAudit(actor,'regulatory.bootstrap','regulatoryChangeCenter','v2.4',undefined,{created,updated,eligibleGovernanceSources:groups.size});return{created,updated,eligibleGovernanceSources:groups.size};
}

export async function createRegulatoryChange(actor:ActorContext,raw:unknown){
  requireManage(actor);const input=regulatoryChangeCreateSchema.parse(raw),source=await getRecord<RegulatorySource>(actor.orgId,'regulatorySources',input.sourceId,'Regulatory source'),db=adminDb(),ts=now(),id=randomUUID(),record:RegulatoryChange={id,...input,sourceCode:source.code,sourceUrl:source.sourceUrl,detectedAt:ts,status:'new',createdBy:actor.uid,createdAt:ts,updatedAt:ts};const audit=buildAudit(actor,{action:'regulatory.change.create',entityType:'regulatoryChange',entityId:id,after:record}),batch=db.batch();batch.create(db.doc(`organizations/${actor.orgId}/regulatoryChanges/${id}`),record);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return record;
}

export async function actOnRegulatoryChange(actor:ActorContext,id:string,raw:unknown){
  requireManage(actor);const input=regulatoryChangeActionSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/regulatoryChanges/${id}`),before=await getRecord<RegulatoryChange>(actor.orgId,'regulatoryChanges',id,'Regulatory change'),ts=now();let after:RegulatoryChange={...before,updatedAt:ts};
  if(input.action==='triage'){if(!['new','triaged'].includes(before.status))throw new ApiError(409,'Change cannot be triaged from its current state.','invalid_regulatory_change_state');after={...after,status:'triaged',materiality:input.materiality,triageNote:input.triageNote,legalReviewRequired:input.legalReviewRequired,affectedPolicyIds:input.affectedPolicyIds,affectedControlIds:input.affectedControlIds,triagedBy:actor.uid,triagedAt:ts};}
  if(input.action==='start_impact_assessment'){if(!['triaged','legal_review'].includes(before.status))throw new ApiError(409,'Triage is required before impact assessment.','invalid_regulatory_change_state');after={...after,status:'impact_assessing'};}
  let legal:LegalReviewQueueItem|undefined;
  if(input.action==='send_legal_review'){if(['implemented','closed','no_action_required'].includes(before.status))throw new ApiError(409,'Closed/implemented changes cannot enter legal review.','invalid_regulatory_change_state');after={...after,status:'legal_review',legalReviewRequired:true};legal=await queueLegalReview(actor,{entityType:'regulatory_change',entityId:id,title:`Legal review — ${before.title}`,reason:input.reason,sourceUrl:before.sourceUrl,priority:before.materiality,dueDate:input.dueDate});}
  if(input.action==='plan_implementation'){if(!['triaged','impact_assessing','legal_review'].includes(before.status))throw new ApiError(409,'Change must be triaged before implementation planning.','invalid_regulatory_change_state');after={...after,status:'implementation_planned'};}
  if(input.action==='mark_implemented'){requireApprove(actor);if(before.createdBy===actor.uid)throw new ApiError(409,'Implementation closure requires an independent approver.','regulatory_change_self_approval');if(before.status!=='implementation_planned')throw new ApiError(409,'Only planned changes can be marked implemented.','invalid_regulatory_change_state');after={...after,status:'implemented'};}
  if(input.action==='no_action'){requireApprove(actor);if(before.createdBy===actor.uid||before.triagedBy===actor.uid)throw new ApiError(409,'No-action disposition requires an independent approver.','regulatory_change_self_approval');after={...after,status:'no_action_required',triageNote:input.triageNote};}
  if(input.action==='close'){requireApprove(actor);if(!['implemented','no_action_required'].includes(before.status))throw new ApiError(409,'Only implemented or approved no-action changes can close.','invalid_regulatory_change_state');after={...after,status:'closed',closedBy:actor.uid,closedAt:ts};}
  if(input.action==='reopen'){requireApprove(actor);if(before.status!=='closed')throw new ApiError(409,'Only closed changes can reopen.','invalid_regulatory_change_state');after={...after,status:'triaged',closedBy:undefined,closedAt:undefined};}
  const audit=buildAudit(actor,{action:`regulatory.change.${input.action}`,entityType:'regulatoryChange',entityId:id,before,after,metadata:legal?{legalReviewId:legal.id}:undefined}),batch=db.batch();batch.set(ref,after);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return after;
}

export async function createRegulatoryObligation(actor:ActorContext,raw:unknown){
  requireManage(actor);const input=regulatoryObligationCreateSchema.parse(raw),source=await getRecord<RegulatorySource>(actor.orgId,'regulatorySources',input.sourceId,'Regulatory source');if(input.changeId)await getRecord<RegulatoryChange>(actor.orgId,'regulatoryChanges',input.changeId,'Regulatory change');const db=adminDb(),dupe=await db.collection(`organizations/${actor.orgId}/regulatoryObligations`).where('code','==',input.code).limit(1).get();if(!dupe.empty)throw new ApiError(409,'Regulatory obligation code already exists.','regulatory_obligation_code_exists');const ts=now(),id=randomUUID(),record:RegulatoryObligation={id,...input,sourceCode:source.code,jurisdiction:source.jurisdiction,legalConclusionProhibited:true,status:'draft',createdBy:actor.uid,createdAt:ts,updatedAt:ts};const audit=buildAudit(actor,{action:'regulatory.obligation.create',entityType:'regulatoryObligation',entityId:id,after:record}),batch=db.batch();batch.create(db.doc(`organizations/${actor.orgId}/regulatoryObligations/${id}`),record);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return record;
}

export async function actOnRegulatoryObligation(actor:ActorContext,id:string,raw:unknown){
  requireManage(actor);const {action}=regulatoryObligationActionSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/regulatoryObligations/${id}`),before=await getRecord<RegulatoryObligation>(actor.orgId,'regulatoryObligations',id,'Regulatory obligation'),ts=now();let after={...before,updatedAt:ts};
  if(action==='submit_review'){if(before.status!=='draft')throw new ApiError(409,'Only draft obligations can enter review.','invalid_regulatory_obligation_state');after={...after,status:'in_review' as const,submittedBy:actor.uid,submittedAt:ts};}
  if(action==='approve'){requireApprove(actor);if(before.status!=='in_review')throw new ApiError(409,'Only obligations in review can be approved.','invalid_regulatory_obligation_state');if(before.createdBy===actor.uid||before.submittedBy===actor.uid)throw new ApiError(409,'Obligation approval requires an independent reviewer.','regulatory_obligation_self_approval');after={...after,status:'approved' as const,approvedBy:actor.uid,approvedAt:ts};}
  if(action==='retire'){requireApprove(actor);if(before.status==='retired')throw new ApiError(409,'Obligation is already retired.','invalid_regulatory_obligation_state');after={...after,status:'retired' as const,retiredBy:actor.uid,retiredAt:ts};}
  if(action==='reopen'){requireApprove(actor);if(before.status!=='retired')throw new ApiError(409,'Only retired obligations can reopen.','invalid_regulatory_obligation_state');after={...after,status:'draft' as const,submittedBy:undefined,submittedAt:undefined,approvedBy:undefined,approvedAt:undefined,retiredBy:undefined,retiredAt:undefined};}
  const audit=buildAudit(actor,{action:`regulatory.obligation.${action}`,entityType:'regulatoryObligation',entityId:id,before,after}),batch=db.batch();batch.set(ref,after);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();if(action==='approve'&&before.legalReviewRequired)await queueLegalReview(actor,{entityType:'regulatory_obligation',entityId:id,title:`Legal applicability review — ${before.code}`,reason:'This approved regulatory obligation is flagged for qualified legal/specialist review before the organization relies on it as an applicability conclusion.',priority:'high',dueDate:addDays(today(),14)});return after;
}

export async function createPolicyImpact(actor:ActorContext,raw:unknown){
  requireManage(actor);const input=policyImpactCreateSchema.parse(raw),change=await getRecord<RegulatoryChange>(actor.orgId,'regulatoryChanges',input.changeId,'Regulatory change'),policy=await getRecord<Policy>(actor.orgId,'policies',input.policyId,'Policy'),db=adminDb(),dupe=await db.collection(`organizations/${actor.orgId}/policyImpactAssessments`).where('changeId','==',change.id).where('policyId','==',policy.id).limit(1).get();if(!dupe.empty)throw new ApiError(409,'A policy impact assessment already exists for this change and policy.','policy_impact_exists');const ts=now(),id=randomUUID(),record:PolicyImpactAssessment={id,...input,policyCode:policy.code,policyTitle:policy.title,currentPublishedVersionId:policy.currentPublishedVersionId,status:'draft',createdBy:actor.uid,createdAt:ts,updatedAt:ts};const audit=buildAudit(actor,{action:'regulatory.policy_impact.create',entityType:'policyImpactAssessment',entityId:id,after:record}),batch=db.batch();batch.create(db.doc(`organizations/${actor.orgId}/policyImpactAssessments/${id}`),record);batch.set(db.doc(`organizations/${actor.orgId}/regulatoryChanges/${change.id}`),{status:'impact_assessing',updatedAt:ts},{merge:true});batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return record;
}

export async function actOnPolicyImpact(actor:ActorContext,id:string,raw:unknown){
  requireManage(actor);const {action}=policyImpactActionSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/policyImpactAssessments/${id}`),before=await getRecord<PolicyImpactAssessment>(actor.orgId,'policyImpactAssessments',id,'Policy impact assessment'),ts=now();let after={...before,updatedAt:ts};
  if(action==='submit_review'){if(before.status!=='draft')throw new ApiError(409,'Only draft policy impacts can enter review.','invalid_policy_impact_state');after={...after,status:'in_review' as const,submittedBy:actor.uid,submittedAt:ts};}
  if(action==='approve'){requireApprove(actor);if(before.status!=='in_review')throw new ApiError(409,'Only policy impacts in review can be approved.','invalid_policy_impact_state');if(before.createdBy===actor.uid||before.submittedBy===actor.uid)throw new ApiError(409,'Policy impact approval requires an independent reviewer.','policy_impact_self_approval');after={...after,status:'approved' as const,approvedBy:actor.uid,approvedAt:ts};}
  if(action==='mark_implemented'){if(before.status!=='approved')throw new ApiError(409,'Only approved policy impacts can be implemented.','invalid_policy_impact_state');after={...after,status:'implemented' as const,implementedBy:actor.uid,implementedAt:ts};}
  if(action==='close'){requireApprove(actor);if(!['implemented','approved'].includes(before.status))throw new ApiError(409,'Policy impact must be approved/implemented before closure.','invalid_policy_impact_state');after={...after,status:'closed' as const};}
  if(action==='reopen'){requireApprove(actor);if(before.status!=='closed')throw new ApiError(409,'Only closed policy impacts can reopen.','invalid_policy_impact_state');after={...after,status:'draft' as const,submittedBy:undefined,submittedAt:undefined,approvedBy:undefined,approvedAt:undefined,implementedBy:undefined,implementedAt:undefined};}
  const audit=buildAudit(actor,{action:`regulatory.policy_impact.${action}`,entityType:'policyImpactAssessment',entityId:id,before,after}),batch=db.batch();batch.set(ref,after);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();if(action==='approve'&&(before.legalReviewRequired||before.recommendedAction==='seek_legal_review'))await queueLegalReview(actor,{entityType:'policy_impact',entityId:id,title:`Policy impact legal review — ${before.policyCode}`,reason:before.rationale,priority:before.impactLevel==='urgent'?'critical':before.impactLevel==='material'?'high':'medium',dueDate:before.dueDate});return after;
}


export async function createPolicyRevisionFromImpact(actor: ActorContext, id: string, raw: unknown) {
  requireManage(actor);
  const input = policyImpactRevisionSchema.parse(raw);
  const db = adminDb();
  const impactRef = db.doc(`organizations/${actor.orgId}/policyImpactAssessments/${id}`);
  const ts = now();
  const versionId = randomUUID();

  return db.runTransaction(async (tx: any) => {
    const impactSnap = await tx.get(impactRef);
    if (!impactSnap.exists) throw new ApiError(404, 'Policy impact assessment not found.', 'policyImpactAssessments_not_found');
    const impact = impactSnap.data() as PolicyImpactAssessment;
    if (impact.status !== 'approved') throw new ApiError(409, 'Policy impact must be independently approved before creating a linked policy revision.', 'policy_impact_not_approved');
    if (impact.recommendedAction !== 'revise_policy') throw new ApiError(409, 'This impact assessment does not require a policy revision.', 'policy_revision_not_recommended');
    if (impact.revisionPolicyVersionId) throw new ApiError(409, 'A linked policy revision already exists for this impact assessment.', 'policy_revision_exists');

    const policyRef = db.doc(`organizations/${actor.orgId}/policies/${impact.policyId}`);
    const policySnap = await tx.get(policyRef);
    if (!policySnap.exists) throw new ApiError(404, 'Policy not found.', 'policy_not_found');
    const policy = policySnap.data() as Policy;
    if (policy.status === 'archived') throw new ApiError(409, 'Archived policies cannot receive new versions.', 'policy_archived');
    if (['draft', 'in_review', 'approved'].includes(policy.status)) throw new ApiError(409, 'Finish the current policy draft lifecycle before creating another revision.', 'policy_version_in_progress');

    const versionNumber = policy.latestVersionNumber + 1;
    const version: PolicyVersion = {
      id: versionId,
      policyId: policy.id,
      versionNumber,
      versionLabel: input.versionLabel,
      content: input.content,
      contentSha256: hash(input.content),
      status: 'draft',
      effectiveDate: input.effectiveDate,
      createdBy: actor.uid,
      createdAt: ts,
    };
    const policyAfter: Policy = { ...policy, latestVersionNumber: versionNumber, status: 'draft', updatedAt: ts };
    const impactAfter: PolicyImpactAssessment = { ...impact, revisionPolicyVersionId: versionId, revisionCreatedAt: ts, updatedAt: ts };
    const policyAudit = buildAudit(actor, {
      action: 'policy.version.create', entityType: 'policy', entityId: policy.id, before: policy,
      after: { ...policyAfter, versionId, contentSha256: version.contentSha256, sourceImpactId: impact.id },
    });
    const impactAudit = buildAudit(actor, {
      action: 'regulatory.policy_impact.create_revision', entityType: 'policyImpactAssessment', entityId: id, before: impact,
      after: { ...impactAfter, revisionContentSha256: version.contentSha256 },
    });

    tx.create(db.doc(`organizations/${actor.orgId}/policyVersions/${versionId}`), version);
    tx.set(policyRef, { latestVersionNumber: versionNumber, status: 'draft', updatedAt: ts }, { merge: true });
    tx.set(impactRef, { revisionPolicyVersionId: versionId, revisionCreatedAt: ts, updatedAt: ts }, { merge: true });
    tx.create(db.doc(`organizations/${actor.orgId}/auditLogs/${policyAudit.id}`), policyAudit);
    tx.create(db.doc(`organizations/${actor.orgId}/auditLogs/${impactAudit.id}`), impactAudit);

    return { impact: impactAfter, policy: policyAfter, version };
  });
}

async function campaignTargets(orgId:string,audience:PolicyReattestationCampaign['audience'],custom:string[]):Promise<string[]>{const db=adminDb(),workers=(await all<Worker>(orgId,'workers',1500)).filter(w=>(w as any).status==='active'),active=new Set<string>(workers.map(w=>(w as any).id as string));if(audience==='all_employees')return [...active];if(audience==='custom'){const unique=[...new Set(custom)];const invalid=unique.filter(id=>!active.has(id));if(invalid.length)throw new ApiError(400,`Campaign includes ${invalid.length} inactive or unknown worker(s).`,'invalid_campaign_worker');return unique;}const memberships=(await all<Membership>(orgId,'memberships',1500)).filter(m=>m.status==='active'&&m.workerId);const roles:Set<string>=audience==='managers'?new Set<string>(['manager']):new Set<string>(['org_admin','hr_admin','hr_partner']);const targetIds:string[]=memberships.filter((m:Membership)=>roles.has(m.role)&&Boolean(m.workerId)&&active.has(m.workerId as string)).map((m:Membership)=>m.workerId as string);return [...new Set<string>(targetIds)];}
async function campaignProgress(orgId:string,c:PolicyReattestationCampaign){const acks=await adminDb().collection(`organizations/${orgId}/policyAcknowledgements`).where('policyVersionId','==',c.policyVersionId).get(),done=new Set(acks.docs.map(d=>(d.data() as PolicyAcknowledgement).workerId)),completed=c.targetWorkerIds.filter(id=>done.has(id)).length,overdue=c.status==='active'&&c.dueDate<today()?c.expectedCount-completed:0;return{completedCount:completed,overdueCount:Math.max(0,overdue)};}

export async function createReattestationCampaign(actor:ActorContext,raw:unknown){
  requireManage(actor);const input=reattestationCampaignCreateSchema.parse(raw),policy=await getRecord<Policy>(actor.orgId,'policies',input.policyId,'Policy');if(!policy.currentPublishedVersionId)throw new ApiError(409,'A re-attestation campaign requires a published policy version.','policy_not_published');const version=await getRecord<PolicyVersion>(actor.orgId,'policyVersions',policy.currentPublishedVersionId,'Policy version'),targets=await campaignTargets(actor.orgId,input.audience,input.targetWorkerIds);if(!targets.length)throw new ApiError(409,'The selected campaign audience contains no active workers.','campaign_empty_audience');const db=adminDb(),ts=now(),id=randomUUID(),record:PolicyReattestationCampaign={id,policyId:policy.id,policyCode:policy.code,policyTitle:policy.title,policyVersionId:version.id,policyVersionLabel:version.versionLabel,contentSha256:version.contentSha256,title:input.title,audience:input.audience,targetWorkerIds:targets,dueDate:input.dueDate,status:'draft',expectedCount:targets.length,completedCount:0,overdueCount:0,createdBy:actor.uid,createdAt:ts,updatedAt:ts};const audit=buildAudit(actor,{action:'regulatory.reattestation.create',entityType:'policyReattestationCampaign',entityId:id,after:{...record,targetWorkerIds:`${targets.length} workers`}}),batch=db.batch();batch.create(db.doc(`organizations/${actor.orgId}/policyReattestationCampaigns/${id}`),record);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return record;
}

export async function actOnReattestationCampaign(actor:ActorContext,id:string,raw:unknown){
  requireManage(actor);const {action}=reattestationCampaignActionSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/policyReattestationCampaigns/${id}`),before=await getRecord<PolicyReattestationCampaign>(actor.orgId,'policyReattestationCampaigns',id,'Re-attestation campaign'),ts=now();let after={...before,updatedAt:ts};
  if(action==='submit_review'){if(before.status!=='draft')throw new ApiError(409,'Only draft campaigns can enter review.','invalid_reattestation_state');after={...after,status:'in_review' as const,submittedBy:actor.uid,submittedAt:ts};}
  if(action==='approve'){requireApprove(actor);if(before.status!=='in_review')throw new ApiError(409,'Only campaigns in review can be approved.','invalid_reattestation_state');if(before.createdBy===actor.uid||before.submittedBy===actor.uid)throw new ApiError(409,'Campaign approval requires an independent reviewer.','reattestation_self_approval');after={...after,status:'approved' as const,approvedBy:actor.uid,approvedAt:ts};}
  if(action==='activate'){requireApprove(actor);if(before.status!=='approved')throw new ApiError(409,'Only approved campaigns can activate.','invalid_reattestation_state');after={...after,status:'active' as const,activatedBy:actor.uid,activatedAt:ts};}
  if(action==='refresh'){const p=await campaignProgress(actor.orgId,before);after={...after,...p};}
  if(action==='close'){requireApprove(actor);const p=await campaignProgress(actor.orgId,before);if(p.completedCount<before.expectedCount)throw new ApiError(409,'Campaign cannot close while required acknowledgements remain outstanding. Use cancel only when closure without completion is intentionally authorized.','reattestation_incomplete');after={...after,...p,status:'closed' as const,closedBy:actor.uid,closedAt:ts};}
  if(action==='cancel'){requireApprove(actor);if(before.status==='closed')throw new ApiError(409,'Closed campaigns cannot be cancelled.','invalid_reattestation_state');after={...after,status:'cancelled' as const};}
  if(action==='reopen'){requireApprove(actor);if(!['closed','cancelled'].includes(before.status))throw new ApiError(409,'Only closed/cancelled campaigns can reopen.','invalid_reattestation_state');after={...after,status:'draft' as const,submittedBy:undefined,submittedAt:undefined,approvedBy:undefined,approvedAt:undefined,activatedBy:undefined,activatedAt:undefined,closedBy:undefined,closedAt:undefined};}
  const audit=buildAudit(actor,{action:`regulatory.reattestation.${action}`,entityType:'policyReattestationCampaign',entityId:id,before:{...before,targetWorkerIds:`${before.targetWorkerIds.length} workers`},after:{...after,targetWorkerIds:`${after.targetWorkerIds.length} workers`}}),batch=db.batch();batch.set(ref,after);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);if(action==='activate'){const ev=buildDomainEvent(actor,'policy.reattestation_started' as any,'policyReattestationCampaign',id,{policyId:before.policyId,policyVersionId:before.policyVersionId,dueDate:before.dueDate,expectedCount:before.expectedCount});batch.create(db.doc(`organizations/${actor.orgId}/domainEvents/${ev.id}`),ev);}await batch.commit();return after;
}

export async function createLegalReview(actor:ActorContext,raw:unknown){requireManage(actor);const input=legalReviewCreateSchema.parse(raw);return queueLegalReview(actor,input);}
export async function actOnLegalReview(actor:ActorContext,id:string,raw:unknown){
  requireManage(actor);const input=legalReviewActionSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/legalReviewQueue/${id}`),before=await getRecord<LegalReviewQueueItem>(actor.orgId,'legalReviewQueue',id,'Legal review item'),ts=now();let after={...before,updatedAt:ts};
  if(input.action==='claim'){if(!['open','returned'].includes(before.status))throw new ApiError(409,'Only open/returned legal review items can be claimed.','invalid_legal_review_state');after={...after,status:'in_review' as const,assignedReviewerUid:actor.uid};}
  if(input.action==='clear'){requireApprove(actor);if(before.status!=='in_review')throw new ApiError(409,'Legal review must be in review before it can be cleared.','invalid_legal_review_state');if(before.createdBy===actor.uid)throw new ApiError(409,'Legal-review clearance requires an independent reviewer.','legal_review_self_clearance');after={...after,status:'cleared' as const,outcomeNote:input.outcomeNote,reviewedBy:actor.uid,reviewedAt:ts};}
  if(input.action==='return'){requireApprove(actor);if(before.status!=='in_review')throw new ApiError(409,'Only items in review can be returned.','invalid_legal_review_state');after={...after,status:'returned' as const,outcomeNote:input.outcomeNote,reviewedBy:actor.uid,reviewedAt:ts};}
  if(input.action==='cancel'){requireApprove(actor);after={...after,status:'cancelled' as const};}
  if(input.action==='reopen'){requireApprove(actor);if(!['cleared','cancelled'].includes(before.status))throw new ApiError(409,'Only cleared/cancelled items can reopen.','invalid_legal_review_state');after={...after,status:'open' as const,assignedReviewerUid:undefined,outcomeNote:undefined,reviewedBy:undefined,reviewedAt:undefined};}
  const audit=buildAudit(actor,{action:`regulatory.legal_review.${input.action}`,entityType:'legalReviewQueueItem',entityId:id,before,after}),batch=db.batch();batch.set(ref,after);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return after;
}

async function notifyOnce(orgId:string,key:string,input:{title:string;message:string;targetRole:string;entityType:string;entityId:string;priority?:string}){const db=adminDb(),ref=db.doc(`organizations/${orgId}/notificationDedupe/${hash(key)}`);try{await ref.create({key,createdAt:now()});const id=randomUUID();await db.doc(`organizations/${orgId}/notifications/${id}`).create({id,type:'regulatory',category:'governance',priority:input.priority||'normal',...input,status:'unread',inAppVisible:true,emailStatus:'disabled',emailAttempts:0,createdAt:now(),updatedAt:now()});return true;}catch{return false;}}

export async function regulatoryDashboard(actor:ActorContext):Promise<RegulatoryDashboard>{
  requireRead(actor);const [sources,changes,obligations,policyImpacts,campaignRows,legalReviews]=await Promise.all([all<RegulatorySource>(actor.orgId,'regulatorySources'),all<RegulatoryChange>(actor.orgId,'regulatoryChanges'),all<RegulatoryObligation>(actor.orgId,'regulatoryObligations'),all<PolicyImpactAssessment>(actor.orgId,'policyImpactAssessments'),all<PolicyReattestationCampaign>(actor.orgId,'policyReattestationCampaigns'),all<LegalReviewQueueItem>(actor.orgId,'legalReviewQueue')]),d=today();const campaigns:PolicyReattestationCampaign[]=[];for(const c of campaignRows){if(c.status==='active'){const p=await campaignProgress(actor.orgId,c);campaigns.push({...c,...p});}else campaigns.push(c);}const openChanges=changes.filter(c=>!['closed','implemented','no_action_required'].includes(c.status));
  const heatmap=['source_monitoring','regulatory_change','obligations','policy_impact','reattestation','legal_review'].map(category=>{if(category==='source_monitoring')return{category,open:sources.filter(s=>s.changePending).length,highCritical:0,overdue:sources.filter(s=>s.status==='active'&&s.nextCheckDate<d).length};if(category==='regulatory_change')return{category,open:openChanges.length,highCritical:openChanges.filter(c=>['high','critical'].includes(c.materiality)).length,overdue:0};if(category==='obligations')return{category,open:obligations.filter(o=>!['approved','retired'].includes(o.status)).length,highCritical:0,overdue:0};if(category==='policy_impact')return{category,open:policyImpacts.filter(p=>!['closed','implemented'].includes(p.status)).length,highCritical:policyImpacts.filter(p=>p.impactLevel==='urgent'&&!['closed','implemented'].includes(p.status)).length,overdue:policyImpacts.filter(p=>!['closed','implemented'].includes(p.status)&&p.dueDate<d).length};if(category==='reattestation')return{category,open:campaigns.filter(c=>c.status==='active').length,highCritical:0,overdue:campaigns.reduce((n,c)=>n+c.overdueCount,0)};return{category,open:legalReviews.filter(l=>['open','in_review','returned'].includes(l.status)).length,highCritical:legalReviews.filter(l=>['open','in_review','returned'].includes(l.status)&&['high','critical'].includes(l.priority)).length,overdue:legalReviews.filter(l=>['open','in_review','returned'].includes(l.status)&&l.dueDate<d).length};});
  return{sources:sources.sort((a,b)=>a.code.localeCompare(b.code)),changes:changes.sort((a,b)=>b.detectedAt.localeCompare(a.detectedAt)),obligations:obligations.sort((a,b)=>a.code.localeCompare(b.code)),policyImpacts:policyImpacts.sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),campaigns:campaigns.sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),legalReviews:legalReviews.sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),metrics:{activeSources:sources.filter(s=>s.status==='active').length,sourceChecksOverdue:sources.filter(s=>s.status==='active'&&s.nextCheckDate<d).length,pendingChangeSignals:sources.filter(s=>s.changePending).length,highCriticalChanges:openChanges.filter(c=>['high','critical'].includes(c.materiality)).length,obligationsAwaitingApproval:obligations.filter(o=>['draft','in_review'].includes(o.status)).length,policyImpactsOpen:policyImpacts.filter(p=>!['closed','implemented'].includes(p.status)).length,campaignsActive:campaigns.filter(c=>c.status==='active').length,reattestationsOverdue:campaigns.reduce((n,c)=>n+c.overdueCount,0),legalReviewsOpen:legalReviews.filter(l=>['open','in_review','returned'].includes(l.status)).length},heatmap,operatingNotice:'Regulatory monitoring produces potential-change signals, not legal conclusions. Source significance, statutory applicability, policy impact and legal sufficiency remain human-reviewed. Automated source fingerprints must never be treated as proof that a legal obligation changed.'};
}

export async function processRegulatoryGovernance(orgId:string){
  const actor=systemActor(orgId,'system:regulatory-governance'),sources=(await all<RegulatorySource>(orgId,'regulatorySources')).filter(s=>s.status==='active'),campaigns=await all<PolicyReattestationCampaign>(orgId,'policyReattestationCampaigns'),legal=await all<LegalReviewQueueItem>(orgId,'legalReviewQueue'),d=today(),summary={sourcesScanned:sources.length,sourcesChecked:0,changesDetected:0,checksFailed:0,reattestationsRefreshed:0,legalReviewsOverdue:0,notifications:0};
  for(const source of sources.filter(s=>s.nextCheckDate<=d)){try{const result=await checkRegulatorySource({...actor,permissions:['regulatory.read','regulatory.manage'] as any},source.id);summary.sourcesChecked++;if(result.changed)summary.changesDetected++;}catch{summary.checksFailed++;if(await notifyOnce(orgId,`regulatory-source-failed:${source.id}:${d}`,{title:'Regulatory source check failed',message:`${source.code} · ${source.title} could not be checked automatically. Human source review is required.`,targetRole:source.ownerRole,entityType:'regulatorySource',entityId:source.id,priority:'high'}))summary.notifications++;}}
  for(const c of campaigns.filter(c=>c.status==='active')){const progress=await campaignProgress(orgId,c);await adminDb().doc(`organizations/${orgId}/policyReattestationCampaigns/${c.id}`).set({...progress,updatedAt:now()},{merge:true});summary.reattestationsRefreshed++;if(progress.overdueCount>0&&await notifyOnce(orgId,`reattestation-overdue:${c.id}:${c.dueDate}`,{title:'Policy re-attestation overdue',message:`${c.policyCode} campaign has ${progress.overdueCount} outstanding acknowledgement(s) after ${c.dueDate}.`,targetRole:'hr_admin',entityType:'policyReattestationCampaign',entityId:c.id,priority:'high'}))summary.notifications++;}
  for(const l of legal.filter(l=>['open','in_review','returned'].includes(l.status)&&l.dueDate<d)){summary.legalReviewsOverdue++;if(await notifyOnce(orgId,`legal-review-overdue:${l.id}:${l.dueDate}`,{title:'Regulatory legal review overdue',message:`${l.title} was due ${l.dueDate}.`,targetRole:'hr_admin',entityType:'legalReviewQueueItem',entityId:l.id,priority:['high','critical'].includes(l.priority)?'high':'normal'}))summary.notifications++;}
  return summary;
}
