import { describe,expect,it } from 'vitest';
import { buildIntegrationProductionUatEvidence } from '@/lib/integration/production-uat';
import type { IntegrationDashboard } from '@/domain/integration';
import type { IntegrationRuntimeDashboard } from '@/domain/integration-runtime';
const now=new Date().toISOString();
const connector={id:'c1',code:'PAY',name:'Payroll',category:'payroll',protocol:'rest_json',direction:'inbound',baseUrl:'https://example.invalid/api',authMode:'api_key',secretRef:'[configured]',ownerRole:'hr_admin',dataClassification:'restricted',systemOfRecordFor:['payroll'],standardProfile:'custom',timeoutMs:1000,maxBatchSize:10,idempotencyRequired:true,reconciliationRequired:true,mutationMode:'staging_only',status:'active',health:'healthy',consequentialWorkerMutationProhibited:true,createdBy:'u1',createdAt:now,updatedAt:now} as const;
const contract={id:'k1',code:'K1',name:'K1',entityType:'worker',direction:'inbound',schemaVersion:'1',schemaDialect:'https://json-schema.org/draft/2020-12/schema',validationProfile:'opsiqo-json-schema-subset-v1',jsonSchema:{type:'object'},fieldMappings:[],standardProfile:'custom',compatibility:'compatible',compatibilityNotes:'',status:'approved',createdBy:'u2',createdAt:now,updatedAt:now} as const;
function fixtures(){const base={connectors:[connector],contracts:[contract],runs:[{id:'r1',connectorId:'c1',contractId:'k1',direction:'inbound',mode:'test',idempotencyHash:'x',correlationId:'x',traceId:'x',status:'succeeded',recordsReceived:1,recordsAccepted:1,recordsRejected:0,reconciliationStatus:'matched',mutationMode:'staging_only',startedBy:'u1',startedAt:now,completedAt:now}],stagingRecords:[],deadLetters:[],reconciliations:[{id:'q1',runId:'r1',connectorId:'c1',contractId:'k1',expectedCount:1,actualCount:1,matchedCount:1,missingCount:0,extraCount:0,fieldMismatchCount:0,variancePct:0,status:'matched',reviewStatus:'resolved',createdBy:'u1',createdAt:now}],events:[],metrics:{approvedConnectors:1,activeConnectors:1,degradedFailingConnectors:0,approvedContracts:1,failedRuns24h:0,successRate30d:100,averageLatencyMs:1,stagedRecords:0,rejectedStagingRecords:0,openDeadLetters:0,reconciliationVariances:0,activeRuntimeProfiles:1,openRuntimeCircuits:0,overdueRuntimeSchedules:0,rejectedWebhookReceipts24h:0,readinessScore:100,readinessLevel:'resilient'},standards:[],operatingNotice:'',generatedAt:now} as unknown as IntegrationDashboard;const runtime={profiles:[{id:'p1',code:'P1',name:'P1',connectorId:'c1',contractId:'k1',adapterKind:'rest_pull',deltaMode:'none',requestMethod:'GET',staticHeaders:{},retryPolicy:{maxAttempts:3,baseDelayMs:100,maxDelayMs:1000,retryOn429:true,retryOn5xx:true},circuitBreaker:{failureThreshold:3,resetAfterMs:1000},status:'active',transportAvailability:'built_in',consequentialWorkerMutationProhibited:true,createdBy:'u1',createdAt:now,updatedAt:now}],schedules:[],states:[{id:'s1',profileId:'p1',connectorId:'c1',circuitStatus:'closed',consecutiveFailures:0,updatedAt:now}],webhookReceipts:[],replayRequests:[],sandboxResults:[{id:'sb1',profileId:'p1',connectorId:'c1',contractId:'k1',status:'passed',endpointValidated:true,secretReferenceValidated:true,mappingValidated:true,contractValidated:true,transportAvailability:'available',issueCodes:[],executedBy:'u1',executedAt:now}],metrics:{activeProfiles:1,activeSchedules:0,openCircuits:0,overdueSchedules:0,webhookReceipts24h:0,rejectedWebhookReceipts24h:0,pendingReplayApprovals:0,sandboxFailures30d:0},operatingNotice:'',generatedAt:now} as IntegrationRuntimeDashboard;return{base,runtime}}
describe('V7.23 production integration UAT evidence',()=>{it('becomes a candidate only with full recorded evidence',()=>{const{base,runtime}=fixtures();const result=buildIntegrationProductionUatEvidence(base,runtime);expect(result.status).toBe('candidate');expect(result.coverage).toBe(100);expect(JSON.stringify(result)).not.toContain('secret-manager/');});it('fails closed when recent test evidence is absent',()=>{const{base,runtime}=fixtures();base.runs=[];const result=buildIntegrationProductionUatEvidence(base,runtime);expect(result.status).toBe('review_required');expect(result.connectors[0]?.checks.find(x=>x.id==='test-run')?.status).toBe('fail');});it('never executes or promotes staged HCM records',()=>{const{base,runtime}=fixtures();const result=buildIntegrationProductionUatEvidence(base,runtime);expect(result.boundary).toContain('performs no external connector execution');expect(result.boundary).toContain('no direct HCM domain mutation');});});
