import type { AutomationMarketplacePack } from '@/domain/opsiqo-one-v7-13';
export const H51_AUTOMATION_PACKS:AutomationMarketplacePack[]=[
 {id:'h51-manager-excellence',version:1,name:'H51 Manager Excellence Pack',category:'Manager',description:'Governed manager follow-up workflows for time, performance, learning and service attention.',operationalBoundary:'Creates disabled workflow definitions. Manager and HR decision rights remain unchanged.',workflows:[
  {name:'H51 · Timesheet review due',description:'Route submitted time evidence to manager review.',trigger:'timesheet.submitted',conditionMode:'all',conditions:[],steps:[{id:'review',name:'Review submitted timesheet',type:'approval',ownerRole:'manager',dueInDays:2,escalationOwnerRole:'hr_admin',escalateAfterHours:12}]},
  {name:'H51 · Performance action overdue',description:'Route overdue governed performance-plan work without determining the employment outcome.',trigger:'performance.pip_overdue',conditionMode:'all',conditions:[],steps:[{id:'review',name:'Review overdue performance-plan action',type:'task',ownerRole:'manager',dueInDays:1,escalationOwnerRole:'hr_admin',escalateAfterHours:8}]},
  {name:'H51 · Certificate expiry manager notice',description:'Notify responsible management of expiring workforce qualifications.',trigger:'learning.certificate_expiring',conditionMode:'all',conditions:[],steps:[{id:'review',name:'Review expiring qualification',type:'task',ownerRole:'manager',dueInDays:5,escalationOwnerRole:'hr_admin',escalateAfterHours:24}]},
 ]},
 {id:'h51-recruiting-operations',version:1,name:'H51 Recruiting Operations Pack',category:'Recruiting',description:'Structured recruiting coordination without autonomous hiring, rejection, ranking or protected-trait scoring.',operationalBoundary:'All candidate decisions remain with authorized humans. The pack only coordinates evidence review and operational tasks.',workflows:[
  {name:'H51 · New application evidence review',description:'Create a recruiter evidence-review task for new applications.',trigger:'application.created',conditionMode:'all',conditions:[],steps:[{id:'review',name:'Review structured candidate evidence',type:'task',ownerRole:'hr_admin',dueInDays:2,escalationOwnerRole:'org_admin',escalateAfterHours:12}]},
  {name:'H51 · ATS review completed follow-up',description:'Route ATS analysis to human recruiter follow-up.',trigger:'recruiting.ats_review_completed',conditionMode:'all',conditions:[],steps:[{id:'review',name:'Human review of ATS evidence',type:'task',ownerRole:'hr_admin',dueInDays:1,escalationOwnerRole:'org_admin',escalateAfterHours:8}]},
  {name:'H51 · Accepted offer onboarding handoff',description:'Coordinate post-acceptance operational handoff.',trigger:'offer.accepted',conditionMode:'all',conditions:[],steps:[{id:'handoff',name:'Prepare onboarding handoff',type:'task',ownerRole:'hr_admin',dueInDays:1,escalationOwnerRole:'org_admin',escalateAfterHours:8}]},
 ]},
 {id:'h51-offboarding-control',version:1,name:'H51 Offboarding Control Pack',category:'Offboarding',description:'Operational offboarding evidence and task coordination after authorized separation decisions.',operationalBoundary:'The pack never initiates or approves termination. It starts only from governed separation events.',workflows:[
  {name:'H51 · Approved separation operational checklist',description:'Coordinate post-approval offboarding tasks.',trigger:'separation.approved',conditionMode:'all',conditions:[],steps:[{id:'review',name:'Review offboarding evidence and task owners',type:'task',ownerRole:'hr_admin',dueInDays:1,escalationOwnerRole:'org_admin',escalateAfterHours:4},{id:'notify',name:'Notify responsible operational owners',type:'notification',ownerRole:'hr_admin',dependsOn:['review']}]},
  {name:'H51 · Separation task overdue',description:'Escalate overdue separation tasks.',trigger:'separation.task_overdue',conditionMode:'all',conditions:[],steps:[{id:'review',name:'Resolve overdue offboarding task',type:'task',ownerRole:'hr_admin',dueInDays:1,escalationOwnerRole:'org_admin',escalateAfterHours:4}]},
 ]},
 {id:'h51-payroll-readiness',version:1,name:'H51 Payroll Readiness Pack',category:'Payroll',description:'Governed payroll readiness and exception follow-up.',operationalBoundary:'Does not calculate, approve, transmit or alter pay without existing authoritative payroll controls.',workflows:[
  {name:'H51 · Payroll readiness review',description:'Route payroll-ready evidence for authorized review/export processing.',trigger:'payroll.ready',conditionMode:'all',conditions:[],steps:[{id:'review',name:'Review payroll readiness evidence',type:'task',ownerRole:'hr_admin',dueInDays:1,escalationOwnerRole:'org_admin',escalateAfterHours:8}]},
  {name:'H51 · Compensation change downstream review',description:'Create downstream review after an already-authorized compensation change.',trigger:'compensation.changed',conditionMode:'all',conditions:[],steps:[{id:'review',name:'Review downstream payroll implications',type:'task',ownerRole:'hr_admin',dueInDays:2,escalationOwnerRole:'org_admin',escalateAfterHours:12}]},
 ]},
 {id:'h51-compliance-assurance',version:1,name:'H51 Compliance Assurance Pack',category:'Compliance',description:'Evidence-first compliance follow-up with explicit human/legal review boundaries.',operationalBoundary:'No legal conclusion is generated or executed. Potential regulatory impacts remain human/legal review items.',workflows:[
  {name:'H51 · Compliance evidence gap escalation',description:'Escalate configured evidence gaps for review.',trigger:'compliance.gap',conditionMode:'all',conditions:[],steps:[{id:'review',name:'Review evidence gap',type:'task',ownerRole:'hr_admin',dueInDays:2,escalationOwnerRole:'org_admin',escalateAfterHours:8}]},
  {name:'H51 · Policy review human checkpoint',description:'Ensure due policy reviews receive a governed human checkpoint.',trigger:'policy.review_due',conditionMode:'all',conditions:[],steps:[{id:'review',name:'Review policy and supporting evidence',type:'approval',ownerRole:'hr_admin',dueInDays:5,escalationOwnerRole:'org_admin',escalateAfterHours:24}]},
 ]},
];
