import type { ActorContext } from '@/domain/security';
import type { AiControlTowerDashboard, TevvEvaluation } from '@/domain/intelligence-control-plane';
import { adminDb } from '@/lib/firebase/admin';
import { ApiError } from '@/lib/http/errors';
import { effectiveAgentPolicies } from '@/lib/opsiqo-one/agent-governance';
import { aiValueDashboard } from '@/lib/opsiqo-one/ai-value';
import { automationPackCatalog } from '@/lib/opsiqo-one/automation-marketplace';
import { listDurableSagas } from '@/lib/orchestrator/durable-saga';
import { aiActivitySummary } from './ai-activity';
import { integrationIntelligence } from './integration-intelligence';

export async function aiControlTower(actor:ActorContext):Promise<AiControlTowerDashboard>{if(!(actor.permissions.includes('ai.audit')||actor.permissions.includes('ai.manage')))throw new ApiError(403,'AI audit or management permission required.','forbidden');const db=adminDb();const [policies,value,customSnap,nextSnap,securitySnap,evalSnap,activities,sagas,integration]=await Promise.all([
 effectiveAgentPolicies(actor),aiValueDashboard(actor,30),db.collection(`organizations/${actor.orgId}/aiAgentDefinitions`).limit(200).get(),db.collection(`organizations/${actor.orgId}/nextBestActions`).limit(500).get(),db.collection(`organizations/${actor.orgId}/agentSecurityEvents`).orderBy('createdAt','desc').limit(500).get(),db.collection(`organizations/${actor.orgId}/aiEvaluationRuns`).orderBy('generatedAt','desc').limit(1).get(),aiActivitySummary(actor,500),listDurableSagas(actor,250).catch(()=>[]),integrationIntelligence(actor).catch(()=>null)
 ]);const next=nextSnap.docs.map(d=>d.data() as Record<string,unknown>),security=securitySnap.docs.map(d=>d.data() as Record<string,unknown>),latest=evalSnap.empty?null:evalSnap.docs[0].data() as TevvEvaluation,activeSagas=sagas.filter((s:any)=>!['completed','cancelled'].includes(s.status)).length,recon=sagas.filter((s:any)=>s.status==='reconciliation_required').length,promptEvents=security.filter(s=>String(s.type||'').includes('prompt_injection')).length,blockedTools=security.filter(s=>String(s.type||'').includes('tool')).length,accessViolations=security.filter(s=>String(s.type||'').includes('access')||String(s.reason||'').includes('PERMISSION')).length;return{generatedAt:new Date().toISOString(),inventory:{totalAgents:policies.length,enabledAgents:policies.filter(p=>p.enabled).length,shadowModeAgents:policies.filter(p=>p.enabled&&p.shadowMode).length,customAgents:customSnap.size,automationPacks:automationPackCatalog().length},governance:{executeCapAgents:policies.filter(p=>p.hardMaxActionLevel==='execute').length,nextActionsAwaitingApproval:next.filter(a=>a.status==='awaiting_approval').length,humanDecisionActions:next.filter(a=>a.autonomyLevel===4).length},security:{promptInjectionEvents:promptEvents,blockedToolCalls:blockedTools,accessViolations},quality:{latestTevvPassed:latest?latest.passed:null,criticalFailures:latest?.criticalFailures||[],averageConfidencePct:value.metrics.averageConfidencePct,evidenceCompletenessPct:value.metrics.averageEvidenceCompletenessPct},operations:{aiRuns:value.metrics.aiRuns,failedRuns:value.metrics.failedRuns,blockedRuns:value.metrics.blockedRuns,activeSagas,reconciliationRequired:recon,completedActions:next.filter(a=>a.status==='completed').length},value:{estimatedHoursSaved:value.estimatedSavings.hours,estimatedCostAvoided:value.estimatedSavings.amount,currency:value.estimatedSavings.currency,status:value.estimatedSavings.status},cost:{trackedTokenCost:activities.tokenCost,trackedMonetaryCost:activities.monetaryCost,status:activities.tokenCost!==null||activities.monetaryCost!==null?'measured':'not_configured'},integration:{readinessScore:integration?.readinessScore??null,exceptions:integration?(integration.failedRuns24h+integration.openDeadLetters+integration.reconciliationVariances):null},notices:['Metrics are evidence-backed. Missing ROI/cost baselines remain Not configured rather than fabricated.','Consequential employment decisions remain human-only and outside autonomous execution.','Control Tower does not grant permissions; it observes governed AI/automation state within the active organization.']};}
