import { createHash } from 'node:crypto';
import type { ActorContext } from '@/domain/security';
import type { LearningCategory, TenantLearningMemory } from '@/domain/intelligence-control-plane';
import { adminDb } from '@/lib/firebase/admin';
import { ApiError } from '@/lib/http/errors';
import { buildAudit } from '@/lib/audit/service';
const ALLOWED=new Set<LearningCategory>(['column_mapping','terminology','template_choice','routing_preference','language_preference','approved_default']);
const FORBIDDEN=/hire|reject|terminat|disciplin|promot|compensation|salary|performance rating|accommodation|medical|protected|race|religion|gender|disability|age|ethnicity/i;
const now=()=>new Date().toISOString(),idFor=(c:string,k:string)=>createHash('sha256').update(`${c}:${k}`).digest('hex').slice(0,28);
export async function proposeTenantLearning(actor:ActorContext,input:{category:LearningCategory;key:string;value:string;evidenceCount:number}){if(!actor.permissions.includes('ai.manage'))throw new ApiError(403,'AI management permission required.','forbidden');if(!ALLOWED.has(input.category)||FORBIDDEN.test(`${input.key} ${input.value}`))throw new ApiError(409,'This learning category is not permitted for tenant adaptive memory.','unsafe_learning_prohibited');const id=idFor(input.category,input.key),ref=adminDb().doc(`organizations/${actor.orgId}/learningMemoryMappings/${id}`),beforeSnap=await ref.get(),before=beforeSnap.exists?beforeSnap.data() as TenantLearningMemory:undefined,row:TenantLearningMemory={id,category:input.category,key:input.key.slice(0,160),value:input.value.slice(0,2000),status:'proposed',evidenceCount:Math.max(1,Math.min(10000,input.evidenceCount)),createdBy:before?.createdBy||actor.uid,createdAt:before?.createdAt||now(),updatedAt:now(),previousValue:before?.status==='approved'?before.value:before?.previousValue};const audit=buildAudit(actor,{action:'intelligence.learning.propose',entityType:'learningMemoryMapping',entityId:id,before,after:row});const batch=adminDb().batch();batch.set(ref,row);batch.create(adminDb().doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return row;}
export async function approveTenantLearning(actor:ActorContext,id:string){if(!actor.permissions.includes('ai.approve'))throw new ApiError(403,'AI approval permission required.','forbidden');const ref=adminDb().doc(`organizations/${actor.orgId}/learningMemoryMappings/${id}`),snap=await ref.get();if(!snap.exists)throw new ApiError(404,'Learning proposal not found.','not_found');const before=snap.data() as TenantLearningMemory;if(before.createdBy===actor.uid)throw new ApiError(409,'Independent approval is required for tenant learning.','independent_approval_required');if(before.status!=='proposed')throw new ApiError(409,'Only proposed learning can be approved.','invalid_state');const row={...before,status:'approved' as const,approvedBy:actor.uid,approvedAt:now(),updatedAt:now()},audit=buildAudit(actor,{action:'intelligence.learning.approve',entityType:'learningMemoryMapping',entityId:id,before,after:row});const batch=adminDb().batch();batch.set(ref,row);batch.create(adminDb().doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return row;}
export async function approvedTenantLearning(actor:ActorContext,category?:LearningCategory){const snap=await adminDb().collection(`organizations/${actor.orgId}/learningMemoryMappings`).limit(500).get();return snap.docs.map(d=>d.data() as TenantLearningMemory).filter(x=>x.status==='approved'&&(!category||x.category===category));}
