'use client';
import { FormEvent,useEffect,useMemo,useState } from 'react';
import { OAuthProvider,SAMLAuthProvider,getRedirectResult,signInWithEmailAndPassword,signInWithRedirect } from 'firebase/auth';
import { firebaseAppCheck, firebaseAuth } from '@/lib/firebase/client';
import { getToken as getAppCheckToken } from 'firebase/app-check';
import { useRouter } from 'next/navigation';

type PublicProvider={name:string;protocol:'oidc'|'saml';firebaseProviderId:string;jitMode:string};
function safeReturnTo(){if(typeof window==='undefined')return'/dashboard';const value=new URLSearchParams(window.location.search).get('returnTo');return value&&value.startsWith('/')&&!value.startsWith('//')?value:'/dashboard'}
function orgContext(){if(typeof window==='undefined')return process.env.NEXT_PUBLIC_OPSIQO_DEFAULT_ORG_ID||'';const v=new URLSearchParams(window.location.search).get('orgId')||process.env.NEXT_PUBLIC_OPSIQO_DEFAULT_ORG_ID||'';return /^[A-Za-z0-9._-]{2,200}$/.test(v)?v:''}
async function jitIfConfigured(user:{getIdToken():Promise<string>},orgId:string){if(!orgId)return{status:'not_configured'};const token=await user.getIdToken();const headers:Record<string,string>={authorization:`Bearer ${token}`};const appCheck=firebaseAppCheck();if(appCheck)headers['x-firebase-appcheck']=(await getAppCheckToken(appCheck,false)).token;const res=await fetch(`/api/identity/jit/${encodeURIComponent(orgId)}`,{method:'POST',headers});const body=await res.json().catch(()=>({})) as{data?:{status?:string;requestId?:string};message?:string};if(!res.ok)throw new Error(body.message||'Identity access evaluation could not be completed.');return body.data||{status:'unknown'}}
export default function SignInPage(){const router=useRouter(),[error,setError]=useState(''),[notice,setNotice]=useState(''),[providers,setProviders]=useState<PublicProvider[]>([]),[checking,setChecking]=useState(true);const orgId=useMemo(()=>orgContext(),[]);useEffect(()=>{let live=true;(async()=>{try{const auth=firebaseAuth(),result=await getRedirectResult(auth);if(result?.user){const jit=await jitIfConfigured(result.user,orgId);if(jit?.status==='approval_required'){if(live)setNotice(`Your identity is verified. Access request ${jit.requestId||''} is awaiting independent approval.`);return}router.push(safeReturnTo());return}if(orgId){const r=await fetch(`/api/identity/providers/public?orgId=${encodeURIComponent(orgId)}`,{cache:'no-store'});if(r.ok){const j=await r.json() as{data?:PublicProvider[]};if(live)setProviders(j.data||[])}}}catch(e){if(live)setError(e instanceof Error?e.message:'SSO completion failed.')}finally{if(live)setChecking(false)}})();return()=>{live=false}},[orgId,router]);if(process.env.NEXT_PUBLIC_OPSIQO_DEMO_MODE==='true')return <div className="card"><h1>Demo mode active</h1><p className="muted">Sign-in is intentionally bypassed for local/demo testing.</p><button className="button" onClick={()=>router.push(safeReturnTo())}>Continue</button></div>;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget);try{const result=await signInWithEmailAndPassword(firebaseAuth(),String(f.get('email')),String(f.get('password')));const jit=await jitIfConfigured(result.user,orgId);if(jit?.status==='approval_required'){setNotice(`Your identity is verified. Access request ${jit.requestId||''} is awaiting independent approval.`);return}router.push(safeReturnTo())}catch(e){setError(e instanceof Error?e.message:'Sign-in failed.')}}
 async function sso(p:PublicProvider){try{setError('');const provider=p.protocol==='saml'?new SAMLAuthProvider(p.firebaseProviderId):new OAuthProvider(p.firebaseProviderId);await signInWithRedirect(firebaseAuth(),provider)}catch(e){setError(e instanceof Error?e.message:'SSO sign-in could not start.')}}
 return <div className="stack" style={{maxWidth:460}}><form className="card stack" onSubmit={submit}><h1>Sign in</h1><label className="field"><span>Email</span><input className="input" name="email" type="email" required/></label><label className="field"><span>Password</span><input className="input" name="password" type="password" required/></label>{error&&<div className="error">{error}</div>}{notice&&<div className="notice">{notice}</div>}<button className="button">Sign in securely</button></form>{!checking&&providers.length>0&&<section className="card stack"><h2 className="sectionTitle">Enterprise SSO</h2>{providers.map(p=><button key={p.firebaseProviderId} className="button secondary" onClick={()=>sso(p)}>Continue with {p.name}</button>)}<p className="muted">Enterprise federation is available only for active, independently approved provider profiles. JIT access remains subject to the organization identity policy.</p></section>}</div>}
