'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { OAuthProvider, SAMLAuthProvider, getRedirectResult, signInAnonymously, signInWithEmailAndPassword, signInWithRedirect } from 'firebase/auth';
import { getToken as getAppCheckToken } from 'firebase/app-check';
import { useRouter } from 'next/navigation';
import { AuthBrand } from '@/components/auth-brand';
import { firebaseAppCheck, firebaseAuth } from '@/lib/firebase/client';
import { setActiveOrgId } from '@/lib/http/client';

type PublicProvider = { name:string; protocol:'oidc'|'saml'; firebaseProviderId:string; jitMode:string };
type Policy={registrationMode:'invite_only'|'open_auth_only'|'disabled';guestAccessEnabled:boolean;allowPasswordSignIn:boolean;allowSelfPasswordReset:boolean};

function safeReturnTo(){const fallback=process.env.NEXT_PUBLIC_OPSIQO_DEMO_MODE==='true'?'/dashboard':'/setup';if(typeof window==='undefined')return fallback;const v=new URLSearchParams(window.location.search).get('returnTo');return v&&v.startsWith('/')&&!v.startsWith('//')?v:fallback}
function orgContext(){if(typeof window==='undefined')return process.env.NEXT_PUBLIC_OPSIQO_DEFAULT_ORG_ID||'';const value=new URLSearchParams(window.location.search).get('orgId')||process.env.NEXT_PUBLIC_OPSIQO_DEFAULT_ORG_ID||process.env.NEXT_PUBLIC_OPSIQO_ORG_ID||'';return /^[A-Za-z0-9._-]{2,200}$/.test(value)?value:''}
async function jitIfConfigured(user:{getIdToken():Promise<string>},orgId:string){if(!orgId)return{status:'not_configured'};const token=await user.getIdToken(),headers:Record<string,string>={authorization:`Bearer ${token}`},appCheck=firebaseAppCheck();if(appCheck)headers['x-firebase-appcheck']=(await getAppCheckToken(appCheck,false)).token;const response=await fetch(`/api/identity/jit/${encodeURIComponent(orgId)}`,{method:'POST',headers});const body=await response.json().catch(()=>({})) as{data?:{status?:string;requestId?:string};message?:string};if(!response.ok)throw new Error(body.message||'Identity access evaluation could not be completed.');return body.data||{status:'unknown'}}

export default function SignInPage(){const router=useRouter(),[error,setError]=useState(''),[notice,setNotice]=useState(''),[providers,setProviders]=useState<PublicProvider[]>([]),[policy,setPolicy]=useState<Policy>({registrationMode:'invite_only',guestAccessEnabled:false,allowPasswordSignIn:true,allowSelfPasswordReset:true}),[checking,setChecking]=useState(true),[busy,setBusy]=useState(false),orgId=useMemo(()=>orgContext(),[]);
useEffect(()=>{let live=true;(async()=>{try{const auth=firebaseAuth(),result=await getRedirectResult(auth);if(result?.user){const jit=await jitIfConfigured(result.user,orgId);if(jit?.status==='approval_required'){if(live)setNotice(`Your identity is verified. Access request ${jit.requestId||''} is awaiting independent approval.`);return}if(orgId)setActiveOrgId(orgId);router.push(safeReturnTo());return}const [providerResponse,policyResponse]=await Promise.all([orgId?fetch(`/api/identity/providers/public?orgId=${encodeURIComponent(orgId)}`,{cache:'no-store'}):Promise.resolve(null),fetch(`/api/public/registration-policy${orgId?`?orgId=${encodeURIComponent(orgId)}`:''}`,{cache:'no-store'})]);if(providerResponse?.ok){const body=await providerResponse.json() as{data?:PublicProvider[]};if(live)setProviders(body.data||[])}if(policyResponse.ok){const body=await policyResponse.json() as{data?:Policy};if(live&&body.data)setPolicy(body.data)}}catch(e){if(live)setError(e instanceof Error?e.message:'Sign-in initialization failed.')}finally{if(live)setChecking(false)}})();return()=>{live=false}},[orgId,router]);
if(process.env.NEXT_PUBLIC_OPSIQO_DEMO_MODE==='true')return <div className="authShell"><section className="authBrandPanel"><AuthBrand eyebrow="Demo workspace"/></section><section className="authFormPanel"><div className="authCard"><h1>Demo mode active</h1><p className="muted">Sign-in is intentionally bypassed for local/demo testing.</p><button className="button" onClick={()=>router.push(safeReturnTo())}>Continue</button></div></section></div>;
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!policy.allowPasswordSignIn)return;setError('');setBusy(true);const form=new FormData(e.currentTarget);try{const result=await signInWithEmailAndPassword(firebaseAuth(),String(form.get('email')),String(form.get('password'))),jit=await jitIfConfigured(result.user,orgId);if(jit?.status==='approval_required'){setNotice(`Your identity is verified. Access request ${jit.requestId||''} is awaiting independent approval.`);return}if(orgId)setActiveOrgId(orgId);router.push(safeReturnTo())}catch(e){setError(e instanceof Error?e.message:'Sign-in failed.')}finally{setBusy(false)}}
async function guest(){if(!orgId||!policy.guestAccessEnabled)return;setBusy(true);setError('');try{await signInAnonymously(firebaseAuth());setActiveOrgId(orgId);router.push('/organization')}catch(e){setError(e instanceof Error?e.message:'Guest access could not be started.')}finally{setBusy(false)}}
async function sso(p:PublicProvider){try{setError('');const provider=p.protocol==='saml'?new SAMLAuthProvider(p.firebaseProviderId):new OAuthProvider(p.firebaseProviderId);await signInWithRedirect(firebaseAuth(),provider)}catch(e){setError(e instanceof Error?e.message:'SSO sign-in could not start.')}}
return <div className="authShell"><section className="authBrandPanel"><AuthBrand eyebrow="Secure workforce intelligence"/><div className="authTrustGrid"><div><strong>Evidence aware</strong><span>Readiness is separated from evidence sufficiency.</span></div><div><strong>Human governed</strong><span>Consequential employment decisions remain human-authorized.</span></div><div><strong>Audit ready</strong><span>Organization boundaries and privileged actions remain traceable.</span></div></div></section><section className="authFormPanel"><form className="authCard stack" onSubmit={submit}><div><span className="authKicker">Secure access</span><h1>Sign in to OPSIQO</h1><p className="muted">Use your approved organization identity to continue.</p></div>{!policy.allowPasswordSignIn&&<div className="notice">Email/password sign-in is disabled by organization policy. Use an approved SSO provider.</div>}<label className="field"><span>Email</span><input className="input" name="email" type="email" autoComplete="email" required disabled={!policy.allowPasswordSignIn}/></label><label className="field"><span>Password</span><input className="input" name="password" type="password" autoComplete="current-password" required disabled={!policy.allowPasswordSignIn}/></label>{error&&<div className="error">{error}</div>}{notice&&<div className="notice">{notice}</div>}<button className="button" disabled={busy||!policy.allowPasswordSignIn}>{busy?'Signing in…':'Sign in securely'}</button><div className="authLinks">{policy.allowSelfPasswordReset&&<Link href={`/forgot-password${orgId?`?orgId=${encodeURIComponent(orgId)}`:''}`}>Forgot password?</Link>}{policy.registrationMode==='open_auth_only'&&<Link href={`/register${orgId?`?orgId=${encodeURIComponent(orgId)}`:''}`}>Register account</Link>}</div>{policy.guestAccessEnabled&&orgId&&<button type="button" className="button secondary" disabled={busy} onClick={guest}>Continue as read-only guest</button>}{checking&&<p className="muted authInlineStatus">Checking approved enterprise identity providers…</p>}</form>{!checking&&providers.length>0&&<section className="authCard stack"><h2 className="sectionTitle">Enterprise SSO</h2>{providers.map(p=><button key={p.firebaseProviderId} className="button secondary" onClick={()=>sso(p)}>Continue with {p.name}</button>)}<p className="muted">Federation is shown only for active, approved provider profiles. JIT access remains governed.</p></section>}</section></div>}
