export type AiProvider='demo'|'openai'|'gemini';
export type AiRunStatus='completed'|'blocked'|'failed'|'insufficient_evidence';
export type AiEvidenceKind='metric'|'forecast'|'lifecycle'|'workforce_plan'|'policy'|'operational'|'diagnostic'|'privacy'|'resilience'|'strategy'|'org_design'|'enterprise_command'|'integration'|'identity'|'security_ops'|'platform_reliability';
export type AiRecommendationType='investigate'|'review'|'analyze'|'communicate'|'plan'|'monitor';
export interface AiEvidenceItem { id:string; kind:AiEvidenceKind; title:string; summary:string; source:string; asOf:string; href?:string; dataQuality?:string; sensitivity:'aggregate'|'team'|'self'; }
export interface AiCitation { evidenceId:string; claim:string; }
export interface AiRecommendation { id:string; type:AiRecommendationType; title:string; rationale:string; evidenceIds:string[]; priority:'low'|'medium'|'high'; suggestedOwnerRole?:string|null; suggestedDueDays?:number|null; }
export interface AiCopilotAnswer { summary:string; findings:string[]; citations:AiCitation[]; recommendations:AiRecommendation[]; limitations:string[]; confidence:number; evidenceCompleteness:number; requiresHumanDecision:boolean; blockedReason?:string; }
export interface AiPromptTemplate { id:string; code:string; name:string; version:number; status:'draft'|'active'|'retired'; systemInstruction:string; prohibitedUses:string[]; createdBy:string; createdAt:string; updatedAt:string; activatedBy?:string; activatedAt?:string; }
export interface AiModelProfile { id:string; code:string; provider:AiProvider; model:string; purpose:string; dataHandlingNote:string; version:number; status:'draft'|'active'|'retired'; createdBy:string; createdAt:string; updatedAt:string; approvedBy?:string; approvedAt?:string; }
export interface AiRun { id:string; question:string; questionHash:string; status:AiRunStatus; provider:AiProvider; model:string; promptCode:string; promptVersion:number; modelProfileCode:string; modelProfileVersion:number; evidenceIds:string[]; answer?:AiCopilotAnswer; blockedReason?:string; latencyMs:number; inputChars:number; outputChars:number; actorUid:string; actorRole:string; createdAt:string; completedAt:string; }
export interface AiActionPlanTask { id:string; title:string; description:string; ownerRole:string; dueDate:string; status:'pending'|'completed'|'cancelled'; evidenceIds:string[]; }
export interface AiActionPlan { id:string; aiRunId:string; recommendationId:string; title:string; status:'draft'|'approved'|'cancelled'|'completed'; tasks:AiActionPlanTask[]; createdBy:string; createdAt:string; updatedAt:string; approvedBy?:string; approvedAt?:string; }
export interface AiCopilotDashboard { provider:AiProvider; model:string; prompt?:AiPromptTemplate; promptTemplates:AiPromptTemplate[]; modelProfile?:AiModelProfile; modelProfiles:AiModelProfile[]; recentRuns:AiRun[]; actionPlans:AiActionPlan[]; governance:{remoteStorageDisabled:boolean; consequentialDecisionsBlocked:boolean; evidenceRequired:boolean; directWritesBlocked:boolean}; }
