export type JobArchitectureStatus='active'|'inactive';
export type PayBasis='annual_salary'|'hourly';
export type CompensationChangeReason='hire'|'merit'|'promotion'|'market'|'equity'|'adjustment'|'demotion'|'other';
export type CompensationCycleStatus='draft'|'open'|'manager_review'|'hr_review'|'approved'|'applied'|'closed'|'cancelled';
export type RecommendationStatus='draft'|'submitted'|'hr_review'|'approved'|'rejected'|'applied';
export type RecommendationType='merit'|'promotion'|'market'|'equity'|'lump_sum'|'other';
export type JobClassGender='female'|'male'|'neutral'|'unknown';
export type PayEquityReviewStatus='draft'|'review_required'|'reviewed'|'action_required'|'closed';

export interface JobFamily{ id:string; code:string; name:string; description?:string; status:JobArchitectureStatus; createdBy:string; createdAt:string; updatedAt:string; }
export interface JobLevel{ id:string; code:string; name:string; rank:number; description?:string; status:JobArchitectureStatus; createdBy:string; createdAt:string; updatedAt:string; }
export interface SalaryBand{ id:string; code:string; name:string; jobFamilyId?:string; levelId?:string; currency:string; payBasis:PayBasis; min:number; midpoint:number; max:number; location?:string; effectiveDate:string; status:JobArchitectureStatus; createdBy:string; createdAt:string; updatedAt:string; }
export interface PositionCompensationProfile{ id:string; positionId:string; jobFamilyId?:string; levelId?:string; salaryBandId?:string; marketBenchmarkId?:string; exemptionNote?:string; updatedBy:string; updatedAt:string; }
export interface WorkerCompensationRecord{ id:string; workerId:string; effectiveDate:string; endDate?:string; currency:string; payBasis:PayBasis; basePay:number; annualizedBasePay:number; variableTargetPct:number; allowancesAnnual:number; changeReason:CompensationChangeReason; sourceCycleId?:string; sourceRecommendationId?:string; note?:string; createdBy:string; createdAt:string; }
export interface MarketBenchmark{ id:string; code:string; title:string; source:string; sourceDate:string; currency:string; location?:string; jobFamilyId?:string; levelId?:string; positionId?:string; p25:number; p50:number; p75:number; p90?:number; note?:string; createdBy:string; createdAt:string; updatedAt:string; }
export interface CompensationCycle{ id:string; name:string; cycleYear:number; effectiveDate:string; currency:string; status:CompensationCycleStatus; budgetPct?:number; budgetAmount?:number; eligibleWorkerIds?:string[]; eligibilityNote?:string; createdBy:string; createdAt:string; updatedAt:string; openedAt?:string; approvedAt?:string; approvedBy?:string; appliedAt?:string; closedAt?:string; }
export interface CompensationRecommendation{ id:string; cycleId:string; workerId:string; managerWorkerId?:string; type:RecommendationType; currentBasePay:number; proposedIncreasePct:number; proposedIncreaseAmount:number; proposedBasePay:number; lumpSumAmount:number; currency:string; rationale:string; evidenceRefs:string[]; status:RecommendationStatus; submittedBy:string; submittedAt?:string; reviewedBy?:string; reviewedAt?:string; decisionNote?:string; appliedAt?:string; createdAt:string; updatedAt:string; }
export interface CompensationLetter{ id:string;workerId:string;cycleId:string;recommendationId:string;effectiveDate:string;currency:string;previousBasePay:number;newBasePay:number;increaseAmount:number;increasePct:number;lumpSumAmount:number;status:'ready'|'released';generatedAt:string;generatedBy:string;releasedAt?:string;releasedBy?:string;sourceCompensationRecordId:string;disclaimer:string;}
export interface TotalRewardsStatement{ workerId:string; currency:string; annualBasePay:number; variableTargetValue:number; allowancesAnnual:number; employerBenefitsValue:number; employerRetirementValue:number; otherRewardsValue:number; totalRewardsValue:number; asOfDate:string; components:{label:string;value:number;source:string}[]; disclaimer:string; }
export interface PayEquityJobClass{ id:string; code:string; name:string; establishmentId:string; bargainingUnit?:string; genderPredominance:JobClassGender; jobRate:number; currency:string; skillPoints:number; effortPoints:number; responsibilityPoints:number; workingConditionsPoints:number; totalValuePoints:number; comparatorMethod:'job_to_job'|'proportional_value'|'proxy'|'not_assessed'; comparatorJobClassIds:string[]; reviewStatus:PayEquityReviewStatus; legalBasisNote?:string; lastReviewedAt?:string; lastReviewedBy?:string; createdBy:string; createdAt:string; updatedAt:string; }
export interface PayEquityDiagnostic{ id:string; severity:'info'|'warning'|'high'; jobClassId:string; title:string; description:string; evidence:string[]; recommendedAction:string; disclaimer:string; }
export interface PayTransparencyPolicy{ id:'default'; jurisdiction:string; effectiveDate:string; employerEmployeeThreshold:number; rangeMaxSpreadAnnual:number; exceptionAboveAnnual:number; postingRetentionYears:number; interviewDecisionNoticeDays:number; enabled:boolean; updatedBy:string; updatedAt:string; }
export interface RequisitionCompensationDisclosure{ id:string; requisitionId:string; publiclyAdvertised:boolean; currency:string; expectedMin:number; expectedMax:number; annualized:boolean; vacancyExists:'yes'|'no'|'unknown'; aiUsedInScreening:boolean; aiDisclosureText?:string; validatedStatus:'draft'|'validated'|'review_required'; validationNotes:string[]; createdBy:string; createdAt:string; updatedAt:string; }
export interface WorkerCompensationView{ workerId:string; displayName:string; employeeNumber:string; positionId?:string; positionTitle?:string; managerWorkerId?:string; current?:WorkerCompensationRecord; salaryBand?:SalaryBand; compaRatioPct?:number; rangePenetrationPct?:number; marketPositionPct?:number; performanceRating?:number; totalRewards?:TotalRewardsStatement; }
export interface CompensationDashboard{ scope:'self'|'team'|'organization'; metrics:{key:string;label:string;value:number|string;helper:string}[]; workers:WorkerCompensationView[]; jobFamilies:JobFamily[]; jobLevels:JobLevel[]; salaryBands:SalaryBand[]; positionProfiles:PositionCompensationProfile[]; benchmarks:MarketBenchmark[]; cycles:CompensationCycle[]; recommendations:CompensationRecommendation[]; payEquityJobClasses:PayEquityJobClass[]; payEquityDiagnostics:PayEquityDiagnostic[]; payTransparencyPolicy:PayTransparencyPolicy; requisitionDisclosures:RequisitionCompensationDisclosure[]; compensationLetters:CompensationLetter[]; workerDirectory:{id:string;displayName:string;employeeNumber:string;status:string;primaryPositionId?:string;managerWorkerId?:string}[]; positionDirectory:{id:string;title:string;positionCode:string;orgUnitId:string;status:string}[]; generatedAt:string; legalDisclaimer:string; }
export interface CompensationFxRate{ id:string;fromCurrency:string;toCurrency:string;rate:number;asOfDate:string;source:string;sourceReference:string;methodologyNote:string;verifiedBy:string;verifiedAt:string;createdAt:string; }
export interface MarketBenchmarkProvenance{ id:string;benchmarkId:string;sourceReference:string;sourceRetrievedAt:string;methodology:string;sampleSize?:number;currencyBasis:string;geographyBasis:string;evidenceRefs:string[];verifiedBy:string;verifiedAt:string; }
export interface CompensationCorrection{ id:string;workerId:string;effectiveDate:string;currency:string;payBasis:PayBasis;basePay:number;annualizedBasePay:number;variableTargetPct:number;allowancesAnnual:number;reason:string;evidenceRefs:string[];fxRateId?:string;retroPayAmount:number;retroPayDate?:string;status:'submitted'|'approved'|'rejected';beforeRecordId:string;createdBy:string;createdAt:string;reviewedBy?:string;reviewedAt?:string;decisionNote?:string;appliedRecordId?:string; }
