export type EmployeeRelationsCaseType = 'workplace_harassment'|'workplace_violence'|'discrimination_human_rights'|'grievance'|'discipline'|'accommodation'|'attendance'|'conflict'|'whistleblower'|'other';
export type EmployeeRelationsStatus = 'triage'|'investigating'|'findings_review'|'action_plan'|'monitoring'|'closed'|'cancelled';
export type EmployeeRelationsRisk = 'low'|'medium'|'high'|'critical';
export type EmployeeRelationsConfidentiality = 'restricted'|'highly_confidential'|'legal_privileged';
export type CaseTeamRole = 'case_manager'|'investigator'|'reviewer'|'legal'|'accommodation_specialist';
export interface EmployeeRelationsCase { id:string;referenceNumber:string;type:EmployeeRelationsCaseType;title:string;summary:string;status:EmployeeRelationsStatus;riskLevel:EmployeeRelationsRisk;confidentiality:EmployeeRelationsConfidentiality;reporterUid:string;reporterWorkerId?:string;affectedWorkerIds:string[];respondentWorkerIds:string[];location?:string;incidentDate?:string;reportedAt:string;investigationRequired:boolean;investigationTargetDate?:string;investigationTargetSource?:string;investigationCompletedAt?:string;outcomeNoticeRequired:boolean;outcomeNoticeDueAt?:string;outcomeNoticeDueSource?:string;complainantNoticeSentAt?:string;respondentNoticeSentAt?:string;minimumRetentionUntil?:string;legalHoldActive:boolean;legalHoldReason?:string;legalHoldAppliedAt?:string;legalHoldAppliedBy?:string;legalHoldReleasedAt?:string;legalHoldReleasedBy?:string;createdBy:string;createdAt:string;updatedAt:string;closedAt?:string;closedBy?:string;closureSummary?:string; }
export interface EmployeeRelationsCaseTeamMember {id:string;caseId:string;uid:string;workerId?:string;role:CaseTeamRole;conflictStatus:'pending'|'cleared'|'conflict';conflictNote?:string;assignedBy:string;assignedAt:string;conflictDeclaredAt?:string;}
export interface EmployeeRelationsParticipant {id:string;caseId:string;workerId?:string;externalName?:string;role:'complainant'|'respondent'|'witness'|'representative'|'other';contactNote?:string;createdAt:string;}
export interface EmployeeRelationsEvidence {id:string;caseId:string;type:'document'|'email'|'message'|'photo'|'video'|'audio'|'note'|'other';title:string;source:string;governedDocumentId?:string;evidenceHash?:string;collectedAt:string;collectedBy:string;restricted:boolean;note?:string;createdAt:string;}
export interface EmployeeRelationsInterview {id:string;caseId:string;participantId?:string;workerId?:string;externalName?:string;interviewType:'complainant'|'respondent'|'witness'|'follow_up'|'other';conductedBy:string;conductedAt:string;notes:string;statementConfirmed:boolean;confirmationNote?:string;createdAt:string;}
export interface EmployeeRelationsFinding {id:string;caseId:string;allegation:string;conclusion:'substantiated'|'not_substantiated'|'inconclusive'|'not_applicable';rationale:string;evidenceRefs:string[];standard?:string;recordedBy:string;recordedAt:string;reviewedBy?:string;reviewedAt?:string;}
export interface EmployeeRelationsAction {id:string;caseId:string;type:'remedial'|'corrective'|'disciplinary'|'accommodation'|'safety'|'training'|'policy'|'process'|'monitoring';title:string;description?:string;ownerUid?:string;ownerRole?:string;dueAt?:string;blockingClosure:boolean;status:'open'|'in_progress'|'completed'|'waived'|'overdue';completionNote?:string;completedAt?:string;completedBy?:string;createdAt:string;updatedAt:string;}
export interface AccommodationPlan {id:string;caseId:string;workerId:string;functionalLimitations:string[];abilities:string[];essentialDutiesNote?:string;accommodationMeasures:string[];medicalDocumentId?:string;status:'assessment'|'active'|'modified'|'ended';startDate?:string;reviewDate?:string;endDate?:string;privacyNote:string;createdBy:string;createdAt:string;updatedAt:string;}
export interface EmployeeRelationsDashboard {metrics:{openCases:number;highRisk:number;investigations:number;overdueActions:number;accommodationsDue:number;outcomeNoticesDue:number;closedYtd:number};cases:any[];overdueActions:EmployeeRelationsAction[];reviewDueAccommodations:AccommodationPlan[];}
