export type DiagnosticFrameworkType='maturity'|'compliance'|'composite';
export type DiagnosticFrameworkStatus='draft'|'active'|'retired';
export type DiagnosticControlKind='operational'|'compliance'|'governance';
export type DiagnosticSeverity='info'|'low'|'medium'|'high'|'critical';
export type DiagnosticApplicability='pending'|'applicable'|'not_applicable';
export type DiagnosticControlStatus='not_assessed'|'met'|'partially_met'|'not_met'|'not_applicable';
export type DiagnosticEvidenceQuality='none'|'weak'|'adequate'|'strong';
export type DiagnosticAssessmentStatus='draft'|'in_progress'|'review'|'approved'|'closed';
export type DiagnosticFindingStatus='open'|'action_planned'|'resolved'|'accepted_risk';
export type DiagnosticRemediationStatus='draft'|'approved'|'cancelled'|'completed';
export type DiagnosticApplicabilityRule='always'|'min_current_employees'|'min_ontario_jan1'|'aoda_multi_year'|'pay_equity_ontario'|'manual';
export type DiagnosticEvidenceSourceType='policy'|'document'|'learning'|'analytics'|'safety'|'compensation'|'employee_relations'|'time'|'external_reference';

export interface DiagnosticFramework { id:string; code:string; name:string; type:DiagnosticFrameworkType; jurisdiction:string; version:number; status:DiagnosticFrameworkStatus; description:string; methodologyNotice:string; sourceReviewedAt:string; createdBy:string; createdAt:string; updatedAt:string; }
export interface DiagnosticDomain { code:string; name:string; description:string; weight:number; sortOrder:number; }
export interface DiagnosticControl { id:string; frameworkId:string; domainCode:string; code:string; title:string; objective:string; kind:DiagnosticControlKind; jurisdiction:string; sourceTitle:string; sourceUrl?:string; sourceReviewedAt:string; legalConclusionProhibited:boolean; applicabilityRule:DiagnosticApplicabilityRule; threshold?:number; evidenceRequirements:string[]; weight:number; riskIfMissing:DiagnosticSeverity; maturityLevel:number; enabled:boolean; createdAt:string; updatedAt:string; }
export interface DiagnosticApplicabilityProfile { jurisdiction:string; currentEmployeeCount:number; ontarioEmployeesJan1:number; organizationType:'business'|'nonprofit'|'public_sector'|'other'; isProvinciallyRegulated:boolean; isPublicSector:boolean; notes?:string; }
export interface DiagnosticEvidenceRef { sourceType:DiagnosticEvidenceSourceType; sourceId:string; label:string; note?:string; sourceUrl?:string; validatedAt?:string; }
export interface DiagnosticControlResult { id:string; assessmentId:string; controlId:string; controlCode:string; domainCode:string; applicability:DiagnosticApplicability; status:DiagnosticControlStatus; controlScore:number|null; evidenceQuality:DiagnosticEvidenceQuality; evidenceRefs:DiagnosticEvidenceRef[]; assessorNote?:string; reviewerNote?:string; riskSeverity:DiagnosticSeverity; assessedBy?:string; assessedAt?:string; updatedAt:string; }
export interface DiagnosticFinding { id:string; assessmentId:string; controlId:string; controlCode:string; domainCode:string; severity:DiagnosticSeverity; title:string; gap:string; evidenceSummary:string; recommendation:string; status:DiagnosticFindingStatus; remediationPlanId?:string; acceptedRiskReason?:string; resolvedAt?:string; createdAt:string; updatedAt:string; }
export interface DiagnosticAssessment { id:string; frameworkId:string; frameworkCode:string; name:string; scopeNote:string; profile:DiagnosticApplicabilityProfile; status:DiagnosticAssessmentStatus; score:number; maturityLevel:number; evidenceCoverage:number; counts:{ applicable:number; notApplicable:number; pending:number; met:number; partial:number; notMet:number; critical:number; high:number; medium:number; low:number }; previousAssessmentId?:string; reviewDueDate:string; createdBy:string; createdAt:string; updatedAt:string; submittedBy?:string; submittedAt?:string; approvedBy?:string; approvedAt?:string; closedBy?:string; closedAt?:string; }
export interface DiagnosticRemediationTask { id:string; title:string; description?:string; ownerRole:string; dueDate:string; status:'pending'|'completed'|'cancelled'; completedBy?:string; completedAt?:string; }
export interface DiagnosticRemediationPlan { id:string; assessmentId:string; findingId:string; title:string; ownerRole:string; dueDate:string; successMetric:string; status:DiagnosticRemediationStatus; tasks:DiagnosticRemediationTask[]; createdBy:string; createdAt:string; updatedAt:string; approvedBy?:string; approvedAt?:string; completedAt?:string; }
export interface DiagnosticDashboard { frameworks:DiagnosticFramework[]; domains:DiagnosticDomain[]; controls:DiagnosticControl[]; assessments:DiagnosticAssessment[]; results:DiagnosticControlResult[]; findings:DiagnosticFinding[]; remediationPlans:DiagnosticRemediationPlan[]; metrics:{ currentScore:number; maturityLevel:number; evidenceCoverage:number; openCritical:number; openHigh:number; openFindings:number; overdueRemediation:number; }; methodologyNotice:string; }
