export type UnifiedWorkforceKind='employee'|'temporary'|'contractor'|'intern'|'volunteer'|'digital_agent';
export interface UnifiedWorkforceRecord {id:string;kind:UnifiedWorkforceKind;displayName:string;status:string;source:'hris'|'cortex';positionTitle?:string;orgUnitName?:string;managerName?:string;fte?:number;authority?:string;humanOversight?:boolean;}
export interface UnifiedWorkforceDashboard {records:UnifiedWorkforceRecord[];counts:Record<UnifiedWorkforceKind,number>;humanCount:number;digitalAgentCount:number;generatedAt:string;governanceNotice:string;}
export interface GrantFundingSource {id:string;code:string;name:string;funder:string;startDate:string;endDate:string;currency:string;totalBudget?:number;status:'planned'|'active'|'closed';notes?:string;createdBy:string;createdAt:string;updatedBy:string;updatedAt:string;}
export interface GrantWorkforceAllocation {id:string;fundingSourceId:string;projectId?:string;workerId:string;allocationPct:number;plannedAnnualAmount?:number;startDate:string;endDate?:string;createdBy:string;createdAt:string;updatedBy:string;updatedAt:string;}
export interface GrantWorkforceDashboard {sources:GrantFundingSource[];allocations:Array<GrantWorkforceAllocation&{workerName:string;fundingName:string}>;metrics:{activeSources:number;expiring90d:number;fundedWorkers:number;activeAllocationPct:number;plannedAnnualFunding:number|null};signals:Array<{id:string;severity:'high'|'medium'|'info';title:string;summary:string;href:string}>;generatedAt:string;governanceNotice:string;}
export interface MeetingActionItem {id:string;description:string;ownerLabel?:string;dueDate?:string;status:'open'|'done';}
export interface MeetingActionDraft {id:string;title:string;meetingDate:string;participantNames:string[];summary:string;decisions:string[];actions:MeetingActionItem[];status:'draft'|'reviewed'|'archived';createdBy:string;createdAt:string;updatedAt:string;reviewedAt?:string;archivedAt?:string;promotedWorkflowId?:string;promotedAt?:string;}
export interface MeetingActionDashboard {drafts:MeetingActionDraft[];governanceNotice:string;}
export interface NotificationDigestGroup {id:string;title:string;priority:'critical'|'high'|'normal';count:number;href:string;items:Array<{id:string;title:string;message:string}>;}
