export type PlatformRisk='low'|'medium'|'high'|'critical';
export type PlatformLifecycle='draft'|'in_review'|'approved'|'active'|'completed'|'verified'|'closed'|'rejected'|'retired';
export interface PlatformSbomRecord{ id:string;releaseVersion:string;format:'CycloneDX';specVersion:'1.7';serialNumber:string;componentCount:number;directDependencyCount:number;lockfileSha256:string;artifactSha256?:string;evidenceRef:string;status:'generated'|'verified'|'rejected';generatedBy:string;generatedAt:string;verifiedBy?:string;verifiedAt?:string;standardsClaim:'inventory_evidence_only'; }
export interface PlatformSupplyChainScan{ id:string;code:string;scanType:'dependency_vulnerability'|'secret'|'sast'|'license'|'container'|'iac';tool:string;toolVersion?:string;releaseVersion:string;critical:number;high:number;medium:number;low:number;informational:number;evidenceRef:string;status:'draft'|'in_review'|'approved'|'rejected'|'superseded';createdBy:string;createdAt:string;updatedAt:string;submittedBy?:string;submittedAt?:string;approvedBy?:string;approvedAt?:string; }
export interface PlatformBuildProvenance{ id:string;code:string;releaseVersion:string;subjectName:string;subjectSha256:string;predicateType:'https://slsa.dev/provenance/v1';builderId:string;buildType:string;sourceRepository:string;sourceDigest:string;workflowRef:string;invocationId:string;startedOn:string;finishedOn:string;ciEvidenceRef:string;signed:boolean;status:'draft'|'in_review'|'approved'|'rejected'|'superseded';createdBy:string;createdAt:string;updatedAt:string;submittedBy?:string;submittedAt?:string;approvedBy?:string;approvedAt?:string;slsaLevelClaimed:false; }
export interface PlatformBackupPolicy{ id:string;code:string;service:string;dataStores:string[];rpoMinutes:number;rtoMinutes:number;retentionDays:number;pitrRequired:boolean;encryptionRequired:boolean;ownerRole:string;nextReviewDate:string;status:'draft'|'in_review'|'approved'|'retired';createdBy:string;createdAt:string;updatedAt:string;submittedBy?:string;submittedAt?:string;approvedBy?:string;approvedAt?:string; }
export interface PlatformBackupEvidence{ id:string;policyId:string;backupAt:string;restoreTested:boolean;restoreTestAt?:string;actualRpoMinutes?:number;actualRtoMinutes?:number;integrityVerified:boolean;evidenceRef:string;status:'recorded'|'verified'|'rejected';createdBy:string;createdAt:string;verifiedBy?:string;verifiedAt?:string; }
export interface PlatformDrPlan{ id:string;code:string;title:string;criticalServices:string[];rtoMinutes:number;rpoMinutes:number;activationCriteria:string;communicationsPlan:string;recoveryProcedure:string;ownerRole:string;nextExerciseDate:string;status:'draft'|'in_review'|'approved'|'retired';createdBy:string;createdAt:string;updatedAt:string;submittedBy?:string;submittedAt?:string;approvedBy?:string;approvedAt?:string; }
export interface PlatformDrExercise{ id:string;planId:string;exerciseType:'tabletop'|'restore'|'failover'|'game_day';conductedAt:string;result:'pass'|'partial'|'fail';actualRtoMinutes?:number;actualRpoMinutes?:number;gaps:string[];actions:string[];evidenceRef:string;status:'draft'|'in_review'|'verified'|'rejected';createdBy:string;createdAt:string;updatedAt:string;submittedBy?:string;submittedAt?:string;verifiedBy?:string;verifiedAt?:string; }
export interface PlatformConfigBaseline{ id:string;code:string;environment:'development'|'staging'|'production';sourceRef:string;configSha256:string;protectedKeys:string[];nextReviewDate:string;status:'draft'|'in_review'|'approved'|'retired';createdBy:string;createdAt:string;updatedAt:string;submittedBy?:string;submittedAt?:string;approvedBy?:string;approvedAt?:string; }
export interface PlatformDriftSnapshot{ id:string;baselineId:string;observedSha256:string;changedKeys:string[];severity:PlatformRisk;detectedAt:string;status:'open'|'accepted'|'resolved';reason?:string;resolvedBy?:string;resolvedAt?:string;createdBy:string;createdAt:string; }
export interface PlatformIncident{ id:string;code:string;title:string;service:string;severity:PlatformRisk;impact:string;startedAt:string;resolvedAt?:string;rootCause?:string;correctiveActions:string[];postmortemDueDate:string;postmortemRef?:string;status:'active'|'contained'|'resolved'|'closed';createdBy:string;createdAt:string;updatedAt:string;closedBy?:string;closedAt?:string;employmentDecisionProhibited:true; }
export interface PlatformServiceObjective{ id:string;code:string;service:string;availabilityTarget:number;currentAvailability:number;latencyTargetMs?:number;currentP95LatencyMs?:number;errorBudgetMinutes:number;errorBudgetRemainingMinutes:number;measurementWindow:string;measurementSource:string;ownerRole:string;nextReviewDate:string;breach:boolean;status:'draft'|'in_review'|'approved'|'retired';createdBy:string;createdAt:string;updatedAt:string;submittedBy?:string;submittedAt?:string;approvedBy?:string;approvedAt?:string; }
export interface PlatformReliabilitySnapshot{ id:string;capturedAt:string;capturedBy:string;readinessScore:number;level:'fragile'|'developing'|'controlled'|'resilient';criticalHighSupplyChainFindings:number;unverifiedSbom:boolean;missingApprovedProvenance:boolean;backupEvidenceOverdue:number;restoreTestsFailing:number;drExercisesOverdue:number;configDriftsHighCritical:number;openCriticalIncidents:number;sloBreaches:number; }
export interface PlatformReliabilityDashboard{sboms:PlatformSbomRecord[];scans:PlatformSupplyChainScan[];provenance:PlatformBuildProvenance[];backupPolicies:PlatformBackupPolicy[];backupEvidence:PlatformBackupEvidence[];drPlans:PlatformDrPlan[];drExercises:PlatformDrExercise[];baselines:PlatformConfigBaseline[];drifts:PlatformDriftSnapshot[];incidents:PlatformIncident[];objectives:PlatformServiceObjective[];snapshots:PlatformReliabilitySnapshot[];metrics:{readinessScore:number;readinessLevel:'fragile'|'developing'|'controlled'|'resilient';criticalHighSupplyChainFindings:number;verifiedSboms:number;approvedProvenance:number;backupPoliciesApproved:number;backupEvidenceOverdue:number;restoreTestsFailing:number;drExercisesOverdue:number;configDriftsHighCritical:number;openCriticalIncidents:number;sloBreaches:number};operatingNotice:string;generatedAt:string;}
