export type Role =
  | 'super_admin'
  | 'org_admin'
  | 'hr_admin'
  | 'hr_partner'
  | 'manager'
  | 'employee';

export type Permission =
  | 'organization.read'
  | 'organization.manage'
  | 'people.read.directory'
  | 'people.read.private'
  | 'people.manage'
  | 'positions.read'
  | 'positions.manage'
  | 'workflow.read'
  | 'workflow.manage'
  | 'workflow.run'
  | 'workflow.act'
  | 'audit.read'
  | 'audit.export'
  | 'membership.read'
  | 'membership.invite'
  | 'membership.manage'
  | 'self.read'
  | 'self.update'
  | 'team.read'
  | 'team.manage'
  | 'automation.read'
  | 'automation.run'
  | 'notifications.read'
  | 'notifications.manage'
  | 'security.manage'
  | 'recruiting.read'
  | 'recruiting.manage'
  | 'recruiting.approve'
  | 'recruiting.interview'
  | 'recruiting.offer'
  | 'recruiting.hire'
  | 'onboarding.read'
  | 'onboarding.manage'
  | 'onboarding.activate'
  | 'documents.read'
  | 'documents.manage'
  | 'documents.dispose'
  | 'policies.read'
  | 'policies.manage'
  | 'policies.approve'
  | 'compliance.read'
  | 'compliance.manage'
  | 'retention.manage'
  | 'leave.read'
  | 'leave.request'
  | 'leave.approve'
  | 'leave.manage'
  | 'time.read'
  | 'time.clock'
  | 'time.manage'
  | 'time.approve'
  | 'time.configure'
  | 'payroll.export'
  | 'separation.read'
  | 'separation.request'
  | 'separation.manage'
  | 'separation.approve'
  | 'separation.close'
  | 'separation.analytics'
  | 'performance.read'
  | 'performance.manage'
  | 'performance.review'
  | 'performance.calibrate'
  | 'performance.pip'
  | 'learning.read'
  | 'learning.manage'
  | 'learning.assign'
  | 'learning.verify'
  | 'learning.self_assign'
  | 'career.read'
  | 'career.manage'
  | 'succession.read'
  | 'succession.manage'
  | 'talent.calibrate'
  | 'compensation.read'
  | 'compensation.manage'
  | 'compensation.approve'
  | 'jobarchitecture.manage'
  | 'payequity.review'
  | 'er.intake'
  | 'er.read'
  | 'er.manage'
  | 'er.investigate'
  | 'er.findings'
  | 'er.accommodation'
  | 'er.legal_hold'
  | 'er.analytics'
  | 'safety.report'
  | 'safety.read'
  | 'safety.manage'
  | 'safety.investigate'
  | 'safety.rtw'
  | 'safety.committee'
  | 'safety.analytics'
  | 'experience.read'
  | 'experience.survey'
  | 'experience.manage'
  | 'service.read'
  | 'service.request'
  | 'service.manage'
  | 'recognition.send'
  | 'recognition.manage'
  | 'workforce.read'
  | 'workforce.manage'
  | 'workforce.approve'
  | 'peopleanalytics.read'
  | 'peopleanalytics.manage'
  | 'peopleanalytics.approve'
  | 'ai.use'
  | 'ai.manage'
  | 'ai.approve'
  | 'ai.audit'
  | 'diagnostic.read'
  | 'diagnostic.manage'
  | 'diagnostic.approve'
  | 'governance.read'
  | 'governance.manage'
  | 'governance.approve'
  | 'governance.audit'
  | 'regulatory.read'
  | 'regulatory.manage'
  | 'regulatory.approve'
  | 'regulatory.audit'
  | 'assurance.read'
  | 'assurance.manage'
  | 'assurance.approve'
  | 'assurance.audit'
  | 'privacy.read'
  | 'privacy.manage'
  | 'privacy.approve'
  | 'privacy.audit'
  | 'resilience.read'
  | 'resilience.manage'
  | 'resilience.approve'
  | 'resilience.audit'
  | 'resilience.incident'
  | 'strategy.read'
  | 'strategy.manage'
  | 'strategy.approve'
  | 'strategy.audit'
  | 'orgdesign.read'
  | 'orgdesign.manage'
  | 'orgdesign.approve'
  | 'orgdesign.audit'
  | 'commandcenter.read'
  | 'commandcenter.manage'
  | 'commandcenter.approve'
  | 'commandcenter.audit'
  | 'integration.read'
  | 'integration.manage'
  | 'integration.approve'
  | 'integration.audit'
  | 'identity.read'
  | 'identity.manage'
  | 'identity.approve'
  | 'identity.audit'
  | 'securityops.read'
  | 'securityops.manage'
  | 'securityops.approve'
  | 'securityops.audit'
  | 'platform.read'
  | 'platform.manage'
  | 'platform.approve'
  | 'platform.audit';

export interface Membership {
  uid: string;
  workerId?: string;
  role: Role;
  status: 'active' | 'inactive';
  orgUnitScope?: string[];
  createdAt: string;
  updatedAt: string;
}

export interface Invitation {
  id: string;
  email: string;
  role: Role;
  status: 'pending' | 'accepted' | 'revoked' | 'expired';
  workerId?: string;
  invitedBy: string;
  expiresAt: string;
  createdAt: string;
  acceptedAt?: string;
  acceptedByUid?: string;
  revokedAt?: string;
  revokedByUid?: string;
  revokeReason?: string;
  lastSentAt?: string;
  sendCount?: number;
}


export interface ActorContext {
  uid: string;
  orgId: string;
  role: Role;
  workerId?: string;
  permissions: Permission[];
  demo?: boolean;
}
