import type { MetricDefinition, MetricId } from "./types";

export const METRIC_CATALOG: Record<MetricId, MetricDefinition> = {
  active_headcount: {
    id: "active_headcount",
    title: "Active headcount",
    description: "Active workers in the selected organization scope and period.",
    formula: "Count of active authoritative worker/employment records at the period end.",
    unit: "count",
    category: "workforce",
    allowedDimensions: ["none", "organization_unit", "location_category", "job_family", "employment_type", "month", "quarter"],
    individualScoring: false,
  },
  hires: {
    id: "hires",
    title: "Hires",
    description: "Approved hires with authoritative employment start in the selected period.",
    formula: "Count of employment starts during the selected period.",
    unit: "count",
    category: "workforce",
    allowedDimensions: ["none", "organization_unit", "location_category", "job_family", "employment_type", "month", "quarter"],
    individualScoring: false,
  },
  exits: {
    id: "exits",
    title: "Exits",
    description: "Authoritative employment exits in the selected period.",
    formula: "Count of employment end events during the selected period.",
    unit: "count",
    category: "workforce",
    allowedDimensions: ["none", "organization_unit", "location_category", "job_family", "employment_type", "month", "quarter"],
    individualScoring: false,
  },
  workforce_movement: {
    id: "workforce_movement",
    title: "Workforce movement",
    description: "Authoritative workforce movement events in the selected period.",
    formula: "Count of governed workforce movement events, excluding manager-only changes when not defined as transfer.",
    unit: "count",
    category: "workforce",
    allowedDimensions: ["none", "organization_unit", "job_family", "month", "quarter"],
    individualScoring: false,
  },
  turnover_rate: {
    id: "turnover_rate",
    title: "Turnover rate",
    description: "Aggregate employment exits relative to average headcount.",
    formula: "Exits during period / average headcount during period * 100.",
    unit: "percent",
    category: "workforce",
    allowedDimensions: ["none", "organization_unit", "location_category", "job_family", "employment_type", "month", "quarter"],
    individualScoring: false,
  },
  vacancy_count: {
    id: "vacancy_count",
    title: "Vacancy count",
    description: "Open authorized positions/vacancies in scope.",
    formula: "Count of authoritative open vacancy records in scope.",
    unit: "count",
    category: "workforce",
    allowedDimensions: ["none", "organization_unit", "location_category", "job_family"],
    individualScoring: false,
  },
  vacancy_rate: {
    id: "vacancy_rate",
    title: "Vacancy rate",
    description: "Open vacancies relative to authorized positions in scope.",
    formula: "Open vacancies / authorized positions * 100.",
    unit: "percent",
    category: "workforce",
    allowedDimensions: ["none", "organization_unit", "location_category", "job_family"],
    individualScoring: false,
  },
  average_span_of_control: {
    id: "average_span_of_control",
    title: "Average span of control",
    description: "Average number of direct reports for managers in scope.",
    formula: "Total authoritative direct-report relationships / managers with direct reports.",
    unit: "ratio",
    category: "workforce",
    allowedDimensions: ["none", "organization_unit", "location_category"],
    individualScoring: false,
  },
  onboarding_completion_rate: {
    id: "onboarding_completion_rate",
    title: "Onboarding completion rate",
    description: "Completed required onboarding cases relative to applicable onboarding cases.",
    formula: "Completed applicable onboarding cases / applicable onboarding cases * 100.",
    unit: "percent",
    category: "lifecycle",
    allowedDimensions: ["none", "organization_unit", "month", "quarter"],
    individualScoring: false,
  },
  onboarding_overdue_rate: {
    id: "onboarding_overdue_rate",
    title: "Onboarding overdue rate",
    description: "Overdue active onboarding cases relative to active applicable cases.",
    formula: "Overdue active onboarding cases / active applicable onboarding cases * 100.",
    unit: "percent",
    category: "lifecycle",
    allowedDimensions: ["none", "organization_unit", "month", "quarter"],
    individualScoring: false,
  },
  offboarding_completion_rate: {
    id: "offboarding_completion_rate",
    title: "Offboarding completion rate",
    description: "Completed required offboarding cases relative to applicable cases.",
    formula: "Completed applicable offboarding cases / applicable offboarding cases * 100.",
    unit: "percent",
    category: "lifecycle",
    allowedDimensions: ["none", "organization_unit", "month", "quarter"],
    individualScoring: false,
  },
  training_completion_rate: {
    id: "training_completion_rate",
    title: "Mandatory training completion",
    description: "Completed mandatory training assignments relative to applicable assignments.",
    formula: "Completed mandatory assignments / applicable mandatory assignments * 100.",
    unit: "percent",
    category: "lifecycle",
    allowedDimensions: ["none", "organization_unit", "job_family", "employment_type", "month", "quarter"],
    individualScoring: false,
  },
  policy_acknowledgement_completion_rate: {
    id: "policy_acknowledgement_completion_rate",
    title: "Policy acknowledgement completion",
    description: "Completed required acknowledgements relative to applicable acknowledgements.",
    formula: "Completed required acknowledgements / applicable required acknowledgements * 100.",
    unit: "percent",
    category: "lifecycle",
    allowedDimensions: ["none", "organization_unit", "month", "quarter"],
    individualScoring: false,
  },
  approval_average_age_days: {
    id: "approval_average_age_days",
    title: "Average approval age",
    description: "Average age of open approval work items.",
    formula: "Sum of age in days of open approvals / open approvals.",
    unit: "days",
    category: "operations",
    allowedDimensions: ["none", "organization_unit", "source_module"],
    individualScoring: false,
  },
  workflow_completion_rate: {
    id: "workflow_completion_rate",
    title: "Workflow completion rate",
    description: "Completed governed workflows relative to started workflows.",
    formula: "Completed governed workflows / started governed workflows * 100.",
    unit: "percent",
    category: "operations",
    allowedDimensions: ["none", "organization_unit", "source_module", "month", "quarter"],
    individualScoring: false,
  },
  blocked_workflow_rate: {
    id: "blocked_workflow_rate",
    title: "Blocked workflow rate",
    description: "Blocked governed workflows relative to active/started workflows.",
    formula: "Blocked workflows / applicable workflows * 100.",
    unit: "percent",
    category: "operations",
    allowedDimensions: ["none", "organization_unit", "source_module", "month", "quarter"],
    individualScoring: false,
  },
  import_review_backlog: {
    id: "import_review_backlog",
    title: "Import review backlog",
    description: "Governed import batches waiting for human review.",
    formula: "Count of import batches in review-required states.",
    unit: "count",
    category: "operations",
    allowedDimensions: ["none", "source_module"],
    individualScoring: false,
  },
  document_exception_backlog: {
    id: "document_exception_backlog",
    title: "Document exception backlog",
    description: "Governed document items blocked by security/review exceptions.",
    formula: "Count of active document exception/review items.",
    unit: "count",
    category: "operations",
    allowedDimensions: ["none", "source_module"],
    individualScoring: false,
  },
  orchestrator_reconciliation_rate: {
    id: "orchestrator_reconciliation_rate",
    title: "Orchestrator reconciliation rate",
    description: "Governed orchestrator executions entering reconciliation.",
    formula: "Executions requiring reconciliation / governed executions * 100.",
    unit: "percent",
    category: "operations",
    allowedDimensions: ["none", "source_module", "month", "quarter"],
    individualScoring: false,
  },
  compliance_task_completion_rate: {
    id: "compliance_task_completion_rate",
    title: "Compliance task completion",
    description: "Completed required compliance tasks relative to applicable tasks.",
    formula: "Completed required compliance tasks / applicable compliance tasks * 100.",
    unit: "percent",
    category: "compliance",
    allowedDimensions: ["none", "organization_unit", "month", "quarter"],
    individualScoring: false,
  },
  overdue_compliance_tasks: {
    id: "overdue_compliance_tasks",
    title: "Overdue compliance tasks",
    description: "Required compliance tasks past their authoritative due date.",
    formula: "Count of active required compliance tasks past due.",
    unit: "count",
    category: "compliance",
    allowedDimensions: ["none", "organization_unit"],
    individualScoring: false,
  },
  mandatory_evidence_coverage: {
    id: "mandatory_evidence_coverage",
    title: "Mandatory evidence coverage",
    description: "Available required evidence relative to required evidence items.",
    formula: "Required evidence items present and valid / required evidence items * 100.",
    unit: "percent",
    category: "compliance",
    allowedDimensions: ["none", "organization_unit"],
    individualScoring: false,
  },
};

export function getMetricDefinition(id: MetricId): MetricDefinition {
  return METRIC_CATALOG[id];
}
