/**
 * Generated by OPSIQO 8.5 integration repair.
 * Inventory only: it does not grant permissions or execute HR writes.
 */
export const OPSIQO_8_INTEGRATION_INVENTORY = [
  {
    "path": "src\\lib\\hr\\service.ts",
    "exportedSymbols": [
      "createEmployee",
      "createPosition"
    ]
  },
  {
    "path": "src\\lib\\membership\\service.ts",
    "exportedSymbols": [
      "createInvitation",
      "acceptInvitation"
    ]
  },
  {
    "path": "src\\lib\\onboarding\\service.ts",
    "exportedSymbols": [
      "listOnboardingCases"
    ]
  },
  {
    "path": "src\\lib\\time\\service.ts",
    "exportedSymbols": [
      "requestLeave"
    ]
  },
  {
    "path": "src\\lib\\workflow\\service.ts",
    "exportedSymbols": [
      "startWorkflow"
    ]
  }
] as const;

export const OPSIQO_8_INTEGRATION_GENERATED_AT = "2026-08-14T18:23:00.406Z";
