import { describe, expect, it } from 'vitest';
import { deterministicSample, evidenceIntegrityHash, ledgerEntryHash, verifyLedger } from '@/lib/assurance/integrity';
import { calculateAssuranceReadiness } from '@/lib/assurance/readiness';
import type { AssuranceEvidence, AssuranceEvidenceLedgerEntry } from '@/domain/assurance';
const evidence=(overrides:Partial<AssuranceEvidence>={}):AssuranceEvidence=>({id:'e1',code:'EVD.1',title:'Policy evidence',description:'Controlled evidence used for assurance testing.',sourceType:'external_reference',sourceUrl:'https://example.com/evidence',evidenceDate:'2026-08-10',ownerRole:'hr_partner',classification:'confidential',status:'active',legalHold:false,integrityHash:'',integrityStatus:'verified',lastLedgerHash:'',lastLedgerSequence:1,createdBy:'u1',createdAt:'2026-08-10T00:00:00Z',updatedBy:'u1',updatedAt:'2026-08-10T00:00:00Z',...overrides});
describe('v2.5 assurance integrity and readiness',()=>{
  it('produces deterministic unique samples',()=>{const population=['a','b','c','d','e','f'];const a=deterministicSample(population,3,'seed-1'),b=deterministicSample([...population].reverse(),3,'seed-1');expect(a).toEqual(b);expect(new Set(a).size).toBe(3);});
  it('detects a tampered ledger entry',()=>{const base={evidenceId:'e1',sequence:1,eventType:'created' as const,eventAt:'2026-08-10T00:00:00Z',actorUid:'u1',previousHash:'GENESIS',recordIntegrityHash:'abc',note:'created'},entry:AssuranceEvidenceLedgerEntry={id:'l1',...base,entryHash:ledgerEntryHash(base)};expect(verifyLedger([entry]).ok).toBe(true);expect(verifyLedger([{...entry,note:'tampered'}]).ok).toBe(false);});
  it('keeps assurance readiness operational and penalizes high-risk open work',()=>{const e=evidence();e.integrityHash=evidenceIntegrityHash(e);const base=calculateAssuranceReadiness({evidence:[e],tests:[],findings:[],capaPlans:[],requests:[],today:'2026-08-10'});const penalized=calculateAssuranceReadiness({evidence:[e],tests:[],findings:[{id:'f1',code:'AF-1',planId:'p1',title:'Material exception',severity:'critical',condition:'Observed control exception.',criteria:'Governed control requirement.',cause:'Cause under investigation.',effectRisk:'Material operational assurance risk.',recommendation:'Remediate and retest.',ownerRole:'hr_partner',dueDate:'2026-08-01',status:'open',createdBy:'u1',createdAt:'2026-08-01T00:00:00Z',updatedAt:'2026-08-01T00:00:00Z'}],capaPlans:[],requests:[],today:'2026-08-10'});expect(penalized.score).toBeLessThan(base.score);expect(penalized.explanation).toContain('does not certify legal');});
});
