import { describe,expect,it } from 'vitest';import { can } from '@/lib/auth/permissions';import { accommodationSchema,erCaseActionSchema,erCaseCreateSchema,findingSchema } from '@/lib/employee-relations/schemas';import { workflowDefinitionCreateSchema } from '@/lib/workflow/schemas';
describe('Phase 3 v1.5 employee-relations controls',()=>{
 it('requires substantive confidential intake evidence',()=>{expect(erCaseCreateSchema.safeParse({type:'workplace_harassment',title:'Concern',summary:'too short',affectedWorkerIds:[],respondentWorkerIds:[]}).success).toBe(false);expect(erCaseCreateSchema.safeParse({type:'workplace_harassment',title:'Repeated conduct concern',summary:'Repeated conduct was reported with dates and observable examples for confidential HR triage.',affectedWorkerIds:[],respondentWorkerIds:[]}).success).toBe(true);});
 it('keeps findings as explicit human conclusions with rationale',()=>{expect(findingSchema.safeParse({allegation:'Repeated unwelcome comments over several meetings.',conclusion:'substantiated',rationale:'Documented interview and message evidence consistently supports the allegation.',evidenceRefs:['ev1']}).success).toBe(true);});
 it('stores accommodation around functional limitations rather than diagnosis',()=>{const p=accommodationSchema.parse({workerId:'w1',functionalLimitations:['Avoid prolonged standing over 30 minutes'],abilities:['Can perform all cognitive duties'],accommodationMeasures:['Provide sit/stand workstation'],status:'active'});expect((p as any).diagnosis).toBeUndefined();});
 it('separates intake from investigation/findings authority',()=>{expect(can('employee','er.intake')).toBe(true);expect(can('employee','er.investigate')).toBe(false);expect(can('manager','er.intake')).toBe(true);expect(can('manager','er.read')).toBe(false);expect(can('hr_partner','er.investigate')).toBe(true);expect(can('hr_partner','er.findings')).toBe(false);expect(can('hr_admin','er.findings')).toBe(true);});
 it('requires a reason and new date shape for investigation-target extensions',()=>{expect(erCaseActionSchema.safeParse({action:'extend_investigation_target',investigationTargetDate:'2026-12-15',note:'Key witness is temporarily unavailable and additional records are being collected.'}).success).toBe(true);});
 it('supports ER workflow triggers',()=>{expect(workflowDefinitionCreateSchema.parse({name:'ER intake',trigger:'er.case_opened',enabled:true,steps:[{id:'triage',name:'Confidential triage',type:'task',ownerRole:'hr_admin',dependsOn:[]}]}).trigger).toBe('er.case_opened');});
});
