import { describe,expect,it } from 'vitest';
import type { EnterpriseRiskNode } from '../src/domain/enterprise-command';
import { enterpriseIndex,evidenceCoverage,releaseGate,riskStatus,sloBreach } from '../src/lib/operations/enterprise-risk';
const node=(key:any,readinessScore:number,status:any='low',overdue=0,highCritical=0,weight=1,assessed=true,evidence=100):EnterpriseRiskNode=>({key,label:key,href:'/',readinessScore,status:assessed?status:'not_assessed',assessed,evidenceCoverage:evidence,evidenceStatus:assessed?'sufficient':evidence>=25?'partial':'insufficient',open:0,overdue,highCritical,weight,summary:''});
describe('v3.6.1 enterprise HCM command-center governance',()=>{
 it('degrades the enterprise index when assessed domain risk and overdue work increase',()=>{const strong=enterpriseIndex([node('lifecycle',95),node('assurance',92),node('privacy_ai',90)]);const weak=enterpriseIndex([node('lifecycle',50,'high',4,1),node('assurance',35,'critical',5,3),node('privacy_ai',55,'high',2,1)]);expect(strong.score).toBeGreaterThan(weak.score);expect(weak.level).toBe('fragile')});
 it('excludes insufficient-evidence domains instead of treating absence as healthy or critical',()=>{const result=enterpriseIndex([node('integration',80,'low',0,0,1,false,0),node('security_ops',100,'low',0,0,1,false,25)]);expect(result.score).toBe(0);expect(result.level).toBe('not_assessed');expect(result.assessedDomains).toBe(0);expect(result.totalDomains).toBe(2);expect(riskStatus(100,0,0,false)).toBe('not_assessed')});
 it('calculates evidence coverage deterministically from observed evidence signals',()=>{expect(evidenceCoverage([0,0,0,0])).toBe(0);expect(evidenceCoverage([1,0,true,false])).toBe(50);expect(evidenceCoverage([1,1,1,1])).toBe(100)});
 it('classifies material risk deterministically only after assessment',()=>{expect(riskStatus(35,0,0)).toBe('critical');expect(riskStatus(85,0,0)).toBe('low');expect(riskStatus(90,1,0)).toBe('high')});
 it('blocks release promotion until every mandatory dependency-aware gate passes',()=>{expect(releaseGate({environment:'production',readinessOkay:true,dependencyInstall:'pending',typecheck:'passed',tests:'passed',rulesTests:'passed',build:'passed',aiGovernance:'passed',lifecycleUat:'passed'})).toBe('blocked');expect(releaseGate({environment:'production',readinessOkay:true,ciEvidencePresent:true,dependencyInstall:'passed',typecheck:'passed',tests:'passed',rulesTests:'passed',build:'passed',aiGovernance:'passed',lifecycleUat:'passed'})).toBe('ready')});
 it('requires a traceable CI evidence reference for production release readiness',()=>{expect(releaseGate({environment:'production',readinessOkay:true,dependencyInstall:'passed',typecheck:'passed',tests:'passed',rulesTests:'passed',build:'passed',aiGovernance:'passed',lifecycleUat:'passed'})).toBe('blocked');expect(releaseGate({environment:'staging',readinessOkay:true,dependencyInstall:'passed',typecheck:'passed',tests:'passed',rulesTests:'passed',build:'passed',aiGovernance:'passed',lifecycleUat:'passed'})).toBe('ready')});
 it('evaluates SLO tolerances in both directions',()=>{expect(sloBreach('higher_better',99.8,99.9,0)).toBe(true);expect(sloBreach('lower_better',180,200,0)).toBe(false)});
});
