import fs from 'node:fs';import {describe,expect,it} from 'vitest';import type {AtsResumeReview} from '../src/domain/ats';import {summarizeAtsFit} from '../src/lib/recruiting/candidate-fit-service';
const read=(p:string)=>fs.readFileSync(p,'utf8');
describe('H50.5 Recruiting Intelligence',()=>{
 it('summarizes explainable fit dimensions',()=>{const r={id:'r',score:87,band:'strong_alignment',breakdown:{requirements:92},evidence:[{confidence:.9},{confidence:.8}],assessmentCoverage:90,missingRequirements:['gap'],scoringVersion:'test',createdAt:'2026-09-07T00:00:00.000Z'} as unknown as AtsResumeReview;expect(summarizeAtsFit(r)).toMatchObject({overallFit:87,requirementsCoverage:92,evidenceConfidence:85,assessmentCoverage:90,gapCount:1,humanReviewRequired:true})});
 it('has public resume-first application experience',()=>{const p=read('src/components/candidate-application-portal.tsx');for(const x of ['Resume','Cover letter','LinkedIn','Portfolio / website','Other social/professional profile','Save & continue later'])expect(p).toContain(x);expect(p).not.toContain('atsLatestScore');expect(p).not.toContain('overallFit')});
 it('keeps public routes App Check protected and rate limited',()=>{for(const p of ['src/app/api/public/recruiting/apply/[token]/route.ts','src/app/api/public/recruiting/apply/[token]/parse/route.ts','src/app/api/public/recruiting/apply/[token]/submit/route.ts'])expect(read(p)).toContain('verifyAppCheckRequest');const s=read('src/lib/recruiting/candidate-portal-service.ts');expect(s).toContain('publicRecruitingRateLimits');expect(s).toContain('adminBucket()');expect(s).toContain('unsafe_screening_question')});
 it('auto-scores every stored submitted resume path',()=>{const f=read('src/lib/recruiting/candidate-fit-service.ts'),s=read('src/lib/recruiting/service.ts');for(const x of ['autoScoreStoredApplication','atsLatestRequirementsCoverage','atsLatestEvidenceConfidence','atsLatestGapCount','humanReviewRequired:true'])expect(f).toContain(x);expect(s).toContain('autoScoreStoredApplication')});
 it('adds recruiter ranking, public links and document evidence',()=>{const w=read('src/components/recruiting-workspace.tsx'),f=read('src/components/candidate-fit-board.tsx');expect(w).toContain('<CandidateFitBoard');expect(w).toContain('<CandidateApplicationLinksPanel');expect(w).toContain('<CandidateSubmissionDocumentsPanel');expect(f).toContain('Highest fit');expect(f).toContain('Evidence confidence');expect(f).toContain('Refresh all resume fit')});
 it('preserves protected-trait and human-decision guardrails',()=>{expect(read('src/lib/recruiting/candidate-portal-service.ts')).toContain('unsafe_screening_question');expect(read('src/components/candidate-fit-board.tsx')).toContain('does not auto-reject, auto-hire or auto-advance');expect(read('src/lib/recruiting/ats-engine.ts')).toContain('PROTECTED')});
});
