import { describe,expect,it } from 'vitest';
import { assessedTeamCompliance,attentionScore,mutableSuperAppPreference,sanitizePinned,sortAttention,superAppPrivacy } from '@/lib/superapp/guardrails';
import { visibleSuperAppActions } from '@/lib/superapp/catalog';
import { preferenceSchema } from '@/lib/superapp/schemas';
describe('OPSIQO SuperApp 6.0.1 hardening',()=>{
 it('never permits offline caching of HR API/document/payroll data',()=>{expect(superAppPrivacy.apiOfflineCache).toBe(false);expect(superAppPrivacy.documentOfflineCache).toBe(false);expect(superAppPrivacy.payrollOfflineCache).toBe(false);expect(superAppPrivacy.staticAssetCacheOnly).toBe(true);});
 it('sanitizes pinned actions to allowed unique maximum',()=>{expect(sanitizePinned(['a','a','x','b'],new Set(['a','b']))).toEqual(['a','b']);expect(sanitizePinned(['1','2','3','4','5','6','7','8','9'],new Set(['1','2','3','4','5','6','7','8','9']))).toHaveLength(8);});
 it('prioritizes critical/high attention deterministically',()=>{const a:any={id:'a',type:'x',severity:'medium',title:'A',summary:'',href:'/',priorityScore:attentionScore('medium')},b:any={id:'b',type:'x',severity:'critical',title:'B',summary:'',href:'/',priorityScore:attentionScore('critical')};expect(sortAttention([a,b])[0].id).toBe('b');});
 it('filters quick actions by role and permissions',()=>{const employee:any={uid:'u',orgId:'o',role:'employee',workerId:'w',permissions:['self.read','time.read','documents.read']};const employeeActions=visibleSuperAppActions(employee,'employee');expect(employeeActions.some(x=>x.id==='my_profile')).toBe(true);expect(employeeActions.some(x=>x.id==='manager_team')).toBe(false);expect(employeeActions.some(x=>x.id==='contract_import')).toBe(false);const hr:any={...employee,role:'hr_admin',permissions:['self.read','documents.read']};expect(visibleSuperAppActions(hr,'employee').some(x=>x.id==='contract_import')).toBe(true);});
 it('accepts only mutable preference fields and validates timezone',()=>{expect(preferenceSchema.parse({homeMode:'auto',pinnedActionIds:['my_profile'],compactMode:false,locale:'en',timeZone:'America/Toronto'}).locale).toBe('en');expect(()=>preferenceSchema.parse({homeMode:'auto',pinnedActionIds:[],compactMode:false,locale:'auto',timeZone:'Not/AZone'})).toThrow();expect(()=>preferenceSchema.parse({homeMode:'auto',pinnedActionIds:[],compactMode:false,locale:'auto',timeZone:'auto',uid:'unexpected'})).toThrow();});
 it('serializes only mutable preference fields for POST',()=>{const payload=mutableSuperAppPreference({id:'u',uid:'u',homeMode:'auto',pinnedActionIds:['my_profile'],compactMode:false,locale:'en',timeZone:'America/Toronto',updatedBy:'admin',updatedAt:'2026-08-13'} as any);expect(Object.keys(payload).sort()).toEqual(['compactMode','homeMode','locale','pinnedActionIds','timeZone'].sort());expect(()=>preferenceSchema.parse(payload)).not.toThrow();});
 it('never reports 100 percent when nobody on the team was assessed',()=>{expect(assessedTeamCompliance([],12)).toEqual({rate:undefined,assessed:0,total:12,state:'not_assessed'});expect(assessedTeamCompliance([{workerId:'a',score:100},{workerId:'b',score:80}],12)).toEqual({rate:90,assessed:2,total:12,state:'partial'});expect(assessedTeamCompliance([{workerId:'a',score:100},{workerId:'a',score:70}],1)).toEqual({rate:70,assessed:1,total:1,state:'available'});});
});
