import { createHash, randomUUID } from 'crypto';
import { FieldPath } from 'firebase-admin/firestore';
import type { ActorContext } from '@/domain/security';
import type { Assignment, OrgUnit, Position, Worker } from '@/domain/hr';
import type { WorkerCompensationRecord } from '@/domain/compensation';
import type { SeparationCase } from '@/domain/separation';
import type { HrServiceTicket, EmployeeSurvey } from '@/domain/experience';
import type { SafetyIncident } from '@/domain/safety';
import type { PerformanceReview } from '@/domain/performance';
import type { LearningAssignment } from '@/domain/learning';
import type { AnalyticsMetricDefinition, AnalyticsSnapshot, AnalyticsSegmentSnapshot, AnalyticsForecastModel, AnalyticsForecastRun, AnalyticsForecastPoint, PeopleAnalyticsDashboard } from '@/domain/people-analytics';
import { adminDb } from '@/lib/firebase/admin';
import { ApiError } from '@/lib/http/errors';
import { buildAudit } from '@/lib/audit/service';
import { buildDomainEvent } from '@/lib/events/build';
import { systemActor } from '@/lib/automation/system-actor';
import { workforcePlanningDashboard } from '@/lib/workforce-planning/service';
import { analyticsMetricSchema, analyticsMetricActionSchema, forecastModelSchema, forecastModelActionSchema, forecastRunActionSchema } from './schemas';
import { forecastMonthlySeries } from './forecast';

const now=()=>new Date().toISOString();
const today=()=>now().slice(0,10);
const money=(n:number)=>Math.round((Number(n)||0)*100)/100;
const adminRoles=new Set(['super_admin','org_admin','hr_admin']);
const hrRoles=new Set(['super_admin','org_admin','hr_admin','hr_partner']);
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');

async function loadAll<T>(orgId:string,collection:string):Promise<T[]>{
  const db=adminDb(),out:T[]=[];let cursor:any;
  for(let page=0;page<100;page++){
    let q:any=db.collection(`organizations/${orgId}/${collection}`).orderBy(FieldPath.documentId()).limit(500);
    if(cursor)q=q.startAfter(cursor);const snap=await q.get();out.push(...snap.docs.map((d:any)=>d.data() as T));
    if(snap.size<500)break;cursor=snap.docs[snap.docs.length-1];
  }return out;
}
function requireRead(actor:ActorContext){if(!actor.permissions.includes('peopleanalytics.read'))throw new ApiError(403,'People analytics access required.','forbidden');if(!hrRoles.has(actor.role))throw new ApiError(403,'Organization people analytics is restricted to HR/administrative roles.','forbidden');}
function requireManage(actor:ActorContext){if(!actor.permissions.includes('peopleanalytics.manage'))throw new ApiError(403,'People analytics management permission required.','forbidden');}
function requireApprove(actor:ActorContext){if(!actor.permissions.includes('peopleanalytics.approve')||!adminRoles.has(actor.role))throw new ApiError(403,'HR administrator analytics approval is required.','forbidden');}

export const STANDARD_ANALYTICS_METRICS:Omit<AnalyticsMetricDefinition,'id'|'createdBy'|'createdAt'|'updatedAt'|'status'>[]=[
 {code:'workforce.headcount',name:'Active headcount',description:'Point-in-time count of active worker records.',category:'workforce',unit:'count',aggregation:'point_in_time',formula:'COUNT(active workers)',sourceCollections:['workers'],ownerRole:'hr_admin',sensitive:false,minimumGroupSize:5},
 {code:'workforce.fte',name:'Active FTE',description:'Point-in-time active full-time-equivalent workforce based on active employment records.',category:'workforce',unit:'fte',aggregation:'point_in_time',formula:'SUM(active employment FTE)',sourceCollections:['employments'],ownerRole:'hr_admin',sensitive:false,minimumGroupSize:5},
 {code:'workforce.vacancies',name:'Vacant/open positions',description:'Positions represented as open/planned or without an active assignment.',category:'workforce',unit:'count',aggregation:'point_in_time',formula:'COUNT(vacant/open represented positions)',sourceCollections:['positions','assignments'],ownerRole:'hr_admin',sensitive:false,minimumGroupSize:5},
 {code:'workforce.base_pay',name:'Annual base payroll',description:'Annualized base pay for active workers with a current compensation record.',category:'compensation',unit:'currency',aggregation:'point_in_time',formula:'SUM(current annualized base pay)',sourceCollections:['workerCompensationCurrent'],ownerRole:'hr_admin',sensitive:true,minimumGroupSize:5},
 {code:'workforce.employer_cost',name:'Estimated employer cost',description:'Current annual base payroll plus the workforce-planning employer on-cost assumption.',category:'compensation',unit:'currency',aggregation:'point_in_time',formula:'Annual base payroll × (1 + employer on-cost assumption)',sourceCollections:['workerCompensationCurrent'],ownerRole:'hr_admin',sensitive:true,minimumGroupSize:5},
 {code:'recruiting.open_requisitions',name:'Open requisitions',description:'Recruiting requisitions currently open, approved, or pending approval.',category:'recruiting',unit:'count',aggregation:'point_in_time',formula:'COUNT(open/approved/pending requisitions)',sourceCollections:['requisitions'],ownerRole:'hr_admin',sensitive:false,minimumGroupSize:5},
 {code:'talent.verified_skill_gaps',name:'Verified skill gaps',description:'Position skill requirements not currently met by manager/evidence-verified worker skill evidence.',category:'talent',unit:'count',aggregation:'point_in_time',formula:'COUNT(required skill level > verified skill level)',sourceCollections:['positionSkillRequirements','workerSkills','assignments'],ownerRole:'hr_admin',sensitive:true,minimumGroupSize:5},
 {code:'succession.uncovered_critical_positions',name:'Uncovered critical positions',description:'Critical positions without a confirmed successor nomination.',category:'talent',unit:'count',aggregation:'point_in_time',formula:'COUNT(critical positions without confirmed successor)',sourceCollections:['criticalPositions','successorNominations'],ownerRole:'hr_admin',sensitive:true,minimumGroupSize:5},
 {code:'lifecycle.active_separations',name:'Active separations',description:'Separation cases that are not closed or cancelled.',category:'lifecycle',unit:'count',aggregation:'point_in_time',formula:'COUNT(non-terminal separation cases)',sourceCollections:['separationCases'],ownerRole:'hr_admin',sensitive:true,minimumGroupSize:5},
 {code:'lifecycle.separations_ytd',name:'Separations YTD',description:'Employees with an effective separation date during the current calendar year.',category:'lifecycle',unit:'count',aggregation:'period_total',formula:'COUNT(separation effective date within calendar year)',sourceCollections:['separationCases'],ownerRole:'hr_admin',sensitive:true,minimumGroupSize:5},
 {code:'lifecycle.turnover_ytd_pct',name:'Turnover YTD',description:'Directional YTD separation rate using current active headcount plus YTD separations as the exposed population.',category:'lifecycle',unit:'percent',aggregation:'period_rate',formula:'Separations YTD ÷ (active headcount + separations YTD) × 100',sourceCollections:['workers','separationCases'],ownerRole:'hr_admin',sensitive:true,minimumGroupSize:5},
 {code:'service.open_tickets',name:'Open HR service requests',description:'HR service tickets that are not resolved, closed, or cancelled.',category:'service',unit:'count',aggregation:'point_in_time',formula:'COUNT(non-terminal HR service tickets)',sourceCollections:['serviceTickets'],ownerRole:'hr_admin',sensitive:true,minimumGroupSize:5},
 {code:'safety.open_incidents',name:'Open safety incidents',description:'Safety incidents that are not closed or cancelled.',category:'safety',unit:'count',aggregation:'point_in_time',formula:'COUNT(non-terminal safety incidents)',sourceCollections:['safetyIncidents'],ownerRole:'hr_admin',sensitive:true,minimumGroupSize:5},
 {code:'performance.open_reviews',name:'Open performance reviews',description:'Performance reviews that are not completed.',category:'talent',unit:'count',aggregation:'point_in_time',formula:'COUNT(performance reviews where status != completed)',sourceCollections:['performanceReviews'],ownerRole:'hr_admin',sensitive:true,minimumGroupSize:5},
 {code:'learning.overdue_assignments',name:'Overdue learning assignments',description:'Incomplete learning assignments past their due date.',category:'talent',unit:'count',aggregation:'point_in_time',formula:'COUNT(incomplete learning assignments past due date)',sourceCollections:['learningAssignments'],ownerRole:'hr_admin',sensitive:true,minimumGroupSize:5},
 {code:'experience.active_surveys',name:'Active engagement surveys',description:'Employee experience surveys currently published.',category:'experience',unit:'count',aggregation:'point_in_time',formula:'COUNT(published employee surveys)',sourceCollections:['employeeSurveys'],ownerRole:'hr_admin',sensitive:false,minimumGroupSize:5},
];

export async function bootstrapAnalyticsMetrics(actor:ActorContext){requireManage(actor);const db=adminDb(),timestamp=now(),created:string[]=[];for(const base of STANDARD_ANALYTICS_METRICS){const id=hash(base.code).slice(0,32),ref=db.doc(`organizations/${actor.orgId}/analyticsMetrics/${id}`),snap=await ref.get();if(snap.exists)continue;const row:AnalyticsMetricDefinition={...base,id,status:'active',createdBy:actor.uid,createdAt:timestamp,updatedAt:timestamp};const indexRef=db.doc(`organizations/${actor.orgId}/analyticsMetricCodeIndex/${hash(base.code)}`);const batch=db.batch();batch.create(ref,row);batch.create(indexRef,{metricId:id,code:base.code,createdAt:timestamp});const audit=buildAudit(actor,{action:'analytics.metric.bootstrap',entityType:'analyticsMetric',entityId:id,after:row});batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();created.push(id);}return{created:created.length};}

export async function createAnalyticsMetric(actor:ActorContext,raw:unknown){requireManage(actor);const input=analyticsMetricSchema.parse(raw),db=adminDb(),id=randomUUID(),timestamp=now(),indexRef=db.doc(`organizations/${actor.orgId}/analyticsMetricCodeIndex/${hash(input.code)}`);try{await db.runTransaction(async tx=>{const ix=await tx.get(indexRef);if(ix.exists)throw new ApiError(409,'Metric code already exists.','analytics_metric_code_exists');const row:AnalyticsMetricDefinition={id,...input,status:'draft',createdBy:actor.uid,createdAt:timestamp,updatedAt:timestamp};tx.create(db.doc(`organizations/${actor.orgId}/analyticsMetrics/${id}`),row);tx.create(indexRef,{metricId:id,code:input.code,createdAt:timestamp});const audit=buildAudit(actor,{action:'analytics.metric.create',entityType:'analyticsMetric',entityId:id,after:row});tx.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);});}catch(e){throw e;}const snap=await db.doc(`organizations/${actor.orgId}/analyticsMetrics/${id}`).get();return snap.data() as AnalyticsMetricDefinition;}
export async function actOnAnalyticsMetric(actor:ActorContext,id:string,raw:unknown){requireManage(actor);const input=analyticsMetricActionSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/analyticsMetrics/${id}`),snap=await ref.get();if(!snap.exists)throw new ApiError(404,'Analytics metric not found.','analytics_metric_not_found');const before=snap.data() as AnalyticsMetricDefinition;if(input.action==='activate')requireApprove(actor);const after={...before,status:input.action==='activate'?'active':'retired',updatedAt:now()} as AnalyticsMetricDefinition;const audit=buildAudit(actor,{action:`analytics.metric.${input.action}`,entityType:'analyticsMetric',entityId:id,before,after});const batch=db.batch();batch.set(ref,after);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return after;}

function currentAssignment(a:Assignment,date=today()){return a.startDate<=date&&(!a.endDate||a.endDate>=date);}
function safePct(n:number,d:number){return d>0?money(n/d*100):0;}
function segmentKey(type:'org_unit'|'location',id:string){return `${type}:${id||'unknown'}`;}

export async function generateAnalyticsSnapshot(orgId:string,generatedBy:string,forcedDate=today()):Promise<AnalyticsSnapshot>{
  const actor=systemActor(orgId,generatedBy);const db=adminDb();
  const [workforce,separations,tickets,incidents,reviews,learning,surveys,workers,assignments,positions,orgUnits,currentComp]=await Promise.all([
    workforcePlanningDashboard(actor),loadAll<SeparationCase>(orgId,'separationCases'),loadAll<HrServiceTicket>(orgId,'serviceTickets'),loadAll<SafetyIncident>(orgId,'safetyIncidents'),loadAll<PerformanceReview>(orgId,'performanceReviews'),loadAll<LearningAssignment>(orgId,'learningAssignments'),loadAll<EmployeeSurvey>(orgId,'employeeSurveys'),loadAll<Worker>(orgId,'workers'),loadAll<Assignment>(orgId,'assignments'),loadAll<Position>(orgId,'positions'),loadAll<OrgUnit>(orgId,'orgUnits'),loadAll<WorkerCompensationRecord>(orgId,'workerCompensationCurrent')]);
  const year=forcedDate.slice(0,4);const activeWorkers=workers.filter(w=>w.status==='active');const sepYtd=separations.filter(s=>String(s.effectiveDate||'').startsWith(year)&&s.status!=='cancelled').length;
  const metrics:Record<string,number>={
    'workforce.headcount':workforce.baseline.headcount,'workforce.fte':workforce.baseline.activeFte,'workforce.vacancies':workforce.baseline.vacantPositions,'workforce.base_pay':workforce.baseline.annualBasePay,'workforce.employer_cost':workforce.baseline.estimatedEmployerCost,'recruiting.open_requisitions':workforce.baseline.openRequisitions,'talent.verified_skill_gaps':workforce.baseline.verifiedSkillGaps,'succession.uncovered_critical_positions':workforce.baseline.uncoveredCriticalPositions,'lifecycle.active_separations':workforce.baseline.activeSeparations,'lifecycle.separations_ytd':sepYtd,'lifecycle.turnover_ytd_pct':safePct(sepYtd,activeWorkers.length+sepYtd),'service.open_tickets':tickets.filter(t=>!['resolved','closed','cancelled'].includes(t.status)).length,'safety.open_incidents':incidents.filter(i=>!['closed','cancelled'].includes(i.status)).length,'performance.open_reviews':reviews.filter(r=>r.status!=='completed').length,'learning.overdue_assignments':learning.filter(a=>!['completed','waived','expired'].includes(a.status)&&!!a.dueAt&&a.dueAt<now()).length,'experience.active_surveys':surveys.filter(s=>s.status==='published').length,
  };
  const activeAssignments=assignments.filter(a=>currentAssignment(a,forcedDate));const posMap=new Map(positions.map(p=>[p.id,p]));const unitMap=new Map(orgUnits.map(u=>[u.id,u]));const workerSet=new Set(activeWorkers.map(w=>w.id));const compMap=new Map(currentComp.map(c=>[c.workerId,c]));const groups=new Map<string,{dimensionType:'org_unit'|'location';dimensionId:string;label:string;workerIds:Set<string>;fte:number;basePay:number}>();
  for(const a of activeAssignments.filter(a=>workerSet.has(a.workerId)&&a.primary)){const p=posMap.get(a.positionId);const orgId2=a.orgUnitId||p?.orgUnitId||'unknown';const location=p?.location||'Unspecified';for(const [type,id,label] of [['org_unit',orgId2,unitMap.get(orgId2)?.name||orgId2],['location',location,location]] as const){const k=segmentKey(type,id),g=groups.get(k)||{dimensionType:type,dimensionId:id,label,workerIds:new Set<string>(),fte:0,basePay:0};if(!g.workerIds.has(a.workerId)){g.workerIds.add(a.workerId);g.fte+=Number(a.allocationFte??1);g.basePay+=Number(compMap.get(a.workerId)?.annualizedBasePay||0);}groups.set(k,g);}}
  const segments:AnalyticsSegmentSnapshot[]=[...groups.values()].map(g=>{const population=g.workerIds.size,suppressed=population<5;return{dimensionType:g.dimensionType,dimensionId:g.dimensionId,label:g.label,population,suppressed,metrics:suppressed?{}:{'workforce.headcount':population,'workforce.fte':money(g.fte),'workforce.base_pay':money(g.basePay)}};}).sort((a,b)=>a.dimensionType.localeCompare(b.dimensionType)||a.label.localeCompare(b.label));
  const id=`daily_${forcedDate}`,row:AnalyticsSnapshot={id,snapshotDate:forcedDate,period:'daily',currency:workforce.baseline.currency,metricVersion:1,metrics,segments,sourceCounts:{...workforce.baseline.sourceCounts,separations:separations.length,serviceTickets:tickets.length,safetyIncidents:incidents.length,performanceReviews:reviews.length,learningAssignments:learning.length,employeeSurveys:surveys.length},generatedBy,generatedAt:now(),methodologyNotice:'Descriptive aggregate snapshot generated from authoritative OPSIQO records. Small groups under five are suppressed in segmented outputs. Metrics are operational indicators, not legal findings or automated employment decisions.'};
  const ref=db.doc(`organizations/${orgId}/analyticsSnapshots/${id}`);try{await ref.create(row);return row;}catch(error:any){if(error?.code===6||String(error?.message||'').toLowerCase().includes('already exists')){const existing=await ref.get();if(existing.exists)return existing.data() as AnalyticsSnapshot;}throw error;}
}

async function listSnapshots(orgId:string,limit=60){const snap=await adminDb().collection(`organizations/${orgId}/analyticsSnapshots`).orderBy('snapshotDate','desc').limit(Math.min(Math.max(limit,1),120)).get();return snap.docs.map(d=>d.data() as AnalyticsSnapshot).sort((a,b)=>a.snapshotDate.localeCompare(b.snapshotDate));}
function monthlySeries(rows:AnalyticsSnapshot[],metricCode:string){const m=new Map<string,{period:string;value:number}>();for(const r of rows){const v=r.metrics[metricCode];if(Number.isFinite(v))m.set(r.snapshotDate.slice(0,7),{period:r.snapshotDate.slice(0,7),value:Number(v)});}return[...m.values()].sort((a,b)=>a.period.localeCompare(b.period));}
function buildForecast(model:AnalyticsForecastModel,history:AnalyticsSnapshot[]):AnalyticsForecastRun{
  const series=monthlySeries(history,model.metricCode);if(series.length<model.minimumHistoryPoints)throw new ApiError(409,`Forecast requires at least ${model.minimumHistoryPoints} monthly history points; ${series.length} available.`,'insufficient_forecast_history');const calc=forecastMonthlySeries(series,{metricCode:model.metricCode,modelType:model.modelType,horizonPeriods:model.horizonPeriods,confidenceLevel:model.confidenceLevel,rollingWindow:model.rollingWindow});return{id:randomUUID(),modelId:model.id,modelCode:model.code,modelVersion:model.version,metricCode:model.metricCode,generatedAt:now(),historyStart:series[0].period,historyEnd:series[series.length-1].period,historyPoints:series.length,forecast:calc.forecast,diagnostics:calc.diagnostics,dataQualityWarnings:calc.warnings,assumptions:model.assumptions,confidenceLevel:model.confidenceLevel,status:'draft',generatedBy:'system:forecast-engine'};
}

export async function createForecastModel(actor:ActorContext,raw:unknown){requireManage(actor);const input=forecastModelSchema.parse(raw),db=adminDb(),metricSnap=await db.collection(`organizations/${actor.orgId}/analyticsMetrics`).where('code','==',input.metricCode).limit(1).get();if(metricSnap.empty)throw new ApiError(404,'Metric definition not found.','analytics_metric_not_found');const metric=metricSnap.docs[0].data() as AnalyticsMetricDefinition;if(metric.status!=='active')throw new ApiError(409,'Forecast model requires an active metric definition.','metric_not_active');const id=randomUUID(),timestamp=now(),indexRef=db.doc(`organizations/${actor.orgId}/analyticsForecastModelCodeIndex/${hash(input.code)}`);await db.runTransaction(async tx=>{const ix=await tx.get(indexRef);if(ix.exists)throw new ApiError(409,'Forecast model code already exists.','forecast_model_code_exists');const row:AnalyticsForecastModel={id,...input,version:1,status:'draft',createdBy:actor.uid,createdAt:timestamp,updatedAt:timestamp};tx.create(db.doc(`organizations/${actor.orgId}/analyticsForecastModels/${id}`),row);tx.create(indexRef,{modelId:id,code:input.code,createdAt:timestamp});const audit=buildAudit(actor,{action:'analytics.forecast_model.create',entityType:'analyticsForecastModel',entityId:id,after:row});tx.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);});return(await db.doc(`organizations/${actor.orgId}/analyticsForecastModels/${id}`).get()).data() as AnalyticsForecastModel;}
export async function actOnForecastModel(actor:ActorContext,id:string,raw:unknown){requireManage(actor);const input=forecastModelActionSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/analyticsForecastModels/${id}`),snap=await ref.get();if(!snap.exists)throw new ApiError(404,'Forecast model not found.','forecast_model_not_found');const before=snap.data() as AnalyticsForecastModel;if(input.action==='activate'){requireApprove(actor);if(before.status!=='draft')throw new ApiError(409,'Only draft models can be activated.','invalid_forecast_model_state');const after={...before,status:'active' as const,approvedBy:actor.uid,approvedAt:now(),updatedAt:now()};const audit=buildAudit(actor,{action:'analytics.forecast_model.activate',entityType:'analyticsForecastModel',entityId:id,before,after});const batch=db.batch();batch.set(ref,after);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return after;}if(input.action==='retire'){const after={...before,status:'retired' as const,updatedAt:now()};const audit=buildAudit(actor,{action:'analytics.forecast_model.retire',entityType:'analyticsForecastModel',entityId:id,before,after});const batch=db.batch();batch.set(ref,after);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return after;}if(before.status!=='active')throw new ApiError(409,'Only active forecast models can run.','forecast_model_not_active');const history=await listSnapshots(actor.orgId,120),run=buildForecast(before,history);run.generatedBy=actor.uid;const audit=buildAudit(actor,{action:'analytics.forecast.run',entityType:'analyticsForecastRun',entityId:run.id,after:run});const batch=db.batch();batch.create(db.doc(`organizations/${actor.orgId}/analyticsForecastRuns/${run.id}`),run);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return run;}
export async function actOnForecastRun(actor:ActorContext,id:string,raw:unknown){requireManage(actor);const input=forecastRunActionSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/analyticsForecastRuns/${id}`),snap=await ref.get();if(!snap.exists)throw new ApiError(404,'Forecast run not found.','forecast_run_not_found');const before=snap.data() as AnalyticsForecastRun;let after:AnalyticsForecastRun;if(input.action==='review'){if(before.status!=='draft')throw new ApiError(409,'Only draft forecast runs can be reviewed.','invalid_forecast_state');after={...before,status:'reviewed',reviewedBy:actor.uid,reviewedAt:now(),reviewNote:input.note};}else{requireApprove(actor);if(input.action==='approve'){if(before.status!=='reviewed')throw new ApiError(409,'Forecast must be reviewed before approval.','forecast_review_required');if(before.reviewedBy===actor.uid)throw new ApiError(409,'Forecast reviewer cannot approve the same run.','segregation_required');after={...before,status:'approved',approvedBy:actor.uid,approvedAt:now(),reviewNote:before.reviewNote};}else{after={...before,status:'rejected',reviewedBy:actor.uid,reviewedAt:now(),reviewNote:input.note};}}
  const audit=buildAudit(actor,{action:`analytics.forecast.${input.action}`,entityType:'analyticsForecastRun',entityId:id,before,after});const batch=db.batch();batch.set(ref,after);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);if(input.action==='approve'){const ev=buildDomainEvent(actor,'analytics.forecast_approved','analyticsForecastRun',id,{modelId:after.modelId,metricCode:after.metricCode,historyPoints:after.historyPoints});batch.create(db.doc(`organizations/${actor.orgId}/domainEvents/${ev.id}`),ev);}await batch.commit();return after;}

export async function peopleAnalyticsDashboard(actor:ActorContext):Promise<PeopleAnalyticsDashboard>{requireRead(actor);let history=await listSnapshots(actor.orgId,60);let latest=history[history.length-1];if(!latest||latest.snapshotDate!==today()){latest=await generateAnalyticsSnapshot(actor.orgId,actor.uid);history=await listSnapshots(actor.orgId,60);}const [metrics,models,runs]=await Promise.all([loadAll<AnalyticsMetricDefinition>(actor.orgId,'analyticsMetrics'),loadAll<AnalyticsForecastModel>(actor.orgId,'analyticsForecastModels'),loadAll<AnalyticsForecastRun>(actor.orgId,'analyticsForecastRuns')]);const warnings:string[]=[];const months=new Set(history.map(h=>h.snapshotDate.slice(0,7))).size;if(months<6)warnings.push('Fewer than six monthly history points are available; forecasts should remain exploratory.');if(!metrics.some(m=>m.status==='active'))warnings.push('No active governed metric definitions are configured. Run the analytics bootstrap before production use.');const score=Math.max(0,100-(months<6?25:0)-(warnings.length>1?10:0));return{latestSnapshot:latest,history,metrics:metrics.sort((a,b)=>a.code.localeCompare(b.code)),forecastModels:models.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),forecastRuns:runs.sort((a,b)=>b.generatedAt.localeCompare(a.generatedAt)).slice(0,50),quality:{score,warnings,historyPoints:months,lastSnapshotDate:latest.snapshotDate},headline:[{key:'headcount',label:'Active headcount',value:latest.metrics['workforce.headcount']||0,unit:'count',helper:'Authoritative active worker count'},{key:'fte',label:'Active FTE',value:latest.metrics['workforce.fte']||0,unit:'fte',helper:'Current active employment FTE'},{key:'cost',label:'Estimated employer cost',value:latest.metrics['workforce.employer_cost']||0,unit:'currency',helper:'Planning estimate, not payroll actual'},{key:'turnover',label:'Turnover YTD',value:latest.metrics['lifecycle.turnover_ytd_pct']||0,unit:'percent',helper:'Directional operational rate'},{key:'vacancies',label:'Vacancies',value:latest.metrics['workforce.vacancies']||0,unit:'count',helper:'Open/planned or unoccupied positions'},{key:'skillgaps',label:'Verified skill gaps',value:latest.metrics['talent.verified_skill_gaps']||0,unit:'count',helper:'Requirements vs verified evidence'}],governanceNotice:'People Analytics v1.9 provides descriptive aggregate metrics and simple governed forecasts. Forecasts are exploratory decision-support evidence, not predictions about individual employees and not automated employment decisions. Small segmented groups are suppressed; protected-characteristic inference and individual attrition/retirement scoring are intentionally excluded.',generatedAt:now()};}

async function notifyOnce(orgId:string,key:string,input:any){const db=adminDb(),ref=db.doc(`organizations/${orgId}/notificationDedupe/${hash(key)}`);try{await ref.create({key,createdAt:now()});const id=randomUUID();await db.doc(`organizations/${orgId}/notifications/${id}`).create({id,type:'people_analytics',category:'people_analytics',priority:input.priority||'normal',...input,status:'unread',inAppVisible:true,emailStatus:'disabled',emailAttempts:0,createdAt:now(),updatedAt:now()});return true;}catch{return false;}}
export async function processPeopleAnalyticsGovernance(orgId:string){const actor=systemActor(orgId,'system:people-analytics-governance'),db=adminDb(),summary={snapshotCreated:0,modelsScanned:0,forecastsRun:0,insufficientHistory:0,notifications:0};const snapRef=db.doc(`organizations/${orgId}/analyticsSnapshots/daily_${today()}`);if(!(await snapRef.get()).exists){await generateAnalyticsSnapshot(orgId,actor.uid);summary.snapshotCreated=1;}const [models,history]=await Promise.all([loadAll<AnalyticsForecastModel>(orgId,'analyticsForecastModels'),listSnapshots(orgId,120)]);for(const model of models.filter(m=>m.status==='active')){summary.modelsScanned++;const month=today().slice(0,7),runKey=`${model.id}:${month}`,existing=await db.collection(`organizations/${orgId}/analyticsForecastRuns`).where('modelId','==',model.id).where('generatedAt','>=',`${month}-01T00:00:00.000Z`).limit(1).get();if(!existing.empty)continue;try{const run=buildForecast(model,history);const batch=db.batch();batch.create(db.doc(`organizations/${orgId}/analyticsForecastRuns/${run.id}`),run);const ev=buildDomainEvent(actor,'analytics.forecast_generated' as any,'analyticsForecastRun',run.id,{modelId:model.id,metricCode:model.metricCode,historyPoints:run.historyPoints});batch.create(db.doc(`organizations/${orgId}/domainEvents/${ev.id}`),ev);await batch.commit();summary.forecastsRun++;}catch(e){if(e instanceof ApiError&&e.code==='insufficient_forecast_history'){summary.insufficientHistory++;if(await notifyOnce(orgId,`analytics-history:${runKey}`,{title:'Forecast history is insufficient',message:`Forecast model “${model.name}” does not yet have the required monthly history.`,targetRole:'hr_admin',entityType:'analyticsForecastModel',entityId:model.id,priority:'normal'}))summary.notifications++;}else throw e;}}
  return summary;}
