import { z } from 'zod';
const evidenceRef=z.object({sourceType:z.enum(['policy','document','learning','analytics','safety','compensation','employee_relations','time','external_reference']),sourceId:z.string().min(1).max(200),label:z.string().min(2).max(200),note:z.string().max(1000).optional(),sourceUrl:z.string().url().optional()});
export const diagnosticAssessmentCreateSchema=z.object({frameworkId:z.string().min(1),name:z.string().min(3).max(180),scopeNote:z.string().min(5).max(2000),profile:z.object({jurisdiction:z.string().min(2).max(80).default('Ontario, Canada'),currentEmployeeCount:z.number().int().min(0).max(1_000_000),ontarioEmployeesJan1:z.number().int().min(0).max(1_000_000),organizationType:z.enum(['business','nonprofit','public_sector','other']),isProvinciallyRegulated:z.boolean(),isPublicSector:z.boolean(),notes:z.string().max(1000).optional()})});
export const diagnosticControlAssessmentSchema=z.object({applicability:z.enum(['pending','applicable','not_applicable']),status:z.enum(['not_assessed','met','partially_met','not_met','not_applicable']),evidenceRefs:z.array(evidenceRef).max(20).default([]),assessorNote:z.string().max(4000).optional()}).superRefine((v,ctx)=>{if(v.applicability==='not_applicable'&&v.status!=='not_applicable')ctx.addIssue({code:'custom',message:'Not-applicable controls must use not_applicable status.',path:['status']});if(v.applicability==='applicable'&&v.status==='not_applicable')ctx.addIssue({code:'custom',message:'Applicable controls cannot use not_applicable status.',path:['status']});});
export const diagnosticAssessmentActionSchema=z.object({action:z.enum(['start','submit_review','approve','close','reassess'])});
export const diagnosticRemediationPlanSchema=z.object({title:z.string().min(3).max(180),ownerRole:z.string().min(2).max(80).default('hr_admin'),dueDate:z.string().date(),successMetric:z.string().min(5).max(1000),tasks:z.array(z.object({title:z.string().min(3).max(180),description:z.string().max(1000).optional(),ownerRole:z.string().min(2).max(80).default('hr_admin'),dueDate:z.string().date()})).min(1).max(20)});
export const diagnosticRemediationActionSchema=z.object({action:z.enum(['approve','cancel','complete'])});
export const diagnosticRemediationTaskActionSchema=z.object({action:z.enum(['complete','reopen'])});
export const diagnosticFindingActionSchema=z.object({action:z.enum(['accept_risk','resolve','reopen']),reason:z.string().max(2000).optional()}).superRefine((v,ctx)=>{if(v.action==='accept_risk'&&(!v.reason||v.reason.trim().length<10))ctx.addIssue({code:'custom',message:'Accepted risk requires a documented reason.',path:['reason']});});
