import { createHash, randomUUID } from 'crypto';
import type { ActorContext } from '@/domain/security';
import type {
  ComplianceRequirement, EmployeeDocument, EmployeeDocumentVersion, Policy, PolicyAcknowledgement,
  PolicyVersion, RetentionRule, WorkerComplianceRow,
} from '@/domain/compliance';
import type { Worker, Assignment, Employment } from '@/domain/hr';
import { adminBucket, adminDb } from '@/lib/firebase/admin';
import { ApiError } from '@/lib/http/errors';
import { buildAudit } from '@/lib/audit/service';
import { buildDomainEvent } from '@/lib/events/build';
import { isDirectReport } from '@/lib/hr/service';
import {
  acknowledgementSchema, complianceRequirementSchema, documentActionSchema, documentMetadataSchema,
  policyActionSchema, policyCreateSchema, policyVersionSchema, retentionRuleSchema,
} from './schemas';

const now=()=>new Date().toISOString();
const today=()=>now().slice(0,10);
const hrRoles=new Set(['super_admin','org_admin','hr_admin','hr_partner']);
const adminRoles=new Set(['super_admin','org_admin','hr_admin']);
const sha=(value:Buffer|string)=>createHash('sha256').update(value).digest('hex');
const addDays=(date:string,days:number)=>{const d=new Date(`${date.slice(0,10)}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);};
const addMonths=(date:string,months:number)=>{const d=new Date(`${date.slice(0,10)}T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+months);return d.toISOString().slice(0,10);};
const validMagic=(bytes:Buffer,type:string)=>{if(type==='application/pdf')return bytes.subarray(0,5).toString()==='%PDF-';if(type==='image/png')return bytes.subarray(0,8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]));if(type==='image/jpeg')return bytes.length>3&&bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff;if(type==='application/vnd.openxmlformats-officedocument.wordprocessingml.document'){const head=bytes.subarray(0,2).toString();const text=bytes.toString('latin1');return head==='PK'&&text.includes('[Content_Types].xml')&&text.includes('word/');}return false;};
const requireCleanScan=()=>process.env.OPSIQO_REQUIRE_CLEAN_DOCUMENT_SCAN==='true'&&!process.env.FIRESTORE_EMULATOR_HOST&&process.env.OPSIQO_DEMO_MODE!=='true';

async function workerExists(orgId:string,workerId:string){const s=await adminDb().doc(`organizations/${orgId}/workers/${workerId}`).get();if(!s.exists)throw new ApiError(404,'Employee not found.','worker_not_found');return s.data() as Worker;}
async function canReadWorker(actor:ActorContext,workerId:string){if(hrRoles.has(actor.role))return true;if(actor.workerId===workerId)return true;if(actor.role==='manager')return isDirectReport(actor,workerId);return false;}
async function assertReadWorker(actor:ActorContext,workerId:string){if(!(await canReadWorker(actor,workerId)))throw new ApiError(403,'Employee document access is outside your permitted scope.','forbidden');}

function computeRetention(rule:RetentionRule|undefined,createdAt:string,expiryDate?:string){if(!rule||!rule.enabled)return undefined;if(rule.trigger==='document_created')return addDays(createdAt,rule.retentionDays);if(rule.trigger==='document_expiry'&&expiryDate)return addDays(expiryDate,rule.retentionDays);return undefined;}
async function getRetentionRule(orgId:string,id?:string){if(!id)return undefined;const s=await adminDb().doc(`organizations/${orgId}/retentionRules/${id}`).get();if(!s.exists)throw new ApiError(400,'Retention rule not found.','retention_rule_not_found');return s.data() as RetentionRule;}

export async function listEmployeeDocuments(actor:ActorContext,workerId?:string){
  const db=adminDb();
  let resolved=workerId;
  if(!hrRoles.has(actor.role)){resolved=resolved||actor.workerId;if(!resolved)throw new ApiError(409,'Worker-linked membership required.','worker_link_required');await assertReadWorker(actor,resolved);}
  let q:any=db.collection(`organizations/${actor.orgId}/employeeDocuments`);
  if(resolved)q=q.where('workerId','==',resolved);
  const snap=await q.orderBy('updatedAt','desc').limit(300).get();
  const docs=snap.docs.map((d:any)=>d.data() as EmployeeDocument);
  const versions=await Promise.all(docs.map(async d=>{const s=await db.doc(`organizations/${actor.orgId}/employeeDocumentVersions/${d.currentVersionId}`).get();const v=s.exists?s.data() as EmployeeDocumentVersion:undefined;return [d.id,v] as const;}));
  const versionMap=Object.fromEntries(versions);const visible=hrRoles.has(actor.role)?docs:docs.filter(d=>d.classification!=='highly_confidential'&&(actor.workerId===d.workerId?['employee_and_hr','manager_employee_hr'].includes(d.visibility):actor.role==='manager'&&d.visibility==='manager_employee_hr'));
  return visible.map(d=>({...d,currentVersion:versionMap[d.id]||null}));
}

export async function uploadEmployeeDocument(actor:ActorContext,form:FormData){
  if(!hrRoles.has(actor.role))throw new ApiError(403,'HR document-management permission required.','forbidden');
  const file=form.get('file');if(!(file instanceof File))throw new ApiError(400,'Document file is required.','file_required');
  if(file.size<=0||file.size>15*1024*1024)throw new ApiError(400,'File must be between 1 byte and 15 MB.','invalid_file_size');
  const allowed=new Set(['application/pdf','image/jpeg','image/png','application/vnd.openxmlformats-officedocument.wordprocessingml.document']);
  if(!allowed.has(file.type))throw new ApiError(400,'Only PDF, JPG, PNG and DOCX files are accepted.','unsupported_file_type');
  const input=documentMetadataSchema.parse({workerId:String(form.get('workerId')||''),title:String(form.get('title')||''),category:String(form.get('category')||''),classification:String(form.get('classification')||'confidential'),visibility:String(form.get('visibility')||'employee_and_hr'),issueDate:String(form.get('issueDate')||''),expiryDate:String(form.get('expiryDate')||''),retentionRuleId:String(form.get('retentionRuleId')||'')});
  await workerExists(actor.orgId,input.workerId);
  const rule=await getRetentionRule(actor.orgId,input.retentionRuleId||undefined);
  const timestamp=now(),documentId=randomUUID(),versionId=randomUUID();
  const safeName=file.name.replace(/[^A-Za-z0-9._-]/g,'_').slice(-140),bytes=Buffer.from(await file.arrayBuffer());if(!validMagic(bytes,file.type))throw new ApiError(400,'File signature does not match the declared file type.','file_signature_mismatch');
  const storagePath=`organizations/${actor.orgId}/employee-documents/${input.workerId}/${documentId}/v1-${versionId}-${safeName}`;
  await adminBucket().file(storagePath).save(bytes,{resumable:false,contentType:file.type,metadata:{cacheControl:'private,max-age=0,no-store',metadata:{orgId:actor.orgId,workerId:input.workerId,documentId,versionId}}});
  const version:EmployeeDocumentVersion={id:versionId,documentId,workerId:input.workerId,version:1,fileName:safeName,contentType:file.type,size:file.size,storagePath,sha256:sha(bytes),scanStatus:'not_scanned',uploadedBy:actor.uid,uploadedAt:timestamp};
  const doc:EmployeeDocument={id:documentId,workerId:input.workerId,title:input.title,category:input.category,classification:input.classification,visibility:input.classification==='highly_confidential'?'hr_only':input.visibility,status:'active',currentVersionId:versionId,versionCount:1,issueDate:input.issueDate||undefined,expiryDate:input.expiryDate||undefined,retentionRuleId:input.retentionRuleId||undefined,retentionUntil:computeRetention(rule,timestamp,input.expiryDate||undefined),legalHold:false,createdBy:actor.uid,createdAt:timestamp,updatedAt:timestamp};
  const audit=buildAudit(actor,{action:'document.create',entityType:'employeeDocument',entityId:documentId,after:{...doc,file:{fileName:safeName,size:file.size,sha256:version.sha256,scanStatus:version.scanStatus}}});
  const event=buildDomainEvent(actor,'document.uploaded','employeeDocument',documentId,{workerId:doc.workerId,category:doc.category});
  const batch=adminDb().batch();batch.create(adminDb().doc(`organizations/${actor.orgId}/employeeDocuments/${documentId}`),doc);batch.create(adminDb().doc(`organizations/${actor.orgId}/employeeDocumentVersions/${versionId}`),version);batch.create(adminDb().doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);batch.create(adminDb().doc(`organizations/${actor.orgId}/domainEvents/${event.id}`),event);await batch.commit();
  return{...doc,currentVersion:version};
}

export async function addDocumentVersion(actor:ActorContext,documentId:string,file:File){
  if(!hrRoles.has(actor.role))throw new ApiError(403,'HR document-management permission required.','forbidden');
  if(file.size<=0||file.size>15*1024*1024)throw new ApiError(400,'File must be between 1 byte and 15 MB.','invalid_file_size');
  const allowed=new Set(['application/pdf','image/jpeg','image/png','application/vnd.openxmlformats-officedocument.wordprocessingml.document']);if(!allowed.has(file.type))throw new ApiError(400,'Unsupported file type.','unsupported_file_type');
  const db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/employeeDocuments/${documentId}`),snap=await ref.get();if(!snap.exists)throw new ApiError(404,'Employee document not found.','document_not_found');const doc=snap.data() as EmployeeDocument;if(doc.status==='disposed'||doc.status==='pending_disposal')throw new ApiError(409,'Disposed or pending-disposal records cannot receive a new version.','document_locked_for_disposal');
  const timestamp=now(),versionId=randomUUID(),number=doc.versionCount+1,safeName=file.name.replace(/[^A-Za-z0-9._-]/g,'_').slice(-140),bytes=Buffer.from(await file.arrayBuffer());if(!validMagic(bytes,file.type))throw new ApiError(400,'File signature does not match the declared file type.','file_signature_mismatch');const storagePath=`organizations/${actor.orgId}/employee-documents/${doc.workerId}/${doc.id}/v${number}-${versionId}-${safeName}`;
  await adminBucket().file(storagePath).save(bytes,{resumable:false,contentType:file.type,metadata:{cacheControl:'private,max-age=0,no-store'}});
  const version:EmployeeDocumentVersion={id:versionId,documentId,workerId:doc.workerId,version:number,fileName:safeName,contentType:file.type,size:file.size,storagePath,sha256:sha(bytes),scanStatus:'not_scanned',uploadedBy:actor.uid,uploadedAt:timestamp};
  const patch={currentVersionId:versionId,versionCount:number,status:'active',updatedAt:timestamp};const audit=buildAudit(actor,{action:'document.version.create',entityType:'employeeDocument',entityId:documentId,before:doc,after:{...doc,...patch,currentFile:safeName}});
  const batch=db.batch();batch.create(db.doc(`organizations/${actor.orgId}/employeeDocumentVersions/${versionId}`),version);batch.set(db.doc(`organizations/${actor.orgId}/employeeDocumentVersions/${doc.currentVersionId}`),{supersededAt:timestamp},{merge:true});batch.set(ref,patch,{merge:true});batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return{...doc,...patch,currentVersion:version};
}

export async function downloadEmployeeDocument(actor:ActorContext,documentId:string){const db=adminDb();const snap=await db.doc(`organizations/${actor.orgId}/employeeDocuments/${documentId}`).get();if(!snap.exists)throw new ApiError(404,'Document not found.','document_not_found');const doc=snap.data() as EmployeeDocument;await assertReadWorker(actor,doc.workerId);if(!hrRoles.has(actor.role)&&(doc.classification==='highly_confidential'||(actor.workerId===doc.workerId?!['employee_and_hr','manager_employee_hr'].includes(doc.visibility):doc.visibility!=='manager_employee_hr')))throw new ApiError(403,'Document visibility does not permit access.','forbidden');if(doc.status==='disposed')throw new ApiError(410,'Document has been disposed.','document_disposed');const vs=await db.doc(`organizations/${actor.orgId}/employeeDocumentVersions/${doc.currentVersionId}`).get();if(!vs.exists)throw new ApiError(404,'Current document version not found.','version_not_found');const version=vs.data() as EmployeeDocumentVersion;if(version.scanStatus==='blocked')throw new ApiError(423,'Document is quarantined.','document_quarantined');if(requireCleanScan()&&version.scanStatus!=='clean')throw new ApiError(423,'Document download is blocked until malware scanning reports clean.','scan_required');const[bytes]=await adminBucket().file(version.storagePath).download();return{doc,version,bytes};}

export async function actOnDocument(actor:ActorContext,documentId:string,raw:unknown){const input=documentActionSchema.parse(raw);const db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/employeeDocuments/${documentId}`),snap=await ref.get();if(!snap.exists)throw new ApiError(404,'Document not found.','document_not_found');const doc=snap.data() as EmployeeDocument;if(!hrRoles.has(actor.role))throw new ApiError(403,'HR document-management permission required.','forbidden');if(['dispose','place_legal_hold','release_legal_hold','set_scan_clean','set_scan_blocked'].includes(input.action)&&!adminRoles.has(actor.role))throw new ApiError(403,'HR administrator permission required for this document control.','forbidden');
  const timestamp=now();let patch:any={updatedAt:timestamp};if(input.action==='set_scan_clean'||input.action==='set_scan_blocked'){const scanStatus=input.action==='set_scan_clean'?'clean':'blocked';await db.doc(`organizations/${actor.orgId}/employeeDocumentVersions/${doc.currentVersionId}`).set({scanStatus},{merge:true});patch.status=scanStatus==='blocked'?'quarantined':'active';}
  if(input.action==='place_legal_hold'){patch.legalHold=true;patch.legalHoldReason=input.reason||'Legal hold placed by HR administrator.';}
  if(input.action==='release_legal_hold'){patch.legalHold=false;patch.legalHoldReason=null;}
  if(input.action==='dispose'){if(doc.legalHold)throw new ApiError(409,'Document is under legal hold and cannot be disposed.','legal_hold');if(doc.status!=='pending_disposal')throw new ApiError(409,'Document must first be marked pending disposal by the retention review.','retention_review_required');const versions=await db.collection(`organizations/${actor.orgId}/employeeDocumentVersions`).where('documentId','==',doc.id).get();for(const versionSnap of versions.docs){const v=versionSnap.data() as EmployeeDocumentVersion;if(v.storagePath)await adminBucket().file(v.storagePath).delete({ignoreNotFound:true});}patch.status='disposed';patch.disposedAt=timestamp;patch.disposedBy=actor.uid;patch.disposalReason=input.reason||'Approved retention disposition';patch.disposedVersionCount=versions.size;}
  const audit=buildAudit(actor,{action:`document.${input.action}`,entityType:'employeeDocument',entityId:documentId,before:doc,after:{...doc,...patch}});const batch=db.batch();batch.set(ref,patch,{merge:true});batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return{...doc,...patch};}

export async function listRetentionRules(actor:ActorContext){if(!hrRoles.has(actor.role))throw new ApiError(403,'HR permission required.','forbidden');const s=await adminDb().collection(`organizations/${actor.orgId}/retentionRules`).orderBy('name').get();return s.docs.map(d=>d.data() as RetentionRule);}
export async function createRetentionRule(actor:ActorContext,raw:unknown){if(!adminRoles.has(actor.role))throw new ApiError(403,'HR administrator permission required.','forbidden');const input=retentionRuleSchema.parse(raw),timestamp=now(),id=randomUUID();const rule:RetentionRule={id,...input,createdBy:actor.uid,createdAt:timestamp,updatedAt:timestamp};const audit=buildAudit(actor,{action:'retention.rule.create',entityType:'retentionRule',entityId:id,after:rule});const batch=adminDb().batch();batch.create(adminDb().doc(`organizations/${actor.orgId}/retentionRules/${id}`),rule);batch.create(adminDb().doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return rule;}

export async function listPolicies(actor:ActorContext){const snap=await adminDb().collection(`organizations/${actor.orgId}/policies`).orderBy('updatedAt','desc').limit(200).get();const all=snap.docs.map(d=>d.data() as Policy);if(hrRoles.has(actor.role))return all;return all.filter(p=>Boolean(p.currentPublishedVersionId)&&p.status!=='archived').map(p=>({...p,status:'published' as const}));}
export async function createPolicy(actor:ActorContext,raw:unknown){if(!hrRoles.has(actor.role))throw new ApiError(403,'HR policy-management permission required.','forbidden');const input=policyCreateSchema.parse(raw),db=adminDb(),timestamp=now(),policyId=randomUUID(),versionId=randomUUID();const dup=await db.collection(`organizations/${actor.orgId}/policies`).where('code','==',input.code).limit(1).get();if(!dup.empty)throw new ApiError(409,'Policy code already exists.','policy_code_exists');const nextReviewDate=input.reviewFrequencyMonths?addMonths(input.effectiveDate,input.reviewFrequencyMonths):undefined;const policy:Policy={id:policyId,code:input.code,title:input.title,ownerUid:actor.uid,latestVersionNumber:1,status:'draft',acknowledgementRequired:input.acknowledgementRequired,onboardingRequired:input.onboardingRequired,audience:input.audience,audienceOrgUnitIds:input.audienceOrgUnitIds,audienceEmploymentTypes:input.audienceEmploymentTypes,reviewFrequencyMonths:input.reviewFrequencyMonths,nextReviewDate,createdAt:timestamp,updatedAt:timestamp};const version:PolicyVersion={id:versionId,policyId,versionNumber:1,versionLabel:input.versionLabel,content:input.content,contentSha256:sha(input.content),status:'draft',effectiveDate:input.effectiveDate,createdBy:actor.uid,createdAt:timestamp};const audit=buildAudit(actor,{action:'policy.create',entityType:'policy',entityId:policyId,after:{...policy,versionId,contentSha256:version.contentSha256}});const batch=db.batch();batch.create(db.doc(`organizations/${actor.orgId}/policies/${policyId}`),policy);batch.create(db.doc(`organizations/${actor.orgId}/policyVersions/${versionId}`),version);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return{policy,version};}
export async function createPolicyVersion(actor:ActorContext,policyId:string,raw:unknown){if(!hrRoles.has(actor.role))throw new ApiError(403,'HR policy-management permission required.','forbidden');const input=policyVersionSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/policies/${policyId}`),snap=await ref.get();if(!snap.exists)throw new ApiError(404,'Policy not found.','policy_not_found');const policy=snap.data() as Policy;if(policy.status==='archived')throw new ApiError(409,'Archived policies cannot receive new versions.','policy_archived');if(policy.status==='draft'||policy.status==='in_review'||policy.status==='approved')throw new ApiError(409,'Finish the current draft lifecycle before creating another version.','policy_version_in_progress');const timestamp=now(),versionId=randomUUID(),n=policy.latestVersionNumber+1;const version:PolicyVersion={id:versionId,policyId,versionNumber:n,versionLabel:input.versionLabel,content:input.content,contentSha256:sha(input.content),status:'draft',effectiveDate:input.effectiveDate,createdBy:actor.uid,createdAt:timestamp};const patch={latestVersionNumber:n,status:'draft',updatedAt:timestamp};const audit=buildAudit(actor,{action:'policy.version.create',entityType:'policy',entityId:policyId,before:policy,after:{...policy,...patch,versionId,contentSha256:version.contentSha256}});const batch=db.batch();batch.create(db.doc(`organizations/${actor.orgId}/policyVersions/${versionId}`),version);batch.set(ref,patch,{merge:true});batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return{policy:{...policy,...patch},version};}
async function latestPolicyVersion(orgId:string,policy:Policy){const snap=await adminDb().collection(`organizations/${orgId}/policyVersions`).where('policyId','==',policy.id).where('versionNumber','==',policy.latestVersionNumber).limit(1).get();if(snap.empty)throw new ApiError(409,'Latest policy version is missing.','policy_version_missing');return snap.docs[0].data() as PolicyVersion;}
export async function actOnPolicy(actor:ActorContext,policyId:string,raw:unknown){const input=policyActionSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/policies/${policyId}`),snap=await ref.get();if(!snap.exists)throw new ApiError(404,'Policy not found.','policy_not_found');const policy=snap.data() as Policy;const version=await latestPolicyVersion(actor.orgId,policy),timestamp=now();let pPatch:any={updatedAt:timestamp},vPatch:any={};if(input.action==='submit_review'){if(!hrRoles.has(actor.role)||version.status!=='draft')throw new ApiError(409,'Only a draft can be submitted for review.','invalid_policy_state');pPatch.status='in_review';vPatch={status:'in_review',submittedAt:timestamp};}
  if(input.action==='approve'){if(!adminRoles.has(actor.role))throw new ApiError(403,'HR administrator approval required.','forbidden');if(version.status!=='in_review')throw new ApiError(409,'Policy must be in review before approval.','invalid_policy_state');if(version.createdBy===actor.uid)throw new ApiError(409,'Policy creator cannot approve their own version.','segregation_of_duties');pPatch.status='approved';vPatch={status:'approved',approvedBy:actor.uid,approvedAt:timestamp};}
  if(input.action==='publish'){if(!adminRoles.has(actor.role))throw new ApiError(403,'HR administrator publishing permission required.','forbidden');if(version.status!=='approved')throw new ApiError(409,'Only an approved policy version can be published.','invalid_policy_state');if(version.effectiveDate>today())throw new ApiError(409,'Future-effective publication is not yet active. Publish on or after the effective date.','future_effective_policy');pPatch.status='published';pPatch.currentPublishedVersionId=version.id;if(policy.reviewFrequencyMonths)pPatch.nextReviewDate=addMonths(version.effectiveDate,policy.reviewFrequencyMonths);vPatch={status:'published',publishedBy:actor.uid,publishedAt:timestamp};}
  if(input.action==='archive'){if(!adminRoles.has(actor.role))throw new ApiError(403,'HR administrator permission required.','forbidden');pPatch.status='archived';vPatch={status:'archived'};}
  const audit=buildAudit(actor,{action:`policy.${input.action}`,entityType:'policy',entityId:policyId,before:{policy,version},after:{policy:{...policy,...pPatch},version:{...version,...vPatch}}});const batch=db.batch();batch.set(ref,pPatch,{merge:true});batch.set(db.doc(`organizations/${actor.orgId}/policyVersions/${version.id}`),vPatch,{merge:true});if(input.action==='publish'&&policy.currentPublishedVersionId&&policy.currentPublishedVersionId!==version.id)batch.set(db.doc(`organizations/${actor.orgId}/policyVersions/${policy.currentPublishedVersionId}`),{status:'superseded',supersededAt:timestamp},{merge:true});batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);if(input.action==='publish'){const event=buildDomainEvent(actor,'policy.published','policy',policyId,{versionId:version.id,versionLabel:version.versionLabel,acknowledgementRequired:policy.acknowledgementRequired});batch.create(db.doc(`organizations/${actor.orgId}/domainEvents/${event.id}`),event);}await batch.commit();return{policy:{...policy,...pPatch},version:{...version,...vPatch}};}
export async function getPolicy(actor:ActorContext,policyId:string){const db=adminDb(),snap=await db.doc(`organizations/${actor.orgId}/policies/${policyId}`).get();if(!snap.exists)throw new ApiError(404,'Policy not found.','policy_not_found');const policy=snap.data() as Policy;if(!hrRoles.has(actor.role)&&(!policy.currentPublishedVersionId||policy.status==='archived'))throw new ApiError(403,'Policy is not published.','forbidden');const versions=await db.collection(`organizations/${actor.orgId}/policyVersions`).where('policyId','==',policyId).orderBy('versionNumber','desc').get();const rows=versions.docs.map(d=>d.data() as PolicyVersion);return{policy:hrRoles.has(actor.role)?policy:{...policy,status:'published' as const},versions:hrRoles.has(actor.role)?rows:rows.filter(v=>v.id===policy.currentPublishedVersionId)};}
export async function acknowledgePolicy(actor:ActorContext,policyId:string,raw:unknown){if(!actor.workerId)throw new ApiError(409,'Worker-linked membership required.','worker_link_required');const input=acknowledgementSchema.parse(raw),db=adminDb(),p=await getPolicy(actor,policyId),policy=p.policy;if(!policy.currentPublishedVersionId)throw new ApiError(409,'Policy has no published version.','policy_not_published');const version=p.versions.find(v=>v.id===policy.currentPublishedVersionId)||(await db.doc(`organizations/${actor.orgId}/policyVersions/${policy.currentPublishedVersionId}`).get()).data() as PolicyVersion;const ackId=sha(`${actor.workerId}:${policy.id}:${version.id}`),ref=db.doc(`organizations/${actor.orgId}/policyAcknowledgements/${ackId}`),existing=await ref.get();if(existing.exists)return existing.data() as PolicyAcknowledgement;const timestamp=now();const ack:PolicyAcknowledgement={id:ackId,workerId:actor.workerId,policyId:policy.id,policyVersionId:version.id,policyVersionLabel:version.versionLabel,acknowledgedAt:timestamp,method:'authenticated_employee_portal',signerUid:actor.uid,signerName:input.signerName,contentSha256:version.contentSha256};const audit=buildAudit(actor,{action:'policy.acknowledge',entityType:'policyAcknowledgement',entityId:ackId,after:ack});const event=buildDomainEvent(actor,'policy.acknowledged','policy',policy.id,{workerId:actor.workerId,versionId:version.id});const batch=db.batch();batch.create(ref,ack);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);batch.create(db.doc(`organizations/${actor.orgId}/domainEvents/${event.id}`),event);await batch.commit();return ack;}
export async function myPolicyAcknowledgements(actor:ActorContext){if(!actor.workerId)return[];const s=await adminDb().collection(`organizations/${actor.orgId}/policyAcknowledgements`).where('workerId','==',actor.workerId).get();return s.docs.map(d=>d.data() as PolicyAcknowledgement);}

export async function listComplianceRequirements(actor:ActorContext){if(!actor.permissions.includes('compliance.read'))throw new ApiError(403,'Compliance permission required.','forbidden');const s=await adminDb().collection(`organizations/${actor.orgId}/complianceRequirements`).orderBy('name').get();return s.docs.map(d=>d.data() as ComplianceRequirement);}
export async function createComplianceRequirement(actor:ActorContext,raw:unknown){if(!hrRoles.has(actor.role))throw new ApiError(403,'HR compliance-management permission required.','forbidden');const input=complianceRequirementSchema.parse(raw),timestamp=now(),id=randomUUID();const item:ComplianceRequirement={id,...input,createdBy:actor.uid,createdAt:timestamp,updatedAt:timestamp};const audit=buildAudit(actor,{action:'compliance.requirement.create',entityType:'complianceRequirement',entityId:id,after:item});const batch=adminDb().batch();batch.create(adminDb().doc(`organizations/${actor.orgId}/complianceRequirements/${id}`),item);batch.create(adminDb().doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return item;}

function currentAssignment(assignments:Assignment[],workerId:string){const d=today();return assignments.find(a=>a.workerId===workerId&&a.primary&&a.startDate<=d&&(!a.endDate||a.endDate>=d));}
function currentEmployment(employments:Employment[],workerId:string){const d=today();return employments.find(e=>e.workerId===workerId&&e.startDate<=d&&(!e.endDate||e.endDate>=d));}
export async function complianceDashboard(actor:ActorContext){if(!actor.permissions.includes('compliance.read'))throw new ApiError(403,'Compliance permission required.','forbidden');const db=adminDb();const [ws,rs,ds,as,ps,vs,ms,assigns,emps]=await Promise.all([
  db.collection(`organizations/${actor.orgId}/workers`).where('status','==','active').limit(500).get(),db.collection(`organizations/${actor.orgId}/complianceRequirements`).get(),db.collection(`organizations/${actor.orgId}/employeeDocuments`).get(),db.collection(`organizations/${actor.orgId}/policyAcknowledgements`).get(),db.collection(`organizations/${actor.orgId}/policies`).get(),db.collection(`organizations/${actor.orgId}/policyVersions`).where('status','==','published').get(),db.collection(`organizations/${actor.orgId}/memberships`).where('status','==','active').get(),db.collection(`organizations/${actor.orgId}/assignments`).get(),db.collection(`organizations/${actor.orgId}/employments`).get(),
  ]);let workers=ws.docs.map(d=>d.data() as Worker);if(!hrRoles.has(actor.role)){if(actor.role==='manager'&&actor.workerId){const direct=(await Promise.all(workers.map(async w=>(await isDirectReport(actor,w.id))?w:null))).filter(Boolean) as Worker[];workers=workers.filter(w=>w.id===actor.workerId).concat(direct.filter(w=>w.id!==actor.workerId));}else workers=workers.filter(w=>w.id===actor.workerId);}
  const requirements=rs.docs.map(d=>d.data() as ComplianceRequirement),docs=ds.docs.map(d=>d.data() as EmployeeDocument),acks=as.docs.map(d=>d.data() as PolicyAcknowledgement),policies=ps.docs.map(d=>d.data() as Policy).filter(p=>Boolean(p.currentPublishedVersionId)&&p.status!=='archived'),versions=vs.docs.map(d=>d.data() as PolicyVersion),members=ms.docs.map(d=>d.data() as any),assignments=assigns.docs.map(d=>d.data() as Assignment),employments=emps.docs.map(d=>d.data() as Employment);const memberRoleByWorker=Object.fromEntries(members.filter(m=>m.workerId).map(m=>[m.workerId,m.role]));const warningDate=(days:number)=>addDays(today(),days);
  const rows:WorkerComplianceRow[]=workers.map(w=>{let required=0,compliant=0,overdue=0,expiring=0;const a=currentAssignment(assignments,w.id),e=currentEmployment(employments,w.id);for(const r of requirements){let applies=r.appliesTo==='all_employees'||(r.appliesTo==='managers'&&memberRoleByWorker[w.id]==='manager');if(r.appliesTo==='custom'){applies=(!r.orgUnitIds?.length||Boolean(a&&r.orgUnitIds.includes(a.orgUnitId)))&&(!r.employmentTypes?.length||Boolean(e&&r.employmentTypes.includes(e.employmentType)));}if(!applies||!r.required)continue;required++;let ok=false;if(r.requirementType==='document'&&r.documentCategory){const candidates=docs.filter(d=>d.workerId===w.id&&d.category===r.documentCategory&&d.status!=='disposed'&&d.status!=='quarantined');const valid=candidates.find(d=>!d.expiryDate||d.expiryDate>=today());ok=Boolean(valid);if(valid?.expiryDate&&valid.expiryDate<=warningDate(r.expiryWarningDays||30))expiring++;}else if(r.requirementType==='policy_ack'&&r.policyId){const p=policies.find(x=>x.id===r.policyId);if(p?.currentPublishedVersionId)ok=acks.some(x=>x.workerId===w.id&&x.policyId===p.id&&x.policyVersionId===p.currentPublishedVersionId);}else if(r.requirementType==='training'){ok=false;}if(ok)compliant++;else overdue++;}return{workerId:w.id,displayName:w.displayName,employeeNumber:w.employeeNumber,required,compliant,overdue,expiring,score:required?Math.round(compliant/required*100):100};});const required=rows.reduce((n,r)=>n+r.required,0),compliant=rows.reduce((n,r)=>n+r.compliant,0);return{metrics:{workers:rows.length,requirements:requirements.length,complianceRate:required?Math.round(compliant/required*100):100,gaps:rows.reduce((n,r)=>n+r.overdue,0),expiring:rows.reduce((n,r)=>n+r.expiring,0)},rows,requirements,policies:policies.map(p=>({...p,currentVersion:versions.find(v=>v.id===p.currentPublishedVersionId)||null}))};}

export async function processDocumentGovernance(orgId:string,limit=200){
  const db=adminDb(),timestamp=now(),day=today(),warning=addDays(day,30);
  const snap=await db.collection(`organizations/${orgId}/employeeDocuments`).where('status','in',['active','expired']).limit(Math.max(1,Math.min(limit,500))).get();
  const summary={scanned:snap.size,expired:0,expiring:0,pendingDisposal:0,retentionCalculated:0,notifications:0};
  const ruleCache=new Map<string,RetentionRule|undefined>(),employmentCache=new Map<string,Employment[]>();
  for(const s of snap.docs){
    const d=s.data() as EmployeeDocument;let patch:any={};
    if(!d.retentionUntil&&d.retentionRuleId){
      let rule=ruleCache.get(d.retentionRuleId);
      if(!ruleCache.has(d.retentionRuleId)){const rs=await db.doc(`organizations/${orgId}/retentionRules/${d.retentionRuleId}`).get();rule=rs.exists?rs.data() as RetentionRule:undefined;ruleCache.set(d.retentionRuleId,rule);}
      if(rule?.enabled){
        let retentionUntil=computeRetention(rule,d.createdAt,d.expiryDate);
        if(rule.trigger==='employment_end'){
          let employments=employmentCache.get(d.workerId);
          if(!employments){const es=await db.collection(`organizations/${orgId}/employments`).where('workerId','==',d.workerId).get();const rows=es.docs.map(x=>x.data() as Employment);employmentCache.set(d.workerId,rows);employments=rows;}
          const employmentRows=employments||[];
          const active=employmentRows.some(e=>e.startDate<=day&&(!e.endDate||e.endDate>=day));
          if(!active){const ended=employmentRows.map(e=>e.endDate).filter((x):x is string=>Boolean(x)&&x!<=day).sort().at(-1);if(ended)retentionUntil=addDays(ended,rule.retentionDays);}
        }
        if(retentionUntil){patch.retentionUntil=retentionUntil;summary.retentionCalculated++;}
      }
    }
    const effectiveRetention=patch.retentionUntil||d.retentionUntil;
    if(d.expiryDate&&d.expiryDate<day&&d.status==='active'){patch.status='expired';summary.expired++;}
    else if(d.expiryDate&&d.expiryDate>=day&&d.expiryDate<=warning&&d.status==='active'){
      summary.expiring++;const key=sha(`doc-expiring:${d.id}:${d.expiryDate}`),nref=db.doc(`organizations/${orgId}/notificationDedupe/${key}`),existing=await nref.get();
      if(!existing.exists){const id=randomUUID(),created=timestamp;const batch=db.batch();batch.create(nref,{id,createdAt:created});batch.create(db.doc(`organizations/${orgId}/notifications/${id}`),{id,title:'Employee document expiring',message:`${d.title} expires on ${d.expiryDate}.`,category:'compliance',priority:'high',targetRole:'hr_admin',status:'unread',inAppVisible:true,emailStatus:'pending',emailAttempts:0,createdAt:created,updatedAt:created});const systemActor={uid:'system:document-governance',orgId,role:'org_admin',permissions:[]} as ActorContext;const event=buildDomainEvent(systemActor,'document.expiring','employeeDocument',d.id,{workerId:d.workerId,expiryDate:d.expiryDate,category:d.category});batch.create(db.doc(`organizations/${orgId}/domainEvents/${event.id}`),event);await batch.commit();summary.notifications++;}
    }
    if(effectiveRetention&&effectiveRetention<=day&&!d.legalHold&&d.status!=='pending_disposal'&&d.status!=='disposed'){patch.status='pending_disposal';summary.pendingDisposal++;}
    if(Object.keys(patch).length)await s.ref.set({...patch,updatedAt:timestamp},{merge:true});
  }
  return summary;
}

export async function processPolicyGovernance(orgId:string,limit=200){
  const db=adminDb(),timestamp=now(),day=today(),warning=addDays(day,30);
  const snap=await db.collection(`organizations/${orgId}/policies`).limit(Math.max(1,Math.min(limit,500))).get();
  const summary={scanned:snap.size,dueSoon:0,overdue:0,notifications:0};
  for(const policySnap of snap.docs){
    const p=policySnap.data() as Policy;
    if(p.status==='archived'||!p.currentPublishedVersionId||!p.nextReviewDate||p.nextReviewDate>warning)continue;
    const overdue=p.nextReviewDate<day;if(overdue)summary.overdue++;else summary.dueSoon++;
    const key=sha(`policy-review:${p.id}:${p.nextReviewDate}`),nref=db.doc(`organizations/${orgId}/notificationDedupe/${key}`);
    if((await nref.get()).exists)continue;
    const id=randomUUID(),title=overdue?'Policy review overdue':'Policy review due soon';
    const batch=db.batch();
    batch.create(nref,{id,createdAt:timestamp});
    batch.create(db.doc(`organizations/${orgId}/notifications/${id}`),{id,title,message:`${p.code} · ${p.title} review date is ${p.nextReviewDate}.`,category:'compliance',priority:overdue?'high':'normal',targetRole:'hr_admin',status:'unread',inAppVisible:true,emailStatus:'pending',emailAttempts:0,createdAt:timestamp,updatedAt:timestamp});
    const systemActor={uid:'system:policy-governance',orgId,role:'org_admin',permissions:[]} as ActorContext;
    const event=buildDomainEvent(systemActor,'policy.review_due','policy',p.id,{reviewDate:p.nextReviewDate,overdue});
    batch.create(db.doc(`organizations/${orgId}/domainEvents/${event.id}`),event);
    await batch.commit();summary.notifications++;
  }
  return summary;
}

export async function promotePrehireEvidence(actor:ActorContext,caseId:string,workerId:string){
  if(!adminRoles.has(actor.role))throw new ApiError(403,'HR administrator permission required to promote prehire evidence.','forbidden');
  const db=adminDb(),timestamp=now(),docsSnap=await db.collection(`organizations/${actor.orgId}/prehireDocuments`).where('caseId','==',caseId).get(),tasksSnap=await db.collection(`organizations/${actor.orgId}/onboardingTasks`).where('caseId','==',caseId).get();
  const tasks=Object.fromEntries(tasksSnap.docs.map(d=>[d.id,d.data() as any]));let documentsPromoted=0,acknowledgementsPromoted=0;
  for(const s of docsSnap.docs){const pre=s.data() as any;const marker=db.doc(`organizations/${actor.orgId}/prehireEvidencePromotion/${pre.id}`);if((await marker.get()).exists)continue;const task=tasks[pre.taskId]||{};const category=String(task.title||'').toLowerCase().includes('payroll')?'payroll_tax':'employment';const documentId=sha(`prehire-document:${pre.id}`),versionId=sha(`prehire-version:${pre.id}`);const safeName=String(pre.fileName||'prehire-document').replace(/[^A-Za-z0-9._-]/g,'_').slice(-140);const targetPath=`organizations/${actor.orgId}/employee-documents/${workerId}/${documentId}/v1-${versionId}-${safeName}`;
    const source=adminBucket().file(pre.storagePath),target=adminBucket().file(targetPath);const[exists]=await target.exists();if(!exists)await source.copy(target);
    const version:EmployeeDocumentVersion={id:versionId,documentId,workerId,version:1,fileName:safeName,contentType:pre.contentType,size:pre.size,storagePath:targetPath,sha256:pre.sha256,scanStatus:pre.scanStatus||'not_scanned',uploadedBy:'candidate',uploadedAt:pre.uploadedAt};
    const doc:EmployeeDocument={id:documentId,workerId,title:task.title||safeName,category:category as any,classification:'confidential',visibility:'employee_and_hr',status:pre.scanStatus==='blocked'?'quarantined':'active',currentVersionId:versionId,versionCount:1,legalHold:false,createdBy:actor.uid,createdAt:pre.uploadedAt||timestamp,updatedAt:timestamp};
    const batch=db.batch();batch.set(db.doc(`organizations/${actor.orgId}/employeeDocuments/${documentId}`),doc,{merge:false});batch.set(db.doc(`organizations/${actor.orgId}/employeeDocumentVersions/${versionId}`),version,{merge:false});batch.create(marker,{prehireDocumentId:pre.id,documentId,workerId,promotedAt:timestamp,promotedBy:actor.uid});await batch.commit();documentsPromoted++;}
  const ackSnap=await db.collection(`organizations/${actor.orgId}/policyAcknowledgements`).where('caseId','==',caseId).get();for(const s of ackSnap.docs){const pre=s.data() as any;if(!pre.policyId||!pre.policyVersionId)continue;const id=sha(`${workerId}:${pre.policyId}:${pre.policyVersionId}`),ref=db.doc(`organizations/${actor.orgId}/policyAcknowledgements/${id}`);if((await ref.get()).exists)continue;const ack:PolicyAcknowledgement={id,workerId,policyId:pre.policyId,policyVersionId:pre.policyVersionId,policyVersionLabel:pre.policyVersion||pre.policyVersionLabel||'unknown',acknowledgedAt:pre.acknowledgedAt,method:'secure_prehire_portal',signerName:pre.signerName||'Prehire candidate',contentSha256:pre.contentSha256||''};await ref.create(ack);acknowledgementsPromoted++;}
  const audit=buildAudit(actor,{action:'onboarding.evidence.promote',entityType:'onboardingCase',entityId:caseId,after:{workerId,documentsPromoted,acknowledgementsPromoted}});await db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`).create(audit);return{documentsPromoted,acknowledgementsPromoted};
}
