import { useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput } from 'react-native';
import { apiFetch } from '@/api/client';
import { useAuth } from '@/auth/provider';
import { useBootstrap } from '@/hooks/use-bootstrap';
import { Button, Card, H1, H2, Muted } from '@/components/ui';
import { colors } from '@/theme/tokens';
export default function Copilot(){const{activeOrgId}=useAuth();const{data}=useBootstrap();const[question,setQuestion]=useState('');const[busy,setBusy]=useState(false);const[result,setResult]=useState<any>(null);const[message,setMessage]=useState('');async function ask(){if(!activeOrgId||!question.trim())return;setBusy(true);setMessage('');setResult(null);try{const r=await apiFetch<{data:any}>(`/api/organizations/${activeOrgId}/ai-copilot/query`,{method:'POST',orgId:activeOrgId,body:JSON.stringify({question})});setResult(r.data);}catch(e){setMessage(e instanceof Error?e.message:'OPSIQO Copilot is unavailable.')}finally{setBusy(false)}}return <ScrollView style={{backgroundColor:colors.bg}} contentContainerStyle={s.content}><H1>Ask OPSIQO</H1><Muted>Evidence-first HR guidance. The Copilot cannot approve leave, change pay, discipline employees, or make employment decisions.</Muted>{!data?.capabilities.aiCopilot?<Card><Muted>AI Copilot is not enabled for your current OPSIQO membership.</Muted></Card>:<Card><Text style={s.label}>What do you need help with?</Text><TextInput value={question} onChangeText={setQuestion} style={s.input} multiline placeholder="How many vacation hours do I have and what is the request process?"/><Button title={busy?'Thinking…':'Ask OPSIQO'} onPress={()=>void ask()} disabled={busy||question.trim().length<3}/></Card>}{result?<Card><H2>{result.status==='completed'?'Guidance':'Copilot result'}</H2>{result.answer?.summary?<Text style={s.answer}>{result.answer.summary}</Text>:null}{(result.answer?.findings||[]).map((x:string,i:number)=><Text key={i} style={s.bullet}>• {x}</Text>)}{result.blockedReason?<Text style={s.error}>{result.blockedReason}</Text>:null}<Muted>Confidence: {result.answer?.confidence??'—'}% · Evidence completeness: {result.answer?.evidenceCompleteness??'—'}%{result.answer?.requiresHumanDecision?' · Human review required':''}</Muted></Card>:null}{message?<Card><Text style={s.error}>{message}</Text></Card>:null}</ScrollView>}
const s=StyleSheet.create({content:{padding:18,gap:14},label:{fontSize:13,fontWeight:'800',color:colors.text},input:{minHeight:110,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:12,backgroundColor:'#fff',fontSize:15,color:colors.text,textAlignVertical:'top'},answer:{fontSize:15,lineHeight:22,color:colors.text},bullet:{fontSize:14,lineHeight:20,color:colors.text},error:{color:colors.danger,fontWeight:'600'}});
