import { useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { apiFetch } from '@/api/client';
import { useAuth } from '@/auth/provider';
import { useBootstrap } from '@/hooks/use-bootstrap';
import { Button, Card, H1, H2, Loading, Muted } from '@/components/ui';
import { colors } from '@/theme/tokens';
export default function Learning(){const{activeOrgId}=useAuth();const{data,loading,reload}=useBootstrap();const[busy,setBusy]=useState('');const[message,setMessage]=useState('');if(loading&&!data)return <View style={s.loading}><Loading label="Loading learning…"/></View>;const workerId=data?.actor.workerId;const learning=data?.learning||{};const assignments=(learning.assignments||[]).filter((a:any)=>!workerId||a.workerId===workerId);const courses=new Map((learning.courses||[]).map((c:any)=>[c.id,c]));const certificates=(learning.certificates||[]).filter((c:any)=>!workerId||c.workerId===workerId);async function start(id:string){if(!activeOrgId)return;setBusy(id);setMessage('');try{await apiFetch(`/api/organizations/${activeOrgId}/learning/assignments/${id}`,{method:'PATCH',orgId:activeOrgId,body:JSON.stringify({action:'start'})});setMessage('Learning assignment started.');await reload();}catch(e){setMessage(e instanceof Error?e.message:'Learning action failed.')}finally{setBusy('')}}return <ScrollView style={{backgroundColor:colors.bg}} contentContainerStyle={s.content}><H1>Learning & certificates</H1><Card><H2>My learning</H2>{assignments.length?assignments.map((a:any)=>{const c:any=courses.get(a.courseId);return <View key={a.id} style={s.row}><Text style={s.title}>{c?.title||a.courseId}</Text><Muted>Status: {String(a.status).replaceAll('_',' ')}{a.dueAt?` · Due ${new Date(a.dueAt).toLocaleDateString()}`:''}</Muted>{['assigned','failed'].includes(a.status)?<Button title={busy===a.id?'Starting…':'Start learning'} onPress={()=>void start(a.id)} disabled={Boolean(busy)} secondary/>:null}</View>}):<Muted>No learning assignments are currently assigned.</Muted>}</Card><Card><H2>Certificates</H2>{certificates.length?certificates.map((c:any)=><View key={c.id} style={s.row}><Text style={s.title}>{c.certificateNumber||'Learning certificate'}</Text><Muted>Status: {c.status}{c.issuedAt?` · Issued ${new Date(c.issuedAt).toLocaleDateString()}`:''}{c.expiresAt?` · Expires ${new Date(c.expiresAt).toLocaleDateString()}`:''}</Muted></View>):<Muted>No current certificates are available.</Muted>}</Card>{message?<Card><Text style={s.message}>{message}</Text></Card>:null}</ScrollView>}
const s=StyleSheet.create({content:{padding:18,gap:14},loading:{flex:1,backgroundColor:colors.bg,justifyContent:'center'},row:{paddingVertical:10,borderBottomWidth:1,borderBottomColor:colors.line,gap:6},title:{fontSize:15,fontWeight:'800',color:colors.text},message:{color:colors.navy,fontWeight:'700'}});
