import { useState } from 'react';
import { router } from 'expo-router';
import { ScrollView, StyleSheet, Text } from 'react-native';
import { useAuth } from '@/auth/provider';
import { useBootstrap } from '@/hooks/use-bootstrap';
import { registerDevice } from '@/mobile/device';
import { Button, Card, H1, H2, Muted } from '@/components/ui';
import { colors } from '@/theme/tokens';
export default function Me(){const{activeOrgId,organizations,selectOrg,signOut}=useAuth();const{data}=useBootstrap();const[message,setMessage]=useState('');const worker=data?.employee?.worker;async function notifications(){if(!activeOrgId)return;try{await registerDevice(activeOrgId,{requestPush:true});setMessage('Mobile notifications enabled for this device.');}catch(e){setMessage(e instanceof Error?e.message:'Could not register this device.')}}return <ScrollView style={{backgroundColor:colors.bg}} contentContainerStyle={s.content}><H1>Me</H1><Card><H2>{worker?.displayName||'Employee profile'}</H2><Muted>{data?.employee?.assignment?.positionTitle||'Employee'}</Muted><Muted>Role: {data?.actor.role.replaceAll('_',' ')}</Muted></Card><Card><H2>Digital employee ID</H2><Text style={s.idName}>{worker?.displayName||'Employee'}</Text><Muted>Employee #: {worker?.employeeNumber||'Not assigned'}</Muted><Muted>{data?.employee?.assignment?.positionTitle||'Employee'}{data?.employee?.assignment?.orgUnitName?` · ${data.employee.assignment.orgUnitName}`:''}</Muted><Muted>Organization: {organizations.find(o=>o.orgId===activeOrgId)?.name||activeOrgId}</Muted><Text style={s.verified}>AUTHENTICATED OPSIQO PROFILE</Text></Card><Card><H2>Organization</H2>{organizations.map(o=><Text key={o.orgId} onPress={()=>void selectOrg(o.orgId)} style={[s.org,o.orgId===activeOrgId&&s.active]}>{o.name}{o.orgId===activeOrgId?' ✓':''}</Text>)}</Card><Card><H2>Mobile security</H2><Muted>Your sign-in stays active on this device with no app-imposed session timeout. Short-lived Firebase access tokens refresh automatically in the background. Explicit sign-out, administrator revocation, account disablement or credential revocation still ends access. Face ID, Touch ID or Android biometrics can be used to verify attendance actions without sending biometric templates to OPSIQO.</Muted><Button title="Enable mobile notifications" onPress={()=>void notifications()} secondary/></Card>{message?<Card><Text style={s.message}>{message}</Text></Card>:null}<Button title="Sign out" onPress={()=>void signOut().then(()=>router.replace('/sign-in'))} secondary/></ScrollView>}
const s=StyleSheet.create({content:{padding:18,gap:14},org:{paddingVertical:10,fontSize:15,color:colors.text},active:{fontWeight:'900',color:colors.teal},message:{color:colors.navy,fontWeight:'700'},idName:{fontSize:22,fontWeight:'900',color:colors.navy},verified:{fontSize:11,fontWeight:'900',letterSpacing:.8,color:colors.teal,marginTop:4}});
