import { useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { apiFetch } from '@/api/client';
import { useAuth } from '@/auth/provider';
import { useBootstrap } from '@/hooks/use-bootstrap';
import { Button, Card, H1, H2, Muted } from '@/components/ui';
import { colors } from '@/theme/tokens';
const TYPES=['near_miss','injury','illness','first_aid','workplace_violence','property_damage','exposure','other'] as const;
export default function Safety(){const{activeOrgId}=useAuth();const{data}=useBootstrap();const[type,setType]=useState<(typeof TYPES)[number]>('near_miss');const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[location,setLocation]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');async function submit(){if(!activeOrgId)return;setBusy(true);setMessage('');try{await apiFetch(`/api/organizations/${activeOrgId}/safety/incidents`,{method:'POST',orgId:activeOrgId,body:JSON.stringify({type,title,description,severity:'moderate',affectedWorkerId:data?.actor.workerId,location,occurredAt:new Date().toISOString(),immediateActions:[],medicalAttention:false,lostTime:false,modifiedWork:false,firstAidOnly:type==='first_aid'})});setTitle('');setDescription('');setLocation('');setMessage('Safety report submitted for governed review.');}catch(e){setMessage(e instanceof Error?e.message:'Safety report failed.')}finally{setBusy(false)}}return <ScrollView style={{backgroundColor:colors.bg}} contentContainerStyle={s.content}><H1>Safety reporting</H1><Muted>Use this for hazards, near misses, injuries, workplace violence, property damage, or other workplace safety events. Emergency situations should use local emergency procedures first.</Muted>{!data?.capabilities.safety?<Card><Muted>Safety reporting is not enabled for your current membership.</Muted></Card>:<Card><H2>Report an incident</H2><View style={s.chips}>{TYPES.map(x=><Text key={x} onPress={()=>setType(x)} style={[s.chip,type===x&&s.chipActive]}>{x.replaceAll('_',' ')}</Text>)}</View><TextInput value={title} onChangeText={setTitle} style={s.input} placeholder="Short title"/><TextInput value={location} onChangeText={setLocation} style={s.input} placeholder="Location"/><TextInput value={description} onChangeText={setDescription} style={[s.input,{minHeight:120}]} multiline placeholder="Describe what happened, what you observed, and any immediate actions taken."/><Button title={busy?'Submitting…':'Submit safety report'} onPress={()=>void submit()} disabled={busy||title.trim().length<4||description.trim().length<20}/></Card>}{message?<Card><Text style={s.message}>{message}</Text></Card>:null}</ScrollView>}
const s=StyleSheet.create({content:{padding:18,gap:14},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{paddingHorizontal:9,paddingVertical:7,borderRadius:10,borderWidth:1,borderColor:colors.line,color:colors.text,textTransform:'capitalize'},chipActive:{backgroundColor:colors.teal,color:'#fff',borderColor:colors.teal},input:{borderWidth:1,borderColor:colors.line,borderRadius:12,padding:12,backgroundColor:'#fff',fontSize:15,color:colors.text,textAlignVertical:'top'},message:{color:colors.navy,fontWeight:'700'}});
