import { z } from 'zod';
const iso=z.string().datetime(); const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
export const incidentCreateSchema=z.object({type:z.enum(['injury','illness','near_miss','exposure','first_aid','workplace_violence','property_damage','environmental','fatality','other']),title:z.string().min(4).max(200),description:z.string().min(20).max(10000),severity:z.enum(['low','moderate','serious','critical','fatal']).default('moderate'),affectedWorkerId:z.string().optional(),location:z.string().max(250).optional(),occurredAt:iso,immediateActions:z.array(z.string().min(2).max(1000)).max(25).default([]),medicalAttention:z.boolean().default(false),lostTime:z.boolean().default(false),modifiedWork:z.boolean().default(false),firstAidOnly:z.boolean().default(false)});
export const incidentReviewSchema=z.object({action:z.enum(['triage','start_investigation','complete_investigation','move_to_actions','start_rtw','record_reporting_review','record_submission','release_scene','close','cancel','reopen']),note:z.string().max(5000).optional(),rootCauseSummary:z.string().max(8000).optional(),mlitsdReview:z.enum(['not_reviewed','not_required','potentially_required','required','submitted']).optional(),committeeNoticeReview:z.enum(['not_reviewed','not_required','potentially_required','required','submitted']).optional(),wsibReview:z.enum(['not_reviewed','not_required','potentially_required','required','submitted']).optional(),mlitsdReference:z.string().max(200).optional(),wsibClaimNumber:z.string().max(200).optional()});
export const hazardCreateSchema=z.object({title:z.string().min(4).max(200),description:z.string().min(10).max(8000),location:z.string().max(250).optional(),category:z.string().min(2).max(120),likelihood:z.number().int().min(1).max(5),consequence:z.number().int().min(1).max(5),linkedIncidentId:z.string().optional(),existingControls:z.array(z.string().min(2).max(1000)).max(30).default([]),recommendedControls:z.array(z.string().min(2).max(1000)).max(30).default([]),ownerUid:z.string().optional(),dueAt:iso.optional()});
export const investigationSchema=z.object({leadUid:z.string().min(1),teamUids:z.array(z.string().min(1)).max(20).default([]),method:z.enum(['five_whys','fishbone','barrier_analysis','other']).default('five_whys'),facts:z.array(z.string().min(2).max(2000)).max(100).default([]),contributingFactors:z.array(z.string().min(2).max(2000)).max(100).default([]),rootCauses:z.array(z.string().min(2).max(2000)).min(1).max(50),recommendations:z.array(z.string().min(2).max(2000)).max(50).default([])});
export const correctiveActionSchema=z.object({incidentId:z.string().optional(),hazardId:z.string().optional(),title:z.string().min(4).max(240),description:z.string().max(5000).optional(),controlType:z.enum(['elimination','substitution','engineering','administrative','ppe','other']),ownerUid:z.string().optional(),ownerRole:z.string().max(80).optional(),dueAt:iso.optional(),blockingClosure:z.boolean().default(true)}).refine(v=>Boolean(v.incidentId||v.hazardId),{message:'Incident or hazard linkage is required.'}).refine(v=>Boolean(v.ownerUid||v.ownerRole),{message:'Action owner is required.'});
export const correctiveActionUpdateSchema=z.object({action:z.enum(['start','complete','waive','reopen']),note:z.string().max(5000).optional()});
export const rtwSchema=z.object({workerId:z.string().min(1),functionalAbilities:z.array(z.string().min(2).max(500)).min(1).max(30),limitations:z.array(z.string().min(2).max(500)).max(30).default([]),temporaryDuties:z.array(z.string().min(2).max(1000)).min(1).max(30),hoursSchedule:z.string().max(1000).optional(),contactCadence:z.string().max(500).optional(),startDate:date.optional(),reviewDate:date.optional(),endDate:date.optional(),wsibClaimNumber:z.string().max(200).optional()});
export const inspectionSchema=z.object({location:z.string().min(2).max(250),inspectionType:z.enum(['workplace','equipment','ergonomic','fire','first_aid','ppe','other']),scheduledFor:iso.optional(),conductedByUids:z.array(z.string().min(1)).max(20).default([])});
export const inspectionFindingSchema=z.object({title:z.string().min(4).max(240),description:z.string().min(10).max(5000),likelihood:z.number().int().min(1).max(5),consequence:z.number().int().min(1).max(5),createHazard:z.boolean().default(true)});
export const committeeProfileSchema=z.object({workplaceName:z.string().min(2).max(240),regularWorkerCount:z.number().int().min(0).max(100000),governanceType:z.enum(['none','hsr','jhsc','review_required']),requirementSource:z.string().min(10).max(2000),reviewNote:z.string().max(3000).optional(),certifiedWorkerMemberUid:z.string().optional(),certifiedEmployerMemberUid:z.string().optional(),meetingFrequency:z.string().max(200).optional(),nextMeetingDate:date.optional()});
export const committeeMeetingSchema=z.object({meetingDate:date,memberUids:z.array(z.string().min(1)).min(1).max(100),minutesDocumentId:z.string().optional(),recommendations:z.array(z.string().min(2).max(2000)).max(100).default([]),employerResponses:z.array(z.string().min(2).max(2000)).max(100).default([])});

export const inspectionUpdateSchema=z.object({action:z.enum(['start','complete','cancel']),summary:z.string().max(5000).optional()});
export const recommendationResponseSchema=z.object({response:z.string().min(10).max(8000),implementationTarget:date.optional(),close:z.boolean().default(false)});
