import { createHash, randomUUID } from 'crypto';
import type { ActorContext } from '@/domain/security';
import type { SafetyCorrectiveAction,SafetyDashboard,SafetyHazard,SafetyIncident,SafetyInspection,SafetyInspectionFinding,SafetyInvestigation,ReturnToWorkPlan,SafetyCommitteeProfile,SafetyCommitteeMeeting,SafetyCommitteeRecommendation } from '@/domain/safety';
import { adminDb } from '@/lib/firebase/admin';
import { ApiError } from '@/lib/http/errors';
import { buildAudit } from '@/lib/audit/service';
import { buildDomainEvent } from '@/lib/events/build';
import { systemActor } from '@/lib/automation/system-actor';
import { incidentCreateSchema,incidentReviewSchema,hazardCreateSchema,investigationSchema,correctiveActionSchema,correctiveActionUpdateSchema,rtwSchema,inspectionSchema,inspectionFindingSchema,committeeProfileSchema,committeeMeetingSchema,inspectionUpdateSchema,recommendationResponseSchema } from './schemas';

const now=()=>new Date().toISOString(); const today=()=>now().slice(0,10);
const adminRoles=new Set(['super_admin','org_admin','hr_admin']); const safetyRoles=new Set(['super_admin','org_admin','hr_admin','hr_partner']);
function hash(v:string){return createHash('sha256').update(v).digest('hex');}
function addHours(value:string,hours:number){return new Date(new Date(value).getTime()+hours*3600000).toISOString();}
function addDays(value:string,days:number){return new Date(new Date(value).getTime()+days*86400000).toISOString();}
function addYears(value:string,years:number){const d=new Date(value);d.setUTCFullYear(d.getUTCFullYear()+years);return d.toISOString();}
function addBusinessDays(value:string,days:number){const d=new Date(value);let left=days;while(left>0){d.setUTCDate(d.getUTCDate()+1);const n=d.getUTCDay();if(n!==0&&n!==6)left--;}return d.toISOString();}
async function workerExists(orgId:string,id:string){return (await adminDb().doc(`organizations/${orgId}/workers/${id}`).get()).exists;}
async function isDirectReport(actor:ActorContext,workerId:string){if(!actor.workerId)return false;const s=await adminDb().collection(`organizations/${actor.orgId}/assignments`).where('workerId','==',workerId).where('status','==','active').limit(20).get();return s.docs.some(d=>d.data().managerWorkerId===actor.workerId);}
async function canViewIncident(actor:ActorContext,i:SafetyIncident){if(safetyRoles.has(actor.role))return true;if(i.reporterUid===actor.uid||i.affectedWorkerId===actor.workerId)return true;if(actor.role==='manager'&&i.affectedWorkerId&&await isDirectReport(actor,i.affectedWorkerId))return true;return false;}
function redactIncident(i:SafetyIncident,actor:ActorContext){if(safetyRoles.has(actor.role)||i.reporterUid===actor.uid||i.affectedWorkerId===actor.workerId)return i;return {...i,wsibClaimNumber:undefined,wsibReviewNote:undefined,mlitsdReviewNote:undefined,rootCauseSummary:undefined,description:'Restricted safety incident — operational details available to authorized H&S/HR personnel.'};}
async function nextRef(orgId:string,counter:string,prefix:string){const db=adminDb(),ref=db.doc(`organizations/${orgId}/counters/${counter}`);return db.runTransaction(async tx=>{const s=await tx.get(ref),n=Number(s.data()?.value||0)+1;tx.set(ref,{value:n,updatedAt:now()},{merge:true});return `${prefix}-${new Date().getUTCFullYear()}-${String(n).padStart(5,'0')}`;});}
async function notifyOnce(orgId:string,key:string,input:any){const db=adminDb(),dedupe=db.doc(`organizations/${orgId}/notificationDedupe/${hash(key)}`);try{await dedupe.create({key,createdAt:now()});const id=randomUUID();await db.doc(`organizations/${orgId}/notifications/${id}`).create({id,type:'safety',category:'health_safety',priority:input.priority||'high',...input,status:'unread',inAppVisible:true,emailStatus:'disabled',emailAttempts:0,createdAt:now(),updatedAt:now()});return true;}catch{return false;}}
async function addAudit(actor:ActorContext,batch:any,action:string,entityType:string,entityId:string,before:any,after:any,metadata?:any){const a=buildAudit(actor,{action,entityType,entityId,before,after,metadata});batch.create(adminDb().doc(`organizations/${actor.orgId}/auditLogs/${a.id}`),a);}
function safetyScreening(input:{type:string;severity:string;medicalAttention:boolean;lostTime:boolean;modifiedWork:boolean;firstAidOnly:boolean;occurredAt:string}){
 const critical=['critical','fatal'].includes(input.severity)||input.type==='fatality';
 const injuryLike=['injury','illness','exposure','workplace_violence','fatality'].includes(input.type);
 const ministryPotential=critical||input.type==='illness'||input.type==='exposure'||((input.type==='injury'||input.type==='workplace_violence')&&(input.medicalAttention||input.lostTime));
 const committeePotential=critical||input.medicalAttention||input.lostTime||input.type==='workplace_violence'||input.type==='illness';
 const wsibPotential=injuryLike&&(input.medicalAttention||input.lostTime||input.modifiedWork||!input.firstAidOnly);
 return {critical,mlitsdReview:ministryPotential?'potentially_required':'not_reviewed' as const,committeeNoticeReview:committeePotential?'potentially_required':'not_reviewed' as const,wsibReview:wsibPotential?'potentially_required':'not_reviewed' as const};
}

export async function createSafetyIncident(actor:ActorContext,raw:unknown){
 if(!actor.permissions.includes('safety.report'))throw new ApiError(403,'Safety reporting permission required.','forbidden');const input=incidentCreateSchema.parse(raw);if(input.affectedWorkerId&&!await workerExists(actor.orgId,input.affectedWorkerId))throw new ApiError(404,'Affected worker not found.','worker_not_found');
 const referenceNumber=await nextRef(actor.orgId,'safetyIncidents','INC'),id=randomUUID(),timestamp=now(),screen=safetyScreening(input);const incident:SafetyIncident={id,referenceNumber,...input,status:'reported',reporterUid:actor.uid,reporterWorkerId:actor.workerId,reportedAt:timestamp,scenePreservationRequired:screen.critical,mlitsdReview:screen.mlitsdReview,mlitsdNoticeTargetAt:screen.critical?input.occurredAt:undefined,mlitsdWrittenReportTargetAt:screen.mlitsdReview==='potentially_required'?(screen.critical?addHours(input.occurredAt,48):addDays(input.occurredAt,4)):undefined,committeeNoticeReview:screen.committeeNoticeReview,committeeNoticeTargetAt:screen.committeeNoticeReview==='potentially_required'&&!screen.critical?addDays(input.occurredAt,4):undefined,wsibReview:screen.wsibReview,wsibReportTargetAt:screen.wsibReview==='potentially_required'?addBusinessDays(timestamp,3):undefined,investigationRequired:screen.critical||['injury','illness','exposure','workplace_violence','near_miss'].includes(input.type),createdAt:timestamp,updatedAt:timestamp};
 const db=adminDb(),batch=db.batch();batch.create(db.doc(`organizations/${actor.orgId}/safetyIncidents/${id}`),incident);const ev=buildDomainEvent(actor,'safety.incident_reported','safetyIncident',id,{referenceNumber,type:input.type,severity:input.severity});batch.create(db.doc(`organizations/${actor.orgId}/domainEvents/${ev.id}`),ev);await addAudit(actor,batch,'safety.incident.create','safetyIncident',id,null,incident,{screeningOnly:true});await batch.commit();
 if(screen.critical)await notifyOnce(actor.orgId,`critical-safety:${id}`,{title:'Critical safety incident requires immediate review',message:`${referenceNumber} is reported as ${input.severity}. Follow the emergency response procedure and immediately review OHSA/MLITSD reporting and scene-preservation obligations.`,targetRole:'hr_admin',entityType:'safetyIncident',entityId:id,priority:'critical'});
 return incident;
}

export async function listSafetyIncidents(actor:ActorContext){if(!actor.permissions.includes('safety.read')&&!actor.permissions.includes('safety.report'))throw new ApiError(403,'Safety access required.','forbidden');const rows=(await adminDb().collection(`organizations/${actor.orgId}/safetyIncidents`).orderBy('reportedAt','desc').limit(500).get()).docs.map(d=>d.data() as SafetyIncident);const out=[];for(const i of rows)if(await canViewIncident(actor,i))out.push(redactIncident(i,actor));return out;}
export async function getSafetyIncident(actor:ActorContext,id:string){const db=adminDb(),snap=await db.doc(`organizations/${actor.orgId}/safetyIncidents/${id}`).get();if(!snap.exists)throw new ApiError(404,'Safety incident not found.','not_found');const i=snap.data() as SafetyIncident;if(!await canViewIncident(actor,i))throw new ApiError(403,'Incident is outside your safety access scope.','forbidden');if(!safetyRoles.has(actor.role))return{incident:redactIncident(i,actor),restricted:true};const [investigations,actions,rtw]=await Promise.all([db.collection(`organizations/${actor.orgId}/safetyInvestigations`).where('incidentId','==',id).limit(10).get(),db.collection(`organizations/${actor.orgId}/safetyCorrectiveActions`).where('incidentId','==',id).limit(200).get(),db.collection(`organizations/${actor.orgId}/returnToWorkPlans`).where('incidentId','==',id).limit(20).get()]);return{incident:i,restricted:false,investigations:investigations.docs.map(d=>d.data()),actions:actions.docs.map(d=>d.data()),returnToWorkPlans:rtw.docs.map(d=>d.data())};}

export async function updateSafetyIncident(actor:ActorContext,id:string,raw:unknown){if(!actor.permissions.includes('safety.manage'))throw new ApiError(403,'Safety management permission required.','forbidden');const input=incidentReviewSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/safetyIncidents/${id}`),snap=await ref.get();if(!snap.exists)throw new ApiError(404,'Safety incident not found.','not_found');const i=snap.data() as SafetyIncident,timestamp=now();let patch:any={updatedAt:timestamp};
 if(input.action==='triage')patch.status='triage';
 if(input.action==='start_investigation'){if(!actor.permissions.includes('safety.investigate'))throw new ApiError(403,'Safety investigation permission required.','forbidden');patch={...patch,status:'investigating',investigationRequired:true,investigationStartedAt:i.investigationStartedAt||timestamp,investigationTargetAt:i.investigationTargetAt||addDays(timestamp,30)};}
 if(input.action==='complete_investigation'){if(!actor.permissions.includes('safety.investigate'))throw new ApiError(403,'Safety investigation permission required.','forbidden');if(!input.rootCauseSummary||input.rootCauseSummary.length<20)throw new ApiError(400,'Root-cause summary is required.','root_cause_required');patch={...patch,status:'corrective_action',investigationCompletedAt:timestamp,rootCauseSummary:input.rootCauseSummary};}
 if(input.action==='move_to_actions')patch.status='corrective_action'; if(input.action==='start_rtw')patch.status='rtw_monitoring';
 if(input.action==='record_reporting_review'){if([input.mlitsdReview,input.committeeNoticeReview,input.wsibReview].includes('submitted' as any))throw new ApiError(400,'Use record_submission to record actual statutory submissions.','submission_action_required');if(input.mlitsdReview)patch.mlitsdReview=input.mlitsdReview;if(input.committeeNoticeReview)patch.committeeNoticeReview=input.committeeNoticeReview;if(input.wsibReview)patch.wsibReview=input.wsibReview;if(input.mlitsdReference)patch.mlitsdReference=input.mlitsdReference;if(input.wsibClaimNumber)patch.wsibClaimNumber=input.wsibClaimNumber;if(input.note){patch.mlitsdReviewNote=input.note;patch.wsibReviewNote=input.note;}}
 if(input.action==='record_submission'){let ohsaWrittenEvidence=false;if(input.mlitsdReview==='submitted'){patch.mlitsdReview='submitted';patch.mlitsdNoticeSubmittedAt=timestamp;patch.mlitsdReference=input.mlitsdReference;ohsaWrittenEvidence=true;}if(input.committeeNoticeReview==='submitted'){patch.committeeNoticeReview='submitted';patch.committeeNoticeSentAt=timestamp;ohsaWrittenEvidence=true;}if(input.wsibReview==='submitted'){patch.wsibReview='submitted';patch.wsibSubmittedAt=timestamp;patch.wsibClaimNumber=input.wsibClaimNumber;}if(ohsaWrittenEvidence)patch.ohsaNoticeReportEvidenceRetentionUntil=addYears(timestamp,3);}
 if(input.action==='release_scene'){if(!i.scenePreservationRequired)throw new ApiError(409,'Scene preservation is not currently flagged.','scene_not_flagged');patch={...patch,scenePreservationRequired:false,sceneReleasedAt:timestamp,sceneReleasedBy:actor.uid};}
 if(input.action==='close'){if(!adminRoles.has(actor.role))throw new ApiError(403,'HR administrator authority is required to close a safety incident.','forbidden');const open=await db.collection(`organizations/${actor.orgId}/safetyCorrectiveActions`).where('incidentId','==',id).where('status','in',['open','in_progress','overdue']).limit(100).get();if(open.docs.some(d=>d.data().blockingClosure))throw new ApiError(409,'Blocking corrective actions remain open.','blocking_actions');if(['not_reviewed','potentially_required','required'].includes(i.mlitsdReview)||['not_reviewed','potentially_required','required'].includes(i.wsibReview)||['not_reviewed','potentially_required','required'].includes(i.committeeNoticeReview))throw new ApiError(409,'Safety reporting reviews must reach a final state (not required or submitted) before closure.','reporting_review_incomplete');patch={...patch,status:'closed',closedAt:timestamp,closedBy:actor.uid,closureSummary:input.note||'Closed after H&S review.'};}
 if(input.action==='cancel'){if(!adminRoles.has(actor.role))throw new ApiError(403,'HR administrator authority required.','forbidden');patch.status='cancelled';}
 if(input.action==='reopen'){if(!adminRoles.has(actor.role)||!['closed','cancelled'].includes(i.status))throw new ApiError(409,'Only closed/cancelled incidents can be reopened by an administrator.','invalid_state');patch={...patch,status:'triage',closedAt:null,closedBy:null};}
 const after={...i,...patch},batch=db.batch();batch.set(ref,patch,{merge:true});if(input.action==='start_investigation'){const ev=buildDomainEvent(actor,'safety.investigation_started','safetyIncident',id,{referenceNumber:i.referenceNumber});batch.create(db.doc(`organizations/${actor.orgId}/domainEvents/${ev.id}`),ev);}if(input.action==='close'){const ev=buildDomainEvent(actor,'safety.incident_closed','safetyIncident',id,{referenceNumber:i.referenceNumber});batch.create(db.doc(`organizations/${actor.orgId}/domainEvents/${ev.id}`),ev);}await addAudit(actor,batch,`safety.incident.${input.action}`,'safetyIncident',id,i,after,{note:input.note});await batch.commit();return after;}

export async function createSafetyHazard(actor:ActorContext,raw:unknown){if(!actor.permissions.includes('safety.report'))throw new ApiError(403,'Safety reporting permission required.','forbidden');const input=hazardCreateSchema.parse(raw),id=randomUUID(),timestamp=now(),referenceNumber=await nextRef(actor.orgId,'safetyHazards','HAZ'),riskScore=input.likelihood*input.consequence;const row:SafetyHazard={id,referenceNumber,...input,riskScore,status:riskScore>=15?'escalated':'open',reportedBy:actor.uid,reportedWorkerId:actor.workerId,createdAt:timestamp,updatedAt:timestamp};const db=adminDb(),b=db.batch();b.create(db.doc(`organizations/${actor.orgId}/safetyHazards/${id}`),row);const ev=buildDomainEvent(actor,'safety.hazard_reported','safetyHazard',id,{referenceNumber,riskScore});b.create(db.doc(`organizations/${actor.orgId}/domainEvents/${ev.id}`),ev);await addAudit(actor,b,'safety.hazard.create','safetyHazard',id,null,row);await b.commit();if(riskScore>=15)await notifyOnce(actor.orgId,`safety-hazard-high:${id}`,{title:'High-risk workplace hazard',message:`${referenceNumber} has an initial risk score of ${riskScore}/25 and requires prompt control review.`,targetRole:'hr_admin',entityType:'safetyHazard',entityId:id,priority:'high'});return row;}
export async function listSafetyHazards(actor:ActorContext){if(!actor.permissions.includes('safety.read')&&!actor.permissions.includes('safety.report'))throw new ApiError(403,'Safety access required.','forbidden');const rows=(await adminDb().collection(`organizations/${actor.orgId}/safetyHazards`).orderBy('createdAt','desc').limit(1000).get()).docs.map(d=>d.data() as SafetyHazard);if(safetyRoles.has(actor.role)||actor.role==='manager')return rows;return rows.filter(h=>h.reportedBy===actor.uid);}

export async function saveSafetyInvestigation(actor:ActorContext,incidentId:string,raw:unknown){if(!actor.permissions.includes('safety.investigate'))throw new ApiError(403,'Safety investigation permission required.','forbidden');const input=investigationSchema.parse(raw),db=adminDb(),inc=await db.doc(`organizations/${actor.orgId}/safetyIncidents/${incidentId}`).get();if(!inc.exists)throw new ApiError(404,'Incident not found.','not_found');const id=`investigation_${incidentId}`,timestamp=now(),existing=await db.doc(`organizations/${actor.orgId}/safetyInvestigations/${id}`).get();const row:SafetyInvestigation={id,incidentId,...input,startedAt:(existing.data() as any)?.startedAt||timestamp,createdAt:(existing.data() as any)?.createdAt||timestamp,updatedAt:timestamp};const b=db.batch();b.set(db.doc(`organizations/${actor.orgId}/safetyInvestigations/${id}`),row,{merge:true});await addAudit(actor,b,'safety.investigation.save','safetyInvestigation',id,existing.data()||null,row);await b.commit();return row;}

export async function createSafetyCorrectiveAction(actor:ActorContext,raw:unknown){if(!actor.permissions.includes('safety.manage'))throw new ApiError(403,'Safety management permission required.','forbidden');const input=correctiveActionSchema.parse(raw),id=randomUUID(),timestamp=now(),row:SafetyCorrectiveAction={id,...input,status:'open',createdAt:timestamp,updatedAt:timestamp};const db=adminDb(),b=db.batch();b.create(db.doc(`organizations/${actor.orgId}/safetyCorrectiveActions/${id}`),row);await addAudit(actor,b,'safety.action.create','safetyCorrectiveAction',id,null,row);await b.commit();return row;}
export async function updateSafetyCorrectiveAction(actor:ActorContext,id:string,raw:unknown){const input=correctiveActionUpdateSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/safetyCorrectiveActions/${id}`),snap=await ref.get();if(!snap.exists)throw new ApiError(404,'Corrective action not found.','not_found');const a=snap.data() as SafetyCorrectiveAction;const owner=a.ownerUid===actor.uid;if(!actor.permissions.includes('safety.manage')&&!owner)throw new ApiError(403,'Only the action owner or H&S administrator may update this action.','forbidden');const timestamp=now(),patch:any={updatedAt:timestamp};if(input.action==='start')patch.status='in_progress';if(input.action==='complete'){if(!input.note||input.note.length<5)throw new ApiError(400,'Completion evidence is required.','evidence_required');patch.status='completed';patch.completionEvidence=input.note;patch.completedAt=timestamp;patch.completedBy=actor.uid;}if(input.action==='waive'){if(!adminRoles.has(actor.role)||!input.note)throw new ApiError(403,'Administrator waiver with rationale required.','forbidden');patch.status='waived';patch.completionEvidence=input.note;patch.completedAt=timestamp;patch.completedBy=actor.uid;}if(input.action==='reopen'){if(!actor.permissions.includes('safety.manage'))throw new ApiError(403,'Safety management permission required.','forbidden');patch.status='open';patch.completedAt=null;patch.completedBy=null;}const after={...a,...patch},b=db.batch();b.set(ref,patch,{merge:true});await addAudit(actor,b,`safety.action.${input.action}`,'safetyCorrectiveAction',id,a,after);await b.commit();return after;}

export async function upsertReturnToWorkPlan(actor:ActorContext,incidentId:string,raw:unknown){if(!actor.permissions.includes('safety.rtw'))throw new ApiError(403,'Return-to-work permission required.','forbidden');const input=rtwSchema.parse(raw);if(!await workerExists(actor.orgId,input.workerId))throw new ApiError(404,'Worker not found.','worker_not_found');const db=adminDb(),inc=await db.doc(`organizations/${actor.orgId}/safetyIncidents/${incidentId}`).get();if(!inc.exists)throw new ApiError(404,'Incident not found.','not_found');const id=`rtw_${incidentId}_${input.workerId}`,ref=db.doc(`organizations/${actor.orgId}/returnToWorkPlans/${id}`),prev=await ref.get(),timestamp=now();const row:ReturnToWorkPlan={id,incidentId,...input,status:(prev.data() as any)?.status||'active',privacyNote:'Record functional abilities, restrictions, suitable duties and RTW coordination only. Do not store unnecessary diagnosis or treatment details in the operational RTW plan.',createdBy:(prev.data() as any)?.createdBy||actor.uid,createdAt:(prev.data() as any)?.createdAt||timestamp,updatedAt:timestamp};const b=db.batch();b.set(ref,row,{merge:true});b.set(db.doc(`organizations/${actor.orgId}/safetyIncidents/${incidentId}`),{status:'rtw_monitoring',updatedAt:timestamp},{merge:true});await addAudit(actor,b,'safety.rtw.upsert','returnToWorkPlan',id,prev.data()||null,row);await b.commit();return row;}

export async function createSafetyInspection(actor:ActorContext,raw:unknown){if(!actor.permissions.includes('safety.manage'))throw new ApiError(403,'Safety management permission required.','forbidden');const input=inspectionSchema.parse(raw),id=randomUUID(),timestamp=now(),referenceNumber=await nextRef(actor.orgId,'safetyInspections','INSP');const row:SafetyInspection={id,referenceNumber,...input,status:input.scheduledFor?'scheduled':'in_progress',findingsCount:0,createdBy:actor.uid,createdAt:timestamp,updatedAt:timestamp};const b=adminDb().batch();b.create(adminDb().doc(`organizations/${actor.orgId}/safetyInspections/${id}`),row);await addAudit(actor,b,'safety.inspection.create','safetyInspection',id,null,row);await b.commit();return row;}
export async function addInspectionFinding(actor:ActorContext,inspectionId:string,raw:unknown){if(!actor.permissions.includes('safety.manage'))throw new ApiError(403,'Safety management permission required.','forbidden');const input=inspectionFindingSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/safetyInspections/${inspectionId}`),snap=await ref.get();if(!snap.exists)throw new ApiError(404,'Inspection not found.','not_found');const id=randomUUID(),timestamp=now(),riskScore=input.likelihood*input.consequence;let hazardId:string|undefined;const b=db.batch();if(input.createHazard){hazardId=randomUUID();const referenceNumber=await nextRef(actor.orgId,'safetyHazards','HAZ');const h:SafetyHazard={id:hazardId,referenceNumber,title:input.title,description:input.description,location:(snap.data() as SafetyInspection).location,category:'inspection',likelihood:input.likelihood as any,consequence:input.consequence as any,riskScore,status:riskScore>=15?'escalated':'open',reportedBy:actor.uid,reportedWorkerId:actor.workerId,existingControls:[],recommendedControls:[],createdAt:timestamp,updatedAt:timestamp};b.create(db.doc(`organizations/${actor.orgId}/safetyHazards/${hazardId}`),h);}const row:SafetyInspectionFinding={id,inspectionId,title:input.title,description:input.description,riskScore,hazardId,status:'open',createdAt:timestamp,updatedAt:timestamp};b.create(db.doc(`organizations/${actor.orgId}/safetyInspectionFindings/${id}`),row);b.set(ref,{findingsCount:Number((snap.data() as any).findingsCount||0)+1,updatedAt:timestamp},{merge:true});await addAudit(actor,b,'safety.inspection.finding.create','safetyInspectionFinding',id,null,row);await b.commit();return row;}

export async function upsertSafetyCommitteeProfile(actor:ActorContext,raw:unknown){if(!actor.permissions.includes('safety.committee'))throw new ApiError(403,'Safety committee governance permission required.','forbidden');const input=committeeProfileSchema.parse(raw),id='primary',ref=adminDb().doc(`organizations/${actor.orgId}/safetyCommitteeProfiles/${id}`),prev=await ref.get(),timestamp=now();const row:SafetyCommitteeProfile={id,...input,updatedBy:actor.uid,updatedAt:timestamp};const b=adminDb().batch();b.set(ref,row,{merge:true});await addAudit(actor,b,'safety.committee.profile.upsert','safetyCommitteeProfile',id,prev.data()||null,row,{referenceOnly:true});await b.commit();return row;}
export async function createSafetyCommitteeMeeting(actor:ActorContext,raw:unknown){
 if(!actor.permissions.includes('safety.committee'))throw new ApiError(403,'Safety committee governance permission required.','forbidden');const input=committeeMeetingSchema.parse(raw),id=randomUUID(),timestamp=now(),row:SafetyCommitteeMeeting={id,profileId:'primary',...input,createdBy:actor.uid,createdAt:timestamp};const db=adminDb(),b=db.batch();b.create(db.doc(`organizations/${actor.orgId}/safetyCommitteeMeetings/${id}`),row);
 for(const text of input.recommendations){const rid=randomUUID(),r:SafetyCommitteeRecommendation={id:rid,meetingId:id,recommendation:text,status:'open',responseDueAt:addDays(`${input.meetingDate}T12:00:00.000Z`,21),createdAt:timestamp,updatedAt:timestamp};b.create(db.doc(`organizations/${actor.orgId}/safetyCommitteeRecommendations/${rid}`),r);}
 await addAudit(actor,b,'safety.committee.meeting.create','safetyCommitteeMeeting',id,null,row,{recommendationsCreated:input.recommendations.length});await b.commit();return row;
}
export async function respondSafetyCommitteeRecommendation(actor:ActorContext,id:string,raw:unknown){if(!actor.permissions.includes('safety.committee'))throw new ApiError(403,'Safety committee governance permission required.','forbidden');const input=recommendationResponseSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/safetyCommitteeRecommendations/${id}`),snap=await ref.get();if(!snap.exists)throw new ApiError(404,'JHSC recommendation not found.','not_found');const prev=snap.data() as SafetyCommitteeRecommendation,timestamp=now(),patch={employerResponse:input.response,implementationTarget:input.implementationTarget,status:input.close?'closed':'responded',respondedAt:timestamp,respondedBy:actor.uid,updatedAt:timestamp};const b=db.batch();b.set(ref,patch,{merge:true});await addAudit(actor,b,'safety.committee.recommendation.respond','safetyCommitteeRecommendation',id,prev,{...prev,...patch});await b.commit();return{...prev,...patch};}
export async function updateSafetyInspection(actor:ActorContext,id:string,raw:unknown){if(!actor.permissions.includes('safety.manage'))throw new ApiError(403,'Safety management permission required.','forbidden');const input=inspectionUpdateSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/safetyInspections/${id}`),snap=await ref.get();if(!snap.exists)throw new ApiError(404,'Inspection not found.','not_found');const prev=snap.data() as SafetyInspection,timestamp=now(),patch:any={updatedAt:timestamp};if(input.action==='start')patch.status='in_progress';if(input.action==='complete'){patch.status='completed';patch.conductedAt=timestamp;patch.summary=input.summary||prev.summary||'Inspection completed.';}if(input.action==='cancel')patch.status='cancelled';const b=db.batch();b.set(ref,patch,{merge:true});await addAudit(actor,b,`safety.inspection.${input.action}`,'safetyInspection',id,prev,{...prev,...patch});await b.commit();return{...prev,...patch};}


export async function safetyDashboard(actor:ActorContext):Promise<SafetyDashboard>{
 if(!actor.permissions.includes('safety.read'))throw new ApiError(403,'Safety read permission required.','forbidden');
 const db=adminDb();
 const incidentRows=(await db.collection(`organizations/${actor.orgId}/safetyIncidents`).orderBy('reportedAt','desc').limit(1000).get()).docs.map(d=>d.data() as SafetyIncident);
 const incidents:SafetyIncident[]=[];for(const i of incidentRows)if(await canViewIncident(actor,i))incidents.push(i);
 const hazards=(await db.collection(`organizations/${actor.orgId}/safetyHazards`).orderBy('createdAt','desc').limit(1000).get()).docs.map(d=>d.data() as SafetyHazard);
 const allowedIncidentIds=new Set(incidents.map(i=>i.id));
 let actions=(await db.collection(`organizations/${actor.orgId}/safetyCorrectiveActions`).where('status','in',['open','in_progress','overdue']).limit(2000).get()).docs.map(d=>d.data() as SafetyCorrectiveAction);
 if(actor.role==='manager')actions=actions.filter(a=>Boolean((a.incidentId&&allowedIncidentIds.has(a.incidentId))||a.ownerUid===actor.uid));
 const rtw=actor.role==='manager'?[]:(await db.collection(`organizations/${actor.orgId}/returnToWorkPlans`).where('status','in',['active','modified']).limit(1000).get()).docs.map(d=>d.data() as ReturnToWorkPlan);
 const inspections=(await db.collection(`organizations/${actor.orgId}/safetyInspections`).where('status','in',['scheduled','in_progress']).limit(1000).get()).docs.map(d=>d.data() as SafetyInspection);
 const open=incidents.filter(i=>!['closed','cancelled'].includes(i.status)),openHazards=hazards.filter(h=>!['closed','controlled'].includes(h.status));
 return{metrics:{openIncidents:open.length,criticalIncidents:open.filter(i=>['critical','fatal'].includes(i.severity)).length,openHazards:openHazards.length,highRiskHazards:openHazards.filter(h=>h.riskScore>=15).length,overdueActions:actions.filter(a=>Boolean(a.dueAt&&a.dueAt<now())).length,rtwActive:rtw.length,reportingReviews:open.filter(i=>['not_reviewed','potentially_required'].includes(i.mlitsdReview)||['not_reviewed','potentially_required'].includes(i.wsibReview)||['not_reviewed','potentially_required'].includes(i.committeeNoticeReview)).length,inspectionsDue:inspections.filter(i=>Boolean(i.scheduledFor&&i.scheduledFor<now())).length},incidents:open.slice(0,100),hazards:openHazards.slice(0,100),actions:actions.slice(0,100)};
}

export async function processSafetyGovernance(orgId:string){const db=adminDb(),actor=systemActor(orgId,'system:safety-governance'),timestamp=now(),summary={incidentsScanned:0,reportingOverdue:0,investigationsOverdue:0,actionsOverdue:0,rtwReviewsDue:0,inspectionsDue:0,committeeRecommendationsOverdue:0,monthlyInspectionGap:0,notifications:0};const incidents=(await db.collection(`organizations/${orgId}/safetyIncidents`).where('status','in',['reported','triage','investigating','corrective_action','rtw_monitoring']).limit(2500).get()).docs.map(d=>d.data() as SafetyIncident);summary.incidentsScanned=incidents.length;for(const i of incidents){const reportingTargets=[{kind:'MLITSD immediate notification review',due:i.mlitsdReview==='submitted'||i.mlitsdReview==='not_required'?undefined:i.mlitsdNoticeTargetAt},{kind:'MLITSD written report/notice review',due:i.mlitsdReview==='submitted'||i.mlitsdReview==='not_required'?undefined:i.mlitsdWrittenReportTargetAt},{kind:'committee/representative notice review',due:i.committeeNoticeReview==='submitted'||i.committeeNoticeReview==='not_required'?undefined:i.committeeNoticeTargetAt},{kind:'WSIB reporting review',due:i.wsibReview==='submitted'||i.wsibReview==='not_required'?undefined:i.wsibReportTargetAt}];for(const r of reportingTargets)if(r.due&&r.due<timestamp){summary.reportingOverdue++;if(await notifyOnce(orgId,`safety-reporting:${i.id}:${r.kind}:${r.due}`,{title:'Safety reporting target requires review',message:`${i.referenceNumber}: ${r.kind} target has passed. Confirm the legal/reporting determination and preserve submission evidence.`,targetRole:'hr_admin',entityType:'safetyIncident',entityId:i.id,priority:['critical','fatal'].includes(i.severity)?'critical':'high'}))summary.notifications++;}if(i.investigationTargetAt&&i.investigationTargetAt<timestamp&&!i.investigationCompletedAt){summary.investigationsOverdue++;if(await notifyOnce(orgId,`safety-investigation:${i.id}:${i.investigationTargetAt}`,{title:'Safety investigation target overdue',message:`${i.referenceNumber} passed its investigation target date.`,targetRole:'hr_admin',entityType:'safetyIncident',entityId:i.id,priority:'high'}))summary.notifications++;}}
 const actions=await db.collection(`organizations/${orgId}/safetyCorrectiveActions`).where('status','in',['open','in_progress']).limit(3000).get();for(const d of actions.docs){const a=d.data() as SafetyCorrectiveAction;if(a.dueAt&&a.dueAt<timestamp){summary.actionsOverdue++;await d.ref.set({status:'overdue',updatedAt:timestamp},{merge:true});const first=await notifyOnce(orgId,`safety-action:${a.id}:${a.dueAt}`,{title:'Safety corrective action overdue',message:`${a.title} is overdue.`,targetUid:a.ownerUid,targetRole:a.ownerUid?undefined:a.ownerRole||'hr_admin',entityType:'safetyCorrectiveAction',entityId:a.id,priority:'high'});if(first){summary.notifications++;const ev=buildDomainEvent(actor,'safety.action_overdue','safetyCorrectiveAction',a.id,{incidentId:a.incidentId,hazardId:a.hazardId,dueAt:a.dueAt});await db.doc(`organizations/${orgId}/domainEvents/${ev.id}`).create(ev);}}}
 const plans=await db.collection(`organizations/${orgId}/returnToWorkPlans`).where('status','in',['active','modified']).limit(2000).get();for(const d of plans.docs){const p=d.data() as ReturnToWorkPlan;if(p.reviewDate&&p.reviewDate<=today()){summary.rtwReviewsDue++;if(await notifyOnce(orgId,`safety-rtw:${p.id}:${p.reviewDate}`,{title:'Return-to-work review due',message:'A confidential return-to-work plan is due for functional-abilities/suitable-duty review.',targetRole:'hr_admin',entityType:'returnToWorkPlan',entityId:p.id,priority:'high'}))summary.notifications++;}}
 const inspections=await db.collection(`organizations/${orgId}/safetyInspections`).where('status','==','scheduled').limit(2000).get();for(const d of inspections.docs){const s=d.data() as SafetyInspection;if(s.scheduledFor&&s.scheduledFor<timestamp){summary.inspectionsDue++;if(await notifyOnce(orgId,`safety-inspection:${s.id}:${s.scheduledFor}`,{title:'Safety inspection overdue',message:`${s.referenceNumber} at ${s.location} is overdue.`,targetRole:'hr_admin',entityType:'safetyInspection',entityId:s.id,priority:'high'}))summary.notifications++;}}
 const profileSnap=await db.doc(`organizations/${orgId}/safetyCommitteeProfiles/primary`).get();const profile=profileSnap.exists?profileSnap.data() as SafetyCommitteeProfile:undefined;if(profile&&['hsr','jhsc'].includes(profile.governanceType)){const since=addDays(timestamp,-31);const recent=await db.collection(`organizations/${orgId}/safetyInspections`).where('status','==','completed').where('conductedAt','>=',since).limit(1).get();if(recent.empty){summary.monthlyInspectionGap++;if(await notifyOnce(orgId,`safety-monthly-inspection:${today().slice(0,7)}`,{title:'Monthly workplace inspection evidence not found',message:'The H&S governance profile indicates an HSR/JHSC structure, but no completed workplace inspection is recorded in the last 31 days. Review the applicable OHSA inspection schedule and evidence.',targetRole:'hr_admin',entityType:'safetyCommitteeProfile',entityId:'primary',priority:'high'}))summary.notifications++;}}
 const recs=await db.collection(`organizations/${orgId}/safetyCommitteeRecommendations`).where('status','==','open').limit(1000).get();for(const d of recs.docs){const r=d.data() as SafetyCommitteeRecommendation;if(r.responseDueAt<timestamp){summary.committeeRecommendationsOverdue++;if(await notifyOnce(orgId,`safety-jhsc-response:${r.id}:${r.responseDueAt}`,{title:'JHSC recommendation response target overdue',message:'A written H&S committee recommendation has passed the configured 21-day employer-response target.',targetRole:'hr_admin',entityType:'safetyCommitteeRecommendation',entityId:r.id,priority:'high'}))summary.notifications++;}}
 return summary;}

export async function listSafetyInspections(actor:ActorContext){if(!actor.permissions.includes('safety.read'))throw new ApiError(403,'Safety read permission required.','forbidden');return (await adminDb().collection(`organizations/${actor.orgId}/safetyInspections`).orderBy('createdAt','desc').limit(500).get()).docs.map(d=>d.data() as SafetyInspection);}
export async function getSafetyCommitteeGovernance(actor:ActorContext){if(!actor.permissions.includes('safety.read'))throw new ApiError(403,'Safety read permission required.','forbidden');const db=adminDb(),[profile,meetings,recommendations]=await Promise.all([db.doc(`organizations/${actor.orgId}/safetyCommitteeProfiles/primary`).get(),db.collection(`organizations/${actor.orgId}/safetyCommitteeMeetings`).orderBy('meetingDate','desc').limit(50).get(),db.collection(`organizations/${actor.orgId}/safetyCommitteeRecommendations`).orderBy('createdAt','desc').limit(100).get()]);return{profile:profile.exists?profile.data():null,meetings:meetings.docs.map(d=>d.data()),recommendations:recommendations.docs.map(d=>d.data())};}
