import { createHash, randomUUID } from 'node:crypto';
import type { ActorContext } from '@/domain/security';
import { adminDb } from '@/lib/firebase/admin';
import { ApiError } from '@/lib/http/errors';
import { buildAudit } from '@/lib/audit/service';
import { createEmployee, listOrgUnits, listPositions } from '@/lib/hr/service';
import { parseTabularFile, MAX_IMPORT_ROWS } from './tabular';
import { extractPdfTextLayer } from './pdf-text';
import { parseEmployeeRosterText } from './employee-roster-text';
import { governedEmployeeRosterRows } from './universal-provider';

const sha=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
const now=()=>new Date().toISOString();
const norm=(s:string)=>s.trim().toLowerCase().replace(/[^a-z0-9@.+-]+/g,'');
const headerNorm=(s:string)=>s.trim().toLowerCase().replace(/[^a-z0-9]+/g,'');
const ORG_UNIT_FAMILIES:Record<string,string[]>={
 executive:['executivemanagement','executiveleadership','leadership','executiveoffice'],
 people:['humanresources','hr','peopleculture','peopleandculture','peopleoperations','peopleteam'],
 commercial:['sales','salesclientoperations','salesandclientoperations','commercial','clientoperations','businessdevelopment'],
 marketing:['marketing','marketingcommunications','communicationsmarketing'],
 technology:['it','informationtechnology','technology','digitaltechnology','technologyoperations']
};
function orgUnitFamily(value:string){const key=headerNorm(value);if(!key)return'';for(const[family,aliases]of Object.entries(ORG_UNIT_FAMILIES))if(aliases.includes(key))return family;return''}

const aliases:Record<string,string[]>={
 legalFirstName:['firstname','legalfirstname','first','givenname'],legalLastName:['lastname','legallastname','last','surname','familyname'],fullName:['name','employeename','fullname','workername','staffname'],workEmail:['workemail','email','companyemail','businessemail'],phone:['phone','mobile','telephone','phonenumber'],employeeNumber:['employeenumber','employeeid','staffid','staffnumber','personnelid','workernumber','employeecode','emp'],employmentType:['employmenttype','type','workertype','contracttype'],hireDate:['hiredate','startdate','employmentstartdate','dateofhire'],orgUnit:['orgunit','department','team','organizationunit','businessunit','division'],position:['position','jobtitle','title','role','positiontitle'],manager:['manager','manageremail','managerid','managernumber','supervisor','reportsto','line manager']
};
function value(row:Record<string,string>,key:string){const map=Object.fromEntries(Object.entries(row).map(([k,v])=>[headerNorm(k),v]));for(const a of aliases[key]||[])if(map[headerNorm(a)]!==undefined)return map[headerNorm(a)]||'';return''}
function employmentType(v:string){const x=v.trim().toLowerCase();return ['permanent','temporary','contractor','intern','volunteer'].includes(x)?x:'permanent'}
function date(v:string){const x=v.trim();if(/^\d{4}-\d{2}-\d{2}$/.test(x))return x;const d=new Date(x);return Number.isFinite(d.getTime())?d.toISOString().slice(0,10):''}
function addLookup(map:Map<string,string[]>,key:string,id:string){const k=norm(key);if(!k)return;map.set(k,[...(map.get(k)||[]),id])}
function splitName(v:string){const parts=v.trim().replace(/\s+/g,' ').split(' ').filter(Boolean);return{first:parts[0]||'',last:parts.slice(1).join(' ')}}
function canonicalAiRows(rows:Array<Record<string,unknown>>){const headers=['legalFirstName','legalLastName','fullName','workEmail','phone','employeeNumber','employmentType','hireDate','orgUnit','position','manager'];return{headers,rows:rows.map(r=>Object.fromEntries(headers.map(h=>[h,String(r[h]??'')])))};}
async function parseEmployeeSource(actor:ActorContext,file:File,bytes:Buffer){
 const lower=file.name.toLowerCase();
 if(lower.endsWith('.csv')||lower.endsWith('.xlsx'))return{...parseTabularFile(file.name,bytes),parser:lower.endsWith('.csv')?'csv':'xlsx',warnings:[] as string[],sourceType:lower.endsWith('.csv')?'CSV':'XLSX'};
 if(lower.endsWith('.pdf')||file.type==='application/pdf'){
  let text='';const warnings:string[]=[];
  try{text=extractPdfTextLayer(bytes)}catch(e){warnings.push(e instanceof Error?e.message:'PDF text extraction failed.')}
  const deterministic=parseEmployeeRosterText(text);warnings.push(...deterministic.warnings);
  if(deterministic.rows.length)return{headers:deterministic.headers,rows:deterministic.rows,parser:deterministic.parser,warnings,sourceType:'PDF'};
  try{const ai=await governedEmployeeRosterRows(actor,{name:file.name,mimeType:'application/pdf',bytes,text:text.length>=40?text:undefined});if(ai?.rows.length){const parsed=canonicalAiRows(ai.rows as Array<Record<string,unknown>>);return{...parsed,parser:`governed_ai_${ai.provider}`,warnings:[...warnings,...ai.warnings],sourceType:'PDF'};}}catch(e){warnings.push(e instanceof Error?e.message:'Governed AI PDF roster parsing failed.')}
  throw new ApiError(400,`The PDF could not be mapped to employee rows. ${warnings.filter(Boolean).join(' ')||'Use a text-based roster PDF, CSV or XLSX, or configure an approved AI parser for scanned PDFs.'}`,'pdf_roster_unmapped');
 }
 throw new ApiError(400,'Employee import supports CSV, XLSX and PDF files.','unsupported_employee_import_type');
}

export async function previewEmployeeImport(actor:ActorContext,file:File){
 if(file.size<=0||file.size>15*1024*1024)throw new ApiError(400,'Employee import file must be between 1 byte and 15 MB.','invalid_file_size');
 const bytes=Buffer.from(await file.arrayBuffer()),parsed=await parseEmployeeSource(actor,file,bytes);if(!parsed.rows.length)throw new ApiError(400,'The import file has no employee data rows.','empty_import');if(parsed.rows.length>MAX_IMPORT_ROWS)throw new ApiError(400,'Employee import exceeds the 500 row limit.','row_limit');
 const[units,positions,workersSnap]=await Promise.all([listOrgUnits(actor),listPositions(actor),adminDb().collection(`organizations/${actor.orgId}/workers`).limit(5000).get()]);
 const unitMap=new Map<string,any>();const unitsByFamily=new Map<string,any[]>();for(const u of units as any[]){for(const key of [headerNorm(String(u.name||'')),headerNorm(String(u.code||''))])if(key)unitMap.set(key,u);const family=orgUnitFamily(String(u.name||u.code||''));if(family)unitsByFamily.set(family,[...(unitsByFamily.get(family)||[]),u])}
 const posByKey=new Map<string,any[]>();for(const p of positions as any[]){for(const key of [headerNorm(String(p.title||'')),headerNorm(String(p.positionCode||''))]){if(!key)continue;posByKey.set(key,[...(posByKey.get(key)||[]),p])}}
 const existingNums=new Set<string>(),existingEmails=new Set<string>(),managerLookup=new Map<string,string[]>();
 for(const d of workersSnap.docs){const x=d.data();const id=d.id,number=String(x.employeeNumber||''),email=String(x.workEmail||''),name=String(x.displayName||[x.legalFirstName,x.legalLastName].filter(Boolean).join(' '));if(number){existingNums.add(headerNorm(number));addLookup(managerLookup,number,id)}if(email){existingEmails.add(email.trim().toLowerCase());addLookup(managerLookup,email,id)}if(name)addLookup(managerLookup,name,id)}
 const seenNums=new Set<string>(),seenEmails=new Set<string>();
 const rows:any[]=parsed.rows.map((row,i)=>{const full=value(row,'fullName').trim(),split=splitName(full);const r:any={rowNumber:i+2,legalFirstName:value(row,'legalFirstName').trim()||split.first,legalLastName:value(row,'legalLastName').trim()||split.last,workEmail:value(row,'workEmail').trim().toLowerCase(),phone:value(row,'phone').trim()||undefined,employeeNumber:value(row,'employeeNumber').trim(),employmentType:employmentType(value(row,'employmentType')),hireDate:date(value(row,'hireDate')),managerReference:value(row,'manager').trim()||undefined,errors:[] as string[],warnings:[] as string[]};if(!r.legalFirstName)r.errors.push('First name is required.');if(!r.legalLastName)r.errors.push('Last name is required.');if(r.workEmail&&!/^\S+@\S+\.\S+$/.test(r.workEmail))r.errors.push('Work email is invalid.');if(!r.workEmail)r.warnings.push('Work email is optional.');if(!r.employeeNumber)r.warnings.push('Employee number will be assigned automatically.');if(!r.hireDate)r.errors.push('A valid hire date is required.');const nn=headerNorm(r.employeeNumber);if(nn&&(existingNums.has(nn)||seenNums.has(nn)))r.errors.push('Duplicate employee number.');if(r.workEmail&&(existingEmails.has(r.workEmail)||seenEmails.has(r.workEmail)))r.errors.push('Duplicate work email.');if(nn)seenNums.add(nn);if(r.workEmail)seenEmails.add(r.workEmail);const unitName=value(row,'orgUnit').trim(),positionName=value(row,'position').trim();if(Boolean(unitName)!==Boolean(positionName))r.errors.push('Organization unit and position must both be supplied or both left blank.');if(unitName&&positionName){let unit=unitMap.get(headerNorm(unitName)) as any;if(!unit){const family=orgUnitFamily(unitName),aliasMatches=family?(unitsByFamily.get(family)||[]):[];if(aliasMatches.length===1){unit=aliasMatches[0];r.warnings.push(`Organization unit "${unitName}" mapped to "${String(unit.name||unit.code||unit.id)}" by governed alias.`)}else if(aliasMatches.length>1)r.errors.push(`Organization unit match is ambiguous: ${unitName}`);else r.errors.push(`Organization unit not found: ${unitName}`)}if(unit){const matches=(posByKey.get(headerNorm(positionName))||[]).filter(p=>p.orgUnitId===unit.id&&Number(p.availableHeadcount||0)>0&&!['full','closed','frozen'].includes(String(p.capacityState||'').toLowerCase()));if(matches.length!==1)r.errors.push(matches.length?'Position match is ambiguous.':`No available position found in ${unitName}: ${positionName}`);else{r.orgUnitId=unit.id;r.positionId=matches[0].id}}}return r});
 const batchManagerLookup=new Map<string,number[]>();for(const r of rows){for(const key of [r.employeeNumber,r.workEmail,`${r.legalFirstName} ${r.legalLastName}`]){const k=norm(String(key||''));if(!k)continue;batchManagerLookup.set(k,[...(batchManagerLookup.get(k)||[]),r.rowNumber])}}
 for(const r of rows){if(!r.managerReference)continue;const k=norm(r.managerReference),existing=managerLookup.get(k)||[],batch=(batchManagerLookup.get(k)||[]).filter(x=>x!==r.rowNumber);if(existing.length===1&&batch.length===0)r.managerWorkerId=existing[0];else if(existing.length===0&&batch.length===1)r.managerRowNumber=batch[0];else if(existing.length+batch.length===0)r.errors.push(`Manager not found: ${r.managerReference}`);else r.errors.push(`Manager match is ambiguous: ${r.managerReference}`)}
 // Detect cycles in same-file manager relationships before any authoritative write.
 const byRow=new Map(rows.map(r=>[r.rowNumber,r]));const visiting=new Set<number>(),visited=new Set<number>();
 function visit(n:number,trail:number[]=[]){if(visited.has(n))return;if(visiting.has(n)){const cycle=trail.slice(trail.indexOf(n));for(const row of cycle){const r=byRow.get(row);if(r&&!r.errors.includes('Manager hierarchy contains a cycle.'))r.errors.push('Manager hierarchy contains a cycle.')}return}visiting.add(n);const next=byRow.get(n)?.managerRowNumber;if(next)visit(next,[...trail,n]);visiting.delete(n);visited.add(n)}for(const r of rows)visit(r.rowNumber);
 const ready=rows.filter(r=>r.errors.length===0).map(r=>({rowNumber:r.rowNumber,legalFirstName:r.legalFirstName,legalLastName:r.legalLastName,workEmail:r.workEmail,phone:r.phone,...(r.employeeNumber?{employeeNumber:r.employeeNumber}:{}),employmentType:r.employmentType,hireDate:r.hireDate,orgUnitId:r.orgUnitId,positionId:r.positionId,managerWorkerId:r.managerWorkerId,managerRowNumber:r.managerRowNumber}));
 const previewId=randomUUID(),timestamp=now(),expiresAt=new Date(Date.now()+30*60_000).toISOString(),record={id:previewId,fileName:file.name,fileSha256:sha(bytes),headers:parsed.headers,parser:parsed.parser,sourceType:parsed.sourceType,sourceWarnings:parsed.warnings||[],rowCount:rows.length,readyCount:ready.length,blockedCount:rows.length-ready.length,readyRows:ready,previewRows:rows,createdBy:actor.uid,createdAt:timestamp,expiresAt,status:'ready'};await adminDb().doc(`organizations/${actor.orgId}/employeeImportPreviews/${previewId}`).create(record);return{previewId,fileName:file.name,fileSha256:record.fileSha256,headers:parsed.headers,parser:parsed.parser,sourceType:parsed.sourceType,warnings:parsed.warnings||[],rowCount:record.rowCount,readyCount:record.readyCount,blockedCount:record.blockedCount,expiresAt,rows};
}

export async function commitEmployeeImport(actor:ActorContext,previewId:string){
 const db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/employeeImportPreviews/${previewId}`),snap=await ref.get();if(!snap.exists)throw new ApiError(404,'Employee import preview not found.','preview_not_found');const p=snap.data() as any;if(p.createdBy!==actor.uid)throw new ApiError(403,'Only the user who reviewed this preview may commit it.','preview_owner_required');if(Date.parse(p.expiresAt)<Date.now())throw new ApiError(409,'Employee import preview expired. Create a new preview.','preview_expired');if(p.status==='executing')throw new ApiError(409,'This import is already executing. Reconcile its outcome before retrying.','reconciliation_required');if(p.status==='completed')throw new ApiError(409,'This import was already committed.','import_already_completed');if(p.blockedCount>0)throw new ApiError(409,'Resolve all blocked rows before committing this import.','import_has_blockers');
 await db.runTransaction(async tx=>{const s=await tx.get(ref);if(s.data()?.status!=='ready')throw new ApiError(409,'Import preview is no longer ready.','preview_not_ready');tx.set(ref,{status:'executing',executingAt:now()},{merge:true})});
 const created:any[]=[],failures:any[]=[],createdByRow=new Map<number,string>(),pending=[...(p.readyRows as any[])];
 while(pending.length&&!failures.length){let progressed=false;for(let i=0;i<pending.length;i++){const row=pending[i]!;if(row.managerRowNumber&&!createdByRow.has(row.managerRowNumber))continue;try{const payload={...row};delete payload.rowNumber;delete payload.managerRowNumber;if(row.managerRowNumber)payload.managerWorkerId=createdByRow.get(row.managerRowNumber);const result=await createEmployee(actor,payload),workerId=(result as any).worker?.id||(result as any).id;created.push({row:row.rowNumber,workerId});createdByRow.set(row.rowNumber,workerId);pending.splice(i,1);i--;progressed=true}catch(e){failures.push({row:row.rowNumber,message:e instanceof Error?e.message:'Creation failed'});break}}if(!progressed&&!failures.length){failures.push({row:pending[0]?.rowNumber||0,message:'Manager dependency could not be resolved. Reconciliation is required.'});break}}
 const timestamp=now(),batchId=randomUUID(),status=failures.length?'reconciliation_required':'completed',receipt={id:batchId,previewId,status,createdCount:created.length,expectedCount:p.readyRows.length,failures,created,fileSha256:p.fileSha256,createdAt:timestamp,createdBy:actor.uid},audit=buildAudit(actor,{action:'employee.import.commit',entityType:'employeeImport',entityId:batchId,after:receipt}),batch=db.batch();batch.set(ref,{status,completedAt:status==='completed'?timestamp:undefined,reconciliationRequired:failures.length>0,receiptId:batchId},{merge:true});batch.create(db.doc(`organizations/${actor.orgId}/employeeImportBatches/${batchId}`),receipt);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();if(failures.length)throw new ApiError(409,`Import stopped after ${created.length} employee(s). Reconciliation is required before retrying.`,'reconciliation_required');return receipt;
}
