import { MAX_IMPORT_ROWS } from './tabular';
const norm=(s:string)=>s.trim().toLowerCase().replace(/[^a-z0-9]+/g,'');
const aliases:Record<string,string[]>={legalFirstName:['firstname','legalfirstname','first','givenname'],legalLastName:['lastname','legallastname','last','surname','familyname'],fullName:['name','employeename','fullname','workername','staffname'],workEmail:['workemail','email','companyemail','businessemail'],phone:['phone','mobile','telephone','phonenumber'],employeeNumber:['employeenumber','employeeid','staffid','staffnumber','personnelid','workernumber','employeecode','emp'],employmentType:['employmenttype','type','workertype','contracttype'],hireDate:['hiredate','startdate','employmentstartdate','dateofhire'],orgUnit:['orgunit','department','team','organizationunit','businessunit','division'],position:['position','jobtitle','title','role','positiontitle'],manager:['manager','manageremail','managerid','managernumber','supervisor','reportsto','linemanager']};
export function employeeHeaderTarget(header:string){const h=norm(header);for(const[target,list]of Object.entries(aliases))if(list.some(a=>norm(a)===h))return target;return undefined;}
function splitFullName(value:string){const parts=value.trim().replace(/\s+/g,' ').split(' ').filter(Boolean);return parts.length<2?{first:parts[0]||'',last:''}:{first:parts[0]!,last:parts.slice(1).join(' ')};}
function cells(line:string,mode:'pipe'|'tab'|'multi'|'comma'){if(mode==='pipe')return line.split('|').map(x=>x.trim());if(mode==='tab')return line.split('\t').map(x=>x.trim());if(mode==='multi')return line.split(/\s{2,}/).map(x=>x.trim());const out:string[]=[];let field='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i]!;if(quoted){if(c==='"'&&line[i+1]==='"'){field+='"';i++;}else if(c==='"')quoted=false;else field+=c;}else if(c==='"')quoted=true;else if(c===','){out.push(field.trim());field='';}else field+=c;}out.push(field.trim());return out;}
function bestMode(line:string){const modes:Array<'pipe'|'tab'|'multi'|'comma'>=['pipe','tab','multi','comma'];let best:{mode:'pipe'|'tab'|'multi'|'comma';hits:number;count:number}|null=null;for(const mode of modes){const c=cells(line,mode),hits=c.filter(x=>employeeHeaderTarget(x)).length;if(!best||hits>best.hits||(hits===best.hits&&c.length>best.count))best={mode,hits,count:c.length};}return best;}
function canonicalRow(targets:Array<string|undefined>,rowCells:string[]){const row:Record<string,string>={};targets.forEach((target,i)=>{if(target&&rowCells[i]!=null)row[target]=rowCells[i]!.trim();});if((!row.legalFirstName||!row.legalLastName)&&row.fullName){const n=splitFullName(row.fullName);row.legalFirstName||=n.first;row.legalLastName||=n.last;}return row;}
function tableParse(text:string){const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);for(let i=0;i<Math.min(lines.length,120);i++){const guess=bestMode(lines[i]!);if(!guess||guess.hits<3)continue;const headers=cells(lines[i]!,guess.mode),targets=headers.map(employeeHeaderTarget),important=new Set(targets.filter(Boolean));if(!important.has('workEmail')&&!important.has('employeeNumber'))continue;const rows:Record<string,string>[]=[];for(let j=i+1;j<lines.length&&rows.length<MAX_IMPORT_ROWS;j++){const c=cells(lines[j]!,guess.mode);if(c.length<2)continue;const mapped=canonicalRow(targets,c);if(Object.values(mapped).filter(Boolean).length<2)continue;rows.push(mapped);}if(rows.length)return{headers:targets.filter(Boolean) as string[],rows,parser:`pdf_text_${guess.mode}`};}return null;}
function labeledParse(text:string){const lines=text.split(/\r?\n/).map(x=>x.trim()),rows:Record<string,string>[]=[];let current:Record<string,string>={};const flush=()=>{if(Object.keys(current).length>=3){if((!current.legalFirstName||!current.legalLastName)&&current.fullName){const n=splitFullName(current.fullName);current.legalFirstName||=n.first;current.legalLastName||=n.last;}rows.push(current);}current={};};for(const line of lines){if(!line){if(Object.keys(current).length>=3)flush();continue;}const m=/^([^:]{2,50})\s*:\s*(.+)$/.exec(line);if(!m)continue;const target=employeeHeaderTarget(m[1]!);if(!target)continue;if((target==='employeeNumber'||target==='workEmail')&&current[target]&&Object.keys(current).length>=3)flush();current[target]=m[2]!.trim();if(rows.length>=MAX_IMPORT_ROWS)break;}flush();return rows.length?{headers:[...new Set(rows.flatMap(r=>Object.keys(r)))],rows,parser:'pdf_text_labeled'}:null;}
export function parseEmployeeRosterText(text:string){const clean=text.replace(/\u0000/g,' ').replace(/\r/g,'\n').replace(/\n{3,}/g,'\n\n').trim();if(clean.length<20)return{headers:[] as string[],rows:[] as Record<string,string>[],parser:'pdf_text_none',warnings:['No machine-readable employee text was detected in the PDF.']};const parsed=tableParse(clean)||labeledParse(clean);if(!parsed)return{headers:[] as string[],rows:[] as Record<string,string>[],parser:'pdf_text_unmapped',warnings:['Machine-readable PDF text was found, but no employee roster table or labeled employee blocks could be mapped safely.']};return{...parsed,warnings:[] as string[]};}
