import { inflateRawSync } from 'node:zlib';
export const MAX_IMPORT_ROWS=500;const MAX_COLUMNS=120,MAX_FIELD=20_000,MAX_ZIP_ENTRIES=4096,MAX_XML=12*1024*1024;
function clean(v:unknown){const s=String(v??'').replace(/\u0000/g,'').trim();if(s.length>MAX_FIELD)throw new Error('A field exceeds the 20,000 character safety limit.');return s}
export function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i]!;if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"')quoted=true;else if(c===','){row.push(clean(field));field=''}else if(c==='\n'){row.push(clean(field));rows.push(row);row=[];field=''}else if(c!=='\r')field+=c}if(field||row.length){row.push(clean(field));rows.push(row)}return normalize(rows)}
function normalize(rows:string[][]){const non=rows.filter(r=>r.some(Boolean));if(!non.length)return{headers:[],rows:[] as Record<string,string>[]};const headers=non[0]!.map((h,i)=>clean(h)||`Column ${i+1}`);if(headers.length>MAX_COLUMNS)throw new Error('Too many columns. Maximum is 120.');const seen=new Set<string>();for(const h of headers){const k=h.toLowerCase();if(seen.has(k))throw new Error(`Duplicate column header: ${h}`);seen.add(k)}const body=non.slice(1);if(body.length>MAX_IMPORT_ROWS)throw new Error(`Employee imports are limited to ${MAX_IMPORT_ROWS} data rows per batch.`);return{headers,rows:body.map(r=>Object.fromEntries(headers.map((h,i)=>[h,clean(r[i]||'')])))} }
function u16(b:Buffer,o:number){return b.readUInt16LE(o)}function u32(b:Buffer,o:number){return b.readUInt32LE(o)}
type Z={name:string;method:number;size:number;uncompressed:number;local:number;flags:number};function zipEntries(buf:Buffer){let e=-1;for(let i=Math.max(0,buf.length-65557);i<=buf.length-22;i++)if(u32(buf,i)===0x06054b50)e=i;if(e<0)throw new Error('Invalid XLSX ZIP container.');const total=u16(buf,e+10);if(total>MAX_ZIP_ENTRIES)throw new Error('XLSX contains too many ZIP entries.');const out:Z[]=[];let o=u32(buf,e+16);for(let i=0;i<total;i++){if(u32(buf,o)!==0x02014b50)throw new Error('Invalid XLSX central directory.');const flags=u16(buf,o+8),method=u16(buf,o+10),size=u32(buf,o+20),uncompressed=u32(buf,o+24),nameLen=u16(buf,o+28),extra=u16(buf,o+30),comment=u16(buf,o+32),local=u32(buf,o+42),name=buf.subarray(o+46,o+46+nameLen).toString('utf8');if(flags&1)throw new Error('Encrypted XLSX files are not supported.');out.push({name,method,size,uncompressed,local,flags});o+=46+nameLen+extra+comment}return out}
function entry(buf:Buffer,e:Z){if(e.uncompressed>MAX_XML||e.uncompressed>Math.max(4096,e.size*250))throw new Error('XLSX XML part exceeds decompression safety limits.');if(u32(buf,e.local)!==0x04034b50)throw new Error('Invalid XLSX local entry.');const nl=u16(buf,e.local+26),xl=u16(buf,e.local+28),start=e.local+30+nl+xl,data=buf.subarray(start,start+e.size);if(e.method===0)return data;if(e.method===8)return inflateRawSync(data,{maxOutputLength:MAX_XML} as any);throw new Error('Unsupported XLSX compression method.')}
function xml(v:string){return v.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&')}
function colIndex(ref:string){let n=0;for(const c of ref.replace(/\d/g,''))n=n*26+(c.charCodeAt(0)-64);return Math.max(0,n-1)}
export function parseXlsx(buf:Buffer){if(buf.subarray(0,2).toString()!=='PK')throw new Error('Invalid XLSX signature.');const ents=zipEntries(buf),map=new Map(ents.map(e=>[e.name,e])),sheet=map.get('xl/worksheets/sheet1.xml');if(!sheet)throw new Error('XLSX first worksheet was not found.');let shared:string[]=[];const ss=map.get('xl/sharedStrings.xml');if(ss){const t=entry(buf,ss).toString('utf8');shared=[...t.matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g)].map(m=>xml([...m[1].matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(x=>x[1]).join('')))}const text=entry(buf,sheet).toString('utf8'),rows:string[][]=[];for(const rm of text.matchAll(/<row\b[^>]*>([\s\S]*?)<\/row>/g)){const row:string[]=[];for(const cm of rm[1].matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)){const attrs=cm[1],body=cm[2],ref=/\br="([A-Z]+\d+)"/.exec(attrs)?.[1]||'',type=/\bt="([^"]+)"/.exec(attrs)?.[1]||'',raw=/<v>([\s\S]*?)<\/v>/.exec(body)?.[1]??/<t\b[^>]*>([\s\S]*?)<\/t>/.exec(body)?.[1]??'';const val=type==='s'?shared[Number(raw)]||'':xml(raw);row[colIndex(ref)]=clean(val)}rows.push(row)}return normalize(rows)}
export function parseTabularFile(name:string,bytes:Buffer){const lower=name.toLowerCase();if(lower.endsWith('.csv'))return parseCsv(bytes.toString('utf8'));if(lower.endsWith('.xlsx'))return parseXlsx(bytes);throw new Error('Only CSV and XLSX employee files are supported.')}
