import { createHash,randomUUID } from 'node:crypto';
import type { ActorContext } from '@/domain/security';
import type { IntegrationConnector,IntegrationContract,IntegrationRun,IntegrationStagingRecord } from '@/domain/integration';
import type { IntegrationAdapterProfile,IntegrationReplayRequest,IntegrationRuntimeDashboard,IntegrationRuntimeState,IntegrationSandboxResult,IntegrationSchedule,IntegrationWebhookReceipt } from '@/domain/integration-runtime';
import { adminDb } from '@/lib/firebase/admin';
import { ApiError } from '@/lib/http/errors';
import { buildAudit } from '@/lib/audit/service';
import { systemActor } from '@/lib/automation/system-actor';
import { actRun,createRun,stageIntegrationRecord } from './service';
import { adapterProfileActionSchema,adapterProfileCreateSchema,replayActionSchema,replayCreateSchema,runtimeExecuteSchema,sandboxSchema,scheduleActionSchema,scheduleCreateSchema } from './runtime-schemas';
import { assertSecretReferenceShape,resolveSecretReference,secretProviderKind } from './secret-provider';
import { hasSftpRuntimeProvider,pullInbound,pushOutbound,verifyWebhookSignature } from './runtime-adapters';
import { circuitAllows,getPath,nextFailureState,nextScheduleAt,nextSuccessState } from './runtime-utils';
import { validateIntegrationEndpoint } from './endpoint-security';
import { validateContractRecord } from './contract-validation';

const now=()=>new Date().toISOString();const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
const requireRead=(a:ActorContext)=>{if(!a.permissions.includes('integration.read'))throw new ApiError(403,'Integration read permission required.','forbidden')};
const requireManage=(a:ActorContext)=>{if(!a.permissions.includes('integration.manage'))throw new ApiError(403,'Integration management permission required.','forbidden')};
const requireApprove=(a:ActorContext)=>{if(!a.permissions.includes('integration.approve'))throw new ApiError(403,'Integration approval permission required.','forbidden')};
const independent=(a:ActorContext,r:{createdBy?:string;submittedBy?:string})=>{requireApprove(a);if(r.createdBy===a.uid||r.submittedBy===a.uid)throw new ApiError(409,'Independent approval is required.','independent_approval_required')};
async function all<T>(orgId:string,c:string,limit=3000):Promise<T[]>{const s=await adminDb().collection(`organizations/${orgId}/${c}`).limit(limit).get();return s.docs.map(d=>d.data() as T)}
async function get<T>(orgId:string,c:string,id:string,label:string):Promise<T>{const s=await adminDb().doc(`organizations/${orgId}/${c}/${id}`).get();if(!s.exists)throw new ApiError(404,`${label} not found.`,'not_found');return s.data() as T}
async function audit(a:ActorContext,action:string,type:string,id:string,before:unknown,after:unknown){const x=buildAudit(a,{action,entityType:type,entityId:id,before,after});await adminDb().doc(`organizations/${a.orgId}/auditLogs/${x.id}`).create(x)}
async function createCode<T extends{id:string;code:string}>(a:ActorContext,c:string,index:string,r:T,action:string){const db=adminDb(),ref=db.doc(`organizations/${a.orgId}/${c}/${r.id}`),ix=db.doc(`organizations/${a.orgId}/${index}/${r.code}`),au=buildAudit(a,{action,entityType:c,entityId:r.id,after:r});await db.runTransaction(async(tx:any)=>{if((await tx.get(ix)).exists)throw new ApiError(409,`${r.code} already exists.`,'duplicate_code');tx.create(ref,r);tx.create(ix,{id:r.id,code:r.code,createdAt:now()});tx.create(db.doc(`organizations/${a.orgId}/auditLogs/${au.id}`),au)});return r}

function transportAvailability(kind:IntegrationAdapterProfile['adapterKind']){return kind==='sftp_json'?'external_provider_required' as const:'built_in' as const;}
function validateProfileCompatibility(connector:IntegrationConnector,contract:IntegrationContract,input:{adapterKind:IntegrationAdapterProfile['adapterKind'];requestMethod:string;fileObjectPath?:string;sftpRemotePath?:string}){
  if(contract.direction==='inbound'&&['rest_push'].includes(input.adapterKind))throw new ApiError(400,'Inbound contracts cannot use rest_push.','adapter_contract_direction_mismatch');
  if(contract.direction==='outbound'&&['rest_pull','webhook_hmac'].includes(input.adapterKind))throw new ApiError(400,'Outbound contracts cannot use pull/webhook adapters.','adapter_contract_direction_mismatch');
  if(input.adapterKind.startsWith('scim_')&&connector.protocol!=='scim2')throw new ApiError(400,'SCIM adapter profiles require a scim2 connector.','scim_connector_required');
  if(input.adapterKind==='webhook_hmac'&&connector.protocol!=='webhook')throw new ApiError(400,'Signed webhook profiles require a webhook connector.','webhook_connector_required');
  if(input.adapterKind==='file_json'&&connector.protocol!=='file')throw new ApiError(400,'File adapter profiles require a file connector.','file_connector_required');
  if(input.adapterKind==='sftp_json'&&connector.protocol!=='sftp')throw new ApiError(400,'SFTP adapter profiles require an sftp connector.','sftp_connector_required');
  if(input.adapterKind==='rest_pull'&&connector.protocol!=='rest_json')throw new ApiError(400,'REST pull profiles require a rest_json connector.','rest_connector_required');
  if(input.adapterKind==='rest_push'&&connector.protocol!=='rest_json')throw new ApiError(400,'REST push profiles require a rest_json connector.','rest_connector_required');
  if(input.adapterKind==='webhook_hmac'&&connector.authMode!=='hmac_secret')throw new ApiError(400,'Signed webhook profiles require connector authMode hmac_secret and a server-side secret reference.','webhook_secret_required');
  if(input.adapterKind==='rest_pull'&&input.requestMethod!=='GET')throw new ApiError(400,'REST pull adapter requestMethod must be GET.','invalid_rest_pull_method');
  if(input.adapterKind==='rest_push'&&input.requestMethod==='GET')throw new ApiError(400,'REST push adapter requestMethod must be POST, PUT or PATCH.','invalid_rest_push_method');
  if(input.adapterKind.startsWith('scim_')&&contract.direction==='inbound'&&input.requestMethod!=='GET')throw new ApiError(400,'Inbound SCIM adapter requestMethod must be GET.','invalid_scim_method');
  if(input.adapterKind.startsWith('scim_')&&contract.direction==='outbound'&&input.requestMethod==='GET')throw new ApiError(400,'Outbound SCIM adapter requestMethod must be POST, PUT or PATCH.','invalid_scim_method');
  if(input.adapterKind==='file_json'){
    if(input.requestMethod!=='GET')throw new ApiError(400,'File adapter requestMethod must remain GET; contract direction determines download/upload behavior.','invalid_file_method');
    const expected=`integrations/${connector.id}/${contract.direction}/`;if(!input.fileObjectPath?.startsWith(expected)||input.fileObjectPath.includes('..'))throw new ApiError(400,`File adapter path must remain under ${expected}.`,'invalid_file_object_path');
  }
  if(input.adapterKind==='sftp_json'){
    if(input.requestMethod!=='GET')throw new ApiError(400,'SFTP adapter requestMethod must remain GET; contract direction determines download/upload behavior.','invalid_sftp_method');
    if(!input.sftpRemotePath?.startsWith('/')||input.sftpRemotePath.includes('..'))throw new ApiError(400,'SFTP remote path must be absolute and cannot contain traversal segments.','invalid_sftp_remote_path');
  }
}

export async function runtimeDashboard(a:ActorContext):Promise<IntegrationRuntimeDashboard>{
  requireRead(a);const[profiles,schedules,states,webhookReceipts,replayRequests,sandboxResults]=await Promise.all([all<IntegrationAdapterProfile>(a.orgId,'integrationAdapterProfiles'),all<IntegrationSchedule>(a.orgId,'integrationSchedules'),all<IntegrationRuntimeState>(a.orgId,'integrationRuntimeStates'),all<IntegrationWebhookReceipt>(a.orgId,'integrationWebhookReceipts'),all<IntegrationReplayRequest>(a.orgId,'integrationReplayRequests'),all<IntegrationSandboxResult>(a.orgId,'integrationSandboxRuns')]);const cutoff=Date.now()-86400000,cutoff30=Date.now()-30*86400000;
  return {profiles:profiles.sort((x,y)=>x.code.localeCompare(y.code)),schedules:schedules.sort((x,y)=>x.nextRunAt.localeCompare(y.nextRunAt)),states:states.sort((x,y)=>y.updatedAt.localeCompare(x.updatedAt)),webhookReceipts:webhookReceipts.sort((x,y)=>y.receivedAt.localeCompare(x.receivedAt)).slice(0,200),replayRequests:replayRequests.sort((x,y)=>y.updatedAt.localeCompare(x.updatedAt)).slice(0,200),sandboxResults:sandboxResults.sort((x,y)=>y.executedAt.localeCompare(x.executedAt)).slice(0,100),metrics:{activeProfiles:profiles.filter(x=>x.status==='active').length,activeSchedules:schedules.filter(x=>x.status==='active').length,openCircuits:states.filter(x=>x.circuitStatus==='open'&&(!x.openUntil||new Date(x.openUntil).getTime()>Date.now())).length,overdueSchedules:schedules.filter(x=>x.status==='active'&&new Date(x.nextRunAt).getTime()<Date.now()-60000).length,webhookReceipts24h:webhookReceipts.filter(x=>new Date(x.receivedAt).getTime()>=cutoff).length,rejectedWebhookReceipts24h:webhookReceipts.filter(x=>new Date(x.receivedAt).getTime()>=cutoff&&x.status!=='accepted').length,pendingReplayApprovals:replayRequests.filter(x=>x.status==='in_review').length,sandboxFailures30d:sandboxResults.filter(x=>new Date(x.executedAt).getTime()>=cutoff30&&x.status==='failed').length},operatingNotice:'The v3.2 runtime executes approved integration profiles through bounded transports. HTTP/SCIM and governed Firebase Storage JSON file exchange are built in. SFTP is an explicit deployment-provider extension and fails closed unless registered. Inbound data remains server-only staging; outbound data must already exist as authorized staging for the run. Runtime execution never calls consequential HCM mutation services.',generatedAt:now()};
}

export async function createAdapterProfile(a:ActorContext,raw:unknown){requireManage(a);const i=adapterProfileCreateSchema.parse(raw),[connector,contract]=await Promise.all([get<IntegrationConnector>(a.orgId,'integrationConnectors',i.connectorId,'Connector'),get<IntegrationContract>(a.orgId,'integrationContracts',i.contractId,'Contract')]);if(!['approved','active','paused'].includes(connector.status))throw new ApiError(409,'Adapter profiles require an approved connector.','connector_not_approved');if(contract.status!=='approved')throw new ApiError(409,'Adapter profiles require an approved contract.','contract_not_approved');validateProfileCompatibility(connector,contract,i);if(i.deltaMode==='scim_start_index'&&!i.adapterKind.startsWith('scim_'))throw new ApiError(400,'SCIM start-index delta mode is restricted to SCIM adapters.','invalid_delta_mode');if(i.deltaMode==='cursor'&&i.adapterKind!=='rest_pull')throw new ApiError(400,'Cursor delta mode is restricted to REST pull adapters.','invalid_delta_mode');if(i.adapterKind==='webhook_hmac'&&i.deltaMode!=='none')throw new ApiError(400,'Signed webhook profiles do not use pull delta state.','invalid_delta_mode');if(i.resourcePath){let decoded=i.resourcePath;try{decoded=decodeURIComponent(i.resourcePath)}catch{throw new ApiError(400,'Adapter resourcePath contains invalid URL encoding.','invalid_resource_path')}if(i.resourcePath.includes('://')||i.resourcePath.startsWith('//')||decoded.startsWith('/')||decoded.includes('\\')||decoded.split('/').some(segment=>segment==='..'))throw new ApiError(400,'Adapter resourcePath must remain a traversal-free relative path under the approved connector baseUrl.','absolute_resource_path_prohibited')}assertSecretReferenceShape(connector.secretRef);if(['rest_pull','rest_push','scim_users','scim_groups'].includes(i.adapterKind)&&connector.baseUrl)await validateIntegrationEndpoint(new URL(i.resourcePath||'',connector.baseUrl.endsWith('/')?connector.baseUrl:`${connector.baseUrl}/`).toString());const ts=now(),id=randomUUID(),r:IntegrationAdapterProfile={id,...i,status:'draft',transportAvailability:transportAvailability(i.adapterKind),consequentialWorkerMutationProhibited:true,createdBy:a.uid,createdAt:ts,updatedAt:ts};return createCode(a,'integrationAdapterProfiles','integrationAdapterCodeIndex',r,'integration.runtime.profile.create')}

export async function actAdapterProfile(a:ActorContext,id:string,raw:unknown){requireManage(a);const i=adapterProfileActionSchema.parse(raw),b=await get<IntegrationAdapterProfile>(a.orgId,'integrationAdapterProfiles',id,'Adapter profile'),ts=now();let x={...b,updatedAt:ts};if(i.action==='submit_review'){if(b.status!=='draft')throw new ApiError(409,'Only draft adapter profiles can be submitted.','invalid_state');x={...x,status:'in_review' as const,submittedBy:a.uid,submittedAt:ts}}else if(i.action==='approve'){independent(a,b);if(b.status!=='in_review')throw new ApiError(409,'Only adapter profiles in review can be approved.','invalid_state');const[connector,contract]=await Promise.all([get<IntegrationConnector>(a.orgId,'integrationConnectors',b.connectorId,'Connector'),get<IntegrationContract>(a.orgId,'integrationContracts',b.contractId,'Contract')]);validateProfileCompatibility(connector,contract,b);x={...x,status:'approved' as const,approvedBy:a.uid,approvedAt:ts}}else if(i.action==='activate'){requireApprove(a);if(!['approved','paused'].includes(b.status))throw new ApiError(409,'Only approved or paused adapter profiles can activate.','invalid_state');if(b.adapterKind==='sftp_json'&&!hasSftpRuntimeProvider())throw new ApiError(503,'SFTP runtime provider is not registered; the profile must remain approved/paused.','sftp_provider_required');x={...x,status:'active' as const}}else if(i.action==='pause'){requireApprove(a);if(b.status!=='active')throw new ApiError(409,'Only active adapter profiles can pause.','invalid_state');x={...x,status:'paused' as const}}else if(i.action==='retire'){requireApprove(a);x={...x,status:'retired' as const}}else if(i.action==='reopen'){requireApprove(a);x={...x,status:'draft' as const,submittedBy:undefined,submittedAt:undefined,approvedBy:undefined,approvedAt:undefined}}await adminDb().doc(`organizations/${a.orgId}/integrationAdapterProfiles/${id}`).set(x);await audit(a,`integration.runtime.profile.${i.action}`,'integrationAdapterProfile',id,b,x);return x}

function initialState(profile:IntegrationAdapterProfile):IntegrationRuntimeState{return{id:profile.id,profileId:profile.id,connectorId:profile.connectorId,circuitStatus:'closed',consecutiveFailures:0,updatedAt:now()}}
async function stateFor(orgId:string,profile:IntegrationAdapterProfile){const s=await adminDb().doc(`organizations/${orgId}/integrationRuntimeStates/${profile.id}`).get();return s.exists?s.data() as IntegrationRuntimeState:initialState(profile)}
async function saveState(orgId:string,state:IntegrationRuntimeState){await adminDb().doc(`organizations/${orgId}/integrationRuntimeStates/${state.id}`).set(state)}
async function stagingForRun(orgId:string,runId:string){return (await all<IntegrationStagingRecord>(orgId,'integrationStagingRecords',5000)).filter(x=>x.runId===runId&&x.status==='staged'&&x.validationStatus==='valid')}

export async function executeRuntimeRun(a:ActorContext,raw:unknown){requireManage(a);const {runId}=runtimeExecuteSchema.parse(raw),run=await get<IntegrationRun>(a.orgId,'integrationRuns',runId,'Integration run');if(!['queued','running'].includes(run.status))throw new ApiError(409,'Only queued/running runs can execute through the runtime.','run_not_active');const profiles=(await all<IntegrationAdapterProfile>(a.orgId,'integrationAdapterProfiles')).filter(x=>x.connectorId===run.connectorId&&x.contractId===run.contractId&&['active','approved'].includes(x.status));if(profiles.length!==1)throw new ApiError(409,'Exactly one active/approved adapter profile must match the run connector and contract.','adapter_profile_ambiguous');return executeWithProfile(a,run,profiles[0]!)}

async function executeWithProfile(a:ActorContext,run:IntegrationRun,profile:IntegrationAdapterProfile){const[connector,contract]=await Promise.all([get<IntegrationConnector>(a.orgId,'integrationConnectors',run.connectorId,'Connector'),get<IntegrationContract>(a.orgId,'integrationContracts',run.contractId,'Contract')]);let state=await stateFor(a.orgId,profile);const ts=now();if(!circuitAllows(state)){throw new ApiError(503,`Integration circuit is open until ${state.openUntil||'reset'}.`,'integration_circuit_open')}if(state.circuitStatus==='open')state={...state,circuitStatus:'half_open',updatedAt:ts};state={...state,lastAttemptAt:ts,lastRunId:run.id,updatedAt:ts};await saveState(a.orgId,state);if(run.status==='queued')await actRun(a,run.id,{action:'start'});
  try{
    if(profile.adapterKind==='webhook_hmac')throw new ApiError(409,'Webhook profiles execute only through signed inbound webhook receipt.','webhook_push_only');
    if(run.direction==='inbound'){
      const result=await pullInbound(connector,contract,profile,state);let accepted=0,rejected=0;for(let idx=0;idx<result.records.length;idx++){const record=result.records[idx],key=getPath(record,profile.recordKeyPath)||`runtime-${run.id}-${idx}`;const staged=await stageIntegrationRecord(a,{runId:run.id,recordKey:String(key),record});if(staged.validationStatus==='valid')accepted++;else rejected++;}
      await actRun(a,run.id,{action:'finish',recordsReceived:result.records.length,recordsAccepted:accepted,recordsRejected:rejected,latencyMs:Math.max(0,Date.now()-new Date(ts).getTime()),payloadHash:sha(JSON.stringify(result.records))});state={...state,...nextSuccessState(),cursor:result.cursor??state.cursor,etag:result.etag??state.etag,scimStartIndex:result.scimStartIndex??state.scimStartIndex,lastRunId:run.id,updatedAt:now()};await saveState(a.orgId,state);return{runId:run.id,status:rejected?accepted?'partial':'failed':'succeeded',recordsReceived:result.records.length,recordsAccepted:accepted,recordsRejected:rejected,state};
    }
    const staging=await stagingForRun(a.orgId,run.id);if(!staging.length)throw new ApiError(409,'Outbound runtime execution requires valid server-side staging records for this run.','outbound_staging_required');const records=staging.map(x=>x.data);const result=await pushOutbound(connector,profile,records);await actRun(a,run.id,{action:'finish',recordsReceived:records.length,recordsAccepted:result.accepted,recordsRejected:records.length-result.accepted,latencyMs:Math.max(0,Date.now()-new Date(ts).getTime()),payloadHash:sha(JSON.stringify(records))});const db=adminDb(),batch=db.batch(),u=now();for(const staged of staging)batch.set(db.doc(`organizations/${a.orgId}/integrationStagingRecords/${staged.id}`),{status:'acknowledged',updatedAt:u},{merge:true});await batch.commit();state={...state,...nextSuccessState(),lastRunId:run.id,updatedAt:now()};await saveState(a.orgId,state);return{runId:run.id,status:'succeeded',recordsReceived:records.length,recordsAccepted:result.accepted,recordsRejected:0,state};
  }catch(e){const code=e instanceof ApiError?e.code:'runtime_execution_failed',message=e instanceof Error?e.message:'Runtime execution failed.';try{await actRun(a,run.id,{action:'fail',errorCode:code,errorMessage:message,recordsReceived:0,recordsAccepted:0,recordsRejected:0})}catch{}state={...state,...nextFailureState(state,profile.circuitBreaker,code,message,now()),lastRunId:run.id,updatedAt:now()};await saveState(a.orgId,state);throw e;}
}

export async function executeProfile(a:ActorContext,profileId:string,mode:'scheduled'|'manual'|'test'|'replay'='manual',executionKey?:string){requireManage(a);const profile=await get<IntegrationAdapterProfile>(a.orgId,'integrationAdapterProfiles',profileId,'Adapter profile');if(profile.status!=='active'&&mode!=='test')throw new ApiError(409,'Non-test runtime execution requires an active adapter profile.','adapter_profile_not_active');const contract=await get<IntegrationContract>(a.orgId,'integrationContracts',profile.contractId,'Contract');if(contract.direction==='outbound'&&mode==='scheduled')throw new ApiError(409,'Scheduled outbound execution is blocked because v3.2 does not source consequential domain data automatically. Create an authorized outbound run and staging records first.','scheduled_outbound_prohibited');const idempotencyKey=executionKey||`runtime:${profile.id}:${mode}:${new Date().toISOString().slice(0,16)}:${randomUUID()}`;let run:IntegrationRun;try{run=await createRun(a,{connectorId:profile.connectorId,contractId:profile.contractId,direction:contract.direction,mode,idempotencyKey,correlationId:`runtime-${profile.id}-${Date.now()}`})}catch(e){if(!(executionKey&&e instanceof ApiError&&e.code==='duplicate_idempotency_key'))throw e;const hash=sha(`${profile.connectorId}:${idempotencyKey}`),ix=await adminDb().doc(`organizations/${a.orgId}/integrationIdempotencyIndex/${hash}`).get(),priorId=String(ix.data()?.runId||'');if(!priorId)throw e;run=await get<IntegrationRun>(a.orgId,'integrationRuns',priorId,'Prior idempotent integration run');if(!['queued','running'].includes(run.status)){const state=await stateFor(a.orgId,profile),status=run.status==='succeeded'?'succeeded':run.status==='partial'?'partial':'failed';return{runId:run.id,status,recordsReceived:run.recordsReceived,recordsAccepted:run.recordsAccepted,recordsRejected:run.recordsRejected,state,idempotent:true}}}return executeWithProfile(a,run,profile)}

export async function runSandbox(a:ActorContext,raw:unknown){requireManage(a);const i=sandboxSchema.parse(raw),profile=await get<IntegrationAdapterProfile>(a.orgId,'integrationAdapterProfiles',i.profileId,'Adapter profile'),[connector,contract]=await Promise.all([get<IntegrationConnector>(a.orgId,'integrationConnectors',profile.connectorId,'Connector'),get<IntegrationContract>(a.orgId,'integrationContracts',profile.contractId,'Contract')]);const issues:string[]=[];let endpointValidated=true,secretReferenceValidated=true,mappingValidated=true,contractValidated=true;if(['rest_pull','rest_push','scim_users','scim_groups'].includes(profile.adapterKind)){try{if(!connector.baseUrl)throw new Error('base URL missing');await validateIntegrationEndpoint(new URL(profile.resourcePath||'',connector.baseUrl.endsWith('/')?connector.baseUrl:`${connector.baseUrl}/`).toString())}catch{endpointValidated=false;issues.push('endpoint_invalid')}}if(connector.authMode!=='none'){try{await resolveSecretReference(connector.secretRef)}catch{secretReferenceValidated=false;issues.push(`secret_provider_${secretProviderKind(connector.secretRef)}_unavailable`)}}if(profile.adapterKind==='sftp_json'&&!hasSftpRuntimeProvider())issues.push('sftp_provider_required');if(i.sampleRecord!==undefined){try{const mapped=contract.fieldMappings.length?await import('./runtime-utils').then(m=>m.applyFieldMappings(i.sampleRecord,contract.fieldMappings)):i.sampleRecord;const result=validateContractRecord(contract.jsonSchema,mapped);contractValidated=result.valid;if(!result.valid)issues.push(...result.issues.slice(0,10).map(x=>`contract:${x.code}`));}catch{mappingValidated=false;contractValidated=false;issues.push('mapping_failed')}}const id=randomUUID(),r:IntegrationSandboxResult={id,profileId:profile.id,connectorId:connector.id,contractId:contract.id,status:endpointValidated&&secretReferenceValidated&&mappingValidated&&contractValidated&&!issues.includes('sftp_provider_required')?'passed':'failed',endpointValidated,secretReferenceValidated,mappingValidated,contractValidated,transportAvailability:profile.adapterKind==='sftp_json'&&!hasSftpRuntimeProvider()?'provider_required':'available',issueCodes:[...new Set(issues)],executedBy:a.uid,executedAt:now()};await adminDb().doc(`organizations/${a.orgId}/integrationSandboxRuns/${id}`).create(r);await audit(a,'integration.runtime.sandbox','integrationSandboxRun',id,undefined,r);return r}

export async function createSchedule(a:ActorContext,raw:unknown){requireManage(a);const i=scheduleCreateSchema.parse(raw),profile=await get<IntegrationAdapterProfile>(a.orgId,'integrationAdapterProfiles',i.profileId,'Adapter profile'),contract=await get<IntegrationContract>(a.orgId,'integrationContracts',profile.contractId,'Contract');if(contract.direction!=='inbound')throw new ApiError(409,'Scheduled runtime sync is restricted to inbound profiles in v3.2.','scheduled_outbound_prohibited');const ts=now(),id=randomUUID(),r:IntegrationSchedule={id,code:i.code,name:i.name,profileId:i.profileId,cadence:i.cadence,intervalMinutes:'intervalMinutes'in i?i.intervalMinutes:undefined,dailyTimeUtc:'dailyTimeUtc'in i?i.dailyTimeUtc:undefined,nextRunAt:i.nextRunAt||nextScheduleAt(i),status:'draft',createdBy:a.uid,createdAt:ts,updatedAt:ts};return createCode(a,'integrationSchedules','integrationScheduleCodeIndex',r,'integration.runtime.schedule.create')}
export async function actSchedule(a:ActorContext,id:string,raw:unknown){requireManage(a);const i=scheduleActionSchema.parse(raw),b=await get<IntegrationSchedule>(a.orgId,'integrationSchedules',id,'Integration schedule'),ts=now();let x={...b,updatedAt:ts};if(i.action==='submit_review'){if(b.status!=='draft')throw new ApiError(409,'Only draft schedules can be submitted.','invalid_state');x={...x,status:'in_review' as const,submittedBy:a.uid,submittedAt:ts}}else if(i.action==='approve'){independent(a,b);if(b.status!=='in_review')throw new ApiError(409,'Only schedules in review can be approved.','invalid_state');x={...x,status:'approved' as const,approvedBy:a.uid,approvedAt:ts}}else if(i.action==='activate'){requireApprove(a);if(!['approved','paused'].includes(b.status))throw new ApiError(409,'Only approved/paused schedules can activate.','invalid_state');const p=await get<IntegrationAdapterProfile>(a.orgId,'integrationAdapterProfiles',b.profileId,'Adapter profile');if(p.status!=='active')throw new ApiError(409,'Schedule activation requires an active adapter profile.','adapter_profile_not_active');x={...x,status:'active' as const,nextRunAt:new Date(b.nextRunAt).getTime()>Date.now()?b.nextRunAt:nextScheduleAt(b)}}else if(i.action==='pause'){requireApprove(a);if(b.status!=='active')throw new ApiError(409,'Only active schedules can pause.','invalid_state');x={...x,status:'paused' as const}}else if(i.action==='retire'){requireApprove(a);x={...x,status:'retired' as const}}else if(i.action==='run_now'){requireApprove(a);const result=await executeProfile(a,b.profileId,'scheduled');x={...x,lastRunAt:ts,lastRunId:result.runId,lastStatus:result.status==='succeeded'?'succeeded':result.status==='partial'?'partial':'failed',lastMessage:'Manual scheduled execution completed.',nextRunAt:nextScheduleAt(b)}}await adminDb().doc(`organizations/${a.orgId}/integrationSchedules/${id}`).set(x);await audit(a,`integration.runtime.schedule.${i.action}`,'integrationSchedule',id,b,x);return x}

export async function processIntegrationSchedules(orgId:string){
  const actor=systemActor(orgId,'system:integration-runtime-scheduler'),db=adminDb(),rows=await all<IntegrationSchedule>(orgId,'integrationSchedules'),candidates=rows.filter(x=>x.status==='active'&&new Date(x.nextRunAt).getTime()<=Date.now()),summary={due:candidates.length,claimed:0,succeeded:0,partial:0,failed:0};
  for(const snapshot of candidates){
    const token=randomUUID(),tokenHash=sha(token),ref=db.doc(`organizations/${orgId}/integrationSchedules/${snapshot.id}`);let schedule:IntegrationSchedule|undefined;
    await db.runTransaction(async(tx:any)=>{const current=await tx.get(ref);if(!current.exists)return;const row=current.data() as IntegrationSchedule;const leaseActive=row.leaseUntil&&new Date(row.leaseUntil).getTime()>Date.now();if(row.status!=='active'||new Date(row.nextRunAt).getTime()>Date.now()||leaseActive)return;const claimed={...row,leaseUntil:new Date(Date.now()+10*60000).toISOString(),leaseTokenHash:tokenHash,updatedAt:now()};tx.set(ref,claimed);schedule=claimed});
    if(!schedule)continue;summary.claimed++;let status:'succeeded'|'partial'|'failed'='failed',message='';let runId:string|undefined;
    try{const result=await executeProfile(actor,schedule.profileId,'scheduled',`schedule:${schedule.id}:${schedule.nextRunAt}`);runId=result.runId;status=result.status==='partial'?'partial':result.status==='succeeded'?'succeeded':'failed';message=`Scheduled integration ${status}.`;summary[status]++;}catch(e){summary.failed++;message=e instanceof Error?e.message:'Scheduled integration failed.';}
    await db.runTransaction(async(tx:any)=>{const current=await tx.get(ref);if(!current.exists)return;const row=current.data() as IntegrationSchedule;if(row.leaseTokenHash!==tokenHash)return;tx.set(ref,{lastRunAt:now(),lastRunId:runId,lastStatus:status,lastMessage:message,nextRunAt:nextScheduleAt(row),updatedAt:now(),leaseUntil:null,leaseTokenHash:null},{merge:true})});
  }
  const sigCutoff=Date.now(),oldSigs=await db.collection(`organizations/${orgId}/integrationWebhookSignatureIndex`).limit(500).get();const expired=oldSigs.docs.filter((d:any)=>new Date(String(d.data()?.expiresAt||0)).getTime()<sigCutoff);if(expired.length){const batch=db.batch();for(const d of expired)batch.delete(d.ref);await batch.commit();}
  await audit(actor,'integration.runtime.scheduler.review','organization',orgId,undefined,{...summary,expiredReplayIndexesRemoved:expired.length});return summary;
}

export async function createReplay(a:ActorContext,raw:unknown){requireManage(a);const i=replayCreateSchema.parse(raw),[run,profile]=await Promise.all([get<IntegrationRun>(a.orgId,'integrationRuns',i.sourceRunId,'Source run'),get<IntegrationAdapterProfile>(a.orgId,'integrationAdapterProfiles',i.profileId,'Adapter profile')]);if(run.connectorId!==profile.connectorId||run.contractId!==profile.contractId)throw new ApiError(409,'Replay profile must match the source run connector and contract.','replay_profile_mismatch');if(!['succeeded','partial','failed','dead_lettered'].includes(run.status))throw new ApiError(409,'Only terminal runs can be proposed for replay.','source_run_not_terminal');const ts=now(),id=randomUUID(),r:IntegrationReplayRequest={id,...i,status:'draft',createdBy:a.uid,createdAt:ts,updatedAt:ts};await adminDb().doc(`organizations/${a.orgId}/integrationReplayRequests/${id}`).create(r);await audit(a,'integration.runtime.replay.create','integrationReplayRequest',id,undefined,r);return r}
export async function actReplay(a:ActorContext,id:string,raw:unknown){requireManage(a);const i=replayActionSchema.parse(raw),b=await get<IntegrationReplayRequest>(a.orgId,'integrationReplayRequests',id,'Replay request'),ts=now();let x={...b,updatedAt:ts};if(i.action==='submit_review'){if(b.status!=='draft')throw new ApiError(409,'Only draft replay requests can be submitted.','invalid_state');x={...x,status:'in_review' as const,submittedBy:a.uid,submittedAt:ts}}else if(i.action==='approve'){independent(a,b);if(b.status!=='in_review')throw new ApiError(409,'Only replay requests in review can be approved.','invalid_state');x={...x,status:'approved' as const,approvedBy:a.uid,approvedAt:ts}}else if(i.action==='reject'){requireApprove(a);if(!['draft','in_review','approved'].includes(b.status))throw new ApiError(409,'Replay request cannot be rejected in its current state.','invalid_state');x={...x,status:'rejected' as const}}else if(i.action==='execute'){requireApprove(a);if(b.status!=='approved')throw new ApiError(409,'Replay requires independent approval before execution.','replay_not_approved');const source=await get<IntegrationRun>(a.orgId,'integrationRuns',b.sourceRunId,'Source run'),staged=(await all<IntegrationStagingRecord>(a.orgId,'integrationStagingRecords',5000)).filter(s=>s.runId===source.id&&s.validationStatus==='valid'&&s.data!==undefined);const run=await createRun(a,{connectorId:source.connectorId,contractId:source.contractId,direction:source.direction,mode:'replay',idempotencyKey:`approved-replay:${b.id}`,correlationId:`replay-${b.id}`});for(let idx=0;idx<staged.length;idx++)await stageIntegrationRecord(a,{runId:run.id,recordKey:`replay:${staged[idx]!.recordKeyHash}:${idx}`,record:staged[idx]!.data});const result=source.direction==='outbound'?await executeWithProfile(a,run,await get<IntegrationAdapterProfile>(a.orgId,'integrationAdapterProfiles',b.profileId,'Adapter profile')):await actRun(a,run.id,{action:'finish',recordsReceived:staged.length,recordsAccepted:staged.length,recordsRejected:0,latencyMs:0});x={...x,status:'executed' as const,executedBy:a.uid,executedAt:ts,replayRunId:run.id};void result}await adminDb().doc(`organizations/${a.orgId}/integrationReplayRequests/${id}`).set(x);await audit(a,`integration.runtime.replay.${i.action}`,'integrationReplayRequest',id,b,x);return x}

export async function ingestSignedWebhook(input:{orgId:string;connectorCode:string;timestamp:string;signature:string;body:string;correlationId?:string}){
  const {orgId,connectorCode,timestamp,signature,body}=input;
  const configuredLimit=Number(process.env.OPSIQO_WEBHOOK_MAX_BODY_BYTES||1048576);
  const maxBody=Number.isInteger(configuredLimit)&&configuredLimit>=1024&&configuredLimit<=5*1024*1024?configuredLimit:1048576;
  if(Buffer.byteLength(body,'utf8')>maxBody)throw new ApiError(413,'Webhook body exceeds governed size limit.','webhook_too_large');
  const t=Number(timestamp);
  if(!Number.isFinite(t)||Math.abs(Date.now()-t)>300000)throw new ApiError(401,'Webhook timestamp is outside the five-minute acceptance window.','webhook_timestamp_invalid');

  const db=adminDb(),ix=await db.doc(`organizations/${orgId}/integrationConnectorCodeIndex/${connectorCode.toUpperCase()}`).get();
  if(!ix.exists)throw new ApiError(404,'Webhook connector is not available.','webhook_not_found');
  const connector=await get<IntegrationConnector>(orgId,'integrationConnectors',String(ix.data()?.id),'Connector');
  if(connector.protocol!=='webhook'||connector.status!=='active')throw new ApiError(404,'Webhook connector is not available.','webhook_not_found');
  const profiles=(await all<IntegrationAdapterProfile>(orgId,'integrationAdapterProfiles')).filter(p=>p.connectorId===connector.id&&p.adapterKind==='webhook_hmac'&&p.status==='active');
  if(profiles.length!==1)throw new ApiError(409,'Webhook connector requires exactly one active signed-webhook adapter profile.','webhook_profile_ambiguous');
  const profile=profiles[0]!,secret=await resolveSecretReference(connector.secretRef);
  if(!secret||!verifyWebhookSignature(secret,timestamp,body,signature))throw new ApiError(401,'Webhook signature validation failed.','webhook_signature_invalid');

  let payload:unknown;
  try{payload=JSON.parse(body)}catch{throw new ApiError(400,'Webhook body must be JSON.','webhook_json_required')}
  const contract=await get<IntegrationContract>(orgId,'integrationContracts',profile.contractId,'Contract');
  if(contract.direction!=='inbound')throw new ApiError(409,'Webhook contract must be inbound.','webhook_contract_direction');
  const {extractRecords,applyFieldMappings}=await import('./runtime-utils');
  const rawRecords=extractRecords(payload,profile.recordsPath).slice(0,connector.maxBatchSize);
  const mappedRecords=rawRecords.map((record,idx)=>({record:applyFieldMappings(record,contract.fieldMappings),idx}));

  const signatureHash=sha(`${connector.id}:${timestamp}:${signature.toLowerCase()}`),sigRef=db.doc(`organizations/${orgId}/integrationWebhookSignatureIndex/${signatureHash}`),receiptId=randomUUID(),receivedAt=now();
  const claim=await db.runTransaction(async(tx:any)=>{
    const existing=await tx.get(sigRef),data=existing.exists?existing.data():undefined;
    if(data?.status==='completed'&&data.receiptId&&data.runId)return{duplicate:true,data};
    if(data?.status==='processing'&&new Date(String(data.processingUntil||0)).getTime()>Date.now())throw new ApiError(409,'Webhook delivery is already being processed.','webhook_processing');
    tx.set(sigRef,{id:signatureHash,connectorId:connector.id,status:'processing',receivedAt,processingUntil:new Date(Date.now()+120000).toISOString(),expiresAt:new Date(Date.now()+86400000).toISOString(),receiptId},{merge:false});
    return{duplicate:false,data:undefined};
  });
  if(claim.duplicate){
    return{receiptId:String(claim.data.receiptId),runId:String(claim.data.runId),recordsReceived:Number(claim.data.recordsReceived||0),recordsAccepted:Number(claim.data.recordsAccepted||0),recordsRejected:Number(claim.data.recordsRejected||0),duplicate:true};
  }

  const actor=systemActor(orgId,'system:integration-webhook');let runId:string|undefined;
  try{
    const run=await createRun(actor,{connectorId:connector.id,contractId:contract.id,direction:'inbound',mode:'webhook',idempotencyKey:`webhook:${signatureHash}:${receiptId}`,correlationId:input.correlationId||`webhook-${receiptId}`});
    runId=run.id;let accepted=0,rejected=0;
    for(const item of mappedRecords){
      const key=getPath(item.record,profile.recordKeyPath)||`webhook-${receiptId}-${item.idx}`;
      const staged=await stageIntegrationRecord(actor,{runId:run.id,recordKey:String(key),record:item.record});
      if(staged.validationStatus==='valid')accepted++;else rejected++;
    }
    await actRun(actor,run.id,{action:'finish',recordsReceived:mappedRecords.length,recordsAccepted:accepted,recordsRejected:rejected,latencyMs:0});
    const receipt:IntegrationWebhookReceipt={id:receiptId,connectorId:connector.id,profileId:profile.id,contractId:contract.id,signatureHash,timestamp,receivedAt,runId:run.id,status:'accepted',recordCount:mappedRecords.length};
    const auditRecord=buildAudit(actor,{action:'integration.runtime.webhook.accept',entityType:'integrationWebhookReceipt',entityId:receiptId,after:receipt});
    await db.runTransaction(async(tx:any)=>{
      tx.create(db.doc(`organizations/${orgId}/integrationWebhookReceipts/${receiptId}`),receipt);
      tx.set(sigRef,{status:'completed',processingUntil:null,completedAt:now(),receiptId,runId:run.id,recordsReceived:mappedRecords.length,recordsAccepted:accepted,recordsRejected:rejected},{merge:true});
      tx.create(db.doc(`organizations/${orgId}/auditLogs/${auditRecord.id}`),auditRecord);
    });
    return{receiptId,runId:run.id,recordsReceived:mappedRecords.length,recordsAccepted:accepted,recordsRejected:rejected,duplicate:false};
  }catch(error){
    const errorCode=error instanceof ApiError?error.code:'webhook_processing_failed';
    const receipt:IntegrationWebhookReceipt={id:receiptId,connectorId:connector.id,profileId:profile.id,contractId:contract.id,signatureHash,timestamp,receivedAt,runId,status:'rejected',recordCount:mappedRecords.length,errorCode};
    const auditRecord=buildAudit(actor,{action:'integration.runtime.webhook.reject',entityType:'integrationWebhookReceipt',entityId:receiptId,after:receipt});
    await db.runTransaction(async(tx:any)=>{
      tx.set(db.doc(`organizations/${orgId}/integrationWebhookReceipts/${receiptId}`),receipt,{merge:false});
      tx.set(sigRef,{status:'failed',processingUntil:null,failedAt:now(),receiptId,runId:runId||null,errorCode},{merge:true});
      tx.create(db.doc(`organizations/${orgId}/auditLogs/${auditRecord.id}`),auditRecord);
    });
    throw error;
  }
}
