import { z } from 'zod';
const date=z.string().date();
const ids=z.array(z.string().min(1).max(240)).max(500).default([]);
const role=z.string().min(2).max(80);
export const evidenceCreateSchema=z.object({
  code:z.string().min(2).max(90).regex(/^[A-Z0-9._-]+$/),title:z.string().min(3).max(280),description:z.string().min(10).max(5000),sourceType:z.enum(['system_record','employee_document','policy_version','governance_control','diagnostic_result','regulatory_record','external_reference']),sourceEntityType:z.string().max(120).optional(),sourceEntityId:z.string().max(240).optional(),sourceUrl:z.string().url().refine(v=>v.startsWith('https://'),{message:'Assurance source URLs must use HTTPS.'}).optional(),storagePath:z.string().max(500).optional(),contentSha256:z.string().regex(/^[a-f0-9]{64}$/i).optional(),evidenceDate:date,ownerRole:role.default('hr_partner'),classification:z.enum(['internal','confidential','highly_confidential']).default('confidential'),retentionUntil:date.optional(),
}).superRefine((v,ctx)=>{if(v.sourceType==='external_reference'&&!v.sourceUrl)ctx.addIssue({code:'custom',message:'External reference evidence requires sourceUrl.',path:['sourceUrl']});if(v.sourceType!=='external_reference'&&!v.sourceEntityId&&!v.storagePath)ctx.addIssue({code:'custom',message:'Internal evidence requires a source entity or governed storage path.',path:['sourceEntityId']});});
export const evidenceActionSchema=z.discriminatedUnion('action',[
  z.object({action:z.literal('verify_integrity')}),z.object({action:z.literal('quarantine'),note:z.string().min(10).max(2000)}),z.object({action:z.literal('restore'),note:z.string().min(10).max(2000)}),z.object({action:z.literal('set_legal_hold'),note:z.string().min(10).max(2000)}),z.object({action:z.literal('release_legal_hold'),note:z.string().min(10).max(2000)}),z.object({action:z.literal('supersede'),replacementEvidenceId:z.string().min(1),note:z.string().min(10).max(2000)}),z.object({action:z.literal('expire'),note:z.string().min(10).max(2000)}),
]);
export const assurancePlanCreateSchema=z.object({code:z.string().min(2).max(90).regex(/^[A-Z0-9._-]+$/),title:z.string().min(3).max(280),planType:z.enum(['internal_audit','control_testing','compliance_assurance','external_audit_readiness']),objective:z.string().min(10).max(5000),scopeNote:z.string().min(10).max(5000),scopeControlIds:ids,scopeObligationIds:ids,ownerRole:role.default('hr_partner'),reviewerRole:role.default('hr_admin'),startDate:date,endDate:date,samplingMethod:z.enum(['risk_based','random','stratified','judgmental','full_population']).default('risk_based'),defaultSampleSize:z.number().int().min(1).max(500).default(25)}).refine(v=>v.endDate>=v.startDate,{message:'Plan end date must not precede start date.',path:['endDate']});
export const assurancePlanActionSchema=z.object({action:z.enum(['submit_review','approve','start','complete','close','cancel','reopen'])});
export const assuranceTestCreateSchema=z.object({planId:z.string().min(1),controlId:z.string().min(1),testProcedure:z.string().min(10).max(5000),expectedEvidence:z.string().min(5).max(3000),ownerUid:z.string().max(200).optional(),dueDate:date});
export const assuranceTestActionSchema=z.discriminatedUnion('action',[
  z.object({action:z.literal('start')}),z.object({action:z.literal('submit'),result:z.enum(['effective','partially_effective','ineffective','not_applicable']),evidenceIds:ids,sampleId:z.string().max(240).optional(),testerRationale:z.string().min(10).max(5000),exceptionCount:z.number().int().min(0).max(100000)}),z.object({action:z.literal('approve')}),z.object({action:z.literal('cancel')}),z.object({action:z.literal('reopen')}),
]);
export const evidenceRequestCreateSchema=z.object({planId:z.string().max(240).optional(),testId:z.string().max(240).optional(),title:z.string().min(3).max(260),requestDetail:z.string().min(10).max(5000),requestedFromRole:role,requestedByRole:role.default('hr_admin'),dueDate:date});
export const evidenceRequestActionSchema=z.discriminatedUnion('action',[
 z.object({action:z.literal('start')}),z.object({action:z.literal('submit'),evidenceIds:ids,responseNote:z.string().min(5).max(4000)}),z.object({action:z.literal('accept')}),z.object({action:z.literal('return'),responseNote:z.string().min(10).max(4000)}),z.object({action:z.literal('close')}),z.object({action:z.literal('cancel')}),z.object({action:z.literal('reopen')}),
]);
export const assuranceSampleCreateSchema=z.object({planId:z.string().min(1),testId:z.string().min(1),methodology:z.enum(['random','systematic_hash','judgmental','full_population']),populationDescription:z.string().min(5).max(1000),populationRefs:z.array(z.string().min(1).max(240)).min(1).max(5000),sampleSize:z.number().int().min(1).max(500),judgmentalSelectedRefs:z.array(z.string().min(1).max(240)).max(500).optional()});
export const assuranceFindingCreateSchema=z.object({planId:z.string().min(1),testId:z.string().max(240).optional(),title:z.string().min(3).max(260),severity:z.enum(['low','medium','high','critical']),condition:z.string().min(10).max(5000),criteria:z.string().min(10).max(5000),cause:z.string().min(5).max(4000),effectRisk:z.string().min(10).max(5000),recommendation:z.string().min(10).max(5000),ownerRole:role.default('hr_partner'),dueDate:date});
export const assuranceFindingActionSchema=z.discriminatedUnion('action',[
  z.object({action:z.literal('accept_risk'),reason:z.string().min(15).max(5000)}),z.object({action:z.literal('validate'),note:z.string().min(10).max(3000)}),z.object({action:z.literal('close')}),z.object({action:z.literal('reopen')}),
]);
export const capaCreateSchema=z.object({findingId:z.string().min(1),correctiveAction:z.string().min(10).max(5000),preventiveAction:z.string().min(10).max(5000),ownerRole:role.default('hr_partner'),dueDate:date,kpi:z.string().min(5).max(2000)});
export const capaActionSchema=z.discriminatedUnion('action',[
  z.object({action:z.literal('submit_review')}),z.object({action:z.literal('approve')}),z.object({action:z.literal('start')}),z.object({action:z.literal('complete')}),z.object({action:z.literal('verify'),verificationNote:z.string().min(10).max(4000)}),z.object({action:z.literal('close')}),z.object({action:z.literal('cancel')}),z.object({action:z.literal('reopen')}),
]);
export const reportCreateSchema=z.object({title:z.string().min(3).max(280),reportingDate:date,audience:z.enum(['executive','board','audit_committee','hr_leadership']),managementCommentary:z.string().min(10).max(7000),keyFindingIds:ids});
export const reportActionSchema=z.object({action:z.enum(['submit_review','approve','supersede','reopen'])});
