import { createHash,randomUUID } from 'node:crypto';
import path from 'node:path';
import type { ActorContext } from '@/domain/security';
import { CONTRACT_FIELD_KEYS,type ContractExtractedField,type ContractFieldKey,type ContractImportDraft,type ContractModulePrefill,type ContractWorkerMatch } from '@/domain/contract-import';
import { adminBucket,adminDb } from '@/lib/firebase/admin';
import { ApiError } from '@/lib/http/errors';
import { buildAudit } from '@/lib/audit/service';
import { extractDocxText,extractRtfText } from './docx';
import { extractPdfTextLayer } from '@/lib/data-import/pdf-text';
import { ALLOWED_CONTRACT_EXTENSIONS,ALLOWED_CONTRACT_MIME,confirmContractSchema,contractExtractionSchema,MAX_CONTRACT_BYTES } from './schemas';
import { CONTRACT_IMPORT_PROMPT_VERSION,governedContractExtraction } from './provider';

const HR_ROLES=new Set(['super_admin','org_admin','hr_admin','hr_partner']);
const now=()=>new Date().toISOString();
const norm=(s:string)=>s.toLowerCase().normalize('NFKC').replace(/[^\p{L}\p{N}]+/gu,' ').trim();
function requireContractImport(actor:ActorContext){if(!HR_ROLES.has(actor.role)||!actor.permissions.includes('documents.read' as any))throw new ApiError(403,'Contract import requires authorized HR document access.','forbidden')}
function ext(name:string){return path.extname(name).toLowerCase()}
function cleanName(name:string){return path.basename(name).normalize('NFKC').replace(/[^\p{L}\p{N}._-]+/gu,'_').slice(0,120)||'contract'}
function validMagic(file:{name:string;mimeType:string;bytes:Buffer}){const e=ext(file.name),b=file.bytes;if(e==='.pdf'||file.mimeType==='application/pdf')return b.subarray(0,5).toString()==='%PDF-';if(e==='.docx'||file.mimeType==='application/vnd.openxmlformats-officedocument.wordprocessingml.document')return b.subarray(0,2).toString()==='PK'&&b.toString('latin1').includes('[Content_Types].xml')&&b.toString('latin1').includes('word/');if(e==='.rtf'||file.mimeType==='text/rtf'||file.mimeType==='application/rtf')return b.subarray(0,5).toString('ascii')==='{\\rtf';return !b.subarray(0,4096).includes(0)}
function blankField():ContractExtractedField{return{value:null,confidence:0,sourceSnippet:null,sourcePage:null,verified:false}}
function emptyFields(){return Object.fromEntries(CONTRACT_FIELD_KEYS.map(k=>[k,blankField()])) as Record<ContractFieldKey,ContractExtractedField>}
function sourceAround(text:string,index:number,len:number){return text.slice(Math.max(0,index-80),Math.min(text.length,index+len+180)).replace(/\s+/g,' ').trim().slice(0,700)}
function first(text:string,patterns:RegExp[]):{value:string;sourceSnippet:string}|null{for(const r of patterns){const m=r.exec(text);if(m?.[1])return{value:m[1].trim(),sourceSnippet:sourceAround(text,m.index,m[0].length)}}return null}
function deterministic(text:string){
 const f=emptyFields(),set=(k:ContractFieldKey,patterns:RegExp[],confidence=.72)=>{const x=first(text,patterns);if(x)f[k]={value:x.value,confidence,sourceSnippet:x.sourceSnippet,sourcePage:null,verified:true}};
 set('employerName',[/\b(?:employer|company)\s*(?:name)?\s*[:\-]\s*([^\n\r.;]{2,160})/i,/\bbetween\s+([^\n\r]{2,140}?)\s+(?:\(|and\b)/i],.66);
 set('employeeName',[/\b(?:employee|worker)\s*(?:name)?\s*[:\-]\s*([^\n\r.;]{2,140})/i,/\bemployment\s+of\s+([^\n\r.;]{2,140})/i],.7);
 set('employeeEmail',[/\b(?:employee\s+)?e-?mail\s*[:\-]\s*([^\s,;]+@[^\s,;]+)/i,/\b([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})\b/i],.82);
 set('employeeNumber',[/\bemployee\s*(?:number|no\.?|#)\s*[:\-]\s*([A-Z0-9_-]+)/i],.9);
 set('jobTitle',[/\b(?:position|job\s*title|title)\s*[:\-]\s*([^\n\r.;]{2,100})/i,/\bemployed\s+as\s+(?:an?\s+)?([^\n\r.;]{2,100})/i],.78);
 set('department',[/\bdepartment\s*[:\-]\s*([^\n\r.;]{2,100})/i],.82);
 set('managerName',[/\b(?:reports?\s+to|reporting\s+to|manager)\s*[:\-]?\s*([^\n\r.;]{2,100})/i],.7);
 set('workLocation',[/\b(?:work\s+location|location|place\s+of\s+work)\s*[:\-]\s*([^\n\r.;]{2,160})/i],.76);
 set('employmentType',[/\b(?:employment\s+type|status)\s*[:\-]\s*((?:full|part)[ -]?time|permanent|temporary|fixed[- ]term|casual|contract(?:or)?)/i],.86);
 set('startDate',[/\b(?:start|commencement|hire|effective)\s+date\s*[:\-]?\s*([^\n\r.;]{4,60})/i,/\bcommenc(?:e|ing|es)\s+(?:on\s+)?([^\n\r.;]{4,60})/i],.72);
 set('endDate',[/\b(?:end|expiry|expiration)\s+date\s*[:\-]?\s*([^\n\r.;]{4,60})/i],.75);
 set('probationPeriod',[/\bprobation(?:ary)?\s+(?:period\s*)?(?:of|is|:)\s*([^\n\r.;]{2,100})/i],.78);
 set('hoursPerWeek',[/\b([0-9]{1,3}(?:\.[0-9]+)?\s+hours?\s+per\s+week)\b/i,/\bregular\s+hours\s*[:\-]\s*([^\n\r.;]{2,80})/i],.88);
 set('schedule',[/\b(?:work\s+schedule|schedule|hours\s+of\s+work)\s*[:\-]\s*([^\n\r.;]{3,180})/i],.7);
 set('basePay',[/\b(?:salary|base\s+(?:salary|pay)|hourly\s+rate|wage)\s*[:\-]?\s*((?:CAD|USD|\$)\s*[0-9][0-9,]*(?:\.[0-9]{1,2})?(?:\s*(?:per|\/)(?:\s*)?(?:year|annum|hour|week|month))?)/i],.9);
 set('payFrequency',[/\bpay\s+(?:frequency|period)\s*[:\-]\s*([^\n\r.;]{2,80})/i,/\bpaid\s+(weekly|bi-?weekly|semi-?monthly|monthly)/i],.82);
 set('bonusCommission',[/\b(?:bonus|commission|incentive)\s*(?:plan|compensation)?\s*[:\-]?\s*([^\n\r.;]{3,200})/i],.65);
 set('vacationEntitlement',[/\bvacation\s*(?:entitlement|time|leave)?\s*[:\-]?\s*([^\n\r.;]{3,180})/i],.72);
 set('benefits',[/\bbenefits?\s*[:\-]?\s*([^\n\r.;]{3,220})/i],.64);
 set('overtimeTerms',[/\bovertime\s*[:\-]?\s*([^\n\r.;]{3,220})/i],.7);
 set('terminationNotice',[/\b(?:termination|notice)\s*[:\-]?\s*([^\n\r]{4,280})/i],.6);
 set('governingLaw',[/\bgovern(?:ed|ing)\s+by\s+(?:the\s+)?laws?\s+of\s+([^\n\r.;]{2,120})/i,/\bgoverning\s+law\s*[:\-]\s*([^\n\r.;]{2,120})/i],.86);
 set('signatureDate',[/\b(?:signed|dated)\s+(?:on\s+)?([^\n\r.;]{4,60})/i],.62);
 return{documentType:'employment_agreement',language:'unknown',summary:'Deterministic extraction was used. Review all fields against the source contract.',fields:f,warnings:['AI extraction was unavailable or not authorized; deterministic extraction has lower coverage and requires full human review.']};
}
function localText(file:{name:string;mimeType:string;bytes:Buffer}){const e=ext(file.name);if(e==='.pdf'||file.mimeType==='application/pdf'){try{return extractPdfTextLayer(file.bytes)}catch{return undefined}}if(e==='.docx')return extractDocxText(file.bytes);if(e==='.rtf'||file.mimeType==='text/rtf'||file.mimeType==='application/rtf')return extractRtfText(file.bytes);if(['.txt','.md'].includes(e)||file.mimeType.startsWith('text/'))return file.bytes.toString('utf8').replace(/\u0000/g,'').trim();return undefined}
function sanitizeExtraction(raw:any,text?:string,isPdf=false){
 const parsed=contractExtractionSchema.parse(raw),fields=emptyFields(),warnings=[...parsed.warnings];
 for(const k of CONTRACT_FIELD_KEYS){const x=(parsed.fields as any)[k];if(!x)continue;let confidence=Number(x.confidence||0),snippet=x.sourceSnippet?.trim()||null,value=x.value?.trim()||null,sourcePage=Number.isInteger(x.sourcePage)&&x.sourcePage>0?Number(x.sourcePage):null,verified=false;if(value&&snippet&&text){verified=norm(text).includes(norm(snippet));if(!verified){confidence=Math.min(confidence,.55);warnings.push(`${k}: source snippet could not be verified against extracted document text.`)}}else if(value&&isPdf){verified=false;if(!snippet){confidence=Math.min(confidence,.5);warnings.push(`${k}: PDF extraction returned no source snippet.`)}}if(value&&confidence<.75)warnings.push(`${k}: low-confidence extraction requires careful review.`);fields[k]={value,confidence:Math.max(0,Math.min(1,confidence)),sourceSnippet:snippet,sourcePage,verified};}
 const present=Object.values(fields).filter(x=>x.value!==null),overall=present.length?present.reduce((n,x)=>n+x.confidence,0)/present.length:0;if(isPdf)warnings.push('PDF provenance snippets are model-provided and must be visually checked against the original contract before confirmation.');return{documentType:parsed.documentType,language:parsed.language,summary:parsed.summary,fields,warnings:[...new Set(warnings)].slice(0,30),overallConfidence:Math.round(overall*100)};
}
async function workerMatches(actor:ActorContext,fields:Record<ContractFieldKey,ContractExtractedField>):Promise<ContractWorkerMatch[]>{
 const db=adminDb(),col=db.collection(`organizations/${actor.orgId}/workers`),targetName=norm(fields.employeeName.value||''),targetNo=norm(fields.employeeNumber.value||''),targetEmail=norm(fields.employeeEmail.value||''),found=new Map<string,ContractWorkerMatch>();
 const add=(d:any,score:number,reason:string)=>{const x=d.data() as any,id=String(x.id||d.id),candidate:ContractWorkerMatch={workerId:id,displayName:String(x.displayName||id),employeeNumber:x.employeeNumber?String(x.employeeNumber):undefined,score,reason},prior=found.get(id);if(!prior||score>prior.score)found.set(id,candidate)};
 if(targetNo){const q=await col.where('employeeNumberLower','==',targetNo).limit(5).get();q.docs.forEach((d:any)=>add(d,.99,'Exact employee number'))}
 if(targetEmail){const q=await col.where('workEmailLower','==',targetEmail).limit(5).get();q.docs.forEach((d:any)=>add(d,.97,'Exact employee email'))}
 if(targetName){const exact=await col.where('displayNameLower','==',targetName).limit(10).get();exact.docs.forEach((d:any)=>add(d,.95,'Exact employee name'));if(exact.empty&&targetName.length>=3){const prefix=await col.where('displayNameLower','>=',targetName).where('displayNameLower','<=',`${targetName}\uf8ff`).orderBy('displayNameLower').limit(25).get();prefix.docs.forEach((d:any)=>add(d,.78,'Close employee name'))}}
 return [...found.values()].sort((a,b)=>b.score-a.score).slice(0,8);
}
async function quarantine(actor:ActorContext,file:{name:string;mimeType:string;bytes:Buffer},id:string,sha256:string){const storagePath=`organizations/${actor.orgId}/contract-imports/quarantine/${id}/${cleanName(file.name)}`;try{await adminBucket().file(storagePath).save(file.bytes,{resumable:false,metadata:{contentType:file.mimeType||'application/octet-stream',cacheControl:'private,max-age=0,no-store',metadata:{sha256,scanStatus:'not_scanned',uploadedBy:actor.uid,contractImportId:id}}});return{storagePath,warn:undefined}}catch{return{storagePath:undefined,warn:'The source file could not be retained in governed Storage. The parsed draft is available, but confirm only after Storage is configured and the contract is re-imported.'}}}

export async function parseContractImport(actor:ActorContext,file:{name:string;mimeType:string;bytes:Buffer}):Promise<ContractImportDraft>{
 requireContractImport(actor);if(!file.name||file.bytes.length===0)throw new ApiError(400,'Choose a contract file.','invalid_file');if(file.bytes.length>MAX_CONTRACT_BYTES)throw new ApiError(413,'Contract file exceeds the 10 MB import limit.','file_too_large');const e=ext(file.name);if(!ALLOWED_CONTRACT_EXTENSIONS.has(e)||!ALLOWED_CONTRACT_MIME.has(file.mimeType||''))throw new ApiError(415,'Supported contract formats are PDF, DOCX, TXT, RTF and Markdown.','unsupported_file');if(!validMagic(file))throw new ApiError(400,'The file signature does not match the selected contract format.','file_signature_mismatch');
 const id=randomUUID(),sha256=createHash('sha256').update(file.bytes).digest('hex'),text=localText(file),isPdf=e==='.pdf'||file.mimeType==='application/pdf';let ai:any=null;
 try{ai=await governedContractExtraction(actor,{...file,text})}catch(err){if(isPdf&&!(text&&text.trim().length>=40))throw err}
 if(isPdf&&!ai&&!(text&&text.trim().length>=40))throw new ApiError(422,'Scanned PDF contract parsing requires an active governed AI model and ai.use permission. Text-based PDFs can use deterministic fallback extraction.','ai_required');
 const raw=ai?.extraction||deterministic(text||''),clean=sanitizeExtraction(raw,text,isPdf&&!!ai),matches=await workerMatches(actor,clean.fields),stored=await quarantine(actor,file,id,sha256),warnings=[...clean.warnings];if(stored.warn)warnings.push(stored.warn);
 const draft:ContractImportDraft={id,status:'draft',fileName:cleanName(file.name),mimeType:file.mimeType||'application/octet-stream',sha256,size:file.bytes.length,storagePath:stored.storagePath,scanStatus:'not_scanned',parser:ai?'governed_ai':'deterministic',provider:ai?.provider,model:ai?.model,promptVersion:ai?.promptVersion||CONTRACT_IMPORT_PROMPT_VERSION,documentType:clean.documentType,language:clean.language,summary:clean.summary,overallConfidence:clean.overallConfidence,fields:clean.fields,warnings:[...new Set(warnings)].slice(0,30),workerMatches:matches,createdBy:actor.uid,createdAt:now(),expiresAt:new Date(Date.now()+7*24*3600*1000).toISOString()};
 const db=adminDb(),audit=buildAudit(actor,{action:'contract_import.parse',entityType:'contractImportDraft',entityId:id,before:null,after:{id,fileName:draft.fileName,sha256,size:draft.size,parser:draft.parser,provider:draft.provider,model:draft.model,overallConfidence:draft.overallConfidence,storagePath:draft.storagePath}}),b=db.batch();b.create(db.doc(`organizations/${actor.orgId}/contractImportDrafts/${id}`),draft);b.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await b.commit();return draft;
}
export async function listContractImports(actor:ActorContext){requireContractImport(actor);const s=await adminDb().collection(`organizations/${actor.orgId}/contractImportDrafts`).orderBy('createdAt','desc').limit(25).get();return s.docs.map(d=>d.data() as ContractImportDraft)}
export async function getContractImport(actor:ActorContext,id:string){requireContractImport(actor);const s=await adminDb().doc(`organizations/${actor.orgId}/contractImportDrafts/${id}`).get();if(!s.exists)throw new ApiError(404,'Contract import draft not found.','not_found');return s.data() as ContractImportDraft}
function modulePrefill(values:Record<string,string>):ContractModulePrefill{const pick=(keys:string[])=>Object.fromEntries(keys.filter(k=>values[k]).map(k=>[k,values[k]]));return{coreHr:pick(['employeeName','employeeEmail','employeeNumber','jobTitle','department','managerName','workLocation','employmentType','startDate','endDate','hoursPerWeek','schedule']),compensation:pick(['basePay','payFrequency','bonusCommission','vacationEntitlement','benefits','overtimeTerms']),contractGovernance:pick(['employerName','probationPeriod','terminationNotice','confidentiality','nonSolicitation','nonCompetition','intellectualProperty','governingLaw','signatureDate','employeeSigned','employerSigned'])}}
export async function confirmContractImport(actor:ActorContext,id:string,raw:unknown){
 requireContractImport(actor);const input=confirmContractSchema.parse(raw),draft=await getContractImport(actor,id);if(draft.status!=='draft')throw new ApiError(409,'This contract import is no longer an editable draft.','invalid_state');if(draft.createdBy!==actor.uid&&!['super_admin','org_admin','hr_admin'].includes(actor.role))throw new ApiError(403,'Only the draft creator or an HR administrator can confirm this import.','forbidden');if(!draft.storagePath)throw new ApiError(409,'The contract source file is not retained in governed Storage. Re-import after Storage is configured before confirmation.','source_not_retained');
 if(input.workerId){const worker=await adminDb().doc(`organizations/${actor.orgId}/workers/${input.workerId}`).get();if(!worker.exists)throw new ApiError(404,'Selected worker no longer exists.','worker_not_found')}
 const values:Record<string,string>={},fields=emptyFields();for(const k of CONTRACT_FIELD_KEYS){const original=draft.fields[k],value=String(input.values[k]??original.value??'').trim();if(value)values[k]=value;fields[k]={...original,value:value||null,humanEdited:value!==String(original.value??'')}}const prefill=modulePrefill(values),timestamp=now(),confirmed={...draft,status:'confirmed' as const,fields,confirmedBy:actor.uid,confirmedAt:timestamp},record={id,workerId:input.workerId||null,fileName:draft.fileName,mimeType:draft.mimeType,sha256:draft.sha256,storagePath:draft.storagePath,scanStatus:draft.scanStatus,documentType:draft.documentType,language:draft.language,summary:draft.summary,fields,prefill,parser:draft.parser,provider:draft.provider||null,model:draft.model||null,promptVersion:draft.promptVersion,confirmedBy:actor.uid,confirmedAt:timestamp},proposal={id,workerId:input.workerId||null,status:'pending_review',sourceContractId:id,coreHr:prefill.coreHr,compensation:prefill.compensation,contractGovernance:prefill.contractGovernance,notice:'Contract data is prefilled from human-confirmed extraction. Core HR and compensation mutations must continue through their authoritative domain workflows; compensation is never silently changed by contract AI.',createdBy:actor.uid,createdAt:timestamp},db=adminDb(),audit=buildAudit(actor,{action:'contract_import.confirm',entityType:'contractRecord',entityId:id,before:{status:draft.status},after:{status:'confirmed',workerId:input.workerId||null,humanEditedFields:CONTRACT_FIELD_KEYS.filter(k=>fields[k].humanEdited)}}),b=db.batch();b.set(db.doc(`organizations/${actor.orgId}/contractImportDrafts/${id}`),confirmed,{merge:false});b.create(db.doc(`organizations/${actor.orgId}/contractRecords/${id}`),record);b.create(db.doc(`organizations/${actor.orgId}/contractModuleSyncProposals/${id}`),proposal);if(input.workerId)b.set(db.doc(`organizations/${actor.orgId}/workerContractProfiles/${input.workerId}`),{workerId:input.workerId,latestContractId:id,latestContractFields:values,latestContractAt:timestamp,updatedBy:actor.uid},{merge:true});b.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await b.commit();return{record,proposal};
}
