import type { SeparationCase, SeparationTask, SeparationTaskDocument, SeparationTaskStep } from '@/domain/separation';

type Blueprint={steps:Array<[string,string]>;documents:Array<[string,string,string]>};

const common={
  hr_checklist:{steps:[['Confirm approved basis','Verify the approved separation basis, worker identity, dates and authorization.'],['Review applicable controls','Confirm required HR/legal review evidence is recorded without making an automated legal conclusion.'],['Confirm handoffs','Verify payroll, benefits, IT, manager and facilities owners received their actions.']],documents:[['hr-separation-checklist','HR separation checklist','Approved basis:\nEffective date:\nLast working date:\nRequired reviews:\nHandoff owners:\nOutstanding exceptions:\nReviewer and date:']]},
  knowledge_transfer:{steps:[['Inventory responsibilities','List recurring duties, active work, key deadlines and decision rights.'],['Assign receiving owners','Name an accountable receiving owner for every responsibility and file location.'],['Confirm handover','Review the handover with the manager and record unresolved risks.']],documents:[['knowledge-transfer-plan','Knowledge transfer and handover plan','Responsibilities and recurring duties:\nActive projects and deadlines:\nKey contacts:\nFile and system locations:\nReceiving owners:\nOpen risks and follow-up dates:']]},
  it_deprovision:{steps:[['Inventory access','List email, devices, applications, SaaS, privileged access and shared credentials.'],['Schedule controls','Assign removal, preservation or transfer actions for the approved effective time.'],['Verify execution','Record evidence from the accountable system owners; never store passwords or secrets.']],documents:[['access-deprovision-plan','Access deprovisioning plan','System or access:\nAccount owner:\nAction required:\nExecution date/time:\nResponsible administrator:\nVerification evidence reference:\nExceptions:']]},
  time_leave_review:{steps:[['Reconcile records','Review submitted time, approved leave, corrections and outstanding approvals.'],['Resolve exceptions','Assign unresolved entries to an authorized payroll or HR reviewer.'],['Confirm payroll handoff','Record the reviewed totals and evidence reference for payroll processing.']],documents:[['time-leave-review','Final time and leave review','Pay period:\nTime entries reviewed:\nLeave balance reviewed:\nCorrections required:\nApprovals outstanding:\nPayroll evidence reference:\nReviewer and date:']]},
  asset_return:{steps:[['Inventory property','Confirm all assigned equipment, keys, cards, records and other property.'],['Arrange return','Record return method, location, responsible receiver and target date.'],['Document outcome','Record returned, missing, damaged or authorized write-off outcomes with evidence.']],documents:[['asset-return-record','Property and equipment return record','Asset / tag:\nCondition:\nReturn method and date:\nReceived by:\nMissing or damaged items:\nAuthorized exception / evidence:\nEmployee acknowledgement:']]},
  final_payroll:{steps:[['Collect payroll inputs','Gather approved time, leave, expenses and reviewed separation inputs.'],['Perform authorized review','Have qualified payroll/HR personnel determine applicable amounts under governing rules and agreements.'],['Record approval evidence','Document calculations, reviewer approval and processing reference without AI determining entitlement.']],documents:[['final-payroll-review','Final payroll review record','Final pay period:\nApproved time and leave inputs:\nExpenses / deductions reviewed:\nTermination or severance input source:\nQualified reviewer:\nApproval reference:\nPayment date and evidence:']]},
  roe:{steps:[['Confirm interruption and filing method','Have payroll confirm whether an ROE is required and the applicable electronic or paper timing.'],['Prepare verified information','Review pay-period, interruption-of-earnings and reason-code information.'],['Record filing evidence','Record the official filing confirmation or reference; this document is not an ROE.']],documents:[['roe-preparation-checklist','ROE preparation and filing checklist','Interruption confirmed by payroll:\nFiling method:\nRequired filing date:\nPay-period information verified:\nReason information verified:\nAuthorized filer:\nOfficial filing reference and date:']]},
  benefits:{steps:[['Identify plans','List applicable benefit, pension and savings plans.'],['Obtain administrator direction','Confirm continuation or termination actions with authorized plan administrators.'],['Record communication evidence','Document notices, effective dates and unresolved questions.']],documents:[['benefits-transition','Benefits and pension transition record','Plan / administrator:\nRequired action:\nEffective date:\nEmployee communication date:\nContinuation information supplied:\nEvidence reference:\nOutstanding questions:']]},
  exit_interview:{steps:[['Offer participation','Invite voluntary participation and explain confidentiality and intended use.'],['Conduct structured interview','Use neutral questions and avoid collecting unnecessary sensitive information.'],['Record themes','Capture authorized themes and follow-up actions separately from confidential notes.']],documents:[['exit-interview-guide','Exit interview guide','Participation and confidentiality notice:\nPrimary reason for leaving:\nWhat worked well:\nWhat could improve:\nManager and workplace experience:\nWould consider returning:\nThemes and authorized follow-up:']]},
  replacement:{steps:[['Review operational need','Assess workload, service requirements and position design.'],['Record human decision','Have the authorized leader decide replace, redesign or leave vacant.'],['Create recruiting handoff','If approved, document position and requisition requirements.']],documents:[['replacement-decision','Replacement / position decision record','Operational need:\nWorkload evidence:\nOptions considered:\nHuman decision:\nDecision maker and date:\nPosition changes:\nRecruiting handoff:']]},
  retention:{steps:[['Classify records','Identify employment, payroll, benefits, safety and case records affected by closure.'],['Check holds and schedules','Have authorized personnel confirm retention schedules, litigation holds and access restrictions.'],['Record disposition controls','Document storage owner, retention trigger and approved disposition date.']],documents:[['records-retention-review','Records retention review','Record category:\nRetention authority / schedule:\nRetention trigger:\nLegal hold status:\nStorage and access owner:\nApproved disposition date:\nReviewer:']]},
} satisfies Record<SeparationTask['code'],Blueprint>;

const safe=(value:string|undefined)=>String(value||'Not recorded').replace(/[<>]/g,'');

export function buildTaskWorkspace(task:SeparationTask,c:SeparationCase,actorUid:string,generatedAt:string){
  const plan=common[task.code];
  const context=`Case ${safe(c.id)} | effective ${safe(c.effectiveDate)} | last working date ${safe(c.lastWorkingDate)}`;
  const steps:SeparationTaskStep[]=plan.steps.map(([title,instruction],index)=>({id:`step-${index+1}`,title,instruction,required:true,completed:false}));
  const documents:SeparationTaskDocument[]=plan.documents.map(([id,title,body])=>({id,title,description:`Governed editable working record for ${task.title}. Human review is required.`,content:`${title}\n${context}\n\n${body}`,required:true,confirmed:false}));
  return{workspaceVersion:'H50.6G' as const,workspaceSource:'governed_template' as const,workspaceGeneratedBy:actorUid,workspaceGeneratedAt:generatedAt,steps,documents};
}

export function workspaceReady(task:SeparationTask){
  const steps=task.steps||[],documents=task.documents||[];
  return steps.length>0&&steps.filter(x=>x.required).every(x=>x.completed)&&documents.filter(x=>x.required).every(x=>x.confirmed&&documentHasSubstantiveEvidence(x.content));
}

export function documentHasSubstantiveEvidence(content:string){
  const lines=String(content||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
  const completedFields=lines.filter(line=>{const index=line.indexOf(':');return index>0&&line.slice(index+1).trim().length>=2;});
  return completedFields.length>=2;
}
