import { createHash, randomUUID } from 'crypto';
import type { ActorContext } from '@/domain/security';
import type { DiagnosticControl } from '@/domain/hr-diagnostic';
import type { Policy } from '@/domain/compliance';
import type { GovernanceAttestation, GovernanceControl, GovernanceDashboard, GovernanceException, GovernanceRisk } from '@/domain/governance';
import { governanceRiskLevel } from './risk';
import { adminDb } from '@/lib/firebase/admin';
import { ApiError } from '@/lib/http/errors';
import { buildAudit } from '@/lib/audit/service';
import { buildDomainEvent } from '@/lib/events/build';
import { systemActor } from '@/lib/automation/system-actor';
import { governanceAttestationActionSchema, governanceAttestationCreateSchema, governanceControlActionSchema, governanceControlCreateSchema, governanceExceptionActionSchema, governanceExceptionCreateSchema, governanceRiskActionSchema, governanceRiskCreateSchema } from './schemas';

const now=()=>new Date().toISOString();
const today=()=>now().slice(0,10);
const addDays=(date:string,days:number)=>{const d=new Date(`${date.slice(0,10)}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);};
const addMonths=(date:string,months:number)=>{const d=new Date(`${date.slice(0,10)}T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+months);return d.toISOString().slice(0,10);};
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
const requireRead=(actor:ActorContext)=>{if(!actor.permissions.includes('governance.read'))throw new ApiError(403,'Governance read permission required.','forbidden');};
const requireManage=(actor:ActorContext)=>{if(!actor.permissions.includes('governance.manage'))throw new ApiError(403,'Governance management permission required.','forbidden');};
const requireApprove=(actor:ActorContext)=>{if(!actor.permissions.includes('governance.approve'))throw new ApiError(403,'Governance approval permission required.','forbidden');};
async function loadAll<T>(orgId:string,collection:string):Promise<T[]>{const s=await adminDb().collection(`organizations/${orgId}/${collection}`).limit(1000).get();return s.docs.map((d:any)=>d.data() as T);}
async function controlById(orgId:string,id:string){const s=await adminDb().doc(`organizations/${orgId}/governanceControls/${id}`).get();if(!s.exists)throw new ApiError(404,'Governance control not found.','governance_control_not_found');return s.data() as GovernanceControl;}

export async function createGovernanceControl(actor:ActorContext,raw:unknown){
 requireManage(actor);const input=governanceControlCreateSchema.parse(raw),db=adminDb(),dupe=await db.collection(`organizations/${actor.orgId}/governanceControls`).where('code','==',input.code).limit(1).get();if(!dupe.empty)throw new ApiError(409,'Governance control code already exists.','governance_control_code_exists');
 const ts=now(),id=randomUUID(),record:GovernanceControl={id,...input,status:'draft',sourceNextReviewDate:addMonths(input.sourceReviewedAt,input.sourceReviewCadenceMonths),createdBy:actor.uid,createdAt:ts,updatedBy:actor.uid,updatedAt:ts};
 const audit=buildAudit(actor,{action:'governance.control.create',entityType:'governanceControl',entityId:id,after:record}),batch=db.batch();batch.create(db.doc(`organizations/${actor.orgId}/governanceControls/${id}`),record);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return record;
}

export async function actOnGovernanceControl(actor:ActorContext,id:string,raw:unknown){
 requireManage(actor);const input=governanceControlActionSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/governanceControls/${id}`),s=await ref.get();if(!s.exists)throw new ApiError(404,'Governance control not found.','governance_control_not_found');const before=s.data() as GovernanceControl,ts=now();let after:GovernanceControl={...before,updatedBy:actor.uid,updatedAt:ts};
 if(input.action==='submit_review'){if(!['draft','active'].includes(before.status))throw new ApiError(409,'Only draft or active controls can enter review.','invalid_governance_control_state');after={...after,status:'in_review',reviewNote:input.reviewNote,submittedBy:actor.uid,submittedAt:ts};}
 if(input.action==='source_review'){if(before.status==='retired')throw new ApiError(409,'Retired controls cannot be source-reviewed.','invalid_governance_control_state');after={...after,status:'in_review',sourceTitle:input.sourceTitle,sourceUrl:input.sourceUrl,sourceReviewedAt:input.sourceReviewedAt,sourceNextReviewDate:addMonths(input.sourceReviewedAt,before.sourceReviewCadenceMonths),reviewNote:input.reviewNote,submittedBy:actor.uid,submittedAt:ts};}
 if(input.action==='approve'){requireApprove(actor);if(before.status!=='in_review')throw new ApiError(409,'Only controls in review can be approved.','invalid_governance_control_state');if(before.submittedBy===actor.uid||before.createdBy===actor.uid)throw new ApiError(409,'Control approval requires an independent reviewer.','governance_control_self_approval');after={...after,status:'active',approvedBy:actor.uid,approvedAt:ts};}
 if(input.action==='retire'){requireApprove(actor);if(before.status==='retired')throw new ApiError(409,'Control is already retired.','invalid_governance_control_state');after={...after,status:'retired',retiredBy:actor.uid,retiredAt:ts};}
 if(input.action==='reopen'){requireApprove(actor);if(before.status!=='retired')throw new ApiError(409,'Only retired controls can be reopened.','invalid_governance_control_state');after={...after,status:'draft',retiredBy:undefined,retiredAt:undefined,approvedBy:undefined,approvedAt:undefined};}
 const audit=buildAudit(actor,{action:`governance.control.${input.action}`,entityType:'governanceControl',entityId:id,before,after}),batch=db.batch();batch.set(ref,after);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return after;
}

export async function createGovernanceAttestation(actor:ActorContext,raw:unknown){
 requireManage(actor);const input=governanceAttestationCreateSchema.parse(raw),control=await controlById(actor.orgId,input.controlId);if(control.status!=='active')throw new ApiError(409,'Attestations require an active governance control.','governance_control_not_active');const db=adminDb(),ts=now(),id=randomUUID(),record:GovernanceAttestation={id,controlId:control.id,controlCode:control.code,title:control.title,periodLabel:input.periodLabel,assignedRole:input.assignedRole,dueDate:input.dueDate,statement:input.statement,status:input.dueDate<today()?'overdue':'pending',evidenceRefs:[],createdBy:actor.uid,createdAt:ts,updatedAt:ts};const audit=buildAudit(actor,{action:'governance.attestation.create',entityType:'governanceAttestation',entityId:id,after:record}),batch=db.batch();batch.create(db.doc(`organizations/${actor.orgId}/governanceAttestations/${id}`),record);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return record;
}

export async function actOnGovernanceAttestation(actor:ActorContext,id:string,raw:unknown){
 requireManage(actor);const input=governanceAttestationActionSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/governanceAttestations/${id}`),s=await ref.get();if(!s.exists)throw new ApiError(404,'Governance attestation not found.','governance_attestation_not_found');const before=s.data() as GovernanceAttestation,ts=now();let after:GovernanceAttestation={...before,updatedAt:ts};
 if(input.action==='submit'){if(actor.role!==before.assignedRole&&!actor.permissions.includes('governance.approve'))throw new ApiError(403,'Attestation submission is limited to the assigned role or a governance approver.','governance_attestation_assignment');if(!['pending','overdue'].includes(before.status))throw new ApiError(409,'Only pending or overdue attestations can be submitted.','invalid_governance_attestation_state');after={...after,status:'submitted',response:input.response,responseNote:input.responseNote,evidenceRefs:input.evidenceRefs,submittedBy:actor.uid,submittedAt:ts};}
 if(input.action==='approve'){requireApprove(actor);if(before.status!=='submitted')throw new ApiError(409,'Only submitted attestations can be approved.','invalid_governance_attestation_state');if(before.submittedBy===actor.uid)throw new ApiError(409,'Attestation approval requires an independent reviewer.','governance_attestation_self_approval');after={...after,status:'approved',approvedBy:actor.uid,approvedAt:ts};}
 if(input.action==='reopen'){requireApprove(actor);if(!['submitted','approved','cancelled'].includes(before.status))throw new ApiError(409,'Attestation cannot be reopened from its current state.','invalid_governance_attestation_state');after={...after,status:before.dueDate<today()?'overdue':'pending',response:undefined,responseNote:undefined,evidenceRefs:[],submittedBy:undefined,submittedAt:undefined,approvedBy:undefined,approvedAt:undefined};}
 if(input.action==='cancel'){requireApprove(actor);if(before.status==='approved')throw new ApiError(409,'Approved attestations must be reopened before cancellation.','invalid_governance_attestation_state');after={...after,status:'cancelled'};}
 const audit=buildAudit(actor,{action:`governance.attestation.${input.action}`,entityType:'governanceAttestation',entityId:id,before,after}),batch=db.batch();batch.set(ref,after);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return after;
}

export async function createGovernanceException(actor:ActorContext,raw:unknown){
 requireManage(actor);const input=governanceExceptionCreateSchema.parse(raw),control=await controlById(actor.orgId,input.controlId);const db=adminDb(),ts=now(),id=randomUUID(),record:GovernanceException={id,controlId:control.id,controlCode:control.code,title:input.title,rationale:input.rationale,riskLevel:input.riskLevel,mitigation:input.mitigation,ownerRole:input.ownerRole,startDate:input.startDate,expiryDate:input.expiryDate,status:'draft',createdBy:actor.uid,createdAt:ts,updatedAt:ts};const audit=buildAudit(actor,{action:'governance.exception.create',entityType:'governanceException',entityId:id,after:record}),batch=db.batch();batch.create(db.doc(`organizations/${actor.orgId}/governanceExceptions/${id}`),record);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return record;
}

export async function actOnGovernanceException(actor:ActorContext,id:string,raw:unknown){
 requireManage(actor);const {action}=governanceExceptionActionSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/governanceExceptions/${id}`),s=await ref.get();if(!s.exists)throw new ApiError(404,'Governance exception not found.','governance_exception_not_found');const before=s.data() as GovernanceException,ts=now();let after:GovernanceException={...before,updatedAt:ts};
 if(action==='submit_review'){if(before.status!=='draft')throw new ApiError(409,'Only draft exceptions can be submitted.','invalid_governance_exception_state');after={...after,status:'in_review',submittedBy:actor.uid,submittedAt:ts};}
 if(action==='approve'){requireApprove(actor);if(before.status!=='in_review')throw new ApiError(409,'Only exceptions in review can be approved.','invalid_governance_exception_state');if(before.submittedBy===actor.uid||before.createdBy===actor.uid)throw new ApiError(409,'Exception approval requires an independent reviewer.','governance_exception_self_approval');after={...after,status:before.expiryDate<today()?'expired':'approved',approvedBy:actor.uid,approvedAt:ts};}
 if(action==='close'){requireApprove(actor);if(!['approved','expired'].includes(before.status))throw new ApiError(409,'Only approved or expired exceptions can be closed.','invalid_governance_exception_state');after={...after,status:'closed',closedBy:actor.uid,closedAt:ts};}
 if(action==='cancel'){requireApprove(actor);if(before.status==='closed')throw new ApiError(409,'Closed exceptions cannot be cancelled.','invalid_governance_exception_state');after={...after,status:'cancelled'};}
 if(action==='reopen'){requireApprove(actor);if(!['closed','cancelled','expired'].includes(before.status))throw new ApiError(409,'Exception cannot be reopened from its current state.','invalid_governance_exception_state');after={...after,status:'draft',submittedBy:undefined,submittedAt:undefined,approvedBy:undefined,approvedAt:undefined,closedBy:undefined,closedAt:undefined};}
 const audit=buildAudit(actor,{action:`governance.exception.${action}`,entityType:'governanceException',entityId:id,before,after}),batch=db.batch();batch.set(ref,after);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return after;
}

export async function createGovernanceRisk(actor:ActorContext,raw:unknown){
 requireManage(actor);const input=governanceRiskCreateSchema.parse(raw),db=adminDb(),dupe=await db.collection(`organizations/${actor.orgId}/governanceRisks`).where('code','==',input.code).limit(1).get();if(!dupe.empty)throw new ApiError(409,'Governance risk code already exists.','governance_risk_code_exists');const ts=now(),id=randomUUID(),score=input.likelihood*input.impact,record:GovernanceRisk={...input,id,score,level:governanceRiskLevel(score),status:'open',createdBy:actor.uid,createdAt:ts,updatedAt:ts};const audit=buildAudit(actor,{action:'governance.risk.create',entityType:'governanceRisk',entityId:id,after:record}),batch=db.batch();batch.create(db.doc(`organizations/${actor.orgId}/governanceRisks/${id}`),record);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return record;
}

export async function actOnGovernanceRisk(actor:ActorContext,id:string,raw:unknown){
 requireManage(actor);const input=governanceRiskActionSchema.parse(raw),db=adminDb(),ref=db.doc(`organizations/${actor.orgId}/governanceRisks/${id}`),s=await ref.get();if(!s.exists)throw new ApiError(404,'Governance risk not found.','governance_risk_not_found');const before=s.data() as GovernanceRisk,ts=now();let after:GovernanceRisk={...before,updatedAt:ts};
 if(input.action==='mitigate'){if(before.status==='closed')throw new ApiError(409,'Closed risks must be reopened first.','invalid_governance_risk_state');after={...after,status:'mitigating',acceptedRiskReason:undefined,acceptedBy:undefined,acceptedAt:undefined};}
 if(input.action==='accept'){requireApprove(actor);if(before.createdBy===actor.uid)throw new ApiError(409,'Risk acceptance requires an independent reviewer.','governance_risk_self_acceptance');after={...after,status:'accepted',acceptedRiskReason:input.reason,acceptedBy:actor.uid,acceptedAt:ts};}
 if(input.action==='close'){requireApprove(actor);if(before.createdBy===actor.uid)throw new ApiError(409,'Risk closure requires an independent reviewer.','governance_risk_self_closure');after={...after,status:'closed',closedBy:actor.uid,closedAt:ts};}
 if(input.action==='reopen'){requireApprove(actor);if(before.status!=='closed')throw new ApiError(409,'Only closed risks can be reopened.','invalid_governance_risk_state');after={...after,status:'open',closedBy:undefined,closedAt:undefined};}
 const audit=buildAudit(actor,{action:`governance.risk.${input.action}`,entityType:'governanceRisk',entityId:id,before,after}),batch=db.batch();batch.set(ref,after);batch.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await batch.commit();return after;
}

export async function bootstrapGovernanceControlCenter(actor:ActorContext){
 requireApprove(actor);const db=adminDb(),[diagnosticControls,policies]=await Promise.all([loadAll<DiagnosticControl>(actor.orgId,'diagnosticControls'),loadAll<Policy>(actor.orgId,'policies')]),ts=now();let created=0,skipped=0;const pending:Array<{ref:any;record:GovernanceControl}>=[];
 for(const control of diagnosticControls.filter(c=>c.enabled)){
   const id=`diag_${hash(control.id).slice(0,24)}`,ref=db.doc(`organizations/${actor.orgId}/governanceControls/${id}`),exists=await ref.get();if(exists.exists){skipped++;continue;}
   const record:GovernanceControl={id,code:`DIAG.${control.code}`.slice(0,80),title:control.title,category:control.kind==='compliance'?'statutory':'operational',jurisdiction:control.jurisdiction,controlObjective:control.objective,evidenceRequirement:control.evidenceRequirements.join('; '),ownerRole:'hr_partner',accountableRole:'hr_admin',status:'active',sourceTitle:control.sourceTitle,sourceUrl:control.sourceUrl,sourceReviewedAt:control.sourceReviewedAt.slice(0,10),sourceReviewCadenceMonths:12,sourceNextReviewDate:addMonths(control.sourceReviewedAt.slice(0,10),12),legalConclusionProhibited:control.legalConclusionProhibited,linkedDiagnosticControlId:control.id,createdBy:'system:v2.3-governance-bootstrap',createdAt:ts,updatedBy:actor.uid,updatedAt:ts,approvedBy:actor.uid,approvedAt:ts};pending.push({ref,record});created++;
 }
 for(const policy of policies.filter(p=>!['archived','superseded'].includes(p.status))){
   const id=`policy_${hash(policy.id).slice(0,24)}`,ref=db.doc(`organizations/${actor.orgId}/governanceControls/${id}`),exists=await ref.get();if(exists.exists){skipped++;continue;}
   const reviewed=policy.updatedAt.slice(0,10),cadence=policy.reviewFrequencyMonths||12,record:GovernanceControl={id,code:`POL.${policy.code}`.slice(0,80),title:policy.title,category:'policy',jurisdiction:'Organization policy',controlObjective:`Maintain the approved policy lifecycle, ownership, review schedule and required acknowledgement evidence for ${policy.title}.`,evidenceRequirement:'Approved/published policy version, owner, review date and acknowledgement evidence where required.',ownerRole:'hr_partner',accountableRole:'hr_admin',status:'active',sourceTitle:`Internal policy: ${policy.title}`,sourceReviewedAt:reviewed,sourceReviewCadenceMonths:cadence,sourceNextReviewDate:policy.nextReviewDate||addMonths(reviewed,cadence),legalConclusionProhibited:true,linkedPolicyId:policy.id,createdBy:'system:v2.3-governance-bootstrap',createdAt:ts,updatedBy:actor.uid,updatedAt:ts,approvedBy:actor.uid,approvedAt:ts};pending.push({ref,record});created++;
 }
 for(let i=0;i<pending.length;i+=400){const batch=db.batch();for(const item of pending.slice(i,i+400))batch.create(item.ref,item.record);await batch.commit();}
 if(created){const audit=buildAudit(actor,{action:'governance.bootstrap',entityType:'governanceControlCenter',entityId:'v2.3',after:{created,skipped,diagnosticControls:diagnosticControls.length,policies:policies.length}});await db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`).create(audit);}
 return {created,skipped,diagnosticControls:diagnosticControls.length,policies:policies.length};
}

export async function governanceDashboard(actor:ActorContext):Promise<GovernanceDashboard>{
 requireRead(actor);const [controls,attestationsRaw,exceptionsRaw,risks]=await Promise.all([loadAll<GovernanceControl>(actor.orgId,'governanceControls'),loadAll<GovernanceAttestation>(actor.orgId,'governanceAttestations'),loadAll<GovernanceException>(actor.orgId,'governanceExceptions'),loadAll<GovernanceRisk>(actor.orgId,'governanceRisks')]),d=today(),d30=addDays(d,30);const attestations=attestationsRaw.map(a=>a.status==='pending'&&a.dueDate<d?{...a,status:'overdue' as const}:a),exceptions=exceptionsRaw.map(e=>e.status==='approved'&&e.expiryDate<d?{...e,status:'expired' as const}:e),active=controls.filter(c=>c.status==='active'),categories=['statutory','policy','operational','privacy','ai','security','risk'] as const;
 return {controls:controls.sort((a,b)=>a.code.localeCompare(b.code)),attestations:attestations.sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),exceptions:exceptions.sort((a,b)=>a.expiryDate.localeCompare(b.expiryDate)),risks:risks.sort((a,b)=>b.score-a.score||a.code.localeCompare(b.code)),metrics:{activeControls:active.length,sourceReviewsOverdue:active.filter(c=>c.sourceNextReviewDate<d).length,sourceReviewsDue30:active.filter(c=>c.sourceNextReviewDate>=d&&c.sourceNextReviewDate<=d30).length,attestationsPending:attestations.filter(a=>['pending','submitted'].includes(a.status)).length,attestationsOverdue:attestations.filter(a=>a.status==='overdue').length,openExceptions:exceptions.filter(e=>['draft','in_review','approved','expired'].includes(e.status)).length,exceptionsExpiring30:exceptions.filter(e=>e.status==='approved'&&e.expiryDate>=d&&e.expiryDate<=d30).length,highCriticalRisks:risks.filter(r=>r.status!=='closed'&&['high','critical'].includes(r.level)).length,acceptedRisks:risks.filter(r=>r.status==='accepted').length},categoryCoverage:categories.map(category=>({category,active:active.filter(c=>c.category===category).length,overdue:active.filter(c=>c.category===category&&c.sourceNextReviewDate<d).length})),operatingNotice:'The Governance & Control Center tracks ownership, source review, attestations, exceptions and enterprise HR risk. It does not create legal opinions or certify statutory compliance. Legal and fact-sensitive applicability remains subject to qualified human review.'};
}

async function notifyOnce(orgId:string,key:string,input:{title:string;message:string;targetRole:string;entityType:string;entityId:string;priority?:string}){const db=adminDb(),ref=db.doc(`organizations/${orgId}/notificationDedupe/${hash(key)}`);try{await ref.create({key,createdAt:now()});const id=randomUUID();await db.doc(`organizations/${orgId}/notifications/${id}`).create({id,type:'governance',category:'governance',priority:input.priority||'normal',...input,status:'unread',inAppVisible:true,emailStatus:'disabled',emailAttempts:0,createdAt:now(),updatedAt:now()});return true;}catch{return false;}}

export async function processGovernanceControlCenter(orgId:string){
 const db=adminDb(),actor=systemActor(orgId,'system:governance-control-center'),[controls,attestations,exceptions,risks]=await Promise.all([loadAll<GovernanceControl>(orgId,'governanceControls'),loadAll<GovernanceAttestation>(orgId,'governanceAttestations'),loadAll<GovernanceException>(orgId,'governanceExceptions'),loadAll<GovernanceRisk>(orgId,'governanceRisks')]),d=today(),d30=addDays(d,30),summary={controlsScanned:controls.length,sourceReviewsDue:0,attestationsOverdue:0,exceptionsExpiring:0,highCriticalRisks:risks.filter(r=>r.status!=='closed'&&['high','critical'].includes(r.level)).length,notifications:0};
 for(const c of controls.filter(c=>c.status==='active'&&c.sourceNextReviewDate<=d30)){summary.sourceReviewsDue++;if(await notifyOnce(orgId,`governance-source-review:${c.id}:${c.sourceNextReviewDate}`,{title:c.sourceNextReviewDate<d?'Governance source review overdue':'Governance source review due',message:`${c.code} · ${c.title} has a source review date of ${c.sourceNextReviewDate}. Record a human source review before relying on the control.`,targetRole:c.accountableRole,entityType:'governanceControl',entityId:c.id,priority:c.sourceNextReviewDate<d?'high':'normal'})){summary.notifications++;const ev=buildDomainEvent(actor,'governance.source_review_due' as any,'governanceControl',c.id,{sourceNextReviewDate:c.sourceNextReviewDate});await db.doc(`organizations/${orgId}/domainEvents/${ev.id}`).create(ev);}}
 for(const a of attestations.filter(a=>['pending','overdue'].includes(a.status)&&a.dueDate<d)){summary.attestationsOverdue++;if(a.status!=='overdue')await db.doc(`organizations/${orgId}/governanceAttestations/${a.id}`).set({...a,status:'overdue',updatedAt:now()});if(await notifyOnce(orgId,`governance-attestation:${a.id}:${a.dueDate}`,{title:'Governance attestation overdue',message:`${a.controlCode} attestation for ${a.periodLabel} was due ${a.dueDate}.`,targetRole:a.assignedRole,entityType:'governanceAttestation',entityId:a.id,priority:'high'}))summary.notifications++;}
 for(const e of exceptions.filter(e=>e.status==='approved'&&e.expiryDate<=d30)){summary.exceptionsExpiring++;if(e.expiryDate<d)await db.doc(`organizations/${orgId}/governanceExceptions/${e.id}`).set({...e,status:'expired',updatedAt:now()});if(await notifyOnce(orgId,`governance-exception:${e.id}:${e.expiryDate}`,{title:e.expiryDate<d?'Governance exception expired':'Governance exception expiring',message:`${e.controlCode} · ${e.title} has an exception expiry date of ${e.expiryDate}.`,targetRole:e.ownerRole,entityType:'governanceException',entityId:e.id,priority:e.expiryDate<d?'high':'normal'}))summary.notifications++;}
 return summary;
}
