import { createHash } from 'crypto';
import type { ActorContext } from '@/domain/security';
import type { AutomationMarketplaceDashboard, AutomationMarketplacePack, AutomationPackInstall } from '@/domain/opsiqo-one-v7-13';
import { adminDb } from '@/lib/firebase/admin';
import { ApiError } from '@/lib/http/errors';
import { buildAudit } from '@/lib/audit/service';
import { createWorkflow } from '@/lib/workflow/service';
import { H51_AUTOMATION_PACKS } from '@/lib/intelligence-control-plane/automation-packs';
const now=()=>new Date().toISOString();
const packs:AutomationMarketplacePack[]=[
 {id:'workforce-essentials',version:1,name:'Workforce Essentials Pack',category:'Core HR',description:'Starter workflows for leave, onboarding, policy review and certificate expiry.',operationalBoundary:'Installs disabled workflow definitions. Human task/approval owners retain decision authority.',workflows:[
  {name:'Marketplace · Leave request routing',description:'Manager approval and requester notification for leave requests.',trigger:'leave.requested',conditionMode:'all',conditions:[],steps:[{id:'approve',name:'Manager approval',type:'approval',ownerRole:'manager',dueInDays:2,escalationOwnerRole:'hr_admin',escalateAfterHours:4},{id:'notify',name:'Notify requester',type:'notification',ownerRole:'hr_admin',dueInDays:0,dependsOn:['approve']}]},
  {name:'Marketplace · New-hire onboarding review',description:'HR review and onboarding coordination after an authorized hire.',trigger:'hire.completed',conditionMode:'all',conditions:[],steps:[{id:'review',name:'HR onboarding review',type:'task',ownerRole:'hr_admin',dueInDays:1,escalationOwnerRole:'org_admin',escalateAfterHours:8},{id:'notify',name:'Notify onboarding owner',type:'notification',ownerRole:'hr_admin',dependsOn:['review']}]},
  {name:'Marketplace · Policy review due',description:'Governed review task for policy review deadlines.',trigger:'policy.review_due',conditionMode:'all',conditions:[],steps:[{id:'review',name:'Review policy evidence',type:'task',ownerRole:'hr_admin',dueInDays:5,escalationOwnerRole:'org_admin',escalateAfterHours:24}]},
  {name:'Marketplace · Certificate expiry watch',description:'Review expiring learning/certification evidence.',trigger:'learning.certificate_expiring',conditionMode:'all',conditions:[],steps:[{id:'review',name:'Review expiring certificate',type:'task',ownerRole:'hr_admin',dueInDays:5,escalationOwnerRole:'manager',escalateAfterHours:24},{id:'notify',name:'Notify responsible manager',type:'notification',ownerRole:'hr_admin',dependsOn:['review']}]},
 ]},
 {id:'nonprofit-operations',version:1,name:'Nonprofit Operations Pack',category:'Nonprofit / NGO',description:'Operational starter workflows for workforce demand, policy re-attestation, employee service and onboarding coordination.',operationalBoundary:'Technical starter pack only; it does not encode donor, grant, safeguarding or employment-law compliance conclusions.',workflows:[
  {name:'Marketplace · Workforce demand review',description:'Review approved/planned workforce demand before operational follow-up.',trigger:'workforce.demand_due',conditionMode:'all',conditions:[],steps:[{id:'review',name:'Review workforce demand and funding context',type:'task',ownerRole:'hr_admin',dueInDays:3,escalationOwnerRole:'org_admin',escalateAfterHours:12}]},
  {name:'Marketplace · Policy re-attestation follow-up',description:'Track re-attestation campaign follow-up.',trigger:'policy.reattestation_started',conditionMode:'all',conditions:[],steps:[{id:'monitor',name:'Monitor re-attestation progress',type:'task',ownerRole:'hr_admin',dueInDays:7,escalationOwnerRole:'org_admin',escalateAfterHours:24}]},
  {name:'Marketplace · HR service SLA escalation',description:'Escalate service tickets when the configured SLA is breached.',trigger:'service.ticket_sla_breached',conditionMode:'all',conditions:[],steps:[{id:'review',name:'Review SLA breach',type:'task',ownerRole:'hr_admin',dueInDays:1,escalationOwnerRole:'org_admin',escalateAfterHours:4},{id:'notify',name:'Notify service owner',type:'notification',ownerRole:'hr_admin',dependsOn:['review']}]},
 ]},
 {id:'governance-evidence',version:1,name:'Governance & Evidence Pack',category:'Governance',description:'Starter workflows for compliance gaps, diagnostic findings and governance source reviews.',operationalBoundary:'Creates evidence-review work only. It does not issue legal, audit, assurance or compliance conclusions.',workflows:[
  {name:'Marketplace · Compliance gap review',description:'Route compliance-gap evidence to HR review.',trigger:'compliance.gap',conditionMode:'all',conditions:[],steps:[{id:'review',name:'Review compliance evidence gap',type:'task',ownerRole:'hr_admin',dueInDays:2,escalationOwnerRole:'org_admin',escalateAfterHours:8}]},
  {name:'Marketplace · Diagnostic remediation review',description:'Track a diagnostic remediation item without automatic closure.',trigger:'diagnostic.finding_created',conditionMode:'all',conditions:[],steps:[{id:'plan',name:'Prepare remediation plan',type:'task',ownerRole:'hr_admin',dueInDays:5,escalationOwnerRole:'org_admin',escalateAfterHours:24}]},
  {name:'Marketplace · Governance source review',description:'Review configured governance source evidence when due.',trigger:'governance.source_review_due',conditionMode:'all',conditions:[],steps:[{id:'review',name:'Review governance source evidence',type:'task',ownerRole:'org_admin',dueInDays:5,escalationOwnerRole:'super_admin',escalateAfterHours:24}]},
 ]},
];
packs.push(...H51_AUTOMATION_PACKS);
const installId=(p:AutomationMarketplacePack)=>createHash('sha256').update(`${p.id}:v${p.version}`).digest('hex').slice(0,24);
export async function automationMarketplace(actor:ActorContext):Promise<AutomationMarketplaceDashboard>{if(!actor.permissions.includes('workflow.read')&&!actor.permissions.includes('automation.read'))throw new ApiError(403,'Workflow or automation read permission required.','forbidden');const snap=await adminDb().collection(`organizations/${actor.orgId}/automationPackInstalls`).limit(100).get(),installed=new Map(snap.docs.map(d=>[(d.data() as AutomationPackInstall).packId,d.data() as AutomationPackInstall]));return{packs:packs.map(p=>({...p,installed:installed.get(p.id)?.packVersion===p.version,install:installed.get(p.id)})),canInstall:actor.permissions.includes('workflow.manage'),governanceNotice:'Marketplace packs are versioned OPSIQO workflow starters. Installation creates disabled definitions for human review. Activating a workflow is a separate audited action. Packs never grant permissions and cannot turn human-required employment decisions into autonomous actions.'};}
export async function installAutomationPack(actor:ActorContext,packId:string){if(!actor.permissions.includes('workflow.manage'))throw new ApiError(403,'Workflow management permission required.','forbidden');const pack=packs.find(p=>p.id===packId);if(!pack)throw new ApiError(404,'Automation pack not found.','automation_pack_not_found');const db=adminDb(),id=installId(pack),ref=db.doc(`organizations/${actor.orgId}/automationPackInstalls/${id}`);if((await ref.get()).exists)throw new ApiError(409,'This automation pack version is already installed.','automation_pack_already_installed');const workflowIds:string[]=[];for(const w of pack.workflows){const created=await createWorkflow(actor,{...w,enabled:false});workflowIds.push(created.id);}const row:AutomationPackInstall={id,packId:pack.id,packVersion:pack.version,workflowIds,installedBy:actor.uid,installedAt:now(),status:'installed_disabled'},audit=buildAudit(actor,{action:'automation.marketplace.install',entityType:'automationPackInstall',entityId:id,after:row,metadata:{packName:pack.name}}),b=db.batch();b.create(ref,row);b.create(db.doc(`organizations/${actor.orgId}/auditLogs/${audit.id}`),audit);await b.commit();return row;}
export function automationPackCatalog(){return packs.map(p=>({...p,workflows:p.workflows.map(w=>({...w,conditions:[...w.conditions],steps:w.steps.map(s=>({...s,dependsOn:s.dependsOn?[...s.dependsOn]:undefined}))}))}));}
