import type { ActorContext } from '@/domain/security';
import type { OpsiQoCommandResult } from '@/domain/opsiqo-one';

const clean = (value: string) => value.trim().replace(/\s+/g,' ');
const hasAny = (actor: ActorContext, permissions?: string[]) => !permissions?.length || permissions.some(permission=>actor.permissions.includes(permission as never));

const blockedConsequential: Array<{ pattern:RegExp; title:string; href:string }> = [
  { pattern:/\b(terminat(?:e|es|ing)|fir(?:e|es|ing)|dismiss(?:es|ing)?)\b/i, title:'Separation decision requires human review', href:'/separations' },
  { pattern:/(?:^|\bplease\s+|\bcan you\s+)(hire|employ)\b/i, title:'Hiring decision requires human review', href:'/recruiting' },
  { pattern:/\b(reject|decline|select|advance)\b.{0,80}\b(candidate|applicant)\b/i, title:'Candidate employment decision requires human review', href:'/recruiting' },
  { pattern:/\b(promote|demote|discipline|suspend)\b/i, title:'Employment decision requires human review', href:'/people' },
  { pattern:/\b(change|set|increase|decrease|adjust)\b.{0,80}\b(salary|pay|compensation|wage)\b/i, title:'Individual compensation change requires human approval', href:'/compensation' },
  { pattern:/\b(select|choose|name)\b.{0,80}\bsuccessor\b/i, title:'Succession selection requires human governance', href:'/career' },
  { pattern:/\b(approve|deny|reject)\b.{0,80}\b(leave|vacation|timesheet|expense|request)\b/i, title:'Approval decision requires authorized human review', href:'/my-work' },
  { pattern:/\b(delete|purge)\b.{0,80}\b(employee|worker|person|personnel record)\b/i, title:'Personnel-record deletion requires governed review', href:'/people' },
];

const patterns: Array<{ pattern:RegExp; title:string; message:string; href:string; permissions?:string[]; mode:'navigate'|'prepare'|'execute'|'ai'; actionLevel:'observe'|'recommend'|'prepare'|'execute'; risk:'low'|'administrative'|'high_impact' }> = [
  { pattern:/\b(mark|clear).{0,24}\b(my\s+)?(notifications?|alerts?).{0,16}\b(read|seen)\b/i, title:'Mark my visible notifications read', message:'OPSIQO can execute this low-risk self-service action through the authoritative notification service. Only unread notifications explicitly targeted to you are changed; shared role notifications are left untouched, and the batch is audit-recorded.', href:'/notifications', permissions:['notifications.read'], mode:'execute', actionLevel:'execute', risk:'low' },
  { pattern:/\b(program workforce|program cost|project workforce|project funding|project grant|project to grant)\b/i, title:'Open Program Workforce Intelligence', message:'Review explicit Project → Grant → Position → Worker → Cost evidence. OPSIQO uses human-entered funded amounts and does not infer restricted compensation or future funding.', href:'/program-workforce', permissions:['workforce.read'], mode:'navigate', actionLevel:'recommend', risk:'low' },
  { pattern:/\b(program portfolio|project budget|budget actual|financial evidence|project actual|grant actual)\b/i, title:'Open Program Portfolio', message:'Review explicit project budget, actual, commitment and forecast evidence by currency. OPSIQO does not infer accounting actuals from HR or compensation records.', href:'/program-portfolio', permissions:['workforce.read'], mode:'navigate', actionLevel:'recommend', risk:'low' },
  { pattern:/\b(translation readiness|translation backlog|localization backlog|legacy translation|language completion)\b/i, title:'Open Translation Readiness', message:'Review the exact catalogued EN/FR/ES/AR source strings and the remaining legacy translation backlog. This inventory is evidence for completion work, not a linguistic-quality claim.', href:'/translation-readiness', permissions:['self.read'], mode:'navigate', actionLevel:'observe', risk:'low' },
  { pattern:/\b(accessibility|wcag|language coverage|translation coverage|experience readiness)\b/i, title:'Open Experience Readiness', message:'Review accessibility and multilingual implementation evidence together with the manual certification gates OPSIQO still requires.', href:'/experience-readiness', permissions:['self.read'], mode:'navigate', actionLevel:'observe', risk:'low' },
  { pattern:/\b(organization launchpad|organization setup|set up (the )?organization|configure (the )?organization)\b/i, title:'Open Organization Launchpad', message:'Prepare a reviewed organization foundation. Launchpad does not create employees, grant permissions, publish legal policies or enable workflows automatically.', href:'/organization-launchpad', permissions:['organization.manage'], mode:'prepare', actionLevel:'prepare', risk:'administrative' },
  { pattern:/\b(daily brief|morning brief|today(?:'s)? brief|summarize my day|brief me)\b/i, title:'Open Daily Brief', message:'Open a permission-scoped summary of what needs attention, what is approaching and one evidence-backed OPSIQO insight.', href:'/daily-brief', permissions:['self.read'], mode:'navigate', actionLevel:'observe', risk:'low' },
  { pattern:/\b(unified workforce|workforce registry|human and digital workforce|digital workforce|digital agents)\b/i, title:'Open Unified Workforce', message:'Open the permission-scoped workforce registry. Human HRIS records and digital-agent identities remain separate and governed by their own authority models.', href:'/workforce-registry', permissions:['workforce.read'], mode:'navigate', actionLevel:'observe', risk:'low' },
  { pattern:/\b(grant workforce|grant funding|funding allocation|funded workforce|ngo workforce|nonprofit workforce)\b/i, title:'Open Grant Workforce', message:'Review explicit funding periods and workforce allocations. OPSIQO does not infer donor compliance, employment-law obligations or automatic staff reductions.', href:'/grant-workforce', permissions:['workforce.read'], mode:'navigate', actionLevel:'recommend', risk:'low' },
  { pattern:/\b(employee service center|service center|get hr help|hr request|hr service request|employment letter)\b/i, title:'Open Employee Service Center', message:'Open the governed HR service experience. Existing service-ticket ownership, SLA and evidence controls remain authoritative.', href:'/employee-service-center', permissions:['service.read','service.request'], mode:'navigate', actionLevel:'prepare', risk:'administrative' },
  { pattern:/\b(meeting to action|meeting action|meeting follow.?up|meeting decisions|meeting notes)\b/i, title:'Open Meeting to Action', message:'Prepare a private meeting-action draft. Nothing is written to a personnel record or authoritative workflow without a separate reviewed action.', href:'/meeting-actions', permissions:['self.read'], mode:'prepare', actionLevel:'prepare', risk:'administrative' },
  { pattern:/\b(agent builder|build (an )?agent|create (an )?agent|custom agent)\b/i, title:'Open Agent Builder', message:'Create a governed custom Cortex agent. Custom agents are capped at Prepare and require independent activation.', href:'/agent-builder', permissions:['ai.manage'], mode:'prepare', actionLevel:'prepare', risk:'administrative' },
  { pattern:/\b(automation marketplace|workflow pack|automation pack|operating model pack)\b/i, title:'Open Automation Marketplace', message:'Browse versioned workflow starter packs. Installation creates disabled definitions for review before activation.', href:'/automation-marketplace', permissions:['workflow.read','automation.read'], mode:'navigate', actionLevel:'observe', risk:'low' },
  { pattern:/\b(policy intelligence|policy impact|policy overlap|policy review due)\b/i, title:'Open Policy Intelligence', message:'Review policy lifecycle, acknowledgement, overlap and workflow-impact signals without making a legal conclusion.', href:'/policy-intelligence', permissions:['policies.read','compliance.read'], mode:'navigate', actionLevel:'recommend', risk:'low' },
  { pattern:/\b(organizational memory|company memory|internal knowledge|search our policy|search our policies|what does our policy say|what does the handbook say)\b/i, title:'Search Organizational Memory', message:'Search permission-available internal policies, HR knowledge and workflow definitions with explicit source citations.', href:'/organizational-memory', permissions:['policies.read','service.read','workflow.read'], mode:'navigate', actionLevel:'observe', risk:'low' },
  { pattern:/\b(request|book|take|submit).{0,30}\b(vacation|leave|pto|time off)\b/i, title:'Prepare leave request', message:'OPSIQO can take you to the governed Time & Leave flow with your employee context already available. Balance, overlap, schedule and approval controls remain authoritative.', href:'/time', permissions:['leave.request'], mode:'prepare', actionLevel:'prepare', risk:'administrative' },
  { pattern:/\b(career gps|career path|career goal|target role|next role)\b/i, title:'Open Career GPS', message:'Open transparent target-role readiness evidence and a human-controlled development roadmap.', href:'/career-gps', permissions:['career.read'], mode:'navigate', actionLevel:'recommend', risk:'low' },
  { pattern:/\b(talent marketplace|internal opportunity|internal opportunities|internal mobility|internal job)\b/i, title:'Open Talent Marketplace', message:'Explore internal opportunities using your own permission-available evidence. OPSIQO does not rank employees against one another.', href:'/talent-marketplace', permissions:['career.read'], mode:'navigate', actionLevel:'recommend', risk:'low' },
  { pattern:/\b(scenario lab|digital twin|what if|simulate|simulation)\b/i, title:'Open Scenario Lab', message:'Open read-only workforce scenarios and the bounded organizational digital-twin foundation. Live HR records are not modified.', href:'/scenario-lab', permissions:['workforce.read'], mode:'navigate', actionLevel:'recommend', risk:'low' },
  { pattern:/\b(ai value|ai roi|ai impact|ai usage|ai performance)\b/i, title:'Open AI Value Dashboard', message:'Open measured AI activity, safety blocks, evidence completeness and action-plan outcomes. Unvalidated financial savings remain Not configured.', href:'/ai-value', permissions:['ai.audit','ai.manage'], mode:'navigate', actionLevel:'observe', risk:'low' },
  { pattern:/\b(onboard|onboarding|new hire)\b/i, title:'Prepare onboarding', message:'OPSIQO will hand this outcome to the governed onboarding workflow. Approved-hire evidence and required fields remain mandatory.', href:'/onboarding', permissions:['onboarding.manage','onboarding.manage.team'], mode:'prepare', actionLevel:'prepare', risk:'high_impact' },
  { pattern:/\b(create|open|add).{0,35}\b(position|job position|role)\b/i, title:'Prepare position', message:'OPSIQO will route this to Organization so the position can be prepared and validated against the existing position controls.', href:'/organization', permissions:['positions.manage'], mode:'prepare', actionLevel:'prepare', risk:'high_impact' },
  { pattern:/\b(build|create|design).{0,35}\b(workflow|process|approval flow)\b/i, title:'Prepare workflow', message:'OPSIQO will route this outcome into the governed workflow builder. Production activation remains subject to the normal workflow controls.', href:'/workflows', permissions:['workflow.manage'], mode:'prepare', actionLevel:'prepare', risk:'administrative' },
  { pattern:/\b(show|open|find|search).{0,45}\b(employee|worker|people|person|directory)\b/i, title:'Open People', message:'Open the permission-scoped People workspace.', href:'/people', permissions:['people.read.directory'], mode:'navigate', actionLevel:'observe', risk:'low' },
  { pattern:/\b(overdue approvals|my approvals|what needs my attention|my work|tasks)\b/i, title:'Open My Work', message:'Open the unified cross-module work queue.', href:'/my-work', permissions:['self.read'], mode:'navigate', actionLevel:'observe', risk:'low' },
  { pattern:/\b(policy|policies|compliance requirement|compliance requirements)\b/i, title:'Open compliance knowledge', message:'Open governed policy and compliance evidence.', href:'/compliance', permissions:['compliance.read'], mode:'navigate', actionLevel:'observe', risk:'low' },
  { pattern:/\b(skills passport|my skills|verified skills)\b/i, title:'Open Skills Passport', message:'Open your evidence-backed Skills Passport with verified and self-reported skills clearly separated.', href:'/skills-passport', permissions:['learning.read'], mode:'navigate', actionLevel:'observe', risk:'low' },
  { pattern:/\b(training|learning|certificate|certification|skill)\b/i, title:'Open Learning', message:'Open learning, skills and certification evidence.', href:'/learning', permissions:['learning.read'], mode:'navigate', actionLevel:'observe', risk:'low' },
  { pattern:/\b(turnover|headcount|workforce|analytics|trend|forecast|vacanc|skill gap|fte|employer cost)\b/i, title:'Analyze workforce evidence', message:'OPSIQO will answer from governed aggregate People Analytics evidence and show source references, quality warnings and prior-snapshot changes when available.', href:'/intelligence', permissions:['peopleanalytics.read'], mode:'ai', actionLevel:'recommend', risk:'low' },
];

export function routeOpsiQoCommand(actor: ActorContext, rawCommand: string): OpsiQoCommandResult {
  const command=clean(rawCommand);
  if(command.length<3) return {command,mode:'blocked',actionLevel:'observe',title:'Command is too short',message:'Describe the outcome you want OPSIQO to help with.',requiresHumanDecision:false,risk:'low'};

  for(const item of blockedConsequential){
    if(item.pattern.test(command)) return {command,mode:'blocked',actionLevel:'recommend',title:item.title,message:'OPSIQO will not execute this consequential employment decision from the command layer. Open the governed module to review evidence and complete the authorized human workflow.',href:item.href,requiresHumanDecision:true,risk:'consequential'};
  }

  for(const item of patterns){
    if(!item.pattern.test(command)) continue;
    const permissionLabel=item.permissions?.join(' or ');
    if(!hasAny(actor,item.permissions)) return {command,mode:'blocked',actionLevel:'observe',title:'Permission required',message:`Your current OPSIQO membership is not authorized for this outcome${permissionLabel?` (${permissionLabel})`:''}.`,href:item.href,permission:permissionLabel,requiresHumanDecision:false,risk:item.risk};
    return {command,mode:item.mode,actionLevel:item.actionLevel,title:item.title,message:item.message,href:item.href,permission:permissionLabel,requiresHumanDecision:item.risk==='high_impact',risk:item.risk};
  }

  if(actor.permissions.includes('ai.use')) return {command,mode:'ai',actionLevel:'recommend',title:'Ask OPSIQO',message:'OPSIQO will answer from permission-scoped governed evidence and will not perform a consequential employment decision.',href:'/ai-copilot',permission:'ai.use',requiresHumanDecision:true,risk:'low'};
  return {command,mode:'navigate',actionLevel:'observe',title:'Guided OPSIQO routing',message:'Generative AI is not enabled for this membership. Open My Work or More to continue with permission-scoped self-service.',href:'/more',requiresHumanDecision:false,risk:'low'};
}
