import type { ActorContext } from '@/domain/security';
import type { ComplianceRadarDashboard, ComplianceRadarItem } from '@/domain/opsiqo-one-v7-11';
import { complianceDashboard } from '@/lib/compliance/service';

const today=()=>new Date().toISOString().slice(0,10);
const plusDays=(days:number)=>{const d=new Date();d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)};

export async function complianceRadar(actor:ActorContext):Promise<ComplianceRadarDashboard>{
  const d=await complianceDashboard(actor),items:ComplianceRadarItem[]=[];
  const m=d.metrics;
  if(!m.assessed)items.push({id:'not-assessed',severity:'info',title:'Compliance evidence is not fully assessed',summary:'OPSIQO does not convert missing evidence into a false 100% compliance result.',href:'/compliance',evidence:[`${m.workers} worker(s) in scope`,`${m.requirements} requirement definition(s)`],suggestedActions:[{label:'Review requirements',href:'/compliance'}]});
  if(m.gaps>0)items.push({id:'gaps',severity:'critical',title:`${m.gaps} compliance gap${m.gaps===1?'':'s'} require review`,summary:'Required evidence is missing or not current for one or more workers in your authorized scope.',count:m.gaps,href:'/compliance',evidence:[`Compliance dashboard gaps=${m.gaps}`],suggestedActions:[{label:'Show affected workers',href:'/compliance'},{label:'Open Evidence Center',href:'/evidence-center'}]});
  if(m.expiring>0)items.push({id:'expiring',severity:'high',title:`${m.expiring} requirement${m.expiring===1?' is':'s are'} approaching expiry`,summary:'Review expiring documents or evidence before the configured warning window closes.',count:m.expiring,href:'/compliance',evidence:[`Compliance dashboard expiring=${m.expiring}`],suggestedActions:[{label:'Review expiries',href:'/compliance'}]});
  const day=today(),warn=plusDays(30),due=d.policies.filter((p:any)=>p.nextReviewDate&&p.nextReviewDate>=day&&p.nextReviewDate<=warn),overdue=d.policies.filter((p:any)=>p.nextReviewDate&&p.nextReviewDate<day);
  if(overdue.length)items.push({id:'policy-overdue',severity:'high',title:`${overdue.length} policy review${overdue.length===1?' is':'s are'} overdue`,summary:'Policy review dates have passed. Qualified owners must review the current published content and related workflows.',count:overdue.length,href:'/compliance',evidence:overdue.slice(0,5).map((p:any)=>`${p.code} review ${p.nextReviewDate}`),suggestedActions:[{label:'Review policies',href:'/compliance'}]});
  if(due.length)items.push({id:'policy-due',severity:'medium',title:`${due.length} policy review${due.length===1?' is':'s are'} due within 30 days`,summary:'Upcoming review dates are visible before they become overdue.',count:due.length,href:'/compliance',evidence:due.slice(0,5).map((p:any)=>`${p.code} review ${p.nextReviewDate}`),suggestedActions:[{label:'Plan reviews',href:'/compliance'}]});
  if(!items.length)items.push({id:'healthy',severity:'good',title:'No verified compliance exception is currently flagged',summary:'This means no issue was detected from the available configured evidence; it is not a legal compliance opinion.',href:'/compliance',evidence:[`Evidence coverage ${m.evidenceCoverage}%`],suggestedActions:[{label:'Open compliance evidence',href:'/compliance'}]});
  const status=!m.assessed?'not_assessed':m.gaps>0||overdue.length?'attention_required':m.expiring>0||due.length?'watch':'healthy';
  const workerGaps=d.rows.filter((r:any)=>r.overdue>0||r.expiring>0).sort((a:any,b:any)=>b.overdue-a.overdue||b.expiring-a.expiring).slice(0,20).map((r:any)=>({workerId:r.workerId,displayName:r.displayName,employeeNumber:r.employeeNumber,gaps:r.overdue,expiring:r.expiring,score:r.score}));
  return{status,headline:status==='healthy'?'No verified compliance exception is flagged':status==='not_assessed'?'Compliance evidence requires assessment':status==='attention_required'?'Compliance issues require attention':'Compliance items are approaching deadlines',metrics:{workers:m.workers,requirements:m.requirements,complianceRate:m.complianceRate,gaps:m.gaps,expiring:m.expiring,policiesDue:due.length,policiesOverdue:overdue.length},items,workerGaps,generatedAt:new Date().toISOString(),governanceNotice:'Compliance Radar surfaces configured evidence gaps and deadlines. It does not determine legal applicability or declare the organization legally compliant/non-compliant.'};
}
