import type { ActorContext } from '@/domain/security';
import type { Policy, PolicyVersion } from '@/domain/compliance';
import type { KnowledgeArticle } from '@/domain/experience';
import type { WorkflowDefinition } from '@/domain/workflow';
import type { LearningCourse } from '@/domain/learning';
import type { AiEvidenceItem } from '@/domain/ai-intelligence';
import type { OrganizationalMemoryCitation, OrganizationalMemoryDashboard } from '@/domain/opsiqo-one-v7-13';
import { adminDb } from '@/lib/firebase/admin';
import { ApiError } from '@/lib/http/errors';

const now=()=>new Date().toISOString();
const STOP=new Set(['the','a','an','and','or','to','of','for','in','on','is','are','our','what','how','does','do','we','i','my','this','that','with']);
const tokens=(s:string)=>[...new Set(s.toLowerCase().replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(x=>x.length>1&&!STOP.has(x)))];
const score=(q:string[],text:string)=>{if(!q.length)return 1;const t=text.toLowerCase();let n=0;for(const x of q){if(t.includes(x))n+=t.includes(` ${x} `)?3:2;}return n;};
function excerpt(text:string,q:string[]){const clean=text.replace(/\s+/g,' ').trim();if(clean.length<=420)return clean;const lower=clean.toLowerCase();let at=-1;for(const token of q){const i=lower.indexOf(token);if(i>=0&&(at<0||i<at))at=i;}const start=Math.max(0,(at<0?0:at)-120),end=Math.min(clean.length,start+420);return`${start>0?'…':''}${clean.slice(start,end)}${end<clean.length?'…':''}`;}

export async function organizationalMemory(actor:ActorContext,query=''):Promise<OrganizationalMemoryDashboard>{
 const canPolicy=actor.permissions.includes('policies.read')||actor.permissions.includes('compliance.read'),canKnowledge=actor.permissions.includes('service.read')||actor.permissions.includes('experience.read'),canWorkflow=actor.permissions.includes('workflow.read'),canLearning=actor.permissions.includes('learning.read');
 if(!canPolicy&&!canKnowledge&&!canWorkflow&&!canLearning)throw new ApiError(403,'No organizational-memory source permission is available.','forbidden');
 const db=adminDb(),q=tokens(query),rows:OrganizationalMemoryCitation[]=[];let policies=0,knowledgeArticles=0,workflows=0,learningCourses=0;
 if(canPolicy){const ps=await db.collection(`organizations/${actor.orgId}/policies`).limit(250).get();const published=ps.docs.map(d=>d.data() as Policy).filter(p=>p.status!=='archived'&&Boolean(p.currentPublishedVersionId));policies=published.length;const ids=published.map(p=>p.currentPublishedVersionId!).slice(0,250);const versions=new Map<string,PolicyVersion>();for(let i=0;i<ids.length;i+=30){const batch=ids.slice(i,i+30);if(!batch.length)continue;const snaps=await db.getAll(...batch.map(id=>db.doc(`organizations/${actor.orgId}/policyVersions/${id}`)));for(const d of snaps)if(d.exists)versions.set(d.id,d.data() as PolicyVersion);}for(const p of published){const v=versions.get(p.currentPublishedVersionId!);if(!v)continue;const text=`${p.code} ${p.title} ${v.content}`,s=score(q,text);if(q.length&&s===0)continue;rows.push({id:`POLICY:${p.code}:v${v.versionNumber}`,sourceType:'policy',title:`${p.code} · ${p.title}`,excerpt:excerpt(v.content,q),href:'/compliance',version:v.versionLabel,updatedAt:v.publishedAt||v.createdAt,score:s+5});}}
 if(canKnowledge){const ks=await db.collection(`organizations/${actor.orgId}/knowledgeArticles`).where('status','==','published').limit(250).get();knowledgeArticles=ks.size;for(const d of ks.docs){const a=d.data() as KnowledgeArticle,text=`${a.title} ${a.summary} ${a.body} ${a.keywords.join(' ')}`,s=score(q,text);if(q.length&&s===0)continue;rows.push({id:`KNOWLEDGE:${a.slug}`,sourceType:'knowledge_article',title:a.title,excerpt:excerpt(`${a.summary} ${a.body}`,q),href:'/experience',updatedAt:a.updatedAt,score:s+3});}}
 if(canWorkflow){const ws=await db.collection(`organizations/${actor.orgId}/workflowDefinitions`).limit(250).get();workflows=ws.size;for(const d of ws.docs){const w=d.data() as WorkflowDefinition,text=`${w.name} ${w.description||''} ${w.trigger} ${w.steps.map(s=>s.name).join(' ')}`,s=score(q,text);if(q.length&&s===0)continue;rows.push({id:`WORKFLOW:${w.id}:v${w.version}`,sourceType:'workflow',title:w.name,excerpt:excerpt(`${w.description||'Configured workflow.'} Trigger: ${w.trigger}. Steps: ${w.steps.map(s=>s.name).join(' → ')}.`,q),href:'/workflows',version:`v${w.version}`,updatedAt:w.updatedAt,score:s+1});}}
 if(canLearning){const cs=await db.collection(`organizations/${actor.orgId}/courses`).where('status','==','published').limit(250).get();learningCourses=cs.size;for(const d of cs.docs){const c=d.data() as LearningCourse,text=`${c.code} ${c.title} ${c.description||''} ${c.provider||''} ${(c.skillMappings||[]).map(m=>m.skillId).join(' ')}`,s=score(q,text);if(q.length&&s===0)continue;rows.push({id:`COURSE:${c.code||c.id}`,sourceType:'learning_course',title:`${c.code} · ${c.title}`,excerpt:excerpt(`${c.description||'Published learning course.'}${c.provider?` Provider: ${c.provider}.`:''} Duration: ${c.durationMinutes} minutes.`,q),href:'/learning',version:'published',updatedAt:c.updatedAt,score:s+2});}}
 rows.sort((a,b)=>b.score-a.score||b.updatedAt.localeCompare(a.updatedAt));return{query,citations:rows.slice(0,20),sourceCounts:{policies,knowledgeArticles,workflows,learningCourses},generatedAt:now(),governanceNotice:'Organizational Memory retrieves only permission-available, organization-level published policy/knowledge content, governed workflow definitions and published learning-course metadata. It excludes employee documents, cases, health information, compensation records and other private personnel data. Citations identify the OPSIQO source; consequential or legal interpretations still require qualified human review.'};
}

export async function retrieveOrganizationalMemoryEvidence(actor:ActorContext,question:string):Promise<AiEvidenceItem[]>{
 try{const data=await organizationalMemory(actor,question);return data.citations.slice(0,8).map(c=>({id:`memory:${c.id}`,kind:c.sourceType==='policy'?'policy':'operational',title:c.title,summary:c.excerpt,source:`Organizational Memory · ${c.id}`,asOf:c.updatedAt,href:c.href,dataQuality:'Permission-scoped internal source with explicit OPSIQO citation identity.',sensitivity:'aggregate'}));}catch{return[];}
}
