import type { ActorContext } from '@/domain/security';
import type { ScenarioLabDashboard, ScenarioLabScenario } from '@/domain/opsiqo-one-v7-12';
import { workforcePlanningDashboard } from '@/lib/workforce-planning/service';
import { buildKnowledgeGraphSnapshot } from './knowledge-graph';

const now=()=>new Date().toISOString();

export async function scenarioLab(actor:ActorContext):Promise<ScenarioLabDashboard>{
  const [workforce,graph]=await Promise.all([workforcePlanningDashboard(actor),buildKnowledgeGraphSnapshot(actor)]);
  const b=workforce.baseline;
  const scenarios:ScenarioLabScenario[]=workforce.scenarios.map(s=>({id:s.id,name:s.name,type:s.type,status:s.status,currency:s.assumptions.currency,headcount:s.projection.headcount,activeFte:s.projection.activeFte,vacantPositions:s.projection.vacantPositions,annualBasePay:s.projection.annualBasePay,estimatedEmployerCost:s.projection.estimatedEmployerCost,headcountDelta:s.projection.netHeadcountChange,fteDelta:s.projection.netFteChange,annualBasePayDelta:s.projection.netAnnualBasePayChange,employerCostDelta:s.projection.netEmployerCostChange,budgetLimit:s.budgetLimit,budgetVariance:s.budgetVariance,evidenceStatus:s.status==='approved'?'approved':s.status==='archived'?'archived':s.status==='modelled'?'modelled':'draft'}));
  return{baseline:{headcount:b.headcount,activeFte:b.activeFte,occupiedPositions:b.occupiedPositions,vacantPositions:b.vacantPositions,annualBasePay:b.annualBasePay,estimatedEmployerCost:b.estimatedEmployerCost,currency:b.currency,openRequisitions:b.openRequisitions,verifiedSkillGaps:b.verifiedSkillGaps},digitalTwin:{people:graph.counts.workers,positions:graph.counts.positions,orgUnits:graph.counts.orgUnits,skills:graph.counts.skills,projects:graph.counts.projects,fundingSources:graph.counts.fundingSources,policies:graph.counts.policies,knowledgeArticles:graph.counts.knowledgeArticles,workflows:graph.counts.workflows,courses:graph.counts.courses,learningPaths:graph.counts.learningPaths,complianceRequirements:graph.counts.complianceRequirements,onboardingTasks:graph.counts.onboardingTasks,relationships:graph.counts.relationships,truncated:graph.truncated},scenarios,risks:workforce.risks.map(r=>({id:r.id,severity:r.severity,title:r.title,description:r.description,recommendedAction:r.recommendedAction})),recommendedQuestions:['What happens to employer cost if approved headcount changes?','Which modelled scenario creates the largest FTE change?','Where do current vacancies and verified skill gaps create capacity pressure?','Which assumptions should be validated before scenario approval?'],generatedAt:now(),governanceNotice:'Scenario Lab is a read-only digital-twin view over OPSIQO workforce-planning evidence. Scenario calculations are deterministic estimates from explicit assumptions. They do not predict individual departures, recommend layoffs, infer protected traits, or change live HR records.'};
}
