'use client';
import { useEffect,useState,useRef } from 'react';
import { useLegacySurfaceTranslation } from '@/lib/opsiqo-one/legacy-surface-i18n';
import type { OpsiQoActionLevel } from '@/domain/opsiqo-one';
import type { OpsiQoEffectiveAgentPolicy } from '@/domain/opsiqo-one-v7-11';
import { activeOrgId,apiFetch,isMfaRequiredError } from '@/lib/http/client';
import { mfaSetupHref } from '@/lib/auth/mfa-client';
import Link from 'next/link';
import { executionReadinessDashboard } from '@/lib/opsiqo-one/execution-readiness';
import { executionUatDashboard } from '@/lib/opsiqo-one/execution-uat';
const levels:OpsiQoActionLevel[]=['observe','recommend','prepare','execute'];
const order:Record<OpsiQoActionLevel,number>={observe:0,recommend:1,prepare:2,execute:3};
export function AiGovernanceCenter(){
 const translationRoot=useRef<HTMLDivElement>(null);useLegacySurfaceTranslation('ai_governance',translationRoot);
 const execution=executionReadinessDashboard(),uat=executionUatDashboard();
 const[data,setData]=useState<OpsiQoEffectiveAgentPolicy[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[mfa,setMfa]=useState(false);
 const load=()=>apiFetch<{data:OpsiQoEffectiveAgentPolicy[]}>(`/api/organizations/${activeOrgId()}/opsiqo-one/agent-governance`).then(r=>setData(r.data));
 useEffect(()=>{load().catch(e=>{if(isMfaRequiredError(e))setMfa(true);else setError(e instanceof Error?e.message:'Unable to load AI Governance Center.')})},[]);
 const patch=async(agent:OpsiQoEffectiveAgentPolicy,changes:Partial<Pick<OpsiQoEffectiveAgentPolicy,'enabled'|'maxActionLevel'|'shadowMode'>>)=>{try{setBusy(agent.agentId);setError('');await apiFetch(`/api/organizations/${activeOrgId()}/opsiqo-one/agent-governance/${agent.agentId}`,{method:'PATCH',body:JSON.stringify({enabled:changes.enabled??agent.enabled,maxActionLevel:changes.maxActionLevel??agent.maxActionLevel,shadowMode:changes.shadowMode??agent.shadowMode})});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update AI agent policy.')}finally{setBusy('')}};
 if(mfa)return <section className="card stack"><h2 className="sectionTitle">Multi-factor authentication required</h2><Link className="button" href={mfaSetupHref('/ai-governance')}>Set up MFA</Link></section>;
 return <div ref={translationRoot} className="stack" data-opsiqo-one="ai-governance"><section className="card oneHero"><div><span className="eyebrow">OPSIQO Guard · AI Governance Center</span><h1>Control what every Cortex agent may do</h1><p className="muted">Organization settings can tighten an agent below its hard safety cap, never expand it beyond the code-defined boundary.</p></div><div className="row wrap"><Link className="button secondary" href="/agent-builder">Agent Builder</Link><Link className="button secondary" href="/privacy">Privacy & AI Assurance</Link></div></section>{error&&<div className="error" role="alert">{error}</div>}
 {!data.length?<section className="card"><div className="loadingState"><div className="loadingDot"/><div><strong>Loading agent governance</strong><small>Reading effective policy without exposing model credentials or sensitive evidence.</small></div></div></section>:<section className="card tableWrap"><table><thead><tr><th>Agent</th><th>Organization level</th><th>Hard cap</th><th>Shadow mode</th><th>Status</th></tr></thead><tbody>{data.map(a=><tr key={a.agentId}><td><strong>{a.agentName}</strong><div className="muted">{a.purpose}</div><div className="agentCapabilities">{a.capabilities.slice(0,4).map(c=><span key={c}>{c}</span>)}</div></td><td>{a.editable?<select aria-label={`${a.agentName} action level`} className="input compactInput aiGovernanceActionSelect" value={a.maxActionLevel} disabled={busy===a.agentId} onChange={e=>patch(a,{maxActionLevel:e.target.value as OpsiQoActionLevel})}>{levels.filter(l=>order[l]<=order[a.hardMaxActionLevel]).map(l=><option value={l} key={l}>{l}</option>)}</select>:<span className={`actionLevel level-${a.maxActionLevel}`}>{a.maxActionLevel}</span>}</td><td><span className={`actionLevel level-${a.hardMaxActionLevel}`}>{a.hardMaxActionLevel}</span></td><td>{a.editable?<label className="checkLine"><input type="checkbox" checked={a.shadowMode} disabled={busy===a.agentId} onChange={e=>patch(a,{shadowMode:e.target.checked})}/> Shadow</label>:a.shadowMode?'On':'Off'}</td><td>{a.editable?<button className={`button compact ${a.enabled?'secondary':''}`} disabled={busy===a.agentId} onClick={()=>patch(a,{enabled:!a.enabled})}>{a.enabled?'Enabled':'Disabled'}</button>:<span className="badge">{a.enabled?'enabled':'disabled'}</span>}</td></tr>)}</tbody></table></section>}
 <section className="card stack"><h2 className="sectionTitle">Safe Execute readiness</h2><p className="muted">V7.18 keeps Execute expansion evidence-gated rather than adding authority because an action merely looks convenient.</p>{execution.enabledActions.map(x=><div className="oneWorkItem info" key={x.id}><div><strong>{x.title}</strong><p className="muted">{x.reason}</p></div><span className="badge">enabled</span></div>)}{uat.implementationGates.map(x=><div className="oneWorkItem info" key={x.id}><div><strong>{x.title}</strong><p className="muted">{x.evidence}</p></div><span className="badge">implementation pass</span></div>)}{uat.browserGates.map(x=><div className="oneWorkItem medium" key={x.id}><div><strong>{x.title}</strong><p className="muted">{x.evidence}</p></div><span className="badge">browser UAT required</span></div>)}{execution.candidates.map(x=><div className="oneWorkItem medium" key={x.id}><div><strong>{x.title}</strong><p className="muted">{x.reason}</p></div><span className="badge">hold for UAT</span></div>)}<p className="muted">{uat.boundary}</p></section>
 <section className="card"><h2 className="sectionTitle">Safety invariants</h2><div className="safetyLevelGrid"><div className="safetyLevel level-observe"><span className="actionLevel">Observe</span><p>Permission-scoped reads only.</p></div><div className="safetyLevel level-recommend"><span className="actionLevel">Recommend</span><p>Evidence-backed suggestions; human decides.</p></div><div className="safetyLevel level-prepare"><span className="actionLevel">Prepare</span><p>Drafts and plans stop at review/confirmation.</p></div><div className="safetyLevel level-execute"><span className="actionLevel">Execute</span><p>Only code-registered low-risk actions can ever reach this level; current agent hard caps remain below unrestricted execution.</p></div></div><p className="muted">Shadow Mode lets administrators compare what an agent would prepare with the actual human workflow before granting broader operational authority.</p></section></div>;
}
