'use client';
import { FormEvent, useEffect, useMemo, useState, useRef } from 'react';
import { activeOrgId, apiFetch } from '@/lib/http/client';
import { useLegacySurfaceTranslation } from '@/lib/opsiqo-one/legacy-surface-i18n';

type AppSummary={id:string;stage:string;candidate?:{displayName:string;email:string};requisition?:{title:string;requisitionNumber:string}};
type Review={id:string;score:number;band:string;breakdown:{requirements:number;skills:number;responsibilities:number;experience:number;educationCertification:number;documentQuality:number};assessedDimensions?:string[];assessmentCoverage?:number;warnings?:string[];matchedRequirements:string[];missingRequirements:string[];matchedKeywords:string[];missingKeywords:string[];strengths:string[];gaps:string[];evidence:Array<{criterion:string;category:string;matched:boolean;confidence:number;evidence?:string;missingTerms?:string[]}>;scoringVersion:string;humanReviewRequired:true;decisionBoundary:string;createdAt:string};
type Draft={id:string;text:string;tone:string;provider:string;model?:string;evidenceUsed:string[];createdAt:string};
type State={review:Review|null;history:Review[];coverLetters:Draft[]};
type LetterReview={relevanceScore:number;evidenceGroundingScore:number;matchedJobSignals:string[];unsupportedClaims:string[];missingJobSignals:string[];recommendations:string[]};

function ScoreBar({label,value}:{label:string;value:number}){return <div className="atsScoreRow"><div className="row"><span>{label}</span><strong>{value}%</strong></div><div className="atsTrack"><div className="atsFill" style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div></div>}
function Chips({items,empty='None'}:{items:string[];empty?:string}){return <div className="chipWrap">{items.length?items.map((x,i)=><span key={`${x}-${i}`} className="chip">{x}</span>):<span className="muted">{empty}</span>}</div>}

export function AtsRecruitingPanel({applications,canManage}:{applications:AppSummary[];canManage:boolean}){
 const translationRoot=useRef<HTMLElement>(null);useLegacySurfaceTranslation('ats_studio',translationRoot);
 const[applicationId,setApplicationId]=useState(''),[state,setState]=useState<State|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[letterText,setLetterText]=useState(''),[letterReview,setLetterReview]=useState<LetterReview|null>(null);
 const selected=useMemo(()=>applications.find(a=>a.id===applicationId),[applications,applicationId]);
 async function load(id=applicationId){if(!id){setState(null);return}setError('');try{const r=await apiFetch<{data:State}>(`/api/organizations/${activeOrgId()}/recruiting/applications/${id}/ats`);setState(r.data);if(r.data.coverLetters[0])setLetterText(r.data.coverLetters[0].text);}catch(e){setError(e instanceof Error?e.message:'Unable to load ATS state.')}}
 useEffect(()=>{if(applicationId)load(applicationId);},[applicationId]);
 async function reviewResume(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!applicationId)return;setBusy('resume');setError('');setNotice('');try{const f=new FormData(e.currentTarget);f.set('action','review_resume');const r=await apiFetch<{data:Review}>(`/api/organizations/${activeOrgId()}/recruiting/applications/${applicationId}/ats`,{method:'POST',body:f});setNotice(`ATS review completed at ${r.data.score}%. This is evidence support, not an automated hiring decision.`);await load();}catch(e){setError(e instanceof Error?e.message:'ATS review failed.')}finally{setBusy('')}}
 async function generateLetter(){if(!applicationId)return;setBusy('letter');setError('');try{const tone=(document.getElementById('ats-letter-tone') as HTMLSelectElement|null)?.value||'professional';const r=await apiFetch<{data:Draft}>(`/api/organizations/${activeOrgId()}/recruiting/applications/${applicationId}/ats`,{method:'POST',body:JSON.stringify({action:'generate_cover_letter',tone})});setLetterText(r.data.text);setNotice(`Evidence-grounded cover letter draft generated with ${r.data.provider}. Review and edit before use.`);await load();}catch(e){setError(e instanceof Error?e.message:'Cover letter generation failed.')}finally{setBusy('')}}
 async function reviewLetter(){if(!applicationId||!letterText.trim())return;setBusy('review-letter');setError('');try{const r=await apiFetch<{data:LetterReview}>(`/api/organizations/${activeOrgId()}/recruiting/applications/${applicationId}/ats`,{method:'POST',body:JSON.stringify({action:'review_cover_letter',text:letterText})});setLetterReview(r.data);}catch(e){setError(e instanceof Error?e.message:'Cover letter review failed.')}finally{setBusy('')}}
 async function copyLetter(){await navigator.clipboard.writeText(letterText);setNotice('Cover letter copied to clipboard.')}
 function downloadLetter(){const blob=new Blob([letterText],{type:'text/plain;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`${selected?.candidate?.displayName||'Candidate'}_${selected?.requisition?.title||'Role'}_Cover_Letter.txt`.replace(/[^A-Za-z0-9._-]+/g,'_');a.click();URL.revokeObjectURL(u)}
 return <section ref={translationRoot} className="card stack atsPanel"><div className="toolbar"><div><h2 className="sectionTitle">ATS Resume & Cover Letter Studio</h2><p className="muted">Explainable job-relevance review, resume parsing, evidence gaps, and evidence-grounded cover letters. Protected characteristics are excluded from scoring and OPSIQO never auto-rejects or auto-hires.</p></div><span className="badge">ATS v2</span></div><label className="field"><span>Application</span><select className="input" value={applicationId} onChange={e=>setApplicationId(e.target.value)}><option value="">Select an application</option>{applications.map(a=><option key={a.id} value={a.id}>{a.candidate?.displayName||a.id.slice(0,8)} · {a.requisition?.requisitionNumber} · {a.requisition?.title}</option>)}</select></label>{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="success" role="status">{notice}</div>}{!selected&&<div className="notice"><strong>Start with a candidate application.</strong> Use the Resume Intake Assistant in <a href="#candidate-application-form">Add candidate application</a> to upload PDF, DOCX, TXT, RTF or Markdown and prefill the candidate fields. After the application is saved, select it here to run the explainable ATS review and generate/review a cover letter.</div>}
 {selected&&<div className="atsStudioGrid"><form className="stack atsSection" onSubmit={reviewResume}><h3>Resume review</h3><p className="muted">Upload a newer resume or leave the file blank to review the resume text already stored for this candidate.</p><input className="input" name="file" type="file" accept=".pdf,.docx,.txt,.rtf,.md"/><button className="button" disabled={!canManage||busy==='resume'}>{busy==='resume'?'Analyzing resume…':'Run explainable ATS review'}</button><div className="notice">The ATS score is a document-to-job evidence indicator only. Recruiters must review context, equivalencies and relevant evidence before any employment decision.</div></form><div className="atsSection stack"><h3>Cover letter</h3><div className="row wrap"><select id="ats-letter-tone" className="input compact"><option value="professional">Professional</option><option value="concise">Concise</option><option value="warm">Warm</option></select><button className="button secondary" type="button" disabled={!canManage||!state?.review||busy==='letter'} onClick={generateLetter}>{busy==='letter'?'Drafting…':'Generate from resume evidence'}</button></div><textarea className="input" rows={12} value={letterText} onChange={e=>setLetterText(e.target.value)} placeholder="Generate a draft or paste an existing cover letter to review."/><div className="row wrap"><button type="button" className="button secondary" disabled={!state?.review||letterText.trim().length<100||busy==='review-letter'} onClick={reviewLetter}>{busy==='review-letter'?'Reviewing…':'Review cover letter'}</button><button type="button" className="button secondary" disabled={!letterText} onClick={copyLetter}>Copy</button><button type="button" className="button secondary" disabled={!letterText} onClick={downloadLetter}>Download TXT</button></div></div></div>}
 {state?.review&&<div className="stack atsResults"><div className="atsScoreHero"><div><div className="metricLabel">Job-relevance evidence score</div><div className="metricValue">{state.review.score}%</div><div className="badge">{state.review.band.replaceAll('_',' ')}</div></div><div className="muted">{state.review.scoringVersion}<br/>{new Date(state.review.createdAt).toLocaleString()}</div></div>{typeof state.review.assessmentCoverage==='number'&&<div className="notice"><strong>Job evidence coverage:</strong> {state.review.assessmentCoverage}%. Unassessed dimensions are not treated as perfect matches.</div>}{(state.review.warnings||[]).length>0&&<div className="notice"><strong>ATS review warnings</strong><ul>{(state.review.warnings||[]).map((x,i)=><li key={i}>{x}</li>)}</ul></div>}<div className="atsBreakdown">{(!state.review.assessedDimensions||state.review.assessedDimensions.includes('requirements'))&&<ScoreBar label="Stated requirements" value={state.review.breakdown.requirements}/>}
{(!state.review.assessedDimensions||state.review.assessedDimensions.includes('skills'))&&<ScoreBar label="Job-related skills" value={state.review.breakdown.skills}/>}
{(!state.review.assessedDimensions||state.review.assessedDimensions.includes('responsibilities'))&&<ScoreBar label="Responsibilities" value={state.review.breakdown.responsibilities}/>}
{(!state.review.assessedDimensions||state.review.assessedDimensions.includes('experience'))&&<ScoreBar label="Experience evidence" value={state.review.breakdown.experience}/>}
{(!state.review.assessedDimensions||state.review.assessedDimensions.includes('educationCertification'))&&<ScoreBar label="Education / certification" value={state.review.breakdown.educationCertification}/>}
<ScoreBar label="Document completeness" value={state.review.breakdown.documentQuality}/></div><div className="grid2"><div className="stack"><h3>Matched requirements</h3><Chips items={state.review.matchedRequirements}/><h3>Matched job signals</h3><Chips items={state.review.matchedKeywords}/></div><div className="stack"><h3>Evidence gaps</h3><Chips items={state.review.missingRequirements} empty="No explicit requirement gaps detected."/><h3>Missing job-language signals</h3><Chips items={state.review.missingKeywords}/></div></div><details><summary>Evidence matrix</summary><div className="tableWrap"><table><thead><tr><th>Criterion</th><th>Category</th><th>Match</th><th>Confidence</th><th>Evidence</th></tr></thead><tbody>{state.review.evidence.map((e,i)=><tr key={i}><td>{e.criterion}</td><td>{e.category.replaceAll('_',' ')}</td><td>{e.matched?'Supported':'Gap / partial'}</td><td>{Math.round(e.confidence*100)}%</td><td>{e.evidence||e.missingTerms?.join(', ')||'No direct evidence'}</td></tr>)}</tbody></table></div></details><div className="notice"><strong>Decision boundary:</strong> {state.review.decisionBoundary}</div></div>}
 {letterReview&&<div className="card insetCard stack"><h3>Cover letter review</h3><div className="grid2"><MetricMini label="Role relevance" value={letterReview.relevanceScore}/><MetricMini label="Evidence grounding" value={letterReview.evidenceGroundingScore}/></div><h4>Matched job signals</h4><Chips items={letterReview.matchedJobSignals}/>{letterReview.unsupportedClaims.length>0&&<><h4>Claims requiring verification</h4><ul>{letterReview.unsupportedClaims.map((x,i)=><li key={i}>{x}</li>)}</ul></>}<h4>Recommendations</h4><ul>{letterReview.recommendations.map((x,i)=><li key={i}>{x}</li>)}</ul></div>}
 </section>
}
function MetricMini({label,value}:{label:string;value:number}){return <div className="atsMiniMetric"><span>{label}</span><strong>{value}%</strong></div>}
