'use client';
import {FormEvent,useEffect,useState} from 'react';
import {activeOrgId,apiFetch} from '@/lib/http/client';
type Req={id:string;requisitionNumber:string;title:string;status:string};
type Q={id:string;label:string;type:'yes_no'|'text'|'number'|'select';required:boolean;options:string[]};
type LinkRow={id:string;requisitionId:string;publicToken:string;status:'active'|'paused'|'closed';coverLetterRequired:boolean;allowTalentPoolConsent:boolean;screeningQuestions:Q[];closingAt?:string;applicationsCount?:number};
const q=():Q=>({id:crypto.randomUUID(),label:'',type:'yes_no',required:true,options:[]});
export function CandidateApplicationLinksPanel({requisitions,canManage}:{requisitions:Req[];canManage:boolean}){
 const[links,setLinks]=useState<LinkRow[]>([]),[questions,setQuestions]=useState<Q[]>([]),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');const open=requisitions.filter(r=>r.status==='open');
 async function load(){try{const r=await apiFetch<{data:LinkRow[]}>(`/api/organizations/${activeOrgId()}/recruiting/application-links`);setLinks(r.data)}catch(e){setError(e instanceof Error?e.message:'Unable to load application links.')}}
 useEffect(()=>{void load()},[]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setBusy('create');setError('');try{const r=await apiFetch<{data:LinkRow}>(`/api/organizations/${activeOrgId()}/recruiting/application-links`,{method:'POST',body:JSON.stringify({requisitionId:f.get('requisitionId'),coverLetterRequired:f.get('coverLetterRequired')==='on',allowTalentPoolConsent:f.get('allowTalentPoolConsent')==='on',closingAt:f.get('closingAt')?new Date(String(f.get('closingAt'))).toISOString():undefined,screeningQuestions:questions.filter(x=>x.label.trim()).map(x=>({...x,label:x.label.trim(),options:x.type==='select'?x.options:[]}))})});const u=`${location.origin}/apply/${r.data.publicToken}`;await navigator.clipboard.writeText(u).catch(()=>undefined);setNotice('Public candidate application link created and copied when browser permission allowed.');setQuestions([]);form.reset();await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create link.')}finally{setBusy('')}}
 async function update(id:string,status:LinkRow['status']){setBusy(id);try{await apiFetch(`/api/organizations/${activeOrgId()}/recruiting/application-links/${id}`,{method:'PATCH',body:JSON.stringify({status})});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update link.')}finally{setBusy('')}}
 const publicUrl=(l:LinkRow)=>`${location.origin}/apply/${l.publicToken}`;
 return <section className="card stack" data-h50-5-application-links="true"><div className="toolbar"><div><h2 className="sectionTitle">Candidate Application Portal Links</h2><p className="muted">Create a shareable, mobile-first application link. Resume parsing, cover letter, professional links, consent and screening are handled in the candidate portal.</p></div><span className="badge">Shareable career link</span></div>{error&&<div className="error">{error}</div>}{notice&&<div className="success">{notice}</div>}
 {canManage&&<form className="stack" onSubmit={create}><div className="formGrid"><label className="field"><span>Open requisition</span><select className="input" required name="requisitionId"><option value="">Select requisition</option>{open.map(r=><option key={r.id} value={r.id}>{r.requisitionNumber} · {r.title}</option>)}</select></label><label className="field"><span>Closing date/time · optional</span><input className="input" type="datetime-local" name="closingAt"/></label></div><label><input type="checkbox" name="coverLetterRequired"/> Require cover letter</label><label><input type="checkbox" name="allowTalentPoolConsent" defaultChecked/> Offer separate talent-pool consent</label>
 <div className="toolbar"><strong>Screening questions</strong><button className="button secondary" type="button" onClick={()=>setQuestions(x=>[...x,q()])}>Add question</button></div>{questions.map((x,i)=><div className="card insetCard stack" key={x.id}><div className="formGrid"><label className="field"><span>Question</span><input className="input" value={x.label} onChange={e=>setQuestions(a=>a.map((v,j)=>j===i?{...v,label:e.target.value}:v))}/></label><label className="field"><span>Type</span><select className="input" value={x.type} onChange={e=>setQuestions(a=>a.map((v,j)=>j===i?{...v,type:e.target.value as Q['type']}:v))}><option value="yes_no">Yes / No</option><option value="text">Text</option><option value="number">Number</option><option value="select">Dropdown</option></select></label></div>{x.type==='select'&&<label className="field"><span>Options · one per line</span><textarea className="input" rows={3} value={x.options.join('\n')} onChange={e=>setQuestions(a=>a.map((v,j)=>j===i?{...v,options:e.target.value.split('\n').map(s=>s.trim()).filter(Boolean)}:v))}/></label>}<div className="row"><label><input type="checkbox" checked={x.required} onChange={e=>setQuestions(a=>a.map((v,j)=>j===i?{...v,required:e.target.checked}:v))}/> Required</label><button type="button" className="button secondary" onClick={()=>setQuestions(a=>a.filter((_,j)=>j!==i))}>Remove</button></div></div>)}<div className="notice">OPSIQO blocks screening questions that reference protected/sensitive traits. Ask about work authorization, not citizenship or nationality.</div><button className="button" disabled={busy==='create'||!open.length}>{busy==='create'?'Creating…':'Create & copy public link'}</button></form>}
 <div className="tableWrap"><table><thead><tr><th>Position</th><th>Status</th><th>Applications</th><th>Cover letter</th><th>Share</th></tr></thead><tbody>{links.map(l=>{const r=requisitions.find(x=>x.id===l.requisitionId);return <tr key={l.id}><td><strong>{r?.title||l.requisitionId}</strong><div className="muted">{r?.requisitionNumber}</div></td><td><span className="badge">{l.status}</span></td><td>{l.applicationsCount||0}</td><td>{l.coverLetterRequired?'Required':'Optional'}</td><td><div className="stepActions"><button type="button" className="button secondary" onClick={()=>void navigator.clipboard.writeText(publicUrl(l))}>Copy link</button><a className="button secondary" href={publicUrl(l)} target="_blank" rel="noreferrer">Preview</a>{l.status==='active'&&canManage&&<button type="button" className="button secondary" disabled={busy===l.id} onClick={()=>void update(l.id,'paused')}>Pause</button>}{l.status==='paused'&&canManage&&<button type="button" className="button secondary" disabled={busy===l.id} onClick={()=>void update(l.id,'active')}>Activate</button>}{l.status!=='closed'&&canManage&&<button type="button" className="button secondary" onClick={()=>void update(l.id,'closed')}>Close</button>}</div></td></tr>})}</tbody></table></div></section>;
}
