'use client';
import {useMemo,useState} from 'react';
import {activeOrgId,apiFetch} from '@/lib/http/client';
type App={id:string;stage:string;candidate?:{displayName:string;email:string};requisition?:{requisitionNumber:string;title:string};atsLatestScore?:number;atsLatestRequirementsCoverage?:number;atsLatestEvidenceConfidence?:number;atsLatestGapCount?:number;atsAnalysisStatus?:string;atsReviewedAt?:string};
const ready=(x:App)=>x.atsAnalysisStatus==='ready';const fitScore=(x:App)=>ready(x)&&typeof x.atsLatestScore==='number'?x.atsLatestScore:undefined;
export function CandidateFitBoard({applications,canManage,onRefresh}:{applications:App[];canManage:boolean;onRefresh:()=>void|Promise<void>}){
 const[filter,setFilter]=useState('all'),[sort,setSort]=useState('fit_desc'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const rows=useMemo(()=>{let a=[...applications];if(filter==='80')a=a.filter(x=>(fitScore(x)??-1)>=80);if(filter==='70')a=a.filter(x=>(fitScore(x)??-1)>=70);if(filter==='gaps')a=a.filter(x=>ready(x)&&(x.atsLatestGapCount||0)>0);if(filter==='needs_review')a=a.filter(x=>!ready(x));a.sort((x,y)=>sort==='fit_asc'?(fitScore(x)??101)-(fitScore(y)??101):sort==='requirements_desc'?(ready(y)?y.atsLatestRequirementsCoverage??-1:-1)-(ready(x)?x.atsLatestRequirementsCoverage??-1:-1):sort==='confidence_desc'?(ready(y)?y.atsLatestEvidenceConfidence??-1:-1)-(ready(x)?x.atsLatestEvidenceConfidence??-1:-1):sort==='name'?String(x.candidate?.displayName||'').localeCompare(String(y.candidate?.displayName||'')):(fitScore(y)??-1)-(fitScore(x)??-1));return a},[applications,filter,sort]);
 async function reconcile(force=false){setBusy(true);setError('');setNotice('');try{const r=await apiFetch<{data:{analyzed:number;skipped:number;failed:number;noResume:number}}>(`/api/organizations/${activeOrgId()}/recruiting/ats/reconcile`,{method:'POST',body:JSON.stringify({force})});setNotice(`${r.data.analyzed} analyzed · ${r.data.skipped} current · ${r.data.noResume} without resume · ${r.data.failed} failed.`);await onRefresh()}catch(e){setError(e instanceof Error?e.message:'Unable to reconcile candidate fit.')}finally{setBusy(false)}}
 return <section className="card stack" data-h50-5-candidate-fit-board="true"><div className="toolbar"><div><h2 className="sectionTitle">Candidate Fit Intelligence</h2><p className="muted">Position-specific resume evidence alignment. Protected traits and social-profile content are excluded. OPSIQO does not auto-reject, auto-hire or auto-advance candidates.</p></div><span className="badge">H50.5 · explainable fit</span></div>
 {error&&<div className="error">{error}</div>}{notice&&<div className="success">{notice}</div>}
 <div className="row wrap"><label className="field"><span>Filter</span><select className="input compact" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All candidates</option><option value="80">80%+ fit</option><option value="70">70%+ fit</option><option value="gaps">Has requirement gaps</option><option value="needs_review">Needs analysis / review</option></select></label><label className="field"><span>Sort</span><select className="input compact" value={sort} onChange={e=>setSort(e.target.value)}><option value="fit_desc">Highest fit</option><option value="fit_asc">Lowest fit</option><option value="requirements_desc">Requirements coverage</option><option value="confidence_desc">Evidence confidence</option><option value="name">Candidate name</option></select></label>{canManage&&<><button type="button" className="button secondary" disabled={busy} onClick={()=>void reconcile(false)}>{busy?'Analyzing…':'Analyze missing / stale'}</button><button type="button" className="button secondary" disabled={busy} onClick={()=>void reconcile(true)}>Refresh all resume fit</button></>}</div>
 <div className="tableWrap"><table><thead><tr><th>Candidate</th><th>Position</th><th>Overall fit</th><th>Requirements</th><th>Evidence confidence</th><th>Gaps</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.candidate?.displayName||x.id}</strong><div className="muted">{x.candidate?.email}</div></td><td>{x.requisition?.requisitionNumber} · {x.requisition?.title}</td><td>{ready(x)&&typeof x.atsLatestScore==='number'?<strong>{x.atsLatestScore}%</strong>:<span className="muted">Not scored</span>}</td><td>{ready(x)&&typeof x.atsLatestRequirementsCoverage==='number'?`${x.atsLatestRequirementsCoverage}%`:'—'}</td><td>{ready(x)&&typeof x.atsLatestEvidenceConfidence==='number'?`${x.atsLatestEvidenceConfidence}%`:'—'}</td><td>{ready(x)?x.atsLatestGapCount??'—':'—'}</td><td><span className="badge">{(x.atsAnalysisStatus||'not analyzed').replaceAll('_',' ')}</span>{ready(x)&&x.atsReviewedAt&&<div className="muted">{new Date(x.atsReviewedAt).toLocaleString()}</div>}</td></tr>)}{!rows.length&&<tr><td colSpan={7} className="muted">No candidates match this filter.</td></tr>}</tbody></table></div>
 <div className="notice"><strong>Decision boundary:</strong> Fit % is internal document-to-job evidence support, not a prediction of performance or an automatic employment decision.</div></section>;
}
