'use client';
import {FormEvent,useEffect,useState} from 'react';
import type {ReactNode} from 'react';
import {firebaseAppCheck} from '@/lib/firebase/client';
import {getToken as getAppCheckToken} from 'firebase/app-check';
import {LoadingState} from '@/components/data-states';
type Q={id:string;label:string;type:'yes_no'|'text'|'number'|'select';required:boolean;options?:string[]};
type Context={organization:{name:string;logoUrl?:string};requisition:{requisitionNumber:string;title:string;location?:string;employmentType:string;description:string;requirements:string[]};application:{coverLetterRequired:boolean;allowTalentPoolConsent:boolean;screeningQuestions:Q[];closingAt?:string}};
type Profile={firstName:string;lastName:string;email:string;phone:string;location:string;linkedinUrl:string;portfolioUrl:string;githubUrl:string;socialMediaUrl:string;headline:string;summary:string;skills:string;certifications:string;education:string;yearsOfExperience:string;candidateStatement:string};
const empty:Profile={firstName:'',lastName:'',email:'',phone:'',location:'',linkedinUrl:'',portfolioUrl:'',githubUrl:'',socialMediaUrl:'',headline:'',summary:'',skills:'',certifications:'',education:'',yearsOfExperience:'',candidateStatement:''};
async function call<T>(path:string,init:RequestInit={},draftToken?:string){const h=new Headers(init.headers);if(!(init.body instanceof FormData))h.set('content-type','application/json');if(draftToken)h.set('x-application-draft-token',draftToken);if(process.env.NEXT_PUBLIC_OPSIQO_DEMO_MODE!=='true'){const ac=firebaseAppCheck();if(ac)h.set('x-firebase-appcheck',(await getAppCheckToken(ac,false)).token)}const r=await fetch(path,{...init,headers:h,cache:'no-store'}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.message||`Request failed (${r.status})`);return p as T}
const list=(s:string)=>s.split(/\n|;/).map(x=>x.trim()).filter(Boolean);
export function CandidateApplicationPortal({token}:{token:string}){
 const[ctx,setCtx]=useState<Context|null>(null),[p,setP]=useState<Profile>(empty),[answers,setAnswers]=useState<Record<string,string>>({}),[resume,setResume]=useState<File|null>(null),[cover,setCover]=useState<File|null>(null),[coverText,setCoverText]=useState(''),[step,setStep]=useState(1),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[parseNote,setParseNote]=useState(''),[consent,setConsent]=useState(false),[accuracy,setAccuracy]=useState(false),[talent,setTalent]=useState(false),[submitted,setSubmitted]=useState<{applicationId:string;submissionVersion:number;deduplicated:boolean}|null>(null);
 const key=`opsiqo.candidateDraftToken.${token}`,set=(k:keyof Profile,v:string)=>setP(x=>({...x,[k]:v}));
 useEffect(()=>{void(async()=>{try{const r=await call<{data:Context}>(`/api/public/recruiting/apply/${encodeURIComponent(token)}`);setCtx(r.data);const d=localStorage.getItem(key);if(d){try{const x=await call<{data:{data:any}}>(`/api/public/recruiting/apply/${encodeURIComponent(token)}/draft`,{},d),s=x.data.data||{};setP(v=>({...v,...s,skills:Array.isArray(s.skills)?s.skills.join('\n'):s.skills||v.skills,certifications:Array.isArray(s.certifications)?s.certifications.join('\n'):s.certifications||v.certifications,education:Array.isArray(s.education)?s.education.join('\n'):s.education||v.education,yearsOfExperience:s.yearsOfExperience==null?v.yearsOfExperience:String(s.yearsOfExperience)}));if(s.screeningAnswers)setAnswers(s.screeningAnswers);if(s.coverLetterText)setCoverText(s.coverLetterText);if(typeof s.talentPoolConsent==='boolean')setTalent(s.talentPoolConsent);setNotice('Saved draft restored. Reattach resume/cover-letter files before final submission.')}catch{localStorage.removeItem(key)}}}catch(e){setError(e instanceof Error?e.message:'Unable to open application.')}})()},[token]);
 async function parse(f:File){setBusy('parse');setError('');try{const d=new FormData();d.set('file',f);const r=await call<{data:{profile:any;note:string}}>(`/api/public/recruiting/apply/${encodeURIComponent(token)}/parse`,{method:'POST',body:d}),x=r.data.profile;setP(v=>({...v,firstName:x.firstName||v.firstName,lastName:x.lastName||v.lastName,email:x.email||v.email,phone:x.phone||v.phone,location:x.location||v.location,linkedinUrl:x.linkedinUrl||v.linkedinUrl,headline:x.headline||v.headline,summary:x.summary||v.summary,skills:x.skills?.length?x.skills.join('\n'):v.skills,certifications:x.certifications?.length?x.certifications.join('\n'):v.certifications,education:x.education?.length?x.education.join('\n'):v.education,yearsOfExperience:x.yearsOfExperience==null?v.yearsOfExperience:String(x.yearsOfExperience)}));setParseNote(`${r.data.note}${x.parseQuality==null?'':` Extraction quality: ${x.parseQuality}%.`}`);setStep(2)}catch(e){setError(e instanceof Error?e.message:'Resume parsing failed.')}finally{setBusy('')}}
 async function saveDraft(){setBusy('draft');setError('');try{const d=localStorage.getItem(key)||undefined,r=await call<{data:{draftToken:string;expiresInDays:number}}>(`/api/public/recruiting/apply/${encodeURIComponent(token)}/draft`,{method:'POST',body:JSON.stringify({...p,skills:list(p.skills),certifications:list(p.certifications),education:list(p.education),yearsOfExperience:p.yearsOfExperience?Number(p.yearsOfExperience):undefined,screeningAnswers:answers,coverLetterText:coverText,talentPoolConsent:talent})},d);localStorage.setItem(key,r.data.draftToken);setNotice(`Draft saved for ${r.data.expiresInDays} days. File attachments are not stored until submission.`)}catch(e){setError(e instanceof Error?e.message:'Unable to save draft.')}finally{setBusy('')}}
 async function submit(e:FormEvent){e.preventDefault();if(!resume){setError('Attach your resume before submitting.');setStep(1);return}if(ctx?.application.coverLetterRequired&&!cover&&!coverText.trim()){setError('A cover letter is required.');setStep(5);return}if(!consent||!accuracy){setError('Confirm the declaration and privacy consent.');return}setBusy('submit');setError('');try{const d=new FormData();d.set('resume',resume);if(cover)d.set('coverLetter',cover);d.set('application',JSON.stringify({...p,skills:list(p.skills),certifications:list(p.certifications),education:list(p.education),yearsOfExperience:p.yearsOfExperience?Number(p.yearsOfExperience):undefined,screeningAnswers:answers,coverLetterText:coverText,consent:true,accuracyConfirmed:true,talentPoolConsent:talent}));const r=await call<{data:{applicationId:string;submissionVersion:number;deduplicated:boolean}}>(`/api/public/recruiting/apply/${encodeURIComponent(token)}/submit`,{method:'POST',body:d});localStorage.removeItem(key);setSubmitted(r.data)}catch(e){setError(e instanceof Error?e.message:'Unable to submit application.')}finally{setBusy('')}}
 if(error&&!ctx)return <Shell><section className="prehireCard"><h1>Candidate application</h1><div className="error">{error}</div></section></Shell>;if(!ctx)return <Shell><section className="prehireCard"><LoadingState label="Loading candidate application…"/></section></Shell>;
 if(submitted)return <Shell><section className="prehireCard stack"><Brand ctx={ctx}/><h1>Application submitted successfully</h1><p>Thank you for applying for <strong>{ctx.requisition.title}</strong>.</p><div className="notice">Application reference: <strong>{submitted.applicationId}</strong><br/>Submission version: {submitted.submissionVersion}{submitted.deduplicated?' · Your existing application was updated.':''}</div><p className="muted">OPSIQO may generate an internal job-fit evidence score for human recruiter review. It is not shown to candidates and does not automatically determine hiring, rejection or advancement.</p></section></Shell>;
 const progress=Math.round(step/6*100);
 return <Shell><header className="prehireHero"><div><Brand ctx={ctx}/><h1>{ctx.requisition.title}</h1><p>{ctx.organization.name} · {ctx.requisition.location||'Location not specified'} · {ctx.requisition.employmentType}</p></div><div className="prehireProgress"><strong>{progress}%</strong><span>step {step} of 6</span></div></header>
 <section className="prehireCard stack"><details><summary><strong>Position details</strong></summary><p style={{whiteSpace:'pre-wrap'}}>{ctx.requisition.description}</p>{ctx.requisition.requirements.length>0&&<ul>{ctx.requisition.requirements.map(x=><li key={x}>{x}</li>)}</ul>}</details><div className="atsTrack"><div className="atsFill" style={{width:`${progress}%`}}/></div>{error&&<div className="error">{error}</div>}{notice&&<div className="success">{notice}</div>}</section>
 <form className="stack" onSubmit={submit}>
 {step===1&&<section className="prehireCard stack"><h2>1. Resume</h2><p className="muted">Upload PDF, DOCX, TXT, RTF or Markdown. OPSIQO parses it to prefill your application; you review and correct the fields.</p><input className="input" type="file" accept=".pdf,.docx,.txt,.rtf,.md" required onChange={e=>{const f=e.target.files?.[0]||null;setResume(f);if(f)void parse(f)}}/>{resume&&<div className="notice">Attached: <strong>{resume.name}</strong></div>}{parseNote&&<div className="success">{parseNote}</div>}<button type="button" className="button" disabled={!resume||busy==='parse'} onClick={()=>resume&&void parse(resume)}>{busy==='parse'?'Parsing…':'Parse / refresh fields'}</button></section>}
 {step===2&&<section className="prehireCard stack"><h2>2. Your information</h2><div className="formGrid"><F label="First name" value={p.firstName} onChange={v=>set('firstName',v)} required/><F label="Last name" value={p.lastName} onChange={v=>set('lastName',v)} required/><F label="Email" type="email" value={p.email} onChange={v=>set('email',v)} required/><F label="Phone" value={p.phone} onChange={v=>set('phone',v)}/><F label="Location" value={p.location} onChange={v=>set('location',v)}/><F label="Professional headline" value={p.headline} onChange={v=>set('headline',v)}/></div><label className="field"><span>Professional summary</span><textarea className="input" rows={5} value={p.summary} onChange={e=>set('summary',e.target.value)}/></label></section>}
 {step===3&&<section className="prehireCard stack"><h2>3. Professional evidence</h2><div className="formGrid"><F label="Years of relevant experience" type="number" value={p.yearsOfExperience} onChange={v=>set('yearsOfExperience',v)}/><TA label="Skills · one per line" value={p.skills} onChange={v=>set('skills',v)}/><TA label="Certifications / licences · one per line" value={p.certifications} onChange={v=>set('certifications',v)}/><TA label="Education · one item per line" value={p.education} onChange={v=>set('education',v)}/></div><div className="notice">Internal fit scoring uses submitted resume evidence, not social-media content or unverified edits.</div></section>}
 {step===4&&<section className="prehireCard stack"><h2>4. Screening questions</h2>{ctx.application.screeningQuestions.map(q=><Question key={q.id} q={q} value={answers[q.id]||''} onChange={v=>setAnswers(x=>({...x,[q.id]:v}))}/>) }{!ctx.application.screeningQuestions.length&&<div className="notice">No additional screening questions.</div>}</section>}
 {step===5&&<section className="prehireCard stack"><h2>5. Cover letter & professional/social links</h2><label className="field"><span>Cover letter file {ctx.application.coverLetterRequired?'· required':'· optional'}</span><input className="input" type="file" accept=".pdf,.docx,.txt,.rtf,.md" onChange={e=>setCover(e.target.files?.[0]||null)}/></label><label className="field"><span>Or paste / write cover letter</span><textarea className="input" rows={9} value={coverText} onChange={e=>setCoverText(e.target.value)}/></label><div className="formGrid"><F label="LinkedIn" type="url" value={p.linkedinUrl} onChange={v=>set('linkedinUrl',v)}/><F label="Portfolio / website" type="url" value={p.portfolioUrl} onChange={v=>set('portfolioUrl',v)}/><F label="GitHub" type="url" value={p.githubUrl} onChange={v=>set('githubUrl',v)}/><F label="Other social/professional profile" type="url" value={p.socialMediaUrl} onChange={v=>set('socialMediaUrl',v)}/></div><TA label="Optional note to recruiter" value={p.candidateStatement} onChange={v=>set('candidateStatement',v)}/><div className="notice">Professional/social links are optional and excluded from automated job-fit scoring.</div></section>}
 {step===6&&<section className="prehireCard stack"><h2>6. Review & submit</h2><div className="grid2"><Review l="Candidate" v={`${p.firstName} ${p.lastName}`}/><Review l="Email" v={p.email}/><Review l="Resume" v={resume?.name||'Not attached'}/><Review l="Cover letter" v={cover?.name||(coverText.trim()?'Pasted text':'Not provided')}/></div><label><input type="checkbox" checked={accuracy} onChange={e=>setAccuracy(e.target.checked)} required/> I confirm this application and supporting documents are accurate to the best of my knowledge.</label><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/> I consent to processing my application information for recruitment purposes and acknowledge the privacy notice.</label>{ctx.application.allowTalentPoolConsent&&<label><input type="checkbox" checked={talent} onChange={e=>setTalent(e.target.checked)}/> I agree that my application may be considered for other suitable opportunities. Optional.</label>}<div className="notice">Protected characteristics and social-profile content are excluded from automated fit analysis. OPSIQO does not automatically hire, reject or advance candidates.</div><button className="button" disabled={busy==='submit'}>{busy==='submit'?'Submitting…':'Submit application'}</button></section>}
 <section className="prehireCard"><div className="row wrap"><button type="button" className="button secondary" disabled={step<=1} onClick={()=>setStep(x=>Math.max(1,x-1))}>Back</button>{step<6&&<button type="button" className="button" onClick={()=>setStep(x=>Math.min(6,x+1))}>Continue</button>}<button type="button" className="button secondary" disabled={busy==='draft'} onClick={()=>void saveDraft()}>{busy==='draft'?'Saving…':'Save & continue later'}</button></div><p className="muted">Draft fields are retained securely for 14 days. File attachments are retained only after final submission.</p></section></form><div className="notice">Powered by OPSIQO · Evidence-first recruiting · Human review required</div></Shell>;
}
function Shell({children}:{children:ReactNode}){return <div className="prehireShell"><main className="prehireMain">{children}</main></div>}
function Brand({ctx}:{ctx:Context}){return <div className="prehireBrand"><img className="prehireBrandLogo" src={ctx.organization.logoUrl||'/brand/opsiqo-wordmark.png'} alt={ctx.organization.name}/><span>CANDIDATE APPLICATION</span></div>}
function F({label,value,onChange,type='text',required}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}){return <label className="field"><span>{label}</span><input className="input" type={type} value={value} onChange={e=>onChange(e.target.value)} required={required}/></label>}
function TA({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><textarea className="input" rows={5} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Question({q,value,onChange}:{q:Q;value:string;onChange:(v:string)=>void}){if(q.type==='yes_no'||q.type==='select')return <label className="field"><span>{q.label}</span><select className="input" value={value} onChange={e=>onChange(e.target.value)} required={q.required}><option value="">Select</option>{(q.type==='yes_no'?['Yes','No']:q.options||[]).map(x=><option key={x}>{x}</option>)}</select></label>;return <F label={q.label} type={q.type==='number'?'number':'text'} value={value} onChange={onChange} required={q.required}/>}
function Review({l,v}:{l:string;v:string}){return <div className="metric"><div className="metricLabel">{l}</div><div>{v||'Not provided'}</div></div>}
