'use client';
import { useMemo,useRef,useState } from 'react';
import Link from 'next/link';
import { activeOrgId,apiFetch } from '@/lib/http/client';
import { CONTRACT_FIELD_KEYS,type ContractFieldKey,type ContractImportDraft } from '@/domain/contract-import';

const LABELS:Record<ContractFieldKey,string>={employerName:'Employer name',employeeName:'Employee name',employeeEmail:'Employee email',employeeNumber:'Employee number',jobTitle:'Job title / position',department:'Department',managerName:'Reports to / manager',workLocation:'Work location',employmentType:'Employment type',startDate:'Start date',endDate:'End date',probationPeriod:'Probation period',hoursPerWeek:'Hours per week',schedule:'Work schedule',basePay:'Base pay / salary',payFrequency:'Pay frequency',bonusCommission:'Bonus / commission',vacationEntitlement:'Vacation entitlement',benefits:'Benefits',overtimeTerms:'Overtime terms',terminationNotice:'Termination / notice terms',confidentiality:'Confidentiality',nonSolicitation:'Non-solicitation',nonCompetition:'Non-competition',intellectualProperty:'Intellectual property',governingLaw:'Governing law / jurisdiction',signatureDate:'Signature date',employeeSigned:'Employee signed',employerSigned:'Employer signed'};
const GROUPS:Array<{title:string;keys:ContractFieldKey[]}>= [
 {title:'Identity & assignment',keys:['employerName','employeeName','employeeEmail','employeeNumber','jobTitle','department','managerName','workLocation','employmentType','startDate','endDate']},
 {title:'Hours & compensation',keys:['probationPeriod','hoursPerWeek','schedule','basePay','payFrequency','bonusCommission','vacationEntitlement','benefits','overtimeTerms']},
 {title:'Contract governance',keys:['terminationNotice','confidentiality','nonSolicitation','nonCompetition','intellectualProperty','governingLaw','signatureDate','employeeSigned','employerSigned']}
];
function fmtBytes(n:number){return n<1024*1024?`${Math.max(1,Math.round(n/1024))} KB`:`${(n/1024/1024).toFixed(1)} MB`}
function confidenceClass(n:number){return n>=.85?'high':n>=.7?'medium':'low'}
export function ContractImportWorkspace(){
 const inputRef=useRef<HTMLInputElement>(null),[file,setFile]=useState<File|null>(null),[draft,setDraft]=useState<ContractImportDraft|null>(null),[values,setValues]=useState<Record<string,string>>({}),[workerId,setWorkerId]=useState(''),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[stage,setStage]=useState(0),[status,setStatus]=useState(''),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false);
 const populated=useMemo(()=>draft?CONTRACT_FIELD_KEYS.filter(k=>String(values[k]??draft.fields[k]?.value??'').trim()).length:0,[draft,values]);
 function choose(f:File|null){setFile(f);setDraft(null);setValues({});setWorkerId('');setReviewed(false);setConfirmed(false);setError('');setStatus('');setStage(0)}
 async function parse(){if(!file)return;setBusy(true);setError('');setStatus('Uploading source to governed intake…');setStage(15);try{const form=new FormData();form.append('file',file);setStage(35);setStatus('Extracting contract terms and source evidence…');const r=await apiFetch<{data:ContractImportDraft}>(`/api/organizations/${activeOrgId()}/contract-import/parse`,{method:'POST',body:form});setStage(90);setStatus('Building review draft and employee match suggestions…');const next=r.data;setDraft(next);setValues(Object.fromEntries(CONTRACT_FIELD_KEYS.map(k=>[k,next.fields[k]?.value||''])));if(next.workerMatches?.[0]?.score>=.95)setWorkerId(next.workerMatches[0].workerId);setStage(100);setStatus('Parsing complete. Review every populated field before confirmation.')}catch(e){setError(e instanceof Error?e.message:'Contract parsing failed.');setStage(0);setStatus('')}finally{setBusy(false)}}
 async function confirm(){if(!draft||!reviewed)return;setBusy(true);setError('');setStatus('Confirming reviewed contract data…');try{await apiFetch(`/api/organizations/${activeOrgId()}/contract-import/${encodeURIComponent(draft.id)}/confirm`,{method:'POST',body:JSON.stringify({reviewed:true,workerId:workerId||undefined,values})});setConfirmed(true);setStatus('Confirmed. OPSIQO created the contract profile and module prefill proposal. Core HR/compensation changes still require their normal authorized workflows.')}catch(e){setError(e instanceof Error?e.message:'Unable to confirm contract import.')}finally{setBusy(false)}}
 return <div className="stack contractImport">
  <header className="contractHero"><div className="eyebrow">Documents · governed intake</div><h1>Contract Import</h1><p className="muted">Import an employment contract, extract structured terms with source evidence, review every value, and create a controlled OPSIQO contract profile and module prefill proposal.</p></header>
  <section className="card stack"><div className="toolbar"><div><h3 className="sectionTitle">1. Import contract</h3><p className="muted">PDF, DOCX, TXT, RTF or Markdown · maximum 10 MB. The source is treated as untrusted evidence.</p></div><Link className="textLink" href="/compliance">Documents & compliance →</Link></div>
   <div className="contractDrop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files?.[0]||null)}}><input ref={inputRef} type="file" hidden accept=".pdf,.docx,.txt,.rtf,.md,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain,text/rtf,text/markdown" onChange={e=>choose(e.target.files?.[0]||null)}/><button className="button secondary" type="button" onClick={()=>inputRef.current?.click()}>Choose contract</button><span>{file?`${file.name} · ${fmtBytes(file.size)}`:'or drag and drop the contract here'}</span></div>
   {file&&<button className="button" disabled={busy} onClick={parse}>{busy?'Processing…':'Parse contract & prefill OPSIQO'}</button>}
   {(busy||stage>0)&&<div className="contractProgress" aria-live="polite"><div className="toolbar"><strong>{status}</strong><span>{stage}%</span></div><div className="contractProgressTrack"><span style={{width:`${stage}%`}}/></div></div>}
   {error&&<div className="error">{error}</div>}
  </section>
  {draft&&<><section className="card stack"><div className="toolbar"><div><div className="eyebrow">2. Verify extraction</div><h3 className="sectionTitle">{draft.fileName}</h3></div><div className={`contractConfidence ${draft.overallConfidence>=85?'high':draft.overallConfidence>=70?'medium':'low'}`}><strong>{draft.overallConfidence}%</strong><span>evidence confidence</span></div></div><div className="contractMeta"><span>Parser: <strong>{draft.parser==='governed_ai'?`Governed AI · ${draft.provider||''} ${draft.model||''}`:'Deterministic fallback'}</strong></span><span>SHA-256: <code>{draft.sha256.slice(0,16)}…</code></span><span>Extracted fields: <strong>{populated}/{CONTRACT_FIELD_KEYS.length}</strong></span><span>Scan: <strong>{draft.scanStatus.replace('_',' ')}</strong></span></div><p>{draft.summary}</p>{draft.warnings.length>0&&<div className="contractWarnings"><strong>Review warnings</strong>{draft.warnings.map((w,i)=><div key={`${w}-${i}`}>• {w}</div>)}</div>}</section>
   {GROUPS.map(g=><section className="card stack" key={g.title}><h3 className="sectionTitle">{g.title}</h3><div className="contractFields">{g.keys.map(k=>{const f=draft.fields[k],value=values[k]??'';return <label className="contractField" key={k}><div className="contractFieldHead"><strong>{LABELS[k]}</strong>{f?.value&&<span className={`contractEvidence ${confidenceClass(f.confidence)}`}>{Math.round(f.confidence*100)}%{f.verified?' · source verified':''}</span>}</div>{['terminationNotice','confidentiality','nonSolicitation','nonCompetition','intellectualProperty','benefits','overtimeTerms','bonusCommission','vacationEntitlement','schedule'].includes(k)?<textarea className="input contractTextarea" value={value} onChange={e=>setValues(v=>({...v,[k]:e.target.value}))}/>:<input className="input" value={value} onChange={e=>setValues(v=>({...v,[k]:e.target.value}))}/>} {f?.sourceSnippet&&<details><summary>Source evidence{f.sourcePage?` · page ${f.sourcePage}`:''}</summary><p className="contractSnippet">{f.sourceSnippet}</p></details>}</label>})}</div></section>)}
   <section className="card stack"><div><div className="eyebrow">3. Match & confirm</div><h3 className="sectionTitle">Controlled platform prefill</h3><p className="muted">Select the employee only when the contract belongs to an existing worker. OPSIQO never silently changes salary, title, status or other authoritative HR records from AI output.</p></div><label>Existing employee match<select className="input" value={workerId} onChange={e=>setWorkerId(e.target.value)}><option value="">No employee selected / new or unmatched contract</option>{draft.workerMatches.map(m=><option key={m.workerId} value={m.workerId}>{m.displayName}{m.employeeNumber?` · ${m.employeeNumber}`:''} · {Math.round(m.score*100)}% {m.reason}</option>)}</select></label><label className="checkLine contractReview"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/><span>I reviewed the extracted values against the contract and confirm that OPSIQO may create the contract profile and prefill proposal.</span></label><button className="button" disabled={!reviewed||busy||confirmed} onClick={confirm}>{confirmed?'Confirmed':busy?'Saving…':'Confirm reviewed import'}</button>{confirmed&&<div className="success">{status}</div>}</section></>}
 </div>
}
