'use client';
import { useEffect,useState } from 'react';
import type { AccessibilityReadinessDashboard,TranslationCoverageDashboard } from '@/domain/opsiqo-one-v7-16';
import { activeOrgId,apiFetch } from '@/lib/http/client';
import { LoadingState } from './data-states';

type Data={accessibility:AccessibilityReadinessDashboard;translation:TranslationCoverageDashboard};
export function ExperienceReadinessWorkspace(){const[data,setData]=useState<Data|null>(null),[error,setError]=useState('');useEffect(()=>{apiFetch<{data:Data}>(`/api/organizations/${activeOrgId()}/opsiqo-one/experience-readiness`).then(r=>setData(r.data)).catch(e=>setError(e instanceof Error?e.message:'Unable to load experience readiness evidence.'))},[]);if(!data)return <div className="stack">{error&&<div className="error" role="alert">{error}</div>}<LoadingState label="Loading accessibility and language evidence…"/></div>;return <div className="stack"><section className="card oneHero"><div><span className="eyebrow">OPSIQO ONE · Experience Readiness</span><h1>Accessibility and multilingual evidence</h1><p className="muted">Measure what is implemented and keep manual certification gaps visible instead of turning source-code checks into a false conformance claim.</p></div></section><div className="grid2"><section className="card stack"><h2 className="sectionTitle">Accessibility target</h2><div className="settingsGrid"><Metric label="Target" value={data.accessibility.target}/><Metric label="Implemented evidence" value={data.accessibility.implemented}/><Metric label="Manual review gates" value={data.accessibility.manualReviewRequired}/></div>{data.accessibility.evidence.map(x=><div className={`oneWorkItem ${x.status==='implemented'?'info':'medium'}`} key={x.criterion}><div><strong>{x.criterion}</strong><p className="muted">{x.evidence}</p></div><span className="badge">{x.status.replaceAll('_',' ')}</span></div>)}<div className="warning">{data.accessibility.certificationBoundary}</div></section><section className="card stack"><h2 className="sectionTitle">Language coverage</h2><p className="muted">Supported: {data.translation.supportedLocales.join(' · ')} · RTL: {data.translation.rtlLocales.join(' · ')}</p>{data.translation.surfaces.map(x=><div className="oneWorkItem info" key={x.id}><div><strong>{x.label}</strong></div><span className="badge">{x.coverage.replaceAll('_',' ')}</span></div>)}<div className="notice">AI response language preserves canonical evidence IDs, names, numbers, dates and source-language quotations.</div><div className="warning">{data.translation.boundary}</div></section></div></div>}
function Metric({label,value}:{label:string;value:number|string}){return <div className="card metricCard"><div className="metricLabel">{label}</div><div className="metricValue">{value}</div></div>}
