'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { activeOrgId, apiDownload, apiFetch } from '@/lib/http/client';

type Worker={id:string;displayName:string;employeeNumber?:string};
type Location={id:string;code:string;name:string;address?:string;latitude:number;longitude:number;radiusMeters:number;enabled:boolean;requireDeviceVerification:boolean;allowOfflineClock:boolean;requirePhotoProof:boolean};
type Shift={id:string;workerId:string;workerName?:string;title:string;startAt:string;endAt:string;locationId?:string;locationName?:string;status:string};
type Schedule={shifts:Shift[];locations:Location[];coverage:Array<{date:string;locationName:string;workers:number}>;overtimeForecast:Array<{workerId:string;workerName:string;weekStart?:string;scheduledHours:number;thresholdHours:number;projectedOvertimeHours:number}>};
type AttendanceRow={workerId:string;workerName:string;startAt:string;breakState:string;location?:string|null;latitude?:number;longitude?:number;insideGeofence?:boolean;integrityRisk?:string};
type Attendance={generatedAt:string;working:AttendanceRow[];onBreak:AttendanceRow[];count:number};
type Expense={id:string;workerId:string;workerName?:string;expenseDate:string;merchant?:string;category:string;currency:string;amount:number;businessPurpose:string;receipts:Array<{id:string;fileName:string}>;status:string;createdBy:string};

export function FrontlineOperationsPanel(){
 const[permissions,setPermissions]=useState<string[]>([]),[myWorkerId,setMyWorkerId]=useState(''),[workers,setWorkers]=useState<Worker[]>([]),[schedule,setSchedule]=useState<Schedule|null>(null),[attendance,setAttendance]=useState<Attendance|null>(null),[expenses,setExpenses]=useState<Expense[]>([]),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const can=(p:string)=>permissions.includes(p),canTimeManage=permissions.includes('time.manage')||permissions.includes('time.manage.team'),org=()=>activeOrgId(),browserTimezone=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';
 const load=async()=>{try{setError('');const me=await apiFetch<{actor:{permissions:string[];workerId?:string}}>('/api/me');setPermissions(me.actor.permissions);setMyWorkerId(me.actor.workerId||'');let people:Worker[]=[];if(me.actor.permissions.includes('time.manage')||me.actor.permissions.includes('time.manage.team')||me.actor.permissions.includes('people.read.private'))people=(await apiFetch<{data:Worker[]}>(`/api/organizations/${org()}/employees?pageSize=200`)).data;else if(me.actor.permissions.includes('team.read')){const team=(await apiFetch<{data:Array<{worker:Worker}>}>(`/api/organizations/${org()}/manager/team`)).data;people=team.map(x=>x.worker).filter(Boolean);}if(me.actor.workerId&&!people.some(x=>x.id===me.actor.workerId))people.unshift({id:me.actor.workerId,displayName:'My record'});setWorkers(people);const[s,a,e]=await Promise.all([apiFetch<{data:Schedule}>(`/api/organizations/${org()}/time/schedule`),apiFetch<{data:Attendance}>(`/api/organizations/${org()}/time/attendance-live`),me.actor.permissions.includes('expense.read')?apiFetch<{data:Expense[]}>(`/api/organizations/${org()}/expenses`):Promise.resolve({data:[] as Expense[]})]);setSchedule(s.data);setAttendance(a.data);setExpenses(e.data);}catch(e){setError(e instanceof Error?e.message:'Unable to load frontline operations.');}};
 useEffect(()=>{void load();const id=window.setInterval(()=>void load(),60000);return()=>window.clearInterval(id);},[]);
 const submit=async(path:string,method:string,body:any,message:string)=>{setBusy(path);setError('');setNotice('');try{await apiFetch(path,{method,body:body instanceof FormData?body:JSON.stringify(body)});setNotice(message);await load();}catch(e){setError(e instanceof Error?e.message:'Operation failed.');}finally{setBusy('');}};
 const uploadAttendancePhoto=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);await submit(`/api/organizations/${org()}/time/attendance-evidence`,'POST',f,'Attendance photo captured. It will be attached to the next clock event within 10 minutes.');form.reset();};
 const breakAction=(action:'start'|'end')=>submit(`/api/organizations/${org()}/time/breaks`,'POST',{action,paid:false},action==='start'?'Break started.':'Break ended and unpaid break minutes were added to the active time entry.');
 const createLocation=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await submit(`/api/organizations/${org()}/time/locations`,'POST',{code:f.get('code'),name:f.get('name'),address:f.get('address')||undefined,latitude:Number(f.get('latitude')),longitude:Number(f.get('longitude')),radiusMeters:Number(f.get('radiusMeters')||250),timezone:String(f.get('timezone')||browserTimezone),enabled:true,requireDeviceVerification:f.get('requireDeviceVerification')==='on',allowOfflineClock:f.get('allowOfflineClock')==='on',requirePhotoProof:f.get('requirePhotoProof')==='on'},'Work location and geofence created.');e.currentTarget.reset();};
 const createShift=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),local=(v:FormDataEntryValue|null)=>new Date(String(v)).toISOString();await submit(`/api/organizations/${org()}/time/schedule`,'POST',{workerId:f.get('workerId'),title:f.get('title'),startAt:local(f.get('startAt')),endAt:local(f.get('endAt')),locationId:f.get('locationId')||undefined,status:f.get('publish')==='on'?'published':'draft',note:f.get('note')||undefined},'Shift created.');e.currentTarget.reset();};
 const shiftAction=(id:string,action:'publish'|'cancel')=>submit(`/api/organizations/${org()}/time/schedule/${id}`,'PATCH',{action},`Shift ${action==='publish'?'published':'cancelled'}.`);
 const createExpense=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);f.set('receiptRequired','true');await submit(`/api/organizations/${org()}/expenses`,'POST',f,'Expense draft created with receipt evidence.');form.reset();};
 const expenseAction=(id:string,action:string)=>{const note=action==='reject'?window.prompt('Rejection reason')||'':'';if(action==='reject'&&!note)return;return submit(`/api/organizations/${org()}/expenses/${id}`,'PATCH',{action,note:note||undefined},`Expense ${action.replaceAll('_',' ')} completed.`);};
 const exportExpenses=async()=>{setError('');try{const end=new Date().toISOString().slice(0,10),start=new Date(Date.now()-90*86400000).toISOString().slice(0,10),r=await apiDownload(`/api/organizations/${org()}/expenses/export?periodStart=${start}&periodEnd=${end}`),url=URL.createObjectURL(r.blob),a=document.createElement('a');a.href=url;a.download=r.fileName||`opsiqo-expenses-${start}-${end}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:'Expense export failed.');}};
 const pins=useMemo(()=>[...(attendance?.working||[]),...(attendance?.onBreak||[])].filter(x=>Number.isFinite(x.latitude)&&Number.isFinite(x.longitude)),[attendance]);
 const bounds=useMemo(()=>{if(!pins.length)return null;const lats=pins.map(x=>x.latitude as number),lons=pins.map(x=>x.longitude as number);return{minLat:Math.min(...lats),maxLat:Math.max(...lats),minLon:Math.min(...lons),maxLon:Math.max(...lons)};},[pins]);
 return <div className="stack" data-h46-frontline="true">
  <section className="card stack"><div className="toolbar"><div><span className="eyebrow">H46 · Smart attendance</span><h2 className="sectionTitle">Frontline operations control</h2><p className="muted">Geofenced attendance, live status, explicit breaks, scheduling, overtime forecasting and governed expenses. Location evidence is collected only when an approved policy requires it.</p></div><button className="secondaryButton compact" onClick={()=>load()}>Refresh live data</button></div>{notice&&<div className="notice">{notice}</div>}{error&&<div className="error">{error}</div>}<div className="grid4"><Metric label="Working now" value={attendance?.working.length||0}/><Metric label="On break" value={attendance?.onBreak.length||0}/><Metric label="Published shifts" value={schedule?.shifts.filter(x=>x.status==='published').length||0}/><Metric label="OT watch" value={schedule?.overtimeForecast.length||0}/></div></section>
  <section className="card stack"><div className="toolbar"><div><h2 className="sectionTitle">Live attendance map</h2><span className="muted">Privacy-bounded location evidence for employees currently clocked in. This view does not continuously track employees outside attendance events.</span></div><span className="badge">Updated {attendance?new Date(attendance.generatedAt).toLocaleTimeString():'—'}</span></div>{pins.length&&bounds?<div style={{position:'relative',height:260,border:'1px solid var(--border)',borderRadius:12,overflow:'hidden',background:'linear-gradient(135deg,rgba(127,127,127,.05),rgba(127,127,127,.12))'}}>{pins.map(p=>{const x=bounds.maxLon===bounds.minLon?50:((p.longitude!-bounds.minLon)/(bounds.maxLon-bounds.minLon))*88+6,y=bounds.maxLat===bounds.minLat?50:(1-(p.latitude!-bounds.minLat)/(bounds.maxLat-bounds.minLat))*82+9;return <div key={p.workerId} title={`${p.workerName} · ${p.integrityRisk||'none'} risk`} style={{position:'absolute',left:`${x}%`,top:`${y}%`,transform:'translate(-50%,-50%)',padding:'6px 8px',borderRadius:999,border:'1px solid currentColor',background:'var(--surface)',fontSize:12,maxWidth:160,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{p.breakState==='on_break'?'☕':'●'} {p.workerName}</div>})}</div>:<div className="emptyState">No clocked-in employee has map-ready location evidence right now.</div>}<div className="tableWrap"><table><thead><tr><th>Employee</th><th>Status</th><th>Clock in</th><th>Geofence</th><th>Integrity</th></tr></thead><tbody>{[...(attendance?.working||[]),...(attendance?.onBreak||[])].map(p=><tr key={p.workerId}><td>{p.workerName}</td><td>{p.breakState.replaceAll('_',' ')}</td><td>{new Date(p.startAt).toLocaleString()}</td><td>{p.insideGeofence===true?'Inside':p.insideGeofence===false?'Outside':'Not evaluated'}</td><td>{p.integrityRisk||'none'}</td></tr>)}</tbody></table></div>{myWorkerId&&<><div className="stepActions"><button className="secondaryButton" disabled={busy!==''} onClick={()=>breakAction('start')}>Start unpaid break</button><button className="secondaryButton" disabled={busy!==''} onClick={()=>breakAction('end')}>End break</button></div><form className="formGrid" onSubmit={uploadAttendancePhoto} encType="multipart/form-data"><label className="field"><span>Optional attendance photo proof</span><input className="input" name="file" type="file" accept="image/jpeg,image/png" capture="user" required/></label><button className="secondaryButton">Capture photo for next clock event</button><div className="muted">Photo evidence is stored privately and is not analyzed for facial characteristics, emotion or personality.</div></form></>}</section>
  <section className="card stack"><div className="toolbar"><div><h2 className="sectionTitle">Shift scheduling & overtime forecast</h2><span className="muted">Managers publish shifts; OPSIQO highlights projected overtime and coverage gaps but does not assign or cancel shifts autonomously.</span></div></div>{schedule?.overtimeForecast.length?<div className="notice"><strong>Overtime watch:</strong> {schedule.overtimeForecast.map(x=>`${x.workerName}${x.weekStart?` · week ${x.weekStart}`:''} ${x.scheduledHours}h / ${x.thresholdHours}h${x.projectedOvertimeHours?` (+${x.projectedOvertimeHours}h projected OT)`:''}`).join(' · ')}</div>:<div className="notice">No employee is currently within the overtime watch band for the visible schedule.</div>}{canTimeManage&&<form className="formGrid" onSubmit={createShift}><label className="field"><span>Employee</span><select className="input" name="workerId" required>{workers.map(w=><option key={w.id} value={w.id}>{w.displayName}</option>)}</select></label><Field label="Shift title" name="title"/><Field label="Start" name="startAt" type="datetime-local"/><Field label="End" name="endAt" type="datetime-local"/><label className="field"><span>Location</span><select className="input" name="locationId"><option value="">Remote / unspecified</option>{schedule?.locations.filter(x=>x.enabled).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><Field label="Note" name="note" required={false}/><label className="checkRow"><input type="checkbox" name="publish"/> Publish immediately</label><button className="button">Create shift</button></form>}<div className="tableWrap"><table><thead><tr><th>Employee</th><th>Shift</th><th>When</th><th>Location</th><th>Status</th><th></th></tr></thead><tbody>{schedule?.shifts.map(s=><tr key={s.id}><td>{s.workerName||s.workerId}</td><td>{s.title}</td><td>{new Date(s.startAt).toLocaleString()} → {new Date(s.endAt).toLocaleString()}</td><td>{s.locationName||'—'}</td><td>{s.status}</td><td>{canTimeManage&&s.status!=='cancelled'&&<div className="stepActions">{s.status==='draft'&&<button className="smallButton" onClick={()=>shiftAction(s.id,'publish')}>Publish</button>}<button className="smallButton" onClick={()=>shiftAction(s.id,'cancel')}>Cancel</button></div>}</td></tr>)}</tbody></table></div></section>
  {can('time.configure')&&<section className="card stack"><h2 className="sectionTitle">Work locations & geofences</h2><div className="notice">Geofencing is not activated merely by creating a location. The active Time Policy must enable geolocation/geofence mode and reference a published electronic-monitoring policy.</div><form className="formGrid" onSubmit={createLocation}><Field label="Code" name="code"/><Field label="Location name" name="name"/><Field label="Address" name="address" required={false}/><Field label="Latitude" name="latitude" type="number"/><Field label="Longitude" name="longitude" type="number"/><Field label="Radius metres" name="radiusMeters" type="number" value="250"/><Field label="Time zone" name="timezone" value={browserTimezone}/><label className="checkRow"><input type="checkbox" name="requireDeviceVerification"/> Require device verification</label><label className="checkRow"><input type="checkbox" name="allowOfflineClock"/> Permit governed offline sync</label><label className="checkRow"><input type="checkbox" name="requirePhotoProof"/> Require attendance photo proof</label><button className="button">Create geofence</button></form><div className="tableWrap"><table><thead><tr><th>Code</th><th>Location</th><th>Radius</th><th>Device verification</th><th>Offline</th><th>Photo proof</th></tr></thead><tbody>{schedule?.locations.map(l=><tr key={l.id}><td>{l.code}</td><td>{l.name}<div className="muted">{l.address}</div></td><td>{l.radiusMeters}m</td><td>{l.requireDeviceVerification?'Required':'Optional'}</td><td>{l.allowOfflineClock?'Allowed by location':'No'}</td><td>{l.requirePhotoProof?'Required':'Optional'}</td></tr>)}</tbody></table></div></section>}
  {can('expense.read')&&<section className="card stack"><div><span className="eyebrow">H46 · Expenses</span><h2 className="sectionTitle">Expense & reimbursement</h2>{can('expense.manage')&&<button type="button" className="secondaryButton compact" onClick={()=>exportExpenses()}>Export last 90 days CSV</button>}<p className="muted">Receipt-backed claims with duplicate-receipt detection, manager review, independent finance approval and payment state.</p></div>{can('expense.request')&&<form className="formGrid" onSubmit={createExpense} encType="multipart/form-data"><Field label="Expense date" name="expenseDate" type="date"/><Field label="Merchant" name="merchant" required={false}/><label className="field"><span>Category</span><select className="input" name="category"><option>Travel</option><option>Meals</option><option>Supplies</option><option>Training</option><option>Parking</option><option>Other</option></select></label><Field label="Currency" name="currency" value="CAD"/><Field label="Amount" name="amount" type="number"/><Field label="Tax" name="taxAmount" type="number" required={false}/><Field label="Project code" name="projectCode" required={false}/><Field label="Cost centre" name="costCenter" required={false}/><label className="field"><span>Business purpose</span><textarea className="input" name="businessPurpose" rows={3} required/></label><label className="field"><span>Receipt evidence (PDF/JPG/PNG; up to 5)</span><input className="input" name="receipts" type="file" accept="application/pdf,image/jpeg,image/png" multiple required capture="environment"/></label><button className="button">Create expense draft</button></form>}<div className="tableWrap"><table><thead><tr><th>Employee</th><th>Date</th><th>Expense</th><th>Receipt</th><th>Status</th><th>Governed action</th></tr></thead><tbody>{expenses.map(x=><tr key={x.id}><td>{x.workerName||x.workerId}</td><td>{x.expenseDate}</td><td>{x.merchant||x.category}<div>{x.currency} {x.amount.toFixed(2)}</div></td><td>{x.receipts.length?x.receipts.map(r=>r.fileName).join(', '):'Missing'}</td><td>{x.status.replaceAll('_',' ')}</td><td><div className="stepActions">{x.workerId===myWorkerId&&x.status==='draft'&&<button className="smallButton" onClick={()=>expenseAction(x.id,'submit')}>Submit</button>}{can('expense.approve')&&x.workerId!==myWorkerId&&x.status==='submitted'&&<><button className="smallButton" onClick={()=>expenseAction(x.id,'manager_approve')}>Manager approve</button><button className="smallButton" onClick={()=>expenseAction(x.id,'reject')}>Reject</button></>}{can('expense.manage')&&x.status==='manager_approved'&&<button className="smallButton" onClick={()=>expenseAction(x.id,'finance_approve')}>Finance approve</button>}{can('expense.manage')&&x.status==='finance_approved'&&<button className="smallButton" onClick={()=>expenseAction(x.id,'mark_paid')}>Mark paid</button>}</div></td></tr>)}</tbody></table></div></section>}
 </div>;
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="metricCard"><span>{label}</span><strong>{value}</strong></div>}
function Field({label,name,type='text',required=true,value}:{label:string;name:string;type?:string;required?:boolean;value?:string}){return <label className="field"><span>{label}</span><input className="input" name={name} type={type} required={required} defaultValue={value} step={type==='number'?'any':undefined}/></label>}
