'use client';
import Link from 'next/link';
import { FormEvent,useEffect,useState,useRef } from 'react';
import { useLegacySurfaceTranslation } from '@/lib/opsiqo-one/legacy-surface-i18n';
import type { OpsiQoOneOverview } from '@/domain/opsiqo-one';
import type { NaturalAnalyticsAnswer } from '@/domain/opsiqo-one-v7-11';
import { activeOrgId,apiFetch,isMfaRequiredError } from '@/lib/http/client';
import { mfaSetupHref } from '@/lib/auth/mfa-client';

export function IntelligenceHubWorkspace(){
 const translationRoot=useRef<HTMLDivElement>(null);useLegacySurfaceTranslation('intelligence_hub',translationRoot);
 const[data,setData]=useState<OpsiQoOneOverview|null>(null),[error,setError]=useState(''),[mfa,setMfa]=useState(false),[question,setQuestion]=useState('Compare headcount, turnover and vacancies'),[analytics,setAnalytics]=useState<NaturalAnalyticsAnswer|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;apiFetch<{data:OpsiQoOneOverview}>(`/api/organizations/${activeOrgId()}/opsiqo-one/overview`).then(r=>{if(alive)setData(r.data)}).catch(e=>{if(!alive)return;if(isMfaRequiredError(e))setMfa(true);else setError(e instanceof Error?e.message:'Unable to load Intelligence.')});return()=>{alive=false}},[]);
 if(mfa)return <section className="card stack"><h2 className="sectionTitle">Multi-factor authentication required</h2><p className="muted">Privileged intelligence is withheld until MFA is satisfied.</p><div><Link className="button" href={mfaSetupHref('/intelligence')}>Set up MFA</Link></div></section>;
 if(!data)return <section className="card">{error?<div className="error">{error}</div>:<div className="loadingState"><div className="loadingDot"/><div><strong>Connecting OPSIQO intelligence</strong><small>Loading Cortex capabilities and the permission-scoped organization graph.</small></div></div>}</section>;
 const g=data.knowledgeGraph;
 const askAnalytics=async(e:FormEvent)=>{e.preventDefault();if(question.trim().length<3)return;setBusy(true);setError('');try{const r=await apiFetch<{data:NaturalAnalyticsAnswer}>(`/api/organizations/${activeOrgId()}/opsiqo-one/analytics`,{method:'POST',body:JSON.stringify({question})});setAnalytics(r.data)}catch(err){setError(err instanceof Error?err.message:'Unable to analyze workforce evidence.')}finally{setBusy(false)}};
 return <div ref={translationRoot} className="stack" data-opsiqo-one="intelligence">
   <section className="card oneHero"><div><span className="eyebrow">OPSIQO ONE · Intelligence</span><h1>One intelligence layer across the workforce</h1><p className="muted">Cortex coordinates specialized capabilities while OPSIQO Guard limits every action to governed evidence, permissions and human oversight.</p></div><div className="row wrap"><Link className="button" href="/ai-copilot">Ask with evidence</Link><Link className="button secondary" href="/ai-governance">AI Governance</Link><Link className="button secondary" href="/compliance-radar">Compliance Radar</Link><Link className="button secondary" href="/scenario-lab">Scenario Lab</Link></div></section>
   {data.cortexAgents.some(a=>a.id==='analytics')&&<section className="card"><div className="toolbar"><div><h2 className="sectionTitle">Natural-language analytics</h2><p className="muted">Ask about governed aggregate headcount, FTE, employer-cost estimates, turnover, vacancies or verified skill gaps. No individual risk scoring is used.</p></div></div><form className="row wrap analyticsAsk" onSubmit={askAnalytics}><label className="srOnly" htmlFor="natural-analytics-question">Analytics question</label><input id="natural-analytics-question" className="input grow" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Compare turnover and vacancies"/><button className="button" disabled={busy||question.trim().length<3}>{busy?'Analyzing…':'Analyze'}</button></form>{analytics&&<div className="analyticsAnswer"><strong>{analytics.summary}</strong><div className="metricGrid">{analytics.metrics.map(m=><div className="metricCard" key={m.key}><span>{m.label}</span><strong>{m.value}{m.unit==='percent'?'%':''}</strong><small>{m.change===undefined?m.helper:`${m.change>=0?'+':''}${m.change} vs prior snapshot · ${m.helper}`}</small><code>{m.evidenceRef}</code></div>)}</div><p className="muted">Data quality {analytics.dataQualityScore}% · {analytics.historyPoints} history point(s){analytics.warnings.length?` · ${analytics.warnings.join(' · ')}`:''}</p><small>{analytics.governanceNotice}</small></div>}</section>}
   <section className="card"><div className="toolbar"><div><h2 className="sectionTitle">Advanced OPSIQO ONE intelligence</h2><p className="muted">Use specialist experiences when you need deeper evidence while keeping the five primary outcome surfaces stable.</p></div></div><div className="hubGrid compactHub"><Link className="agentCard" href="/skills-passport"><strong>Skills Passport</strong><p>Separate verified evidence from self-reported skills and current-role gaps.</p><span>→</span></Link><Link className="agentCard" href="/career-gps"><strong>Career GPS</strong><p>Translate target-role evidence into a transparent development roadmap.</p><span>→</span></Link><Link className="agentCard" href="/talent-marketplace"><strong>Talent Marketplace</strong><p>Explore internal opportunities without employee-to-employee ranking.</p><span>→</span></Link><Link className="agentCard" href="/scenario-lab"><strong>Scenario Lab</strong><p>Compare deterministic workforce scenarios against the current baseline.</p><span>→</span></Link><Link className="agentCard" href="/ai-value"><strong>AI Value</strong><p>Measure real AI activity, blocks, plans and evidence quality without fake ROI.</p><span>→</span></Link></div></section>
   <section className="card"><div className="toolbar"><div><h2 className="sectionTitle">Organization Knowledge Graph</h2><p className="muted">Current {g.scope}-scoped relationships available to this membership. Sensitive HR fields are excluded.</p></div><span className="badge">{g.truncated?'bounded view':'current view'}</span></div><div className="metricGrid"><div className="metricCard"><span>People</span><strong>{g.counts.workers}</strong></div><div className="metricCard"><span>Positions</span><strong>{g.counts.positions}</strong></div><div className="metricCard"><span>Org units</span><strong>{g.counts.orgUnits}</strong></div><div className="metricCard"><span>Skills</span><strong>{g.counts.skills}</strong></div><div className="metricCard"><span>Projects</span><strong>{g.counts.projects}</strong></div><div className="metricCard"><span>Funding</span><strong>{g.counts.fundingSources}</strong></div><div className="metricCard"><span>Policies</span><strong>{g.counts.policies}</strong></div><div className="metricCard"><span>Knowledge</span><strong>{g.counts.knowledgeArticles}</strong></div><div className="metricCard"><span>Workflows</span><strong>{g.counts.workflows}</strong></div><div className="metricCard"><span>Courses</span><strong>{g.counts.courses}</strong></div><div className="metricCard"><span>Learning paths</span><strong>{g.counts.learningPaths}</strong></div><div className="metricCard"><span>Compliance requirements</span><strong>{g.counts.complianceRequirements}</strong></div><div className="metricCard"><span>Onboarding links</span><strong>{g.counts.onboardingTasks}</strong></div><div className="metricCard"><span>Relationships</span><strong>{g.counts.relationships}</strong></div></div><div className="graphPreview">{g.edges.slice(0,10).map(edge=><div className="graphEdge" key={edge.id}><span>{g.nodes.find(n=>n.id===edge.from)?.label||edge.from}</span><strong>{edge.label}</strong><span>{g.nodes.find(n=>n.id===edge.to)?.label||edge.to}</span></div>)}{!g.edges.length&&<div className="emptyState"><div><strong>No relationship evidence available</strong><p>The graph does not invent relationships when accessible source records are absent.</p></div></div>}</div><p className="muted">{g.privacyNote}</p></section>
   <section className="card"><div className="toolbar"><div><h2 className="sectionTitle">OPSIQO Cortex</h2><p className="muted">One OPSIQO experience; specialized agents become available only when their source permissions are present.</p></div><span className="badge">{data.cortexAgents.length} available</span></div><div className="agentGrid">{data.cortexAgents.map(agent=><article className="agentCard" key={agent.id}><div className="row wrap"><span className="agentGlyph" aria-hidden="true">✦</span><strong>{agent.name}</strong><span className={`actionLevel level-${agent.maxActionLevel}`}>{agent.maxActionLevel}</span></div><p>{agent.purpose}</p><div className="agentCapabilities">{agent.capabilities.map(cap=><span key={cap}>{cap}</span>)}</div><small>{agent.humanOversight?'Human oversight retained':'Automated'}</small></article>)}</div></section>
   <section className="card"><h2 className="sectionTitle">AI Action Safety Model</h2><div className="safetyLevelGrid">{data.safetyModel.map(item=><div className={`safetyLevel level-${item.level}`} key={item.level}><span className="actionLevel">{item.level}</span><strong>{item.meaning}</strong><p>{item.humanControl}</p></div>)}</div></section>
 </div>;
}
