'use client';
import { useEffect, useMemo, useState } from 'react';
import { activeOrgId, apiFetch } from '@/lib/http/client';
import type { ActorContext } from '@/domain/security';
import type { LearningAssignment, LearningCourseView, LearningDashboard } from '@/domain/learning';
import { LoadingState } from '@/components/data-states';

type Tab='overview'|'skills'|'gaps'|'catalog'|'assignments'|'certificates'|'setup';
const due30=()=>new Date(Date.now()+30*86400000).toISOString();
export function LearningWorkspace(){
 const[data,setData]=useState<LearningDashboard|null>(null);const[actor,setActor]=useState<ActorContext|null>(null);const[tab,setTab]=useState<Tab>('overview');const[error,setError]=useState('');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
 const load=async()=>{setError('');try{const[d,m]=await Promise.all([apiFetch<{data:LearningDashboard}>(`/api/organizations/${activeOrgId()}/learning/dashboard`),apiFetch<{actor:ActorContext}>('/api/me')]);setData(d.data);setActor(m.actor);}catch(e){setError(e instanceof Error?e.message:'Unable to load skills and learning workspace.');}};
 useEffect(()=>{load();const h=()=>load();window.addEventListener('opsiqo:organization-changed',h);return()=>window.removeEventListener('opsiqo:organization-changed',h);},[]);
 async function call(path:string,init:RequestInit){setBusy(true);setError('');setMsg('');try{await apiFetch(path,init);setMsg('Saved successfully.');await load();}catch(e){setError(e instanceof Error?e.message:'Action failed.');}finally{setBusy(false);}}
 if(!data||!actor)return <div className="stack">{error&&<div className="error">{error}</div>}<LoadingState label="Loading skills, learning and compliance evidence…"/></div>;
 const name=(id:string)=>data.workerDirectory.find(w=>w.id===id)?.displayName||id;const course=(id:string)=>data.courses.find(c=>c.id===id);
 return <div className="stack">{error&&<div className="error">{error}</div>}{msg&&<div className="success">{msg}</div>}
  <div className="learningHero"><div><div className="eyebrow">Phase 3 · Skills Intelligence</div><h2>Skills → gaps → learning → verified evidence</h2><p>Self-reported proficiency stays distinct from verified evidence and course-earned capability.</p></div><div className="performanceHeroScore"><span>Scope</span><strong>{data.scope}</strong><small>Generated {new Date(data.generatedAt).toLocaleString()}</small></div></div>
  <div className="tabBar">{(['overview','skills','gaps','catalog','assignments','certificates','setup'] as Tab[]).map(t=><button key={t} className={tab===t?'tab active':'tab'} onClick={()=>setTab(t)}>{t[0]!.toUpperCase()+t.slice(1)}</button>)}</div>
  {tab==='overview'&&<Overview data={data} name={name} course={course}/>} 
  {tab==='skills'&&<Skills data={data} actor={actor} name={name} busy={busy} call={call}/>} 
  {tab==='gaps'&&<Gaps data={data} name={name} course={course} busy={busy} call={call}/>} 
  {tab==='catalog'&&<Catalog data={data} actor={actor} course={course} busy={busy} call={call}/>} 
  {tab==='assignments'&&<Assignments data={data} actor={actor} name={name} course={course} busy={busy} call={call}/>} 
  {tab==='certificates'&&<Certificates data={data} name={name} course={course}/>} 
  {tab==='setup'&&<Setup data={data} actor={actor} busy={busy} call={call}/>} 
 </div>;
}
function Overview({data,name,course}:{data:LearningDashboard;name:(id:string)=>string;course:(id:string)=>LearningCourseView|undefined}){return <>
 <div className="grid4">{data.metrics.map(m=><div className="card metricCard" key={m.key}><div className="metricLabel">{m.label}</div><div className="metricValue">{m.value}</div><div className="metricFoot">{m.helper}</div></div>)}</div>
 <div className="grid2"><section className="card"><h2 className="sectionTitle">Highest-priority skill gaps</h2><div className="gapList">{data.gaps.sort((a,b)=>b.gap-a.gap).slice(0,8).map(g=><div className={`gapCard ${g.criticality}`} key={`${g.workerId}_${g.skillId}`}><div><strong>{g.skillName}</strong><span>{name(g.workerId)} · reported L{g.currentLevel} · verified L{g.verifiedLevel} → required L{g.requiredLevel}</span></div><b>Gap {g.gap}</b></div>)}{!data.gaps.length&&<p className="muted">No current position-skill gaps in scope.</p>}</div></section>
 <section className="card"><h2 className="sectionTitle">Learning safeguards</h2><div className="securityChecklist"><div>✓ Self-reported skills remain visibly unverified</div><div>✓ Position requirements drive gap calculations</div><div>✓ Assessments use the assigned question set exactly</div><div>✓ Course completion can issue verifiable certificates</div><div>✓ Certificate expiry can expire course-derived skills</div><div>✓ Learning changes write central audit evidence</div></div></section></div>
 <section className="card tableWrap"><h2 className="sectionTitle">Active learning queue</h2><table><thead><tr><th>Employee</th><th>Course</th><th>Status</th><th>Progress</th><th>Due</th></tr></thead><tbody>{data.assignments.filter(a=>['assigned','in_progress'].includes(a.status)).slice(0,20).map(a=><tr key={a.id}><td>{name(a.workerId)}</td><td>{course(a.courseId)?.title||a.courseId}</td><td><span className="badge">{a.status.replaceAll('_',' ')}</span></td><td>{a.progressPct}%</td><td>{a.dueAt?new Date(a.dueAt).toLocaleDateString():'—'}</td></tr>)}{!data.assignments.length&&<tr><td colSpan={5} className="muted">No learning assignments in scope.</td></tr>}</tbody></table></section>
 </>}
function Skills({data,actor,name,busy,call}:{data:LearningDashboard;actor:ActorContext;name:(id:string)=>string;busy:boolean;call:(p:string,i:RequestInit)=>Promise<void>}){const[workerId,setWorkerId]=useState(actor.workerId||data.workerDirectory[0]?.id||'');const[skillId,setSkillId]=useState(data.skills[0]?.id||'');const[level,setLevel]=useState(3);const[evidence,setEvidence]=useState('');const canVerify=(actor.permissions.includes('learning.verify')||actor.permissions.includes('learning.verify.team'));const rows=data.workerSkills.filter(s=>!workerId||s.workerId===workerId);return <div className="stack"><section className="card"><h2 className="sectionTitle">Record skill proficiency</h2><div className="learningForm"><label>Employee<select className="input" value={workerId} onChange={e=>setWorkerId(e.target.value)}>{data.workerDirectory.map(w=><option key={w.id} value={w.id}>{w.displayName}</option>)}</select></label><label>Skill<select className="input" value={skillId} onChange={e=>setSkillId(e.target.value)}>{data.skills.map(s=><option key={s.id} value={s.id}>{s.code} · {s.name}</option>)}</select></label><label>Level<select className="input" value={level} onChange={e=>setLevel(Number(e.target.value))}>{[1,2,3,4,5].map(v=><option key={v}>{v}</option>)}</select></label><label className="grow2">Evidence<input className="input" value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Observable evidence, assessment, credential or work sample"/></label><button className="button secondary" disabled={busy||!workerId||!skillId} onClick={()=>call(`/api/organizations/${activeOrgId()}/learning/skills/workers/${workerId}`,{method:'POST',body:JSON.stringify({skillId,level,evidenceNote:evidence||undefined,action:'claim'})})}>Self-report / claim</button>{canVerify&&<button className="button" disabled={busy||!workerId||!skillId} onClick={()=>call(`/api/organizations/${activeOrgId()}/learning/skills/workers/${workerId}`,{method:'POST',body:JSON.stringify({skillId,level,evidenceNote:evidence||undefined,action:'verify'})})}>Verify skill</button>}</div></section>
 <section className="card tableWrap"><h2 className="sectionTitle">Skill evidence</h2><table><thead><tr><th>Employee</th><th>Skill</th><th>Level</th><th>Verification</th><th>Source</th><th>Evidence</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td>{name(s.workerId)}</td><td>{data.skills.find(x=>x.id===s.skillId)?.name||s.skillId}</td><td><strong>L{s.level}</strong></td><td><span className="badge">{s.status.replaceAll('_',' ')}</span></td><td>{s.source}</td><td>{s.evidenceNote||'—'}</td></tr>)}</tbody></table></section></div>}
function Gaps({data,name,course,busy,call}:{data:LearningDashboard;name:(id:string)=>string;course:(id:string)=>LearningCourseView|undefined;busy:boolean;call:(p:string,i:RequestInit)=>Promise<void>}){return <section className="card tableWrap"><h2 className="sectionTitle">Position-to-person skill gap analysis</h2><table><thead><tr><th>Employee</th><th>Skill</th><th>Criticality</th><th>Reported</th><th>Verified</th><th>Required</th><th>Gap</th><th>Recommended learning</th></tr></thead><tbody>{data.gaps.map(g=><tr key={`${g.workerId}_${g.skillId}`}><td>{name(g.workerId)}</td><td><strong>{g.skillName}</strong><div className="muted">{g.verificationStatus?.replaceAll('_',' ')||'no evidence'}</div></td><td><span className="badge">{g.criticality}</span></td><td>L{g.currentLevel}</td><td>L{g.verifiedLevel}</td><td>L{g.requiredLevel}</td><td><strong>{g.gap}</strong></td><td>{g.recommendedCourseIds.length?<div className="recommendationStack">{g.recommendedCourseIds.slice(0,2).map(id=><div key={id}><span>{course(id)?.title||id}</span><button className="button compact" disabled={busy} onClick={()=>call(`/api/organizations/${activeOrgId()}/learning/assignments`,{method:'POST',body:JSON.stringify({workerId:g.workerId,courseId:id,reason:'skill_gap',dueAt:due30()})})}>Assign</button></div>)}</div>:<span className="muted">No published course currently closes this gap.</span>}</td></tr>)}</tbody></table></section>}
function Catalog({data,actor,busy,call}:{data:LearningDashboard;actor:ActorContext;course:(id:string)=>LearningCourseView|undefined;busy:boolean;call:(p:string,i:RequestInit)=>Promise<void>}){const canManage=actor.permissions.includes('learning.manage');return <div className="stack"><section className="card"><h2 className="sectionTitle">Learning catalog</h2><div className="courseGrid">{data.courses.map(c=><article className="courseCard" key={c.id}><div className="rowBetween"><span className="badge">{c.status}</span><small>{c.durationMinutes} min</small></div><h3>{c.title}</h3><p>{c.description||'No description.'}</p><div className="competencyChips">{c.skillMappings.map(m=><span key={m.skillId}>{data.skills.find(s=>s.id===m.skillId)?.code||m.skillId} → L{m.targetLevel}</span>)}</div><div className="courseFoot"><span>{c.assessmentQuestions.length?`${c.assessmentQuestions.length} assessment question(s)`:'Evidence-based completion'}</span>{canManage&&c.status==='draft'&&<button className="button compact" disabled={busy} onClick={()=>call(`/api/organizations/${activeOrgId()}/learning/courses/${c.id}`,{method:'PATCH',body:JSON.stringify({action:'publish'})})}>Publish</button>}</div></article>)}</div></section><section className="card"><h2 className="sectionTitle">Learning paths</h2><div className="pathList">{data.paths.map(p=><div key={p.id}><strong>{p.title}</strong><span>{p.courseIds.length} course(s) · {p.status}</span></div>)}</div></section></div>}
function Assignments({data,actor,name,course,busy,call}:{data:LearningDashboard;actor:ActorContext;name:(id:string)=>string;course:(id:string)=>LearningCourseView|undefined;busy:boolean;call:(p:string,i:RequestInit)=>Promise<void>}){const[workerId,setWorkerId]=useState(actor.workerId||data.workerDirectory[0]?.id||'');const[courseId,setCourseId]=useState(data.courses.find(c=>c.status==='published')?.id||'');const[pathId,setPathId]=useState(data.paths.find(p=>p.status==='published')?.id||'');const[answers,setAnswers]=useState<Record<string,number>>({});const canAssign=actor.permissions.includes('learning.assign');return <div className="stack">{(canAssign||actor.permissions.includes('learning.self_assign'))&&<section className="card"><h2 className="sectionTitle">Assign learning</h2><div className="learningAssignForm"><label>Employee<select className="input" value={workerId} onChange={e=>setWorkerId(e.target.value)}>{data.workerDirectory.map(w=><option key={w.id} value={w.id}>{w.displayName}</option>)}</select></label><label>Published course<select className="input" value={courseId} onChange={e=>setCourseId(e.target.value)}>{data.courses.filter(c=>c.status==='published').map(c=><option key={c.id} value={c.id}>{c.code} · {c.title}</option>)}</select></label><button className="button" disabled={busy||!workerId||!courseId} onClick={()=>call(`/api/organizations/${activeOrgId()}/learning/assignments`,{method:'POST',body:JSON.stringify({workerId,courseId,reason:actor.workerId===workerId?'self':'manager',dueAt:due30()})})}>Assign course</button><label>Learning path<select className="input" value={pathId} onChange={e=>setPathId(e.target.value)}><option value="">Select path</option>{data.paths.filter(p=>p.status==='published').map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><button className="button secondary" disabled={busy||!workerId||!pathId} onClick={()=>call(`/api/organizations/${activeOrgId()}/learning/path-assignments`,{method:'POST',body:JSON.stringify({workerId,pathId,reason:actor.workerId===workerId?'self':'manager',dueAt:due30()})})}>Assign path</button></div></section>}
 <section className="card tableWrap"><h2 className="sectionTitle">Learning assignments</h2><table><thead><tr><th>Employee</th><th>Course</th><th>Status</th><th>Progress</th><th>Score</th><th>Action</th></tr></thead><tbody>{data.assignments.map(a=>{const c=course(a.courseId),canAct=actor.workerId===a.workerId||canAssign;return <tr key={a.id}><td>{name(a.workerId)}</td><td><strong>{c?.title||a.courseId}</strong><div className="muted">{a.reason}</div></td><td><span className="badge">{a.status.replaceAll('_',' ')}</span></td><td>{a.progressPct}%</td><td>{a.scorePct??'—'}</td><td>{canAct&&['assigned','in_progress','failed'].includes(a.status)&&<AssignmentActions assignment={a} course={c} answers={answers} setAnswers={setAnswers} busy={busy} call={call}/>}</td></tr>})}</tbody></table></section></div>}
function AssignmentActions({assignment,course,answers,setAnswers,busy,call}:{assignment:LearningAssignment;course?:LearningCourseView;answers:Record<string,number>;setAnswers:(x:Record<string,number>)=>void;busy:boolean;call:(p:string,i:RequestInit)=>Promise<void>}){if(!course)return null;if(assignment.status==='assigned')return <button className="button compact" disabled={busy} onClick={()=>call(`/api/organizations/${activeOrgId()}/learning/assignments/${assignment.id}`,{method:'PATCH',body:JSON.stringify({action:'start'})})}>Start</button>;if(course.assessmentQuestions.length)return <div className="assessmentMini">{course.assessmentQuestions.map(q=><label key={q.id}>{q.prompt}<select className="input" value={answers[`${assignment.id}_${q.id}`]??0} onChange={e=>setAnswers({...answers,[`${assignment.id}_${q.id}`]:Number(e.target.value)})}>{q.options.map((o,i)=><option key={i} value={i}>{o}</option>)}</select></label>)}<button className="button compact" disabled={busy} onClick={()=>call(`/api/organizations/${activeOrgId()}/learning/assignments/${assignment.id}`,{method:'PATCH',body:JSON.stringify({action:'submit_assessment',answers:course.assessmentQuestions.map(q=>({questionId:q.id,selectedOption:answers[`${assignment.id}_${q.id}`]??0}))})})}>Submit assessment</button></div>;return <span className="muted">Completion requires authorized evidence verification.</span>}
function Certificates({data,name,course}:{data:LearningDashboard;name:(id:string)=>string;course:(id:string)=>LearningCourseView|undefined}){return <section className="card tableWrap"><h2 className="sectionTitle">Certificates & renewal evidence</h2><table><thead><tr><th>Employee</th><th>Credential</th><th>Certificate #</th><th>Status</th><th>Issued</th><th>Expires</th><th>Verification</th></tr></thead><tbody>{data.certificates.map(c=><tr key={c.id}><td>{name(c.workerId)}</td><td>{course(c.courseId)?.title||c.courseId}</td><td>{c.certificateNumber}</td><td><span className="badge">{c.status}</span></td><td>{new Date(c.issuedAt).toLocaleDateString()}</td><td>{c.expiresAt?new Date(c.expiresAt).toLocaleDateString():'No expiry'}</td><td><code>{c.verificationCode}</code></td></tr>)}{!data.certificates.length&&<tr><td colSpan={7} className="muted">No learning certificates in scope.</td></tr>}</tbody></table></section>}
function Setup({data,actor,busy,call}:{data:LearningDashboard;actor:ActorContext;busy:boolean;call:(p:string,i:RequestInit)=>Promise<void>}){const[code,setCode]=useState('DATA');const[name,setName]=useState('People Analytics');const[skillId,setSkillId]=useState(data.skills[0]?.id||'');const[positionId,setPositionId]=useState(data.positionDirectory[0]?.id||'');const[level,setLevel]=useState(3);const[courseCode,setCourseCode]=useState('LMS101');const[courseTitle,setCourseTitle]=useState('Core capability learning');const[courseSkill,setCourseSkill]=useState(data.skills[0]?.id||'');const[pathTitle,setPathTitle]=useState('Manager Development Path');const[pathCourses,setPathCourses]=useState<string[]>([]);if(!actor.permissions.includes('learning.manage'))return <div className="card">Learning administration is restricted to authorized HR administrators.</div>;return <div className="stack"><div className="grid2"><section className="card"><h2 className="sectionTitle">Skill library</h2><div className="inlineControls"><input className="input smallInput" value={code} onChange={e=>setCode(e.target.value)}/><input className="input" value={name} onChange={e=>setName(e.target.value)}/><button className="button" disabled={busy} onClick={()=>call(`/api/organizations/${activeOrgId()}/learning/skills`,{method:'POST',body:JSON.stringify({code,name,category:'Professional',evidenceRequired:true,enabled:true})})}>Add skill</button></div><div className="competencyChips topGap">{data.skills.map(s=><span key={s.id}><strong>{s.code}</strong> {s.name}</span>)}</div></section>
 <section className="card"><h2 className="sectionTitle">Position skill requirement</h2><div className="stack"><label>Position<select className="input" value={positionId} onChange={e=>setPositionId(e.target.value)}>{data.positionDirectory.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Skill<select className="input" value={skillId} onChange={e=>setSkillId(e.target.value)}>{data.skills.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Required level<select className="input" value={level} onChange={e=>setLevel(Number(e.target.value))}>{[1,2,3,4,5].map(v=><option key={v}>{v}</option>)}</select></label><button className="button" disabled={busy||!positionId||!skillId} onClick={()=>call(`/api/organizations/${activeOrgId()}/learning/requirements`,{method:'POST',body:JSON.stringify({positionId,skillId,requiredLevel:level,criticality:'required',weightPct:0})})}>Map requirement</button></div></section></div>
 <section className="card"><h2 className="sectionTitle">Course authoring</h2><div className="learningCourseForm"><input className="input" value={courseCode} onChange={e=>setCourseCode(e.target.value)} placeholder="Course code"/><input className="input" value={courseTitle} onChange={e=>setCourseTitle(e.target.value)} placeholder="Course title"/><select className="input" value={courseSkill} onChange={e=>setCourseSkill(e.target.value)}>{data.skills.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="button" disabled={busy||!courseSkill} onClick={()=>call(`/api/organizations/${activeOrgId()}/learning/courses`,{method:'POST',body:JSON.stringify({code:courseCode,title:courseTitle,description:'Internal OPSIQO learning module linked to a verified capability.',delivery:'self_paced',durationMinutes:45,skillMappings:[{skillId:courseSkill,targetLevel:3,weightPct:100}],assessmentQuestions:[{prompt:'Which response best demonstrates application of this capability?',options:['Apply evidence and document the outcome','Skip verification','Rely on assumption'],correctOption:0,points:1}],passingScorePct:100,certificateValidityDays:365,mandatory:false})})}>Create draft course</button></div></section>
 <section className="card"><h2 className="sectionTitle">Learning path</h2><div className="learningPathForm"><input className="input" value={pathTitle} onChange={e=>setPathTitle(e.target.value)}/><select className="input multiSelect" multiple value={pathCourses} onChange={e=>setPathCourses(Array.from(e.target.selectedOptions).map(o=>o.value))}>{data.courses.filter(c=>c.status==='published').map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><button className="button" disabled={busy||!pathCourses.length} onClick={()=>call(`/api/organizations/${activeOrgId()}/learning/paths`,{method:'POST',body:JSON.stringify({code:`PATH_${Date.now()}`,title:pathTitle,courseIds:pathCourses,targetPositionIds:[],targetSkillIds:[],status:'published'})})}>Create path</button></div></section></div>}
