'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { activeOrgId, apiFetch } from '@/lib/http/client';
import type { LifecycleDashboard } from '@/domain/lifecycle';
import { LoadingState } from '@/components/data-states';

export function LifecycleCommandCenter(){const[data,setData]=useState<LifecycleDashboard|null>(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false);
 const load=()=>apiFetch<{data:LifecycleDashboard}>(`/api/organizations/${activeOrgId()}/lifecycle/dashboard`).then(r=>setData(r.data)).catch(e=>setError(e instanceof Error?e.message:'Unable to load lifecycle command center.'));
 useEffect(()=>{load();},[]);
 async function snapshot(){setBusy(true);setError('');try{await apiFetch(`/api/organizations/${activeOrgId()}/lifecycle/diagnostics`,{method:'POST'});await load();}catch(e){setError(e instanceof Error?e.message:'Unable to persist diagnostics.');}finally{setBusy(false);}}
 if(!data)return <div className="stack">{error&&<div className="error">{error}</div>}<LoadingState label="Loading lifecycle intelligence and authoritative worker evidence…"/></div>;
 return <div className="stack">{error&&<div className="error">{error}</div>}
  <div className="grid4">{data.metrics.map(m=><Link className="card metricLink" href={m.href} key={m.key}><div className="metricLabel">{m.label}</div><div className="metricValue">{m.value}</div><div className="metricFoot">{m.helper}</div></Link>)}</div>
  <div className="grid2"><section className="card"><div className="rowBetween"><div><h2 className="sectionTitle">Lifecycle funnel</h2><p className="muted">One workforce lifecycle from demand through separation.</p></div><span className="badge">Live</span></div><div className="funnelList">{data.funnel.map((f,i)=><Link href={f.href} className="funnelRow" key={f.stage}><span>{i+1}. {f.stage}</span><strong>{f.value}</strong></Link>)}</div></section>
  <section className="card"><div className="rowBetween"><div><h2 className="sectionTitle">Data quality</h2><p className="muted">Cross-module integrity score.</p></div><button className="button secondary" onClick={snapshot} disabled={busy}>{busy?'Running…':'Save diagnostic snapshot'}</button></div><div className="qualityScore">{data.diagnostics.score}<span>/100</span></div><div className="qualityBreakdown"><span>Critical {data.diagnostics.counts.critical}</span><span>High {data.diagnostics.counts.high}</span><span>Warning {data.diagnostics.counts.warning}</span></div>{data.diagnostics.sampled&&<div className="notice">Diagnostic scan reached the {data.diagnostics.sampleLimit}-record safety cap for at least one collection. Run the scheduled batch diagnostic for full large-tenant coverage.</div>}</section></div>
  <section className="card"><div className="rowBetween"><div><h2 className="sectionTitle">Priority lifecycle alerts</h2><p className="muted">Critical and high-priority findings across recruiting, onboarding, workforce, time and offboarding.</p></div><span className="badge">{data.alerts.length} surfaced</span></div><div className="alertGrid">{data.alerts.map(a=><Link href={a.href} key={a.id} className={`alertCard ${a.severity}`}><div><span className="badge">{a.severity}</span><strong>{a.title}</strong></div><p>{a.message}</p></Link>)}{!data.alerts.length&&<div className="success">No critical/high lifecycle alerts in the current scan.</div>}</div></section>
  <section className="card"><h2 className="sectionTitle">Data-quality findings</h2><div className="tableWrap"><table><thead><tr><th>Severity</th><th>Finding</th><th>Recommended action</th></tr></thead><tbody>{data.diagnostics.findings.slice(0,20).map(f=><tr key={f.id}><td><span className="badge">{f.severity}</span></td><td><Link href={f.href}><strong>{f.title}</strong></Link><div className="muted">{f.description}</div></td><td>{f.recommendedAction}</td></tr>)}</tbody></table></div></section>
  <section className="card"><h2 className="sectionTitle">Automation health</h2>{data.lastAutomationRun?<div className="rowBetween"><div><strong>{data.lastAutomationRun.status}</strong><div className="muted">Latest automation run {data.lastAutomationRun.id}</div></div><div className="metricFoot">{data.lastAutomationRun.completedAt?new Date(data.lastAutomationRun.completedAt).toLocaleString():'Still running / incomplete'}</div></div>:<div className="notice">No automation run is recorded yet.</div>}</section>
 </div>}
