'use client';
import { FormEvent, useEffect, useState } from 'react';
import { apiFetch, setActiveOrgId } from '@/lib/http/client';
import type { ActorContext } from '@/domain/security';
import type { PlatformTenantSummary } from '@/lib/platform/tenant-management';

type Me={actor:ActorContext};
type Created={orgId:string;organization:{name:string;environment:string}};

export function PlatformTenantWorkspace(){
  const[me,setMe]=useState<Me|null>(null),[rows,setRows]=useState<PlatformTenantSummary[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const load=async()=>{try{setError('');const m=await apiFetch<Me>('/api/me');setMe(m);if(m.actor.role!=='super_admin')return;setRows((await apiFetch<{data:PlatformTenantSummary[]}>('/api/platform/tenants')).data)}catch(e){setError(e instanceof Error?e.message:'Unable to load platform tenants.')}};
  useEffect(()=>{load()},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setNotice('');const formElement=e.currentTarget;const form=new FormData(formElement);try{const result=await apiFetch<{data:Created}>('/api/platform/tenants',{method:'POST',body:JSON.stringify({organizationName:form.get('organizationName'),administratorFirstName:form.get('administratorFirstName'),administratorLastName:form.get('administratorLastName'),environment:form.get('environment'),reason:form.get('reason')})});setNotice(`${result.data.organization.name} was created successfully. You now have governed super-admin access to the new tenant.`);formElement.reset();await load()}catch(err){setError(err instanceof Error?err.message:'Tenant creation failed.')}finally{setBusy(false)}}
  if(me&&me.actor.role!=='super_admin')return <div className="error">This screen is restricted to platform super-administrators.</div>;
  return <div className="stack">{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="success" role="status">{notice}</div>}<div className="grid2"><form className="card stack" onSubmit={submit}><div><span className="eyebrow">Governed platform administration</span><h2 className="sectionTitle">Create a separate company</h2><p className="muted">Creates an isolated tenant and its administrator foundation. No data is copied from the current organization.</p></div><label className="field"><span>Company name</span><input className="input" name="organizationName" required minLength={2} maxLength={120}/></label><div className="formGrid"><label className="field"><span>Administrator first name</span><input className="input" name="administratorFirstName" required maxLength={80}/></label><label className="field"><span>Administrator last name</span><input className="input" name="administratorLastName" required maxLength={80}/></label></div><label className="field"><span>Environment</span><select className="input" name="environment" defaultValue="test"><option value="test">Test</option><option value="uat">UAT</option><option value="production">Production</option></select></label><label className="field"><span>Creation reason</span><textarea className="input" name="reason" required minLength={10} maxLength={500} defaultValue="Create an isolated company for governed platform testing and user acceptance."/></label><button className="button" disabled={busy}>{busy?'Creating tenant…':'Create company securely'}</button></form><section className="card stack"><h2 className="sectionTitle">Tenant-creation controls</h2><div className="securityChecklist"><div>✓ Super-admin role required</div><div>✓ Verified administrator identity required</div><div>✓ Duplicate company-name protection</div><div>✓ Transactional organization foundation</div><div>✓ Separate worker and membership records</div><div>✓ Immutable audit evidence</div><div>✓ No cross-tenant data copying</div></div></section></div><section className="card tableWrap"><h2 className="sectionTitle">Platform companies</h2><table><thead><tr><th>Company</th><th>Environment</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.name}</strong><div className="muted">{row.id}</div></td><td>{row.environment}</td><td><span className="badge">{row.status}</span></td><td>{row.createdAt?new Date(row.createdAt).toLocaleString():'—'}</td><td><button className="button secondary compact" onClick={()=>{setActiveOrgId(row.id);window.dispatchEvent(new Event('opsiqo:organization-changed'));window.location.assign('/dashboard')}}>Open company</button></td></tr>)}{!rows.length&&<tr><td colSpan={5} className="muted">No platform companies are visible.</td></tr>}</tbody></table></section></div>;
}
