'use client';
import { useEffect,useState } from 'react';
import type { ActorContext } from '@/domain/security';
import type { ProgramPortfolioDashboard,ProgramFinancialEvidenceKind,ProgramFinancialEvidenceSource } from '@/domain/opsiqo-one-v7-17';
import { activeOrgId,apiDownload,apiFetch } from '@/lib/http/client';
import { useShellLocale } from '@/lib/opsiqo-one/shell-i18n';
import { LoadingState } from './data-states';

const text={
 en:{eyebrow:'OPSIQO ONE · Program Portfolio',title:'Budget and actual intelligence from explicit evidence',intro:'Connect program projects to approved-budget, actual, commitment and forecast evidence without treating HR estimates as accounting truth.',projects:'Projects',budget:'With budget evidence',actual:'With actual evidence',complete:'Complete evidence',missing:'Missing financial evidence',summary:'Currency summaries',portfolio:'Program portfolio',financial:'Record financial evidence',kind:'Evidence type',date:'Evidence date',source:'Source type',ref:'Source reference',amount:'Amount',record:'Record governed evidence',exportCsv:'Export CSV',exportJson:'Export evidence JSON',signals:'Evidence signals',currency:'Currency',approvedBudget:'Approved budget',actualLabel:'Actual',commitment:'Commitment',plannedWorkforce:'Planned workforce',selectProject:'Select project',workers:'Workers',balance:'Balance',utilization:'Utilization',boundary:'Methodology boundary'},
 fr:{eyebrow:'OPSIQO ONE · Portefeuille de programmes',title:'Budget et réalisé à partir de preuves explicites',intro:'Reliez les projets aux preuves de budget approuvé, réalisé, engagements et prévisions sans traiter les estimations RH comme vérité comptable.',projects:'Projets',budget:'Avec preuve budgétaire',actual:'Avec preuve du réalisé',complete:'Preuves complètes',missing:'Preuves financières manquantes',summary:'Synthèses par devise',portfolio:'Portefeuille de programmes',financial:'Enregistrer une preuve financière',kind:'Type de preuve',date:'Date de preuve',source:'Type de source',ref:'Référence de source',amount:'Montant',record:'Enregistrer la preuve gouvernée',exportCsv:'Exporter CSV',exportJson:'Exporter les preuves JSON',signals:'Signaux de preuve',currency:'Devise',approvedBudget:'Budget approuvé',actualLabel:'Réalisé',commitment:'Engagement',plannedWorkforce:'Effectif planifié',selectProject:'Sélectionner un projet',workers:'Travailleurs',balance:'Solde',utilization:'Utilisation',boundary:'Limite méthodologique'},
 es:{eyebrow:'OPSIQO ONE · Portafolio de programas',title:'Presupuesto y real desde evidencia explícita',intro:'Conecta proyectos con presupuesto aprobado, real, compromisos y pronóstico sin tratar estimaciones de RR. HH. como verdad contable.',projects:'Proyectos',budget:'Con evidencia presupuestaria',actual:'Con evidencia real',complete:'Evidencia completa',missing:'Falta evidencia financiera',summary:'Resúmenes por moneda',portfolio:'Portafolio de programas',financial:'Registrar evidencia financiera',kind:'Tipo de evidencia',date:'Fecha de evidencia',source:'Tipo de fuente',ref:'Referencia de fuente',amount:'Importe',record:'Registrar evidencia gobernada',exportCsv:'Exportar CSV',exportJson:'Exportar evidencia JSON',signals:'Señales de evidencia',currency:'Moneda',approvedBudget:'Presupuesto aprobado',actualLabel:'Real',commitment:'Compromiso',plannedWorkforce:'Plantilla planificada',selectProject:'Seleccionar proyecto',workers:'Trabajadores',balance:'Saldo',utilization:'Utilización',boundary:'Límite metodológico'},
 ar:{eyebrow:'OPSIQO ONE · محفظة البرامج',title:'الميزانية والفعلي من أدلة صريحة',intro:'اربط المشاريع بأدلة الميزانية المعتمدة والفعلي والالتزامات والتوقعات دون اعتبار تقديرات الموارد البشرية حقيقة محاسبية.',projects:'المشاريع',budget:'بأدلة ميزانية',actual:'بأدلة فعلية',complete:'أدلة مكتملة',missing:'أدلة مالية مفقودة',summary:'ملخصات حسب العملة',portfolio:'محفظة البرامج',financial:'تسجيل دليل مالي',kind:'نوع الدليل',date:'تاريخ الدليل',source:'نوع المصدر',ref:'مرجع المصدر',amount:'المبلغ',record:'تسجيل الدليل المحكوم',exportCsv:'تصدير CSV',exportJson:'تصدير أدلة JSON',signals:'إشارات الأدلة',currency:'العملة',approvedBudget:'الميزانية المعتمدة',actualLabel:'الفعلي',commitment:'الالتزام',plannedWorkforce:'القوى العاملة المخططة',selectProject:'اختيار المشروع',workers:'العاملون',balance:'الرصيد',utilization:'الاستخدام',boundary:'حدود المنهجية'},
};
const kinds:ProgramFinancialEvidenceKind[]=['approved_budget','actual','commitment','forecast'];
const sources:ProgramFinancialEvidenceSource[]=['finance_export','ledger_extract','approved_budget','invoice_batch','manual_verified'];
export function ProgramPortfolioWorkspace(){
 const locale=useShellLocale(),T=text[locale]||text.en;
 const[data,setData]=useState<ProgramPortfolioDashboard|null>(null),[actor,setActor]=useState<ActorContext|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[projectId,setProjectId]=useState(''),[kind,setKind]=useState<ProgramFinancialEvidenceKind>('actual'),[amount,setAmount]=useState(''),[evidenceDate,setEvidenceDate]=useState(new Date().toISOString().slice(0,10)),[sourceType,setSourceType]=useState<ProgramFinancialEvidenceSource>('finance_export'),[sourceReference,setSourceReference]=useState('');
 const download=async(format:'csv'|'json')=>{setError('');try{const r=await apiDownload(`/api/organizations/${activeOrgId()}/opsiqo-one/program-portfolio/export?format=${format}`),url=URL.createObjectURL(r.blob),a=document.createElement('a');a.href=url;a.download=r.fileName||`opsiqo-program-portfolio.${format}`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}catch(e){setError(e instanceof Error?e.message:'Unable to export Program Portfolio.')}};
 const load=async()=>{setError('');try{const[d,a]=await Promise.all([apiFetch<{data:ProgramPortfolioDashboard}>(`/api/organizations/${activeOrgId()}/opsiqo-one/program-portfolio`),apiFetch<{actor:ActorContext}>('/api/me')]);setData(d.data);setActor(a.actor)}catch(e){setError(e instanceof Error?e.message:'Unable to load Program Portfolio.')}};useEffect(()=>{void load()},[]);
 async function record(){if(!data)return;const project=data.rows.find(x=>x.projectId===projectId);if(!project)return;setBusy(true);setError('');setNotice('');try{await apiFetch(`/api/organizations/${activeOrgId()}/opsiqo-one/program-portfolio/evidence`,{method:'POST',body:JSON.stringify({projectId,fundingSourceId:project.fundingSourceId,kind,amount:Number(amount),currency:project.currency,evidenceDate,sourceType,sourceReference})});setAmount('');setSourceReference('');setNotice('Financial evidence recorded and audit-linked.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to record financial evidence.')}finally{setBusy(false)}}
 if(!data||!actor)return <div className="stack">{error&&<div className="error" role="alert">{error}</div>}<LoadingState label="Loading program portfolio evidence…"/></div>;
 const canManage=actor.permissions.includes('workforce.manage');
 return <div className="stack">{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="success" role="status">{notice}</div>}
  <section className="card oneHero"><div><span className="eyebrow">{T.eyebrow}</span><h1>{T.title}</h1><p className="muted">{T.intro}</p></div><div className="row wrap"><button className="button secondary" onClick={()=>download('csv')}>{T.exportCsv}</button><button className="button secondary" onClick={()=>download('json')}>{T.exportJson}</button><button className="button secondary" onClick={load}>Refresh</button></div></section>
  <div className="settingsGrid"><Metric label={T.projects} value={data.metrics.projects}/><Metric label={T.budget} value={data.metrics.projectsWithBudgetEvidence}/><Metric label={T.actual} value={data.metrics.projectsWithActualEvidence}/><Metric label={T.complete} value={data.metrics.projectsWithCompleteEvidence}/><Metric label={T.missing} value={data.metrics.projectsMissingFinancialEvidence}/></div>
  {data.signals.length>0&&<section className="card stack"><h2 className="sectionTitle">{T.signals}</h2>{data.signals.map(s=><div className={`oneWorkItem ${s.severity}`} key={s.id}><div><strong>{s.title}</strong><p className="muted">{s.summary}</p></div></div>)}</section>}
  <section className="card tableWrap"><h2 className="sectionTitle">{T.summary}</h2><table><thead><tr><th>{T.currency}</th><th>{T.projects}</th><th>{T.approvedBudget}</th><th>{T.actualLabel}</th><th>{T.commitment}</th><th>Forecast</th><th>{T.plannedWorkforce}</th></tr></thead><tbody>{data.currencySummaries.map(r=><tr key={r.currency}><td>{r.currency}</td><td>{r.projectCount}</td><td>{fmt(r.approvedBudget)}</td><td>{fmt(r.actual)}</td><td>{fmt(r.commitment)}</td><td>{fmt(r.forecast)}</td><td>{fmt(r.plannedWorkforceAmount)}</td></tr>)}</tbody></table></section>
  {canManage&&<section className="card stack"><h2 className="sectionTitle">{T.financial}</h2><div className="formGrid"><label className="field"><span>Project</span><select className="input" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">{T.selectProject}</option>{data.rows.map(r=><option key={r.projectId} value={r.projectId}>{r.projectCode} · {r.projectName}</option>)}</select></label><label className="field"><span>{T.kind}</span><select className="input" value={kind} onChange={e=>setKind(e.target.value as ProgramFinancialEvidenceKind)}>{kinds.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label><label className="field"><span>{T.amount}</span><input className="input" type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="field"><span>{T.date}</span><input className="input" type="date" value={evidenceDate} onChange={e=>setEvidenceDate(e.target.value)}/></label><label className="field"><span>{T.source}</span><select className="input" value={sourceType} onChange={e=>setSourceType(e.target.value as ProgramFinancialEvidenceSource)}>{sources.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label><label className="field"><span>{T.ref}</span><input className="input" value={sourceReference} onChange={e=>setSourceReference(e.target.value)} placeholder="Ledger/export/budget reference"/></label></div><button className="button" disabled={busy||!projectId||!amount||Number(amount)<0||sourceReference.trim().length<2} onClick={record}>{T.record}</button><small className="muted">Budget and forecast are latest-snapshot evidence. Actual and commitment records are additive evidence entries. Evidence date and currency are server-validated against the project and funding source.</small></section>}
  <section className="card tableWrap"><h2 className="sectionTitle">{T.portfolio}</h2><table><thead><tr><th>Project</th><th>Grant</th><th>{T.workers}</th><th>{T.plannedWorkforce}</th><th>Budget</th><th>{T.actualLabel}</th><th>{T.commitment}</th><th>{T.balance}</th><th>{T.utilization}</th><th>Evidence</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.projectId}><td><strong>{r.projectCode}</strong><br/>{r.projectName}</td><td>{r.fundingCode}<br/><small>{r.fundingName}</small></td><td>{r.workerCount}</td><td>{fmt(r.plannedWorkforceAmount)} {r.plannedWorkforceAmount!==null?r.currency:''}</td><td>{fmt(r.approvedBudget)}</td><td>{fmt(r.actual)}</td><td>{fmt(r.commitment)}</td><td>{fmt(r.budgetVariance)}</td><td>{r.budgetUtilizationPct===null?'Not configured':`${r.budgetUtilizationPct}%`}</td><td>{r.evidenceState.replaceAll('_',' ')}{r.evidenceFreshThrough?<><br/><small>{r.evidenceFreshThrough}</small></>:null}</td></tr>)}</tbody></table></section>
  <section className="card"><strong>{T.boundary}</strong><p className="muted">{data.methodologyNotice}</p></section>
 </div>
}
function fmt(v:number|null){return v===null?'Not configured':v.toLocaleString(undefined,{maximumFractionDigits:2})}
function Metric({label,value}:{label:string;value:number|string}){return <div className="card metricCard"><div className="metricLabel">{label}</div><div className="metricValue">{value}</div></div>}
