'use client';
import { useEffect,useState,useRef } from 'react';
import type { ActorContext } from '@/domain/security';
import type { Worker } from '@/domain/hr';
import type { GrantWorkforceDashboard } from '@/domain/opsiqo-one-v7-15';
import type { ProgramWorkforceDashboard } from '@/domain/opsiqo-one-v7-16';
import { activeOrgId,apiFetch } from '@/lib/http/client';
import { LoadingState } from './data-states';
import { useLegacySurfaceTranslation } from '@/lib/opsiqo-one/legacy-surface-i18n';

export function ProgramWorkforceWorkspace(){
 const translationRoot=useRef<HTMLDivElement>(null);useLegacySurfaceTranslation('program_workforce',translationRoot);
 const[data,setData]=useState<ProgramWorkforceDashboard|null>(null),[grants,setGrants]=useState<GrantWorkforceDashboard|null>(null),[actor,setActor]=useState<ActorContext|null>(null),[workers,setWorkers]=useState<Worker[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{setError('');try{const org=activeOrgId();const[d,g,m]=await Promise.all([apiFetch<{data:ProgramWorkforceDashboard}>(`/api/organizations/${org}/opsiqo-one/program-workforce`),apiFetch<{data:GrantWorkforceDashboard}>(`/api/organizations/${org}/opsiqo-one/grant-workforce`),apiFetch<{actor:ActorContext}>('/api/me')]);setData(d.data);setGrants(g.data);setActor(m.actor);if(m.actor.permissions.includes('workforce.manage')&&m.actor.permissions.includes('people.read.directory')){const w=await apiFetch<{data:Worker[]}>(`/api/organizations/${org}/employees?pageSize=100`);setWorkers(w.data||[])}else setWorkers([])}catch(e){setError(e instanceof Error?e.message:'Unable to load program workforce intelligence.')}};
 useEffect(()=>{void load()},[]);
 const post=async(path:string,body:unknown)=>{setBusy(true);setError('');try{await apiFetch(path,{method:'POST',body:JSON.stringify(body)});await load()}catch(e){setError(e instanceof Error?e.message:'Action failed.')}finally{setBusy(false)}};
 if(!data||!grants||!actor)return <div ref={translationRoot} className="stack">{error&&<div className="error" role="alert">{error}</div>}<LoadingState label="Loading program workforce evidence…"/></div>;
 const canManage=actor.permissions.includes('workforce.manage');
 return <div ref={translationRoot} className="stack">{error&&<div className="error" role="alert">{error}</div>}
  <section className="card oneHero"><div><span className="eyebrow">OPSIQO ONE · Program Workforce Intelligence</span><h1>Project → Grant → Position → Worker → Cost</h1><p className="muted">Connect explicit program, funding and workforce evidence without reading restricted compensation records or guessing future funding.</p></div></section>
  <div className="settingsGrid"><Metric label="Active projects" value={data.metrics.activeProjects}/><Metric label="Active funding sources" value={data.metrics.activeFundingSources}/><Metric label="Funded workers" value={data.metrics.fundedWorkers}/><Metric label="Linked positions" value={data.metrics.linkedPositions}/><Metric label="Explicit planned annual cost" value={data.metrics.explicitPlannedAnnualCost===null?'Not configured':data.metrics.explicitPlannedAnnualCost.toLocaleString()}/><Metric label="Uncosted allocations" value={data.metrics.uncostedAllocations}/></div>
  {data.signals.length>0&&<section className="card stack"><h2 className="sectionTitle">Evidence gaps</h2>{data.signals.map(s=><div className={`oneWorkItem ${s.severity}`} key={s.id}><div><strong>{s.title}</strong><p className="muted">{s.summary}</p></div></div>)}</section>}
  {canManage&&<div className="grid2"><ProjectForm data={data} grants={grants} busy={busy} post={post}/><ProgramAllocationForm data={data} grants={grants} workers={workers} busy={busy} post={post}/></div>}
  <section className="card tableWrap"><h2 className="sectionTitle">Program workforce chain</h2><table><thead><tr><th>Project</th><th>Grant</th><th>Worker</th><th>Position</th><th>Org unit</th><th>Allocation</th><th>Explicit cost</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.allocationId}><td>{r.projectCode} · {r.projectName}</td><td>{r.fundingCode} · {r.fundingName}</td><td>{r.workerName}{r.employmentType?` · ${r.employmentType}`:''}</td><td>{r.positionTitle||'Not linked'}</td><td>{r.orgUnitName||'Not linked'}</td><td>{r.allocationPct}%</td><td>{r.plannedAnnualAmount===null?'Not configured':`${r.plannedAnnualAmount.toLocaleString()} ${r.currency}`}</td></tr>)}</tbody></table></section>
  <section className="card"><strong>Methodology boundary</strong><p className="muted">{data.methodologyNotice}</p></section>
 </div>
}
function ProjectForm({data,grants,busy,post}:{data:ProgramWorkforceDashboard;grants:GrantWorkforceDashboard;busy:boolean;post:(p:string,b:unknown)=>Promise<void>}){const[code,setCode]=useState(''),[name,setName]=useState(''),[funding,setFunding]=useState(''),[start,setStart]=useState(new Date().toISOString().slice(0,10)),[end,setEnd]=useState('');return <section className="card stack"><h2 className="sectionTitle">Create program project</h2><input className="input" aria-label="Project code" placeholder="Project code" value={code} onChange={e=>setCode(e.target.value)}/><input className="input" aria-label="Project name" placeholder="Project name" value={name} onChange={e=>setName(e.target.value)}/><select className="input" aria-label="Project funding source" value={funding} onChange={e=>{setFunding(e.target.value);const s=grants.sources.find(x=>x.id===e.target.value);if(s){setStart(s.startDate);setEnd(s.endDate)}}}><option value="">Funding source</option>{grants.sources.filter(x=>x.status!=='closed').map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select><div className="formGrid"><label className="field"><span>Project start</span><input className="input" type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="field"><span>Project end</span><input className="input" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><button className="button" disabled={busy||!code||!name||!funding||!end} onClick={()=>post(`/api/organizations/${activeOrgId()}/opsiqo-one/program-workforce/project`,{code,name,fundingSourceId:funding,startDate:start,endDate:end,status:'active'})}>Create reviewed project record</button><small className="muted">Projects are planning records only; creating one does not create positions, employees, donor obligations or workflows.</small></section>}
function ProgramAllocationForm({data,grants,workers,busy,post}:{data:ProgramWorkforceDashboard;grants:GrantWorkforceDashboard;workers:Worker[];busy:boolean;post:(p:string,b:unknown)=>Promise<void>}){const[projectId,setProjectId]=useState(''),[workerId,setWorkerId]=useState(''),[pct,setPct]=useState(100),[amount,setAmount]=useState(''),[start,setStart]=useState(new Date().toISOString().slice(0,10));const project=data.projects.find(x=>x.id===projectId);return <section className="card stack"><h2 className="sectionTitle">Link worker to program</h2><select className="input" aria-label="Program project" value={projectId} onChange={e=>{setProjectId(e.target.value);const p=data.projects.find(x=>x.id===e.target.value);if(p)setStart(p.startDate)}}><option value="">Program project</option>{data.projects.filter(x=>x.status!=='closed').map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select><select className="input" aria-label="Program worker" value={workerId} onChange={e=>setWorkerId(e.target.value)}><option value="">Worker</option>{workers.filter(x=>x.status!=='terminated').map(x=><option key={x.id} value={x.id}>{x.displayName}</option>)}</select><label className="field"><span>Allocation %</span><input className="input" type="number" min={0.1} max={100} step={0.1} value={pct} onChange={e=>setPct(Number(e.target.value))}/></label><label className="field"><span>Explicit planned annual funded amount (optional)</span><input className="input" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Do not infer salary"/></label><label className="field"><span>Allocation start</span><input className="input" type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><button className="button" disabled={busy||!project||!workerId} onClick={()=>post(`/api/organizations/${activeOrgId()}/opsiqo-one/grant-workforce/allocation`,{fundingSourceId:project!.fundingSourceId,projectId:project!.id,workerId,allocationPct:pct,startDate:start,...(amount.trim()?{plannedAnnualAmount:Number(amount)}:{})})}>Create governed allocation</button><small className="muted">Allocation is server-validated against grant/project dates and overlapping worker allocations.</small></section>}
function Metric({label,value}:{label:string;value:number|string}){return <div className="card metricCard"><div className="metricLabel">{label}</div><div className="metricValue">{value}</div></div>}
