'use client';
import { FormEvent, useEffect, useState } from 'react';
import { activeOrgId, apiFetch } from '@/lib/http/client';

type Worker={id:string;displayName:string;employeeNumber:string;status:string};
type Case={id:string;workerId:string;managerWorkerId?:string;separationType:string;effectiveDate:string;lastWorkingDate:string;reasonCategory:string;employeeInitiated:boolean;regrettable:boolean;rehireEligible?:boolean;status:string;progress:number;legalReviewRequired:boolean;legalReviewStatus:string;noticeMethod?:string;replacementDecision:string;replacementRequisitionId?:string;replacementRequestedAt?:string;autoCloseOnEffectiveDate:boolean;payPeriodEndDate?:string;roeTargetDate?:string;finalPayTargetDate?:string;createdAt:string};
type Task={id:string;code?:string;title:string;description?:string;ownerType:string;phase:string;required:boolean;blockingClosure:boolean;dueAt?:string;status:string;completionNote?:string};
type Asset={id:string;assetTag?:string;name:string;category?:string;status:string;returnedAt?:string};
type Bundle={case:Case;worker:Worker&{hireDate?:string;terminationDate?:string};tasks:Task[];assets:Asset[];exitInterview?:any};
type Dashboard={metrics:{openCases:number;pendingApproval:number;dueWithin14Days:number;overdueTasks:number;closedYtd:number;voluntaryYtd:number;regrettableYtd:number};reasonMix:Array<{reasonCategory:string;count:number}>;openCases:Case[];overdueTasks:Task[]};

export function SeparationWorkspace(){
 const[permissions,setPermissions]=useState<string[]>([]),[role,setRole]=useState(''),[myWorkerId,setMyWorkerId]=useState(''),[workers,setWorkers]=useState<Worker[]>([]),[cases,setCases]=useState<Case[]>([]),[dashboard,setDashboard]=useState<Dashboard|null>(null),[selectedId,setSelectedId]=useState(''),[bundle,setBundle]=useState<Bundle|null>(null),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const org=()=>activeOrgId(),can=(p:string)=>permissions.includes(p),today=new Date().toISOString().slice(0,10);
 const load=async()=>{try{setError('');const me=await apiFetch<{actor:{permissions:string[];role:string;workerId?:string}}>('/api/me');setPermissions(me.actor.permissions);setRole(me.actor.role);setMyWorkerId(me.actor.workerId||'');let people:Worker[]=[];if(me.actor.permissions.includes('separation.manage'))people=(await apiFetch<{data:Worker[]}>(`/api/organizations/${org()}/employees?pageSize=100`)).data;else if(me.actor.role==='manager'){const team=(await apiFetch<{data:Array<{worker:Worker}>}>(`/api/organizations/${org()}/manager/team`)).data;people=team.map(r=>r.worker).filter(Boolean);}else if(me.actor.workerId)people=[{id:me.actor.workerId,displayName:'My employment',employeeNumber:'',status:'active'}];setWorkers(people);const [c,d]=await Promise.all([apiFetch<{data:Case[]}>(`/api/organizations/${org()}/separations`),apiFetch<{data:Dashboard}>(`/api/organizations/${org()}/separations/dashboard`)]);setCases(c.data);setDashboard(d.data);const next=selectedId&&c.data.some(x=>x.id===selectedId)?selectedId:c.data[0]?.id||'';setSelectedId(next);if(next)await loadCase(next);else setBundle(null);}catch(e){setError(e instanceof Error?e.message:'Unable to load offboarding workspace.');}};
 const loadCase=async(id:string)=>{setSelectedId(id);setBundle((await apiFetch<{data:Bundle}>(`/api/organizations/${org()}/separations/${id}`)).data);};
 useEffect(()=>{load();const f=()=>{setSelectedId('');load();};window.addEventListener('opsiqo:organization-changed',f);return()=>window.removeEventListener('opsiqo:organization-changed',f);},[]);
 const submit=async(path:string,method:string,body:any,msg:string)=>{try{setError('');setNotice('');await apiFetch(path,{method,body:JSON.stringify(body)});setNotice(msg);await load();}catch(e){setError(e instanceof Error?e.message:'Operation failed.');}};
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),self=role==='employee';await submit(`/api/organizations/${org()}/separations`,'POST',{workerId:self?myWorkerId:f.get('workerId'),separationType:f.get('separationType'),effectiveDate:f.get('effectiveDate'),lastWorkingDate:f.get('lastWorkingDate'),reasonCategory:f.get('reasonCategory'),reasonDetail:f.get('reasonDetail')||undefined,employeeInitiated:self?true:f.get('employeeInitiated')==='on',regrettable:f.get('regrettable')==='on',rehireEligible:f.get('rehireEligible')==='on',autoCloseOnEffectiveDate:f.get('autoCloseOnEffectiveDate')==='on',payPeriodEndDate:f.get('payPeriodEndDate')||undefined,finalPayTargetDate:f.get('finalPayTargetDate')||undefined},'Separation case created. Review and submit it for approval.');e.currentTarget.reset();};
 const act=(action:string,body:any={})=>bundle&&submit(`/api/organizations/${org()}/separations/${bundle.case.id}`,'PATCH',{action,...body},`Separation action completed: ${action.replaceAll('_',' ')}.`);
 const legal=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await act('complete_legal_review',{noticeMethod:f.get('noticeMethod'),statutoryNoticeWeeks:Number(f.get('statutoryNoticeWeeks')||0),contractualNoticeWeeks:Number(f.get('contractualNoticeWeeks')||0),severanceReview:f.get('severanceReview'),massTerminationReview:f.get('massTerminationReview'),note:f.get('note')});};
 const task=(id:string,action:string)=>bundle&&submit(`/api/organizations/${org()}/separations/${bundle.case.id}/tasks/${id}`,'PATCH',{action},`Task ${action}d.`);
 const addAsset=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!bundle)return;const f=new FormData(e.currentTarget);await submit(`/api/organizations/${org()}/separations/${bundle.case.id}/assets`,'POST',{assetTag:f.get('assetTag')||undefined,name:f.get('name'),category:f.get('category')||undefined,note:f.get('note')||undefined},'Asset added to offboarding inventory.');e.currentTarget.reset();};
 const asset=(id:string,action:string)=>bundle&&submit(`/api/organizations/${org()}/separations/${bundle.case.id}/assets/${id}`,'PATCH',{action},`Asset marked ${action}.`);
 const interview=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!bundle)return;const f=new FormData(e.currentTarget);await submit(`/api/organizations/${org()}/separations/${bundle.case.id}/exit-interview`,'POST',{overallExperience:Number(f.get('overallExperience')||0)||undefined,managerExperience:Number(f.get('managerExperience')||0)||undefined,reasonForLeaving:f.get('reasonForLeaving')||undefined,whatWorkedWell:f.get('whatWorkedWell')||undefined,whatCouldImprove:f.get('whatCouldImprove')||undefined,destination:f.get('destination')||undefined,wouldRecommend:f.get('wouldRecommend')==='on',wouldReturn:f.get('wouldReturn')==='on',confidentialNote:f.get('confidentialNote')||undefined,themes:String(f.get('themes')||'').split(',').map(x=>x.trim()).filter(Boolean)},'Exit interview recorded.');e.currentTarget.reset();};
 const replacement=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await act('replacement_decision',{replacementDecision:f.get('replacementDecision'),replacementNote:f.get('replacementNote')});};
 const createReplacement=async()=>{if(!bundle)return;await submit(`/api/organizations/${org()}/separations/${bundle.case.id}/replacement-requisition`,'POST',{},'Replacement requisition created as a draft in Recruiting.');};
 const hrControls=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await act('update_hr_controls',{payPeriodEndDate:f.get('payPeriodEndDate')||undefined,roeTargetDate:f.get('roeTargetDate')||undefined,finalPayTargetDate:f.get('finalPayTargetDate')||undefined,rehireEligible:f.get('rehireEligible')==='on',regrettable:f.get('regrettable')==='on',autoCloseOnEffectiveDate:f.get('autoCloseOnEffectiveDate')==='on'});};
 const c=bundle?.case;
 const canActTask=(t:Task)=>can('separation.manage')||(role==='manager'&&t.ownerType==='manager'&&myWorkerId===c?.managerWorkerId)||(role==='employee'&&t.ownerType==='employee'&&myWorkerId===c?.workerId);
 return <div className="stack">
  {notice?<div className="success">{notice}</div>:null}{error?<div className="error">{error}</div>:null}
  {dashboard?<div className="grid4"><Metric label="Open cases" value={dashboard.metrics.openCases}/><Metric label="Pending approval" value={dashboard.metrics.pendingApproval}/><Metric label="Due ≤14 days" value={dashboard.metrics.dueWithin14Days}/><Metric label="Overdue tasks" value={dashboard.metrics.overdueTasks}/><Metric label="Closed YTD" value={dashboard.metrics.closedYtd}/><Metric label="Voluntary YTD" value={dashboard.metrics.voluntaryYtd}/><Metric label="Regrettable YTD" value={dashboard.metrics.regrettableYtd}/><Metric label="Reason categories" value={dashboard.reasonMix.length}/></div>:null}
  <section className="card"><h2 className="sectionTitle">Create separation request</h2><form className="separationCreateForm" onSubmit={create}>{role!=='employee'?<label className="field"><span>Employee</span><select className="input" name="workerId" required>{workers.map(w=><option key={w.id} value={w.id}>{w.displayName} · {w.employeeNumber}</option>)}</select></label>:null}<label className="field"><span>Type</span><select className="input" name="separationType" defaultValue={role==='employee'?'resignation':'employer_initiated'}>{(role==='employee'?['resignation','retirement']:['resignation','retirement','employer_initiated','layoff','contract_end','death','other']).map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label><Field label="Last working date" name="lastWorkingDate" type="date"/><Field label="Effective date" name="effectiveDate" type="date"/><Field label="Reason category" name="reasonCategory"/><Field label="Reason detail" name="reasonDetail" required={false}/>{role!=='employee'?<label className="checkRow"><input type="checkbox" name="employeeInitiated"/> Employee initiated</label>:null}{can('separation.manage')?<label className="checkRow"><input type="checkbox" name="regrettable"/> Regrettable exit</label>:null}{can('separation.manage')?<><label className="checkRow"><input type="checkbox" name="rehireEligible"/> Rehire eligible</label><Field label="Pay period end (ROE target helper)" name="payPeriodEndDate" type="date" required={false}/><Field label="Final-pay target (reviewed)" name="finalPayTargetDate" type="date" required={false}/><label className="checkRow"><input type="checkbox" name="autoCloseOnEffectiveDate"/> Auto-close only after approval + closure controls</label></>:null}<button className="button">Create case</button></form></section>
  <div className="grid2"><section className="card"><h2 className="sectionTitle">Separation cases</h2><div className="caseList">{cases.length?cases.map(x=><button key={x.id} onClick={()=>loadCase(x.id)} className={`caseListItem ${selectedId===x.id?'selected':''}`}><div><strong>{workers.find(w=>w.id===x.workerId)?.displayName||x.workerId}</strong><small>{x.separationType.replaceAll('_',' ')} · effective {x.effectiveDate}</small></div><span className="badge">{x.status.replaceAll('_',' ')}</span></button>):<p className="muted">No separation cases.</p>}</div></section>
  <section className="card">{c?<><div className="runHeader"><div><h2 className="sectionTitle">{bundle?.worker.displayName}</h2><p className="muted">{c.separationType.replaceAll('_',' ')} · {c.reasonCategory} · effective {c.effectiveDate}</p></div><span className="badge">{c.status.replaceAll('_',' ')}</span></div><div className="progressRow"><div className="progressTrack"><span style={{width:`${c.progress||0}%`}}/></div><strong>{c.progress||0}%</strong></div><div className="definitionGrid separationMeta"><span>Legal review</span><strong>{c.legalReviewStatus.replaceAll('_',' ')}</strong><span>ROE target</span><strong>{c.roeTargetDate||'Confirm based on filing/pay cycle'}</strong><span>Replacement</span><strong>{c.replacementDecision.replaceAll('_',' ')}</strong><span>Final-pay target</span><strong>{c.finalPayTargetDate||'HR review required'}</strong><span>Rehire eligible</span><strong>{c.rehireEligible===undefined?'Not assessed':c.rehireEligible?'Yes':'No'}</strong><span>Automatic closure</span><strong>{c.autoCloseOnEffectiveDate?'Enabled after all gates':'Off — HR closes manually'}</strong></div><div className="stepActions">{c.status==='draft'?<button className="button" onClick={()=>act('submit')}>Submit for approval</button>:null}{can('separation.approve')&&c.status==='pending_approval'?<button className="button" onClick={()=>act('approve')}>Approve separation</button>:null}{can('separation.manage')&&c.status==='approved'?<button className="button" onClick={()=>act('start')}>Start offboarding</button>:null}{can('separation.manage')&&!['closed','cancelled'].includes(c.status)?<button className="button secondary" onClick={()=>act('refresh_readiness')}>Refresh readiness</button>:null}{can('separation.close')&&c.effectiveDate<=today&&['approved','in_progress','ready_to_close'].includes(c.status)?<button className="button dangerButton" onClick={()=>act('close')}>Close employment</button>:null}{can('separation.approve')&&!['closed','cancelled'].includes(c.status)?<button className="button secondary" onClick={()=>act('cancel',{reason:'Cancelled by HR administrator'})}>Cancel case</button>:null}</div></>:<p className="muted">Select a separation case.</p>}</section></div>
  {c&&can('separation.approve')&&c.legalReviewRequired&&c.legalReviewStatus!=='completed'?<section className="card"><h2 className="sectionTitle">Legal / HR entitlement review gate</h2><p className="notice">OPSIQO records the reviewed conclusion; it does not automatically determine statutory or contractual termination/severance entitlement. Review applicable legislation, contract, common-law/collective-agreement obligations and protected-right risks before approval.</p><form className="separationLegalForm" onSubmit={legal}><label className="field"><span>Notice method</span><select className="input" name="noticeMethod"><option value="pending_review">Pending review</option><option value="working_notice">Working notice</option><option value="pay_in_lieu">Pay in lieu</option><option value="combination">Combination</option><option value="not_applicable">Not applicable</option></select></label><Field label="Statutory notice weeks reviewed" name="statutoryNoticeWeeks" type="number" required={false}/><Field label="Contractual/common-law weeks reviewed" name="contractualNoticeWeeks" type="number" required={false}/><label className="field"><span>Severance review</span><select className="input" name="severanceReview"><option value="not_reviewed">Not reviewed</option><option value="not_applicable">Not applicable</option><option value="potentially_applicable">Potentially applicable</option><option value="confirmed">Confirmed</option></select></label><label className="field"><span>Mass termination review</span><select className="input" name="massTerminationReview"><option value="not_reviewed">Not reviewed</option><option value="not_applicable">Not applicable</option><option value="potentially_applicable">Potentially applicable</option><option value="confirmed">Confirmed</option></select></label><Field label="Review note / source" name="note" required={false}/><button className="button">Complete review gate</button></form></section>:null}
  {c&&can('separation.approve')&&!['closed','cancelled'].includes(c.status)?<section className="card"><h2 className="sectionTitle">HR closure controls</h2><p className="muted">Record reviewed payroll/ROE targets and closure settings. These fields are operational controls, not automatic legal-entitlement calculations.</p><form className="separationLegalForm" onSubmit={hrControls}><Field label="Pay-period end (ROE scheduling input)" name="payPeriodEndDate" type="date" required={false}/><Field label="ROE filing target date (review / override helper)" name="roeTargetDate" type="date" required={false}/><Field label="Final-pay target date (reviewed)" name="finalPayTargetDate" type="date" required={false}/><label className="checkRow"><input type="checkbox" name="rehireEligible" defaultChecked={c.rehireEligible===true}/> Rehire eligible</label><label className="checkRow"><input type="checkbox" name="regrettable" defaultChecked={c.regrettable}/> Regrettable exit</label><label className="checkRow"><input type="checkbox" name="autoCloseOnEffectiveDate" defaultChecked={c.autoCloseOnEffectiveDate}/> Auto-close after effective date only when all closure gates pass</label><button className="button">Save HR controls</button></form></section>:null}
  {bundle?<section className="card"><h2 className="sectionTitle">Offboarding control plan</h2><div className="onboardingTaskList">{bundle.tasks.map(t=><div key={t.id} className={`onboardingTask ${t.status}`}><div><strong>{t.title}</strong><small>{t.ownerType} · {t.phase.replaceAll('_',' ')}{t.blockingClosure?' · closure gate':''}{t.dueAt?` · due ${new Date(t.dueAt).toLocaleDateString()}`:''}</small>{t.description?<small>{t.description}</small>:null}</div><span className="badge">{t.status}</span><div className="stepActions">{canActTask(t)&&!['completed','waived'].includes(t.status)?<><button className="button secondary compact" onClick={()=>task(t.id,'start')}>Start</button><button className="button compact" onClick={()=>task(t.id,'complete')}>Complete</button>{can('separation.approve')?<button className="button secondary compact" onClick={()=>task(t.id,'waive')}>Waive</button>:null}</>:can('separation.manage')&&['completed','waived'].includes(t.status)?<button className="button secondary compact" onClick={()=>task(t.id,'reopen')}>Reopen</button>:null}</div></div>)}</div></section>:null}
  {bundle&&can('separation.manage')?<div className="grid2"><section className="card"><h2 className="sectionTitle">Company property</h2><form className="assetForm" onSubmit={addAsset}><Field label="Asset tag" name="assetTag" required={false}/><Field label="Item" name="name"/><Field label="Category" name="category" required={false}/><Field label="Note" name="note" required={false}/><button className="button">Add</button></form><div className="assetList">{bundle.assets.map(a=><div className="assetRow" key={a.id}><div><strong>{a.name}</strong><small>{a.assetTag||'No asset tag'} · {a.status}</small></div><div className="stepActions">{a.status==='assigned'?<><button className="button compact" onClick={()=>asset(a.id,'returned')}>Returned</button><button className="button secondary compact" onClick={()=>asset(a.id,'lost')}>Lost</button><button className="button secondary compact" onClick={()=>asset(a.id,'damaged')}>Damaged</button></>:null}</div></div>)}</div></section><section className="card"><h2 className="sectionTitle">Replacement decision</h2><form className="stack" onSubmit={replacement}><label className="field"><span>Position decision</span><select className="input" name="replacementDecision" defaultValue={c?.replacementDecision||'pending'}><option value="pending">Pending</option><option value="replace">Replace</option><option value="do_not_replace">Do not replace</option><option value="redesign">Redesign before recruiting</option></select></label><Field label="Decision note" name="replacementNote" required={false}/><button className="button">Save decision</button></form>{c?.replacementDecision==='replace'?<div className="stack" style={{marginTop:12}}>{c.replacementRequisitionId?<div className="success">Replacement requisition created: {c.replacementRequisitionId}</div>:<button className="button secondary" type="button" onClick={createReplacement}>Create draft replacement requisition</button>}</div>:null}</section></div>:null}
  {bundle&&!bundle.exitInterview?<section className="card"><h2 className="sectionTitle">Exit interview</h2><form className="exitInterviewForm" onSubmit={interview}><Field label="Overall experience 1–5" name="overallExperience" type="number" required={false}/><Field label="Manager experience 1–5" name="managerExperience" type="number" required={false}/><Field label="Primary reason for leaving" name="reasonForLeaving" required={false}/><Field label="What worked well" name="whatWorkedWell" required={false}/><Field label="What should improve" name="whatCouldImprove" required={false}/><Field label="Next destination (optional)" name="destination" required={false}/><Field label="Themes, comma separated" name="themes" required={false}/><label className="checkRow"><input type="checkbox" name="wouldRecommend"/> Would recommend OPSIQO organization as employer</label><label className="checkRow"><input type="checkbox" name="wouldReturn"/> Would consider returning</label>{can('separation.manage')?<Field label="Confidential HR note" name="confidentialNote" required={false}/>:null}<button className="button">Submit exit interview</button></form></section>:bundle?.exitInterview?<section className="card"><h2 className="sectionTitle">Exit interview recorded</h2><p className="muted">Structured exit feedback has been captured for this separation case.</p></section>:null}
 </div>;
}
function Metric({label,value}:{label:string;value:number|string}){return <div className="card"><div className="metricLabel">{label}</div><div className="metricValue">{value}</div></div>}
function Field({label,name,type='text',required=true}:{label:string;name:string;type?:string;required?:boolean}){return <label className="field"><span>{label}</span><input className="input" name={name} type={type} required={required}/></label>}
