'use client';
import { useEffect,useState } from 'react';
import type { TranslationReadinessDashboard } from '@/domain/opsiqo-one-v7-18';
import { activeOrgId,apiFetch } from '@/lib/http/client';
import { useShellLocale } from '@/lib/opsiqo-one/shell-i18n';
import { runtimeUiTranslation } from '@/lib/opsiqo-one/runtime-ui-i18n';
import { LoadingState } from './data-states';
const text={
 en:{eyebrow:'OPSIQO ONE · Translation Readiness',title:'Make translation completion measurable',intro:'Track exact reviewed strings separately from the remaining legacy source backlog. This is evidence for completion work, not a linguistic-quality claim.',reviewed:'Exact candidates reviewed',remaining:'Candidates remaining',surfaces:'Catalogued surfaces',files:'TSX files scanned',backlog:'Largest remaining source backlogs',file:'Source file',total:'Candidates',done:'Reviewed',left:'Remaining',boundary:'Certification boundary'},
 fr:{eyebrow:'OPSIQO ONE · Préparation de la traduction',title:'Rendre la traduction mesurable',intro:'Suivez séparément les chaînes révisées exactement et le reste du code hérité. Il s’agit d’une preuve d’avancement, pas d’une affirmation de qualité linguistique.',reviewed:'Candidats exacts révisés',remaining:'Candidats restants',surfaces:'Surfaces cataloguées',files:'Fichiers TSX analysés',backlog:'Principaux retards de traduction',file:'Fichier source',total:'Candidats',done:'Révisés',left:'Restants',boundary:'Limite de certification'},
 es:{eyebrow:'OPSIQO ONE · Preparación de traducción',title:'Hacer medible la finalización de traducciones',intro:'Separa las cadenas revisadas exactamente del resto del código heredado. Es evidencia de avance, no una afirmación de calidad lingüística.',reviewed:'Candidatos exactos revisados',remaining:'Candidatos restantes',surfaces:'Superficies catalogadas',files:'Archivos TSX analizados',backlog:'Mayores pendientes de traducción',file:'Archivo fuente',total:'Candidatos',done:'Revisados',left:'Restantes',boundary:'Límite de certificación'},
 ar:{eyebrow:'OPSIQO ONE · جاهزية الترجمة',title:'جعل اكتمال الترجمة قابلاً للقياس',intro:'افصل النصوص التي تمت مراجعتها بدقة عن بقية النصوص الموروثة. هذه أدلة تقدم وليست ادعاءً بجودة الترجمة.',reviewed:'النصوص الدقيقة المراجعة',remaining:'النصوص المتبقية',surfaces:'الواجهات المفهرسة',files:'ملفات TSX المفحوصة',backlog:'أكبر قوائم الترجمة المتبقية',file:'ملف المصدر',total:'المرشحات',done:'تمت مراجعتها',left:'المتبقي',boundary:'حدود الاعتماد'},
};
export function TranslationReadinessWorkspace(){
 const locale=useShellLocale(),T=text[locale]||text.en,rt=(source:string)=>runtimeUiTranslation(source,locale)||source,[data,setData]=useState<TranslationReadinessDashboard|null>(null),[error,setError]=useState('');
 useEffect(()=>{apiFetch<{data:TranslationReadinessDashboard}>(`/api/organizations/${activeOrgId()}/opsiqo-one/translation-readiness`).then(r=>setData(r.data)).catch(e=>setError(e instanceof Error?e.message:'Unable to load translation readiness.'))},[]);
 if(!data)return <div className="stack">{error&&<div className="error" role="alert">{error}</div>}<LoadingState label={rt('Loading translation readiness evidence…')}/></div>;
 const pct=data.totalSourceCandidates?Math.round((data.reviewedSourceCandidates/data.totalSourceCandidates)*1000)/10:0;
 return <div className="stack"><section className="card oneHero"><div><span className="eyebrow">{T.eyebrow}</span><h1>{T.title}</h1><p className="muted">{T.intro}</p></div><span className="badge">{rt(`${pct}% exact-source reviewed`)}</span></section><div className="settingsGrid"><Metric label={T.reviewed} value={data.reviewedSourceCandidates}/><Metric label={T.remaining} value={data.remainingCandidates}/><Metric label={T.surfaces} value={data.cataloguedSurfaceCount}/><Metric label={T.files} value={data.scannedFiles}/></div><section className="card tableWrap"><h2 className="sectionTitle">{T.backlog}</h2><table><thead><tr><th>{T.file}</th><th>{T.total}</th><th>{T.done}</th><th>{T.left}</th></tr></thead><tbody>{data.topBacklog.map(row=><tr key={row.file}><td><code>{row.file}</code></td><td>{row.totalCandidates}</td><td>{row.reviewedCandidates}</td><td>{row.remainingCandidates}</td></tr>)}</tbody></table></section><section className="card"><strong>{T.boundary}</strong><p className="muted">{rt(data.boundary)}</p><p className="muted">{rt(`Snapshot: ${new Date(data.generatedAt).toLocaleString()} · Locales: ${data.supportedLocales.join(' · ')}`)}</p></section></div>;
}
function Metric({label,value}:{label:string;value:number|string}){return <div className="card metricCard"><div className="metricLabel">{label}</div><div className="metricValue">{value}</div></div>}
