import { createHash } from 'crypto';
import { adminDb } from '../src/lib/firebase/admin';
import { STANDARD_ANALYTICS_METRICS } from '../src/lib/people-analytics/service';
import { bootstrapOntarioDiagnostic, createDiagnosticAssessment, diagnosticDashboard, assessDiagnosticControl } from '../src/lib/hr-diagnostic/service';
import { permissionsForRole } from '../src/lib/auth/permissions';

const orgId = process.env.OPSIQO_DEMO_ORG_ID || 'demo-org';
const uid = process.env.OPSIQO_DEMO_UID || 'demo-admin';
const db = adminDb();
const timestamp = new Date().toISOString();

async function seed() {
  const batch = db.batch();
  batch.set(db.doc(`organizations/${orgId}`), {
    id: orgId,
    name: 'OPSIQO Demo Organization',
    status: 'active',
    createdAt: timestamp,
    updatedAt: timestamp,
  }, { merge: true });

  batch.set(db.doc(`organizations/${orgId}/memberships/${uid}`), {
    uid,
    workerId: 'worker-001',
    role: 'org_admin',
    status: 'active',
    createdAt: timestamp,
    updatedAt: timestamp,
  }, { merge: true });

  batch.set(db.doc(`organizations/${orgId}/memberships/demo-hr-manager`), { uid:'demo-hr-manager', workerId:'worker-002', role:'manager', status:'active', createdAt:timestamp, updatedAt:timestamp }, { merge:true });
  batch.set(db.doc(`organizations/${orgId}/memberships/demo-ops-manager`), { uid:'demo-ops-manager', workerId:'worker-003', role:'manager', status:'active', createdAt:timestamp, updatedAt:timestamp }, { merge:true });

  const units = [
    { id:'unit-executive', name:'Executive Office', code:'EXEC', type:'department' },
    { id:'unit-people', name:'People & Culture', code:'PPL', type:'department' },
    { id:'unit-operations', name:'Operations', code:'OPS', type:'department' },
  ];
  for (const unit of units) {
    batch.set(db.doc(`organizations/${orgId}/orgUnits/${unit.id}`), {
      ...unit, status:'active', createdAt:timestamp, updatedAt:timestamp,
    }, { merge:true });
  }

  const positions = [
    { id:'pos-ceo', positionCode:'P-001', title:'Chief Executive Officer', orgUnitId:'unit-executive', status:'filled', fte:1, headcountLimit:1 },
    { id:'pos-hrm', positionCode:'P-010', title:'HR Manager', orgUnitId:'unit-people', status:'filled', fte:1, headcountLimit:1, reportsToPositionId:'pos-ceo' },
    { id:'pos-hrc', positionCode:'P-011', title:'HR Coordinator', orgUnitId:'unit-people', status:'open', fte:1, headcountLimit:1, reportsToPositionId:'pos-hrm' },
    { id:'pos-hrd', positionCode:'P-012', title:'HR Director', orgUnitId:'unit-people', status:'open', fte:1, headcountLimit:1, reportsToPositionId:'pos-ceo', location:'Mississauga, ON' },
    { id:'pos-ops', positionCode:'P-020', title:'Operations Manager', orgUnitId:'unit-operations', status:'filled', fte:1, headcountLimit:1, reportsToPositionId:'pos-ceo' },
  ];
  for (const position of positions) {
    batch.set(db.doc(`organizations/${orgId}/positions/${position.id}`), {
      ...position, createdAt:timestamp, updatedAt:timestamp,
    }, { merge:true });
  }
  const occupancy: Record<string, number> = { 'pos-ceo':1, 'pos-hrm':1, 'pos-hrc':0, 'pos-hrd':0, 'pos-ops':1 };
  for (const [positionId, occupiedHeadcount] of Object.entries(occupancy)) {
    batch.set(db.doc(`organizations/${orgId}/positionOccupancy/${positionId}`), { positionId, occupiedHeadcount, occupiedFte:occupiedHeadcount, updatedAt:timestamp }, { merge:true });
  }

  const workers = [
    { id:'worker-001', personId:'person-001', employmentId:'employment-001', employeeNumber:'EMP-001', displayName:'Alex Morgan', legalFirstName:'Alex', legalLastName:'Morgan', workEmail:'alex@example.org', status:'active', hireDate:'2024-01-15', primaryAssignmentId:'assign-001', employmentType:'permanent' },
    { id:'worker-002', personId:'person-002', employmentId:'employment-002', employeeNumber:'EMP-002', displayName:'Jordan Lee', legalFirstName:'Jordan', legalLastName:'Lee', workEmail:'jordan@example.org', status:'active', hireDate:'2025-03-10', primaryAssignmentId:'assign-002', employmentType:'permanent' },
    { id:'worker-003', personId:'person-003', employmentId:'employment-003', employeeNumber:'EMP-003', displayName:'Sam Rivera', legalFirstName:'Sam', legalLastName:'Rivera', workEmail:'sam@example.org', status:'active', hireDate:'2025-09-02', primaryAssignmentId:'assign-003', employmentType:'permanent' },
  ];
  for (const worker of workers) {
    batch.set(db.doc(`organizations/${orgId}/people/${worker.personId}`), {
      id:worker.personId, legalFirstName:worker.legalFirstName, legalLastName:worker.legalLastName, workEmail:worker.workEmail, createdAt:timestamp, updatedAt:timestamp,
    }, { merge:true });
    batch.set(db.doc(`organizations/${orgId}/workers/${worker.id}`), {
      id:worker.id, personId:worker.personId, employeeNumber:worker.employeeNumber, employeeNumberLower:worker.employeeNumber.toLowerCase(), displayName:worker.displayName, displayNameLower:worker.displayName.toLowerCase(), workEmail:worker.workEmail, workEmailLower:worker.workEmail.toLowerCase(),
      status:worker.status, hireDate:worker.hireDate, primaryAssignmentId:worker.primaryAssignmentId, createdAt:timestamp, updatedAt:timestamp,
    }, { merge:true });
    batch.set(db.doc(`organizations/${orgId}/employments/${worker.employmentId}`), {
      id:worker.employmentId, workerId:worker.id, employmentType:worker.employmentType, startDate:worker.hireDate, fte:1, status:'active', createdAt:timestamp, updatedAt:timestamp,
    }, { merge:true });
    batch.set(db.doc(`organizations/${orgId}/employeeNumberIndex/${encodeURIComponent(worker.employeeNumber.toLowerCase())}`), { employeeNumber:worker.employeeNumber, workerId:worker.id, createdAt:timestamp }, { merge:true });
    batch.set(db.doc(`organizations/${orgId}/workEmailIndex/${encodeURIComponent(worker.workEmail.toLowerCase())}`), { workEmail:worker.workEmail.toLowerCase(), workerId:worker.id, createdAt:timestamp }, { merge:true });
  }

  const assignments = [
    { id:'assign-001', workerId:'worker-001', employmentId:'employment-001', positionId:'pos-ceo', orgUnitId:'unit-executive', primary:true, assignmentType:'primary', allocationFte:1, startDate:'2024-01-15' },
    { id:'assign-002', workerId:'worker-002', employmentId:'employment-002', positionId:'pos-hrm', orgUnitId:'unit-people', managerWorkerId:'worker-001', primary:true, assignmentType:'primary', allocationFte:1, startDate:'2025-03-10' },
    { id:'assign-003', workerId:'worker-003', employmentId:'employment-003', positionId:'pos-ops', orgUnitId:'unit-operations', managerWorkerId:'worker-001', primary:true, assignmentType:'primary', allocationFte:1, startDate:'2025-09-02' },
  ];
  for (const a of assignments) batch.set(db.doc(`organizations/${orgId}/assignments/${a.id}`), { ...a, createdAt:timestamp, updatedAt:timestamp }, { merge:true });

  const workflow = {
    id:'wf-new-hire', name:'New Hire Foundation', description:'Phase 1 onboarding control workflow', trigger:'employee.created', enabled:true, version:1,
    steps:[
      { id:'hr-verify', name:'Verify employee record', type:'task', ownerRole:'hr_admin', dueInDays:1, escalationOwnerRole:'org_admin', escalateAfterHours:4, dependsOn:[] },
      { id:'manager-ack', name:'Manager acknowledgement', type:'approval', ownerRole:'manager', dueInDays:2, escalationOwnerRole:'hr_admin', escalateAfterHours:4, dependsOn:['hr-verify'] },
      { id:'employee-notice', name:'Send employee welcome notice', type:'notification', ownerRole:'hr_admin', dueInDays:0, escalationOwnerRole:'org_admin', escalateAfterHours:4, dependsOn:['manager-ack'] },
    ],
    createdAt:timestamp, updatedAt:timestamp,
  };
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${workflow.id}`), workflow, { merge:true });

  const recruitingWorkflow = {
    id:'wf-offer-accepted', name:'Accepted Offer Handoff', description:'Recruiting-to-Core-HR handoff control', trigger:'offer.accepted', enabled:true, version:1,
    steps:[
      { id:'verify', name:'Verify accepted offer and start details', type:'task', ownerRole:'hr_admin', dueInDays:1, escalationOwnerRole:'org_admin', escalateAfterHours:4, dependsOn:[] },
      { id:'hire', name:'Authorize hire conversion', type:'approval', ownerRole:'hr_admin', dueInDays:1, escalationOwnerRole:'org_admin', escalateAfterHours:4, dependsOn:['verify'] },
    ], createdAt:timestamp, updatedAt:timestamp,
  };
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${recruitingWorkflow.id}`), recruitingWorkflow, { merge:true });

  const req = { id:'req-demo-001', requisitionNumber:'REQ-2026-0001', title:'HR Coordinator', positionId:'pos-hrc', orgUnitId:'unit-people', hiringManagerWorkerId:'worker-002', employmentType:'permanent', headcount:1, openingsRemaining:1, location:'Mississauga, ON', description:'Support the People & Culture function.', requirements:['HR administration','Employee service','HRIS accuracy'], status:'open', requestedBy:uid, approvedBy:uid, approvedAt:timestamp, openedAt:timestamp, createdAt:timestamp, updatedAt:timestamp };
  batch.set(db.doc(`organizations/${orgId}/requisitions/${req.id}`), req, { merge:true });
  batch.set(db.doc(`organizations/${orgId}/counters/requisition`), { value:1, updatedAt:timestamp }, { merge:true });
  const candidate = { id:'candidate-demo-001', firstName:'Taylor', lastName:'Chen', displayName:'Taylor Chen', email:'taylor.chen@example.com', emailLower:'taylor.chen@example.com', phone:'416-555-0182', source:'Referral', consentAt:timestamp, createdAt:timestamp, updatedAt:timestamp };
  batch.set(db.doc(`organizations/${orgId}/candidates/${candidate.id}`), candidate, { merge:true });
  batch.set(db.doc(`organizations/${orgId}/candidateEmailIndex/${encodeURIComponent(candidate.emailLower)}`), { candidateId:candidate.id, email:candidate.emailLower, createdAt:timestamp }, { merge:true });
  const app = { id:'application-demo-001', requisitionId:req.id, candidateId:candidate.id, stage:'screening', ownerUid:uid, source:'Referral', appliedAt:timestamp, updatedAt:timestamp };
  batch.set(db.doc(`organizations/${orgId}/applications/${app.id}`), app, { merge:true });
  batch.set(db.doc(`organizations/${orgId}/candidateApplicationIndex/${encodeURIComponent(`${candidate.id}_${req.id}`)}`), { applicationId:app.id, candidateId:candidate.id, requisitionId:req.id, createdAt:timestamp }, { merge:true });


  const demoPolicy = { id:'policy-demo-conduct', title:'Demo Workplace Conduct Policy', version:'demo-1.0', content:'DEMO DATA ONLY — Replace this content with an organization-approved policy before production use. Employees are expected to act respectfully, protect confidential information, and follow applicable workplace rules and reporting procedures.', status:'published', onboardingRequired:true, effectiveDate:'2026-08-10', createdAt:timestamp, updatedAt:timestamp };
  batch.set(db.doc(`organizations/${orgId}/onboardingPolicies/${demoPolicy.id}`), demoPolicy, { merge:true });
  const governedPolicyId='policy-demo-conduct-governed', governedVersionId='policy-demo-conduct-v1';
  batch.set(db.doc(`organizations/${orgId}/policies/${governedPolicyId}`), { id:governedPolicyId, code:'HR-001', title:'Demo Workplace Conduct Policy', ownerUid:uid, currentPublishedVersionId:governedVersionId, latestVersionNumber:1, status:'published', acknowledgementRequired:true, onboardingRequired:true, audience:'all_employees', reviewFrequencyMonths:12, nextReviewDate:'2027-08-10', createdAt:timestamp, updatedAt:timestamp }, { merge:true });
  batch.set(db.doc(`organizations/${orgId}/policyVersions/${governedVersionId}`), { id:governedVersionId, policyId:governedPolicyId, versionNumber:1, versionLabel:'1.0', content:demoPolicy.content, contentSha256:createHash('sha256').update(demoPolicy.content).digest('hex'), status:'published', effectiveDate:'2026-08-10', createdBy:uid, createdAt:timestamp, approvedBy:uid, approvedAt:timestamp, publishedBy:uid, publishedAt:timestamp }, { merge:true });
  batch.set(db.doc(`organizations/${orgId}/retentionRules/retention-employment-demo`), { id:'retention-employment-demo', name:'Demo employment-document review schedule', category:'employment', trigger:'document_created', retentionDays:2555, action:'review', legalBasisNote:'DEMO ONLY — replace with the organization-approved legal/records schedule before production.', enabled:true, createdBy:uid, createdAt:timestamp, updatedAt:timestamp }, { merge:true });
  batch.set(db.doc(`organizations/${orgId}/complianceRequirements/requirement-conduct-demo`), { id:'requirement-conduct-demo', name:'Workplace Conduct Policy acknowledgement', requirementType:'policy_ack', required:true, policyId:governedPolicyId, appliesTo:'all_employees', orgUnitIds:[], employmentTypes:[], expiryWarningDays:30, createdBy:uid, createdAt:timestamp, updatedAt:timestamp }, { merge:true });
  batch.set(db.doc(`organizations/${orgId}/complianceRequirements/requirement-employment-demo`), { id:'requirement-employment-demo', name:'Employment agreement on file', requirementType:'document', required:true, documentCategory:'employment', appliesTo:'all_employees', orgUnitIds:[], employmentTypes:[], expiryWarningDays:30, createdBy:uid, createdAt:timestamp, updatedAt:timestamp }, { merge:true });
  const onboardingReadyWorkflow = { id:'wf-onboarding-ready', name:'Prehire Activation Readiness', description:'Notify HR when mandatory pre-start controls are complete.', trigger:'onboarding.ready', enabled:true, version:1, steps:[{id:'activate-review',name:'Review activation readiness',type:'approval',ownerRole:'hr_admin',dueInDays:1,escalationOwnerRole:'org_admin',escalateAfterHours:4,dependsOn:[]}], createdAt:timestamp, updatedAt:timestamp };
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${onboardingReadyWorkflow.id}`), onboardingReadyWorkflow, { merge:true });
  const onboardingActivatedWorkflow = { id:'wf-onboarding-activated', name:'New Starter Activation', description:'Confirm day-one handoff after Core HR activation.', trigger:'onboarding.activated', enabled:true, version:1, steps:[{id:'manager-welcome',name:'Manager confirms first-day welcome',type:'task',ownerRole:'manager',dueInDays:1,escalationOwnerRole:'hr_admin',escalateAfterHours:8,dependsOn:[]}], createdAt:timestamp, updatedAt:timestamp };
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${onboardingActivatedWorkflow.id}`), onboardingActivatedWorkflow, { merge:true });

  // Phase 2 v0.8 leave, time and attendance demo configuration.
  // These are reference/demo settings only; verify the applicable ESA rules, exemptions,
  // employment agreements and collective agreements before production use.
  const ontCalendarId='holiday-calendar-on-2026';
  batch.set(db.doc(`organizations/${orgId}/holidayCalendars/${ontCalendarId}`), { id:ontCalendarId, name:'Ontario Public Holidays 2026 · Reference', jurisdiction:'Ontario, Canada', timezone:'America/Toronto', enabled:true, createdAt:timestamp, updatedAt:timestamp }, { merge:true });
  const ontHolidays=[
    ['2026-01-01',"New Year's Day"],['2026-02-16','Family Day'],['2026-04-03','Good Friday'],['2026-05-18','Victoria Day'],['2026-07-01','Canada Day'],['2026-09-07','Labour Day'],['2026-10-12','Thanksgiving Day'],['2026-12-25','Christmas Day'],['2026-12-26','Boxing Day'],
  ];
  for(const [date,name] of ontHolidays){const id=`on-${date}`;batch.set(db.doc(`organizations/${orgId}/holidays/${id}`),{id,calendarId:ontCalendarId,date,name,paidPublicHoliday:true,createdAt:timestamp,updatedAt:timestamp},{merge:true});}
  const timePolicyId='time-policy-on-reference';
  batch.set(db.doc(`organizations/${orgId}/timePolicies/${timePolicyId}`), { id:timePolicyId, name:'Ontario ESA Baseline · Advisory Reference', jurisdiction:'Ontario, Canada', timezone:'America/Toronto', weekStartsOn:1, standardDailyHours:8, regularWeeklyHours:40, overtimeThresholdHours:44, overtimeMultiplier:1.5, maxDailyHours:8, maxWeeklyHours:48, minDailyRestHours:11, minBetweenShiftsHours:8, weeklyRestHours:24, mealBreakAfterHours:5, mealBreakMinutes:30, roundingMinutes:15, complianceMode:'advisory', captureGeolocation:false, enabled:true, createdAt:timestamp, updatedAt:timestamp }, { merge:true });
  for(const w of workers)batch.set(db.doc(`organizations/${orgId}/workerTimeProfiles/${w.id}`),{id:w.id,workerId:w.id,timePolicyId,holidayCalendarId:ontCalendarId,workingDays:[1,2,3,4,5],standardDailyHours:8,overtimeEligible:true,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  const leaveTypes=[
    {id:'leave-vac-demo',code:'VAC',name:'Vacation · Demo employer plan',description:'Demo annual vacation bank. Replace with the organization-approved vacation entitlement/pay policy.',paid:true,statutory:false,jobProtected:false,unit:'hours',accrualMethod:'annual_grant',annualEntitlementHours:80,carryoverLimitHours:40,negativeBalanceAllowed:false,partialDayCharging:'actual_hours',requiresApproval:true,evidencePolicy:'No medical evidence applicable.',jurisdiction:'Ontario, Canada',enabled:true},
    {id:'leave-sick-on-ref',code:'ON-SICK',name:'Ontario sick leave · ESA reference',description:'Reference configuration for ESA sick leave; review eligibility, special rules and greater contractual rights.',paid:false,statutory:true,jobProtected:true,unit:'hours',accrualMethod:'annual_grant',annualEntitlementHours:24,carryoverLimitHours:0,negativeBalanceAllowed:false,partialDayCharging:'actual_hours',requiresApproval:false,evidencePolicy:'Do not require a medical note for ESA sick leave. Only reasonable evidence permitted by applicable law/policy.',jurisdiction:'Ontario, Canada',legalReferenceUrl:'https://www.ontario.ca/document/your-guide-employment-standards-act-0/sick-leave',enabled:true},
    {id:'leave-family-on-ref',code:'ON-FAM',name:'Ontario family responsibility leave · ESA reference',description:'Reference configuration only; review eligibility and covered family relationships.',paid:false,statutory:true,jobProtected:true,unit:'hours',accrualMethod:'annual_grant',annualEntitlementHours:24,carryoverLimitHours:0,negativeBalanceAllowed:false,partialDayCharging:'actual_hours',requiresApproval:false,evidencePolicy:'Do not require a medical note for the illness/injury/medical-emergency ground; collect only evidence permitted by applicable law.',jurisdiction:'Ontario, Canada',legalReferenceUrl:'https://www.ontario.ca/document/your-guide-employment-standards-act-0/family-responsibility-leave',enabled:true},
    {id:'leave-bereavement-on-ref',code:'ON-BER',name:'Ontario bereavement leave · ESA reference',description:'Reference configuration only; review eligibility and covered relationships.',paid:false,statutory:true,jobProtected:true,unit:'hours',accrualMethod:'annual_grant',annualEntitlementHours:16,carryoverLimitHours:0,negativeBalanceAllowed:false,partialDayCharging:'actual_hours',requiresApproval:false,evidencePolicy:'Request only evidence that is reasonable in the circumstances and permitted by applicable law.',jurisdiction:'Ontario, Canada',legalReferenceUrl:'https://www.ontario.ca/document/your-guide-employment-standards-act-0/bereavement-leave',enabled:true},
  ];
  for(const lt of leaveTypes)batch.set(db.doc(`organizations/${orgId}/leaveTypes/${lt.id}`),{...lt,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  const demoLeaveId='leave-request-demo-001';
  batch.set(db.doc(`organizations/${orgId}/leaveRequests/${demoLeaveId}`),{id:demoLeaveId,workerId:'worker-002',leaveTypeId:'leave-vac-demo',startDate:'2026-08-17',endDate:'2026-08-18',requestedHours:16,chargedHours:16,note:'Demo pending vacation request',status:'pending',submittedBy:'demo-hr-manager',submittedAt:timestamp,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  const demoEntryId='time-entry-demo-001';
  batch.set(db.doc(`organizations/${orgId}/timeEntries/${demoEntryId}`),{id:demoEntryId,workerId:'worker-001',startAt:'2026-08-10T13:00:00.000Z',endAt:'2026-08-10T21:00:00.000Z',breakMinutes:30,workedMinutes:450,source:'manual',status:'complete',note:'Demo shift',createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  const leaveWorkflow={id:'wf-leave-requested',name:'Leave Approval',description:'Route submitted leave to manager/HR approval.',trigger:'leave.requested',enabled:true,version:1,steps:[{id:'manager-review',name:'Review leave request',type:'approval',ownerRole:'manager',dueInDays:2,escalationOwnerRole:'hr_admin',escalateAfterHours:8,dependsOn:[]}],createdAt:timestamp,updatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${leaveWorkflow.id}`),leaveWorkflow,{merge:true});
  const timesheetWorkflow={id:'wf-timesheet-submitted',name:'Timesheet Approval',description:'Route a submitted timesheet to manager approval.',trigger:'timesheet.submitted',enabled:true,version:1,steps:[{id:'manager-approve',name:'Approve submitted timesheet',type:'approval',ownerRole:'manager',dueInDays:2,escalationOwnerRole:'hr_admin',escalateAfterHours:8,dependsOn:[]}],createdAt:timestamp,updatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${timesheetWorkflow.id}`),timesheetWorkflow,{merge:true});
  const separationReadyWorkflow={id:'wf-separation-ready',name:'Separation Closure Review',description:'Require HR review when an approved offboarding case reaches closure readiness.',trigger:'separation.ready',enabled:true,version:1,steps:[{id:'hr-close-review',name:'Review separation closure evidence',type:'approval',ownerRole:'hr_admin',dueInDays:1,escalationOwnerRole:'org_admin',escalateAfterHours:4,dependsOn:[]}],createdAt:timestamp,updatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${separationReadyWorkflow.id}`),separationReadyWorkflow,{merge:true});

  // Phase 3 v1.1 performance & goals demo data.
  const performanceCycle={id:'perf-cycle-2026',name:'FY2026 Performance Cycle',description:'Demo annual performance cycle with separate self, manager and calibration evidence.',status:'manager_review',periodStart:'2026-01-01',periodEnd:'2026-12-31',selfReviewDueAt:'2026-12-08T22:00:00.000Z',managerReviewDueAt:'2026-12-15T22:00:00.000Z',calibrationDueAt:'2026-12-22T22:00:00.000Z',ratingScale:[{value:1,label:'Does not meet'},{value:2,label:'Partially meets'},{value:3,label:'Meets expectations'},{value:4,label:'Exceeds expectations'},{value:5,label:'Exceptional'}],goalWeightPct:60,competencyWeightPct:40,minimum360Responses:3,createdBy:uid,activatedBy:uid,activatedAt:timestamp,createdAt:timestamp,updatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/performanceCycles/${performanceCycle.id}`),performanceCycle,{merge:true});
  const competencies=[
    {id:'competency-collaboration',code:'COLLAB',name:'Collaboration',description:'Works constructively across teams and builds trust.',category:'Core',behaviors:['Shares information proactively','Builds productive cross-functional relationships'],enabled:true},
    {id:'competency-accountability',code:'ACCOUNT',name:'Accountability',description:'Owns commitments and follows through with evidence.',category:'Core',behaviors:['Meets agreed commitments','Raises risks early and proposes solutions'],enabled:true},
    {id:'competency-people-leadership',code:'LEAD',name:'People Leadership',description:'Creates clarity, feedback, development and accountability.',category:'Leadership',behaviors:['Sets clear expectations','Provides timely coaching and feedback'],enabled:true},
  ];
  for(const c of competencies)batch.set(db.doc(`organizations/${orgId}/competencies/${c.id}`),{...c,createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/competencyExpectations/pos-hrm_competency-collaboration`),{id:'pos-hrm_competency-collaboration',positionId:'pos-hrm',competencyId:'competency-collaboration',requiredLevel:4,weightPct:50,createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/competencyExpectations/pos-hrm_competency-people-leadership`),{id:'pos-hrm_competency-people-leadership',positionId:'pos-hrm',competencyId:'competency-people-leadership',requiredLevel:4,weightPct:50,createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/performanceGoals/goal-demo-001`),{id:'goal-demo-001',workerId:'worker-002',cycleId:performanceCycle.id,title:'Launch manager monthly check-ins',description:'Establish a consistent monthly check-in rhythm across the People team.',type:'smart',status:'active',weightPct:40,progressPct:65,startDate:'2026-01-01',dueDate:'2026-11-30',metric:'Monthly check-in completion',targetValue:'90%+',currentValue:'65%',evidence:'Initial manager adoption measured through HRIS check-in records.',createdBy:'demo-hr-manager',createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/performanceGoals/goal-demo-002`),{id:'goal-demo-002',workerId:'worker-002',cycleId:performanceCycle.id,title:'Improve HR data completeness',description:'Reduce missing critical workforce data and unresolved HRIS data-quality findings.',type:'okr',status:'active',weightPct:60,progressPct:80,startDate:'2026-01-01',dueDate:'2026-12-15',metric:'Lifecycle data quality score',targetValue:'95/100',currentValue:'90/100',evidence:'Tracked through lifecycle diagnostic snapshots.',createdBy:'demo-hr-manager',createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/performanceReviews/${performanceCycle.id}_worker-002`),{id:`${performanceCycle.id}_worker-002`,cycleId:performanceCycle.id,workerId:'worker-002',managerWorkerId:'worker-001',status:'awaiting_manager',selfOverallRating:4,selfSummary:'Delivered core HR foundation work and improved process visibility while continuing to build manager adoption.',selfItems:[{key:'results',label:'Results & delivery',rating:4,comment:'Major HRIS and process milestones delivered.'},{key:'collaboration',label:'Collaboration',rating:4,comment:'Strong cross-functional partnership.'},{key:'growth',label:'Learning & growth',rating:4,comment:'Expanded analytics and governance capability.'}],selfSubmittedAt:timestamp,managerItems:[],createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/performanceReviews/${performanceCycle.id}_worker-003`),{id:`${performanceCycle.id}_worker-003`,cycleId:performanceCycle.id,workerId:'worker-003',managerWorkerId:'worker-001',status:'not_started',selfItems:[],managerItems:[],createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/developmentPlans/dev-demo-001`),{id:'dev-demo-001',workerId:'worker-002',cycleId:performanceCycle.id,title:'Strategic HR leadership development',objective:'Strengthen strategic workforce planning and executive advisory capability.',status:'active',actions:[{id:'dev-act-1',title:'Lead quarterly workforce planning review',dueDate:'2026-09-30',status:'in_progress'},{id:'dev-act-2',title:'Complete advanced people analytics learning',dueDate:'2026-11-30',status:'planned'}],ownerWorkerId:'worker-002',managerWorkerId:'worker-001',createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  const performanceWorkflow={id:'wf-performance-review-submitted',name:'Performance Review Follow-up',description:'Route submitted performance evidence into the next governed review step.',trigger:'performance.review_submitted',enabled:true,version:1,steps:[{id:'review-next-step',name:'Confirm next review stage',type:'task',ownerRole:'hr_partner',dueInDays:2,escalationOwnerRole:'hr_admin',escalateAfterHours:8,dependsOn:[]}],createdAt:timestamp,updatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${performanceWorkflow.id}`),performanceWorkflow,{merge:true});

  // Phase 3 v1.2 skills intelligence + LMS demo data.
  const learningSkills=[
    {id:'skill-people-analytics',code:'PPL-AN',name:'People Analytics',description:'Uses workforce data to identify patterns, explain drivers and support decisions.',category:'People',evidenceRequired:true},
    {id:'skill-employee-relations',code:'ER',name:'Employee Relations',description:'Applies policy, documentation, investigation and fair-process practices to workplace issues.',category:'People',evidenceRequired:true},
    {id:'skill-people-leadership',code:'PPL-LEAD',name:'People Leadership',description:'Sets expectations, coaches, develops and holds people accountable.',category:'Leadership',evidenceRequired:true},
  ];
  for(const sk of learningSkills){batch.set(db.doc(`organizations/${orgId}/skills/${sk.id}`),{...sk,enabled:true,proficiencyLabels:[{level:1,label:'Awareness'},{level:2,label:'Working'},{level:3,label:'Proficient'},{level:4,label:'Advanced'},{level:5,label:'Expert'}],createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});batch.set(db.doc(`organizations/${orgId}/skillCodeIndex/${sk.code}`),{skillId:sk.id,code:sk.code,createdAt:timestamp},{merge:true});}
  const skillRequirements=[
    {id:'pos-hrm_skill-people-analytics',positionId:'pos-hrm',skillId:'skill-people-analytics',requiredLevel:4,criticality:'required',weightPct:35},
    {id:'pos-hrm_skill-employee-relations',positionId:'pos-hrm',skillId:'skill-employee-relations',requiredLevel:4,criticality:'required',weightPct:35},
    {id:'pos-hrm_skill-people-leadership',positionId:'pos-hrm',skillId:'skill-people-leadership',requiredLevel:4,criticality:'important',weightPct:30},
  ];
  for(const r of skillRequirements)batch.set(db.doc(`organizations/${orgId}/positionSkillRequirements/${r.id}`),{...r,createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/workerSkills/worker-002_skill-people-analytics`),{id:'worker-002_skill-people-analytics',workerId:'worker-002',skillId:'skill-people-analytics',level:2,status:'self_reported',source:'self',evidenceNote:'Uses standard HR reports and basic spreadsheet analysis.',assessedAt:timestamp,createdBy:'demo-hr-manager',createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/workerSkills/worker-002_skill-employee-relations`),{id:'worker-002_skill-employee-relations',workerId:'worker-002',skillId:'skill-employee-relations',level:4,status:'evidence_verified',source:'manager',evidenceNote:'Verified through documented complex employee-relations case work.',assessedAt:timestamp,verifiedBy:uid,verifiedAt:timestamp,createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/workerSkills/worker-002_skill-people-leadership`),{id:'worker-002_skill-people-leadership',workerId:'worker-002',skillId:'skill-people-leadership',level:3,status:'manager_verified',source:'manager',evidenceNote:'Regular coaching and team planning demonstrated; advanced capability still developing.',assessedAt:timestamp,verifiedBy:uid,verifiedAt:timestamp,createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  const analyticsCourse={id:'course-people-analytics-advanced',code:'PPLAN401',title:'Advanced People Analytics for HR Decisions',description:'Build evidence-based workforce insights from clean HR data and communicate decision implications.',status:'published',delivery:'self_paced',durationMinutes:120,provider:'OPSIQO Academy',skillMappings:[{skillId:'skill-people-analytics',targetLevel:4,weightPct:100}],assessmentQuestions:[{id:'pplan-q1',prompt:'Which approach best demonstrates evidence-based people analytics?',options:['Define the workforce question, validate data, analyze drivers, and document limits','Start with a preferred conclusion and find supporting metrics','Use only one headline KPI without checking context'],correctOption:0,points:1},{id:'pplan-q2',prompt:'A turnover increase is concentrated among new hires. What should be examined next?',options:['Tenure-segmented exits, source quality, onboarding, manager and role patterns','Ignore tenure and report only total turnover','Assume compensation is the sole cause'],correctOption:0,points:1}],passingScorePct:100,certificateValidityDays:730,mandatory:false,createdBy:uid,publishedAt:timestamp,createdAt:timestamp,updatedAt:timestamp};
  const leaderCourse={id:'course-manager-coaching',code:'LEAD301',title:'Evidence-Based Coaching for Managers',description:'Practice clear expectations, timely feedback, documentation and development conversations.',status:'published',delivery:'blended',durationMinutes:90,provider:'OPSIQO Academy',skillMappings:[{skillId:'skill-people-leadership',targetLevel:4,weightPct:100}],assessmentQuestions:[{id:'lead-q1',prompt:'What is the strongest coaching evidence?',options:['Specific observed behaviour, impact, agreed action and follow-up','A personality label without examples','A vague annual rating only'],correctOption:0,points:1}],passingScorePct:100,certificateValidityDays:730,mandatory:false,createdBy:uid,publishedAt:timestamp,createdAt:timestamp,updatedAt:timestamp};
  const erCourse={id:'course-er-evidence-demo',code:'ER401',title:'Advanced Employee Relations Evidence',description:'Demonstrate structured ER case analysis, fair process, documentation and risk controls.',status:'published',delivery:'external',durationMinutes:60,provider:'OPSIQO Academy',skillMappings:[{skillId:'skill-employee-relations',targetLevel:4,weightPct:100}],assessmentQuestions:[],certificateValidityDays:365,mandatory:false,createdBy:uid,publishedAt:timestamp,createdAt:timestamp,updatedAt:timestamp};
  for(const c of [analyticsCourse,leaderCourse,erCourse]){batch.set(db.doc(`organizations/${orgId}/courses/${c.id}`),c,{merge:true});batch.set(db.doc(`organizations/${orgId}/courseCodeIndex/${c.code}`),{courseId:c.id,code:c.code,createdAt:timestamp},{merge:true});}
  batch.set(db.doc(`organizations/${orgId}/learningPaths/path-hr-manager-growth`),{id:'path-hr-manager-growth',code:'HRM-GROWTH',title:'HR Manager Growth Path',description:'Targeted path for advanced people analytics and people leadership capability.',courseIds:[analyticsCourse.id,leaderCourse.id],targetPositionIds:['pos-hrm'],targetSkillIds:['skill-people-analytics','skill-people-leadership'],status:'published',createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/learningPathCodeIndex/HRM-GROWTH`),{pathId:'path-hr-manager-growth',code:'HRM-GROWTH',createdAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/learningAssignments/learning-demo-001`),{id:'learning-demo-001',workerId:'worker-002',courseId:analyticsCourse.id,pathId:'path-hr-manager-growth',reason:'skill_gap',status:'in_progress',assignedBy:uid,assignedAt:timestamp,dueAt:'2026-09-30T21:00:00.000Z',startedAt:timestamp,progressPct:40,attempts:0,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/learningCertificates/cert-demo-er`),{id:'cert-demo-er',workerId:'worker-002',courseId:'course-er-evidence-demo',assignmentId:'legacy-demo-er',certificateNumber:'OP-2026-DEMOER',verificationCode:'DEMOER2026',status:'valid',issuedAt:'2026-02-01T14:00:00.000Z',expiresAt:'2027-02-01T14:00:00.000Z',createdAt:timestamp,updatedAt:timestamp},{merge:true});
  const learningWorkflow={id:'wf-learning-completed',name:'Learning Completion Follow-up',description:'Connect completed learning to development and capability review.',trigger:'learning.completed',enabled:true,version:1,steps:[{id:'manager-verify-application',name:'Confirm application of learned capability',type:'task',ownerRole:'manager',dueInDays:14,escalationOwnerRole:'hr_partner',escalateAfterHours:24,dependsOn:[]}],createdAt:timestamp,updatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${learningWorkflow.id}`),learningWorkflow,{merge:true});

  // Phase 3 v1.3 career, mobility and succession demo data.
  for(const r of [
    {id:'pos-hrd_skill-people-analytics',positionId:'pos-hrd',skillId:'skill-people-analytics',requiredLevel:4,criticality:'required',weightPct:35},
    {id:'pos-hrd_skill-employee-relations',positionId:'pos-hrd',skillId:'skill-employee-relations',requiredLevel:4,criticality:'required',weightPct:30},
    {id:'pos-hrd_skill-people-leadership',positionId:'pos-hrd',skillId:'skill-people-leadership',requiredLevel:4,criticality:'required',weightPct:35},
  ]) batch.set(db.doc(`organizations/${orgId}/positionSkillRequirements/${r.id}`),{...r,createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/performanceReviews/2025_worker-002`),{id:'2025_worker-002',cycleId:'cycle-2025',workerId:'worker-002',managerWorkerId:'worker-001',status:'completed',managerOverallRating:4.1,managerSummary:'Strong sustained delivery with growing strategic breadth.',managerItems:[],selfItems:[],managerSubmittedAt:'2025-12-15T15:00:00.000Z',calibratedRating:4,calibrationNote:'Calibrated against organization-wide evidence.',calibratedBy:uid,calibratedAt:'2025-12-20T15:00:00.000Z',finalRating:4,createdAt:'2025-12-01T15:00:00.000Z',updatedAt:'2025-12-20T15:00:00.000Z'},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/careerReadinessPolicies/default`),{id:'default',skillsWeightPct:70,performanceWeightPct:20,learningWeightPct:10,minimumPerformanceRating:3,updatedBy:uid,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/careerProfiles/worker-002`),{id:'worker-002',workerId:'worker-002',headline:'People leader progressing toward HR Director readiness',aspirationSummary:'Build strategic workforce planning, advanced analytics and enterprise leadership capability.',targetPositionIds:['pos-hrd'],careerHorizon:'within_1_year',mobilityStatus:'selective',preferredLocations:['Mississauga, ON','Toronto, ON'],openToRemote:true,openToRelocation:false,developmentPriorities:['Advance people analytics from working to advanced proficiency','Broaden enterprise leadership exposure'],visibility:'employee_manager_hr',createdBy:'demo-hr-manager',createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/internalMobilityInterests/worker-002_pos-hrd`),{id:'worker-002_pos-hrd',workerId:'worker-002',positionId:'pos-hrd',status:'interested',note:'Interested in a future HR Director opportunity after closing remaining readiness gaps.',createdBy:'demo-hr-manager',createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/criticalPositions/pos-hrm`),{id:'pos-hrm',positionId:'pos-hrm',criticality:'critical',lossImpact:'Loss of the HR Manager would materially affect employee relations, manager support and HR service continuity.',vacancyRisk:'medium',targetSuccessors:2,reviewDueDate:'2026-12-15',ownerWorkerId:'worker-001',businessContinuityNote:'CEO acts as interim escalation owner while an identified successor is transitioned.',createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/successorNominations/pos-hrm_worker-003`),{id:'pos-hrm_worker-003',positionId:'pos-hrm',workerId:'worker-003',readiness:'1_2_years',status:'nominated',nominationReason:'Demonstrated operational leadership and people-management exposure, with substantial HR-specific development still required.',evidence:['Leads a core operating function and manages cross-functional delivery.'],developmentPriorities:['Build employee-relations capability','Complete foundational HR governance learning'],nominatedBy:uid,nominatedAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/talentAssessments/worker-002_2026`),{id:'worker-002_2026',workerId:'worker-002',cycleLabel:'2026 Talent Review',potentialRating:3,potentialEvidence:'Sustained high performance, demonstrated learning agility, explicit aspiration for broader HR leadership and evidence of increasing strategic scope.',learningAgilityRating:3,aspirationRating:3,mobilityRating:2,leadershipBreadthRating:2,performanceBand:'high',nineBoxCell:'High performance / High potential',assessedBy:uid,assessedAt:timestamp,calibrationNote:'Human-calibrated assessment based on documented performance, aspiration conversation and observed leadership scope.',updatedAt:timestamp},{merge:true});
  const successionWorkflow={id:'wf-succession-review-due',name:'Succession Review Due',description:'Escalate overdue critical-position succession reviews to HR leadership.',trigger:'succession.review_due',enabled:true,version:1,steps:[{id:'refresh-plan',name:'Refresh successor coverage and development evidence',type:'task',ownerRole:'hr_admin',dueInDays:7,escalationOwnerRole:'org_admin',escalateAfterHours:24,dependsOn:[]}],createdAt:timestamp,updatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${successionWorkflow.id}`),successionWorkflow,{merge:true});

  const notificationTemplates=[
    {id:'template-onboarding-overdue',code:'ONBOARDING_TASK_OVERDUE',name:'Onboarding task overdue',subject:'Onboarding action required for {{workerName}}',body:'{{taskTitle}} is overdue for {{workerName}}. Review the onboarding case and complete or formally waive the control.',channels:['in_app','email'],variables:['workerName','taskTitle'],enabled:true},
    {id:'template-time-exception',code:'TIME_EXCEPTION_HIGH',name:'High-risk time exception',subject:'Time exception requires review',body:'{{workerName}} has a high-risk time exception: {{exceptionMessage}}',channels:['in_app'],variables:['workerName','exceptionMessage'],enabled:true},
    {id:'template-separation-ready',code:'SEPARATION_READY',name:'Separation ready for closure',subject:'Separation ready for HR closure',body:'Separation case {{caseId}} for {{workerName}} has reached its effective date and passed closure gates.',channels:['in_app','email'],variables:['caseId','workerName'],enabled:true},
  ];
  for(const t of notificationTemplates)batch.set(db.doc(`organizations/${orgId}/notificationTemplates/${t.id}`),{...t,createdBy:uid,createdAt:timestamp,updatedBy:uid,updatedAt:timestamp},{merge:true});


  // Phase 3 v1.4 compensation, job architecture and total rewards demo data.
  const compFamilies=[
    {id:'jf-executive',code:'EXEC',name:'Executive Leadership',description:'Enterprise executive leadership roles.',status:'active'},
    {id:'jf-people',code:'PEOPLE',name:'People & Culture',description:'Human resources and people leadership roles.',status:'active'},
    {id:'jf-operations',code:'OPS',name:'Operations',description:'Operational delivery and management roles.',status:'active'},
  ];
  for(const f of compFamilies){batch.set(db.doc(`organizations/${orgId}/jobFamilies/${f.id}`),{...f,createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});batch.set(db.doc(`organizations/${orgId}/jobFamilyCodeIndex/${f.code}`),{entityId:f.id,code:f.code,updatedAt:timestamp},{merge:true});}
  const compLevels=[
    {id:'jl-exec',code:'E1',name:'Executive',rank:5,status:'active'},
    {id:'jl-manager',code:'M1',name:'Manager',rank:3,status:'active'},
    {id:'jl-coordinator',code:'P2',name:'Professional / Coordinator',rank:2,status:'active'},
  ];
  for(const l of compLevels){batch.set(db.doc(`organizations/${orgId}/jobLevels/${l.id}`),{...l,createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});batch.set(db.doc(`organizations/${orgId}/jobLevelCodeIndex/${l.code}`),{entityId:l.id,code:l.code,updatedAt:timestamp},{merge:true});}
  const bands=[
    {id:'band-exec-e1',code:'EXEC-E1',name:'Executive E1',jobFamilyId:'jf-executive',levelId:'jl-exec',currency:'CAD',payBasis:'annual_salary',min:135000,midpoint:165000,max:195000,location:'Ontario',effectiveDate:'2026-01-01',status:'active'},
    {id:'band-people-m1',code:'PEOPLE-M1',name:'People Manager M1',jobFamilyId:'jf-people',levelId:'jl-manager',currency:'CAD',payBasis:'annual_salary',min:78000,midpoint:92000,max:106000,location:'Ontario',effectiveDate:'2026-01-01',status:'active'},
    {id:'band-people-p2',code:'PEOPLE-P2',name:'People Professional P2',jobFamilyId:'jf-people',levelId:'jl-coordinator',currency:'CAD',payBasis:'annual_salary',min:55000,midpoint:65000,max:75000,location:'Ontario',effectiveDate:'2026-01-01',status:'active'},
    {id:'band-ops-m1',code:'OPS-M1',name:'Operations Manager M1',jobFamilyId:'jf-operations',levelId:'jl-manager',currency:'CAD',payBasis:'annual_salary',min:76000,midpoint:90000,max:104000,location:'Ontario',effectiveDate:'2026-01-01',status:'active'},
  ];
  for(const b of bands){batch.set(db.doc(`organizations/${orgId}/salaryBands/${b.id}`),{...b,createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});batch.set(db.doc(`organizations/${orgId}/salaryBandCodeIndex/${b.code}`),{entityId:b.id,code:b.code,updatedAt:timestamp},{merge:true});}
  const compProfiles=[
    {id:'pos-ceo',positionId:'pos-ceo',jobFamilyId:'jf-executive',levelId:'jl-exec',salaryBandId:'band-exec-e1'},
    {id:'pos-hrm',positionId:'pos-hrm',jobFamilyId:'jf-people',levelId:'jl-manager',salaryBandId:'band-people-m1',marketBenchmarkId:'market-hr-manager-on'},
    {id:'pos-hrc',positionId:'pos-hrc',jobFamilyId:'jf-people',levelId:'jl-coordinator',salaryBandId:'band-people-p2'},
    {id:'pos-hrd',positionId:'pos-hrd',jobFamilyId:'jf-people',levelId:'jl-exec',salaryBandId:'band-exec-e1'},
    {id:'pos-ops',positionId:'pos-ops',jobFamilyId:'jf-operations',levelId:'jl-manager',salaryBandId:'band-ops-m1'},
  ];
  for(const cp of compProfiles)batch.set(db.doc(`organizations/${orgId}/positionCompensationProfiles/${cp.id}`),{...cp,updatedBy:uid,updatedAt:timestamp},{merge:true});
  const currentComp=[
    {id:'comp-worker-001-2026',workerId:'worker-001',effectiveDate:'2026-01-01',currency:'CAD',payBasis:'annual_salary',basePay:170000,annualizedBasePay:170000,variableTargetPct:15,allowancesAnnual:6000,changeReason:'market'},
    {id:'comp-worker-002-2026',workerId:'worker-002',effectiveDate:'2026-01-01',currency:'CAD',payBasis:'annual_salary',basePay:88000,annualizedBasePay:88000,variableTargetPct:8,allowancesAnnual:1200,changeReason:'merit'},
    {id:'comp-worker-003-2026',workerId:'worker-003',effectiveDate:'2026-01-01',currency:'CAD',payBasis:'annual_salary',basePay:91000,annualizedBasePay:91000,variableTargetPct:5,allowancesAnnual:1000,changeReason:'market'},
  ];
  for(const c of currentComp){const row={...c,createdBy:uid,createdAt:timestamp};batch.set(db.doc(`organizations/${orgId}/workerCompensationRecords/${c.id}`),row,{merge:true});batch.set(db.doc(`organizations/${orgId}/workerCompensationCurrent/${c.workerId}`),row,{merge:true});}
  batch.set(db.doc(`organizations/${orgId}/marketBenchmarks/market-hr-manager-on`),{id:'market-hr-manager-on',code:'HRM-ON-2026',title:'HR Manager — Ontario reference market',source:'Demo market dataset — replace with licensed/approved survey data',sourceDate:'2026-06-01',currency:'CAD',location:'Ontario',jobFamilyId:'jf-people',levelId:'jl-manager',positionId:'pos-hrm',p25:82000,p50:93000,p75:105000,p90:118000,note:'DEMO DATA ONLY. Not an external market survey.',createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/totalRewardsInputs/worker-002`),{workerId:'worker-002',asOfDate:'2026-08-10',employerBenefitsValue:8500,employerRetirementValue:4400,otherRewardsValue:1000,updatedBy:uid,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/compensationCycles/cycle-2027-annual`),{id:'cycle-2027-annual',name:'2027 Annual Compensation Review',cycleYear:2027,effectiveDate:'2027-01-01',currency:'CAD',status:'open',budgetPct:3.5,eligibilityNote:'Demo annual cycle. Eligibility requires HR review against policy and employment status.',createdBy:uid,createdAt:timestamp,updatedAt:timestamp,openedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/compensationRecommendations/cycle-2027-annual_worker-002`),{id:'cycle-2027-annual_worker-002',cycleId:'cycle-2027-annual',workerId:'worker-002',managerWorkerId:'worker-001',type:'merit',currentBasePay:88000,proposedIncreasePct:3,proposedIncreaseAmount:2640,proposedBasePay:90640,lumpSumAmount:0,currency:'CAD',rationale:'Demo recommendation based on documented contribution, internal range position and approved budget.',evidenceRefs:['2025 completed performance review','PEOPLE-M1 salary band'],status:'draft',submittedBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/payEquityJobClasses/HRCOORD`),{id:'HRCOORD',code:'HRCOORD',name:'HR Coordinator',establishmentId:'main',genderPredominance:'female',jobRate:65000,currency:'CAD',skillPoints:25,effortPoints:20,responsibilityPoints:25,workingConditionsPoints:10,totalValuePoints:80,comparatorMethod:'job_to_job',comparatorJobClassIds:['OPSSPEC'],reviewStatus:'review_required',legalBasisNote:'Demo job-class record; predominance and comparator selection require qualified review.',createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/payEquityJobClasses/OPSSPEC`),{id:'OPSSPEC',code:'OPSSPEC',name:'Operations Specialist',establishmentId:'main',genderPredominance:'male',jobRate:69000,currency:'CAD',skillPoints:25,effortPoints:20,responsibilityPoints:25,workingConditionsPoints:10,totalValuePoints:80,comparatorMethod:'not_assessed',comparatorJobClassIds:[],reviewStatus:'reviewed',legalBasisNote:'Demo comparator evidence only.',createdBy:uid,createdAt:timestamp,updatedAt:timestamp,lastReviewedAt:timestamp,lastReviewedBy:uid},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/payTransparencyPolicies/default`),{id:'default',jurisdiction:'Ontario, Canada',effectiveDate:'2026-01-01',employerEmployeeThreshold:25,rangeMaxSpreadAnnual:50000,exceptionAboveAnnual:200000,postingRetentionYears:3,interviewDecisionNoticeDays:45,enabled:true,updatedBy:uid,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/requisitionCompensationDisclosures/${req.id}`),{id:req.id,requisitionId:req.id,publiclyAdvertised:true,currency:'CAD',expectedMin:58000,expectedMax:72000,annualized:true,vacancyExists:'yes',aiUsedInScreening:false,validatedStatus:'validated',validationNotes:[],createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  const compensationWorkflow={id:'wf-compensation-changed',name:'Compensation Change Payroll Handoff',description:'Verify an approved compensation change reaches payroll and employee communication controls.',trigger:'compensation.changed',enabled:true,version:1,steps:[{id:'payroll-handoff',name:'Verify payroll effective-dated change',type:'task',ownerRole:'hr_admin',dueInDays:2,escalationOwnerRole:'org_admin',escalateAfterHours:24,dependsOn:[]},{id:'employee-letter',name:'Release compensation change communication',type:'task',ownerRole:'hr_admin',dueInDays:3,escalationOwnerRole:'org_admin',escalateAfterHours:24,dependsOn:['payroll-handoff']}],createdAt:timestamp,updatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${compensationWorkflow.id}`),compensationWorkflow,{merge:true});


  // Phase 3 v1.5 employee-relations demo evidence. Demo only; replace with organization-approved records/processes.
  const erCase={id:'er-demo-001',referenceNumber:'ER-2026-00001',type:'workplace_harassment',title:'Demo respectful-workplace concern',summary:'DEMO DATA ONLY — A confidential concern was reported for testing the case-management workflow. This is not a real allegation.',status:'investigating',riskLevel:'medium',confidentiality:'highly_confidential',reporterUid:uid,reporterWorkerId:'worker-002',affectedWorkerIds:['worker-002'],respondentWorkerIds:['worker-003'],reportedAt:timestamp,investigationRequired:true,investigationTargetDate:'2026-11-08',investigationTargetSource:'Ontario workplace-harassment investigation guidance target; operational target, not a statutory deadline.',outcomeNoticeRequired:true,legalHoldActive:false,createdBy:uid,createdAt:timestamp,updatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/employeeRelationsCases/${erCase.id}`),erCase,{merge:true});
  batch.set(db.doc(`organizations/${orgId}/employeeRelationsCaseTeam/${erCase.id}_${uid}`),{id:`${erCase.id}_${uid}`,caseId:erCase.id,uid,workerId:'worker-001',role:'investigator',conflictStatus:'cleared',conflictNote:'Demo conflict declaration: no known conflict.',assignedBy:uid,assignedAt:timestamp,conflictDeclaredAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/employeeRelationsActions/er-action-demo-001`),{id:'er-action-demo-001',caseId:erCase.id,type:'monitoring',title:'Document interim workplace safeguards',description:'Demo action to confirm interim safeguards and non-retaliation expectations.',ownerRole:'hr_admin',blockingClosure:true,status:'open',dueAt:'2026-08-20T17:00:00.000Z',createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/employeeAccommodationPlans/accom-demo-001`),{id:'accom-demo-001',caseId:'er-demo-accommodation',workerId:'worker-003',functionalLimitations:['Avoid continuous standing longer than 30 minutes'],abilities:['Can perform essential administrative and supervisory duties'],accommodationMeasures:['Provide sit/stand workstation','Allow brief position changes as needed'],status:'active',startDate:'2026-08-01',reviewDate:'2026-09-01',privacyNote:'DEMO DATA ONLY. Store functional limitations and necessary accommodation information; avoid unnecessary diagnosis/treatment information.',createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  const erWorkflow={id:'wf-er-case-opened',name:'Confidential Employee Relations Triage',description:'Route new ER cases to confidential HR triage without automated findings or disciplinary conclusions.',trigger:'er.case_opened',enabled:true,version:1,steps:[{id:'triage',name:'Confidential HR triage and immediate-risk review',type:'task',ownerRole:'hr_admin',dueInDays:1,escalationOwnerRole:'org_admin',escalateAfterHours:12,dependsOn:[]},{id:'assign',name:'Assign conflict-cleared case team',type:'task',ownerRole:'hr_admin',dueInDays:2,escalationOwnerRole:'org_admin',escalateAfterHours:24,dependsOn:['triage']}],createdAt:timestamp,updatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${erWorkflow.id}`),erWorkflow,{merge:true});
  batch.set(db.doc(`organizations/${orgId}/counters/employeeRelations`),{value:1,updatedAt:timestamp},{merge:true});

  // Phase 3 v1.6 Health, Safety & Incident Management demo records. Demo only.
  const safetyIncident={id:'safety-inc-demo-001',referenceNumber:'INC-2026-00001',type:'near_miss',title:'Demo loading-area near miss',description:'DEMO DATA ONLY — A cart rolled unexpectedly in the loading area. No injury occurred. Used to demonstrate investigation and corrective-action controls.',severity:'moderate',status:'investigating',reporterUid:uid,reporterWorkerId:'worker-003',affectedWorkerId:'worker-003',location:'Operations loading area',occurredAt:'2026-08-08T15:30:00.000Z',reportedAt:timestamp,immediateActions:['Area temporarily isolated','Cart inspected and removed from service'],medicalAttention:false,lostTime:false,modifiedWork:false,firstAidOnly:false,scenePreservationRequired:false,mlitsdReview:'not_required',mlitsdReviewNote:'Demo review only. No injury/fatality; confirm actual circumstances against current OHSA reporting duties.',committeeNoticeReview:'not_required',wsibReview:'not_required',wsibReviewNote:'Demo review only. No worker injury/illness requiring report.',investigationRequired:true,investigationStartedAt:timestamp,investigationTargetAt:'2026-08-22T17:00:00.000Z',createdAt:timestamp,updatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/safetyIncidents/${safetyIncident.id}`),safetyIncident,{merge:true});
  batch.set(db.doc(`organizations/${orgId}/safetyHazards/hazard-demo-001`),{id:'hazard-demo-001',referenceNumber:'HAZ-2026-00001',title:'Unsecured material cart on sloped loading surface',description:'DEMO DATA ONLY — Review cart parking/chocking controls and loading-area slope risk.',location:'Operations loading area',category:'material_handling',likelihood:3,consequence:4,riskScore:12,status:'open',reportedBy:uid,reportedWorkerId:'worker-003',linkedIncidentId:safetyIncident.id,existingControls:['Wheel brakes'],recommendedControls:['Inspect cart brakes','Review wheel chocking/parking control','Assess engineering control for sloped staging area'],ownerUid:'demo-ops-manager',dueAt:'2026-08-20T17:00:00.000Z',createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/safetyCorrectiveActions/safety-action-demo-001`),{id:'safety-action-demo-001',incidentId:safetyIncident.id,hazardId:'hazard-demo-001',title:'Verify material-cart parking controls',description:'Inspect brake condition and implement a more reliable parking/control method using the hierarchy of controls.',controlType:'engineering',ownerUid:'demo-ops-manager',dueAt:'2026-08-20T17:00:00.000Z',blockingClosure:true,status:'open',createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/safetyCommitteeProfiles/primary`),{id:'primary',workplaceName:'OPSIQO Demo Workplace',regularWorkerCount:25,governanceType:'jhsc',requirementSource:'DEMO Ontario reference review: most workplaces with 20+ regularly employed workers require a JHSC; confirm sector, designated-substance, project, and exemption rules.',reviewNote:'Demo configuration only; do not rely on this seed record for legal compliance.',meetingFrequency:'monthly',nextMeetingDate:'2026-09-10',updatedBy:uid,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/safetyInspections/inspection-demo-001`),{id:'inspection-demo-001',referenceNumber:'INSP-2026-00001',location:'Operations loading area',inspectionType:'workplace',scheduledFor:'2026-08-15T14:00:00.000Z',conductedByUids:[uid,'demo-ops-manager'],status:'scheduled',findingsCount:0,createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  const safetyWorkflow={id:'wf-safety-incident-reported',name:'Safety Incident Triage',description:'Route new safety incidents for immediate risk, reporting, investigation and corrective-action review without automating legal classification.',trigger:'safety.incident_reported',enabled:true,version:1,steps:[{id:'immediate-risk',name:'Review immediate safety controls and emergency response',type:'task',ownerRole:'hr_admin',dueInDays:0,escalationOwnerRole:'org_admin',escalateAfterHours:2,dependsOn:[]},{id:'reporting-review',name:'Confirm MLITSD/JHSC-HSR/WSIB reporting obligations',type:'task',ownerRole:'hr_admin',dueInDays:0,escalationOwnerRole:'org_admin',escalateAfterHours:4,dependsOn:['immediate-risk']},{id:'investigation',name:'Confirm investigation plan and assigned lead',type:'task',ownerRole:'hr_admin',dueInDays:1,escalationOwnerRole:'org_admin',escalateAfterHours:12,dependsOn:['reporting-review']}],createdAt:timestamp,updatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${safetyWorkflow.id}`),safetyWorkflow,{merge:true});
  batch.set(db.doc(`organizations/${orgId}/counters/safetyIncidents`),{value:1,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/counters/safetyHazards`),{value:1,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/counters/safetyInspections`),{value:1,updatedAt:timestamp},{merge:true});


  // Phase 3 v1.7 — Employee Experience & HR Service Center demo data.
  const pulseStart=new Date(Date.now()-2*86400_000).toISOString();
  const pulseEnd=new Date(Date.now()+12*86400_000).toISOString();
  batch.set(db.doc(`organizations/${orgId}/employeeSurveys/survey-demo-pulse`),{
    id:'survey-demo-pulse',code:'PULSE_2026_Q3',name:'Q3 Employee Experience Pulse',description:'DEMO DATA — short employee experience pulse.',purpose:'Measure recommendation, workload sustainability and manager support to identify organization-level improvement priorities.',privacyNotice:'Confidential responses are restricted to authorized survey administration and reported only after the configured aggregate threshold is met.',status:'published',responseMode:'confidential',audience:'all',anonymityThreshold:3,allowAnonymousText:false,resultsVisibleToEmployees:true,startsAt:pulseStart,endsAt:pulseEnd,eligibleCountAtPublish:3,questions:[{id:'recommend',type:'enps',prompt:'How likely are you to recommend this organization as a place to work?',required:true,driver:'advocacy'},{id:'workload',type:'likert5',prompt:'My workload is sustainable.',required:true,driver:'workload'},{id:'manager_support',type:'likert5',prompt:'I receive the support I need from my manager.',required:true,driver:'manager_support'}],createdBy:uid,createdAt:timestamp,updatedAt:timestamp,publishedBy:uid,publishedAt:timestamp
  },{merge:true});
  batch.set(db.doc(`organizations/${orgId}/employeeSurveys/survey-demo-closed`),{
    id:'survey-demo-closed',code:'EX_2026_Q2',name:'Q2 Experience Review',description:'DEMO DATA — closed confidential survey with threshold-released aggregate results.',purpose:'Review employee advocacy and workload trends.',privacyNotice:'Confidential responses are stored with restricted identity evidence and are reported in aggregate.',status:'closed',responseMode:'confidential',audience:'all',anonymityThreshold:3,allowAnonymousText:false,resultsVisibleToEmployees:true,startsAt:'2026-06-01T12:00:00.000Z',endsAt:'2026-06-14T21:00:00.000Z',eligibleCountAtPublish:3,questions:[{id:'recommend',type:'enps',prompt:'How likely are you to recommend this organization as a place to work?',required:true,driver:'advocacy'},{id:'workload',type:'likert5',prompt:'My workload is sustainable.',required:true,driver:'workload'}],createdBy:uid,createdAt:timestamp,updatedAt:timestamp,publishedBy:uid,publishedAt:timestamp,closedAt:'2026-06-14T21:00:00.000Z'
  },{merge:true});
  const surveyScores=[['worker-001',9,4],['worker-002',8,3],['worker-003',10,5]] as const;
  for(const [workerId,recommend,workload] of surveyScores){const rid=`survey-demo-response-${workerId}`;batch.set(db.doc(`organizations/${orgId}/surveyResponses/${rid}`),{id:rid,surveyId:'survey-demo-closed',respondentType:'confidential',workerId,submittedByUid:workerId==='worker-001'?uid:workerId==='worker-002'?'demo-hr-manager':'demo-ops-manager',answers:[{questionId:'recommend',numberValue:recommend},{questionId:'workload',numberValue:workload}],submittedAt:'2026-06-10T16:00:00.000Z'},{merge:true});const idx=createHash('sha256').update(`survey-demo-closed:${workerId}`).digest('hex');batch.set(db.doc(`organizations/${orgId}/surveyParticipationIndex/${idx}`),{surveyId:'survey-demo-closed',workerId,submittedAt:'2026-06-10T16:00:00.000Z'},{merge:true});}
  const serviceCatalog=[{id:'svc-letter',code:'EMPLOYMENT_LETTER',name:'Employment Letter',description:'Request a standard employment confirmation letter.',category:'employee_documents',enabled:true,defaultPriority:'normal',firstResponseHours:8,resolutionHours:48,requesterCanView:true},{id:'svc-payroll',code:'PAYROLL_QUESTION',name:'Payroll Question',description:'Ask HR/payroll about a pay statement or payroll process.',category:'payroll',enabled:true,defaultPriority:'high',firstResponseHours:4,resolutionHours:24,requesterCanView:true},{id:'svc-benefits',code:'BENEFITS_HELP',name:'Benefits Support',description:'Request help with benefits eligibility or enrollment.',category:'benefits',enabled:true,defaultPriority:'normal',firstResponseHours:8,resolutionHours:72,requesterCanView:true}];
  for(const c of serviceCatalog)batch.set(db.doc(`organizations/${orgId}/serviceCatalogItems/${c.id}`),{...c,createdAt:timestamp,updatedAt:timestamp,updatedBy:uid},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/hrServiceTickets/ticket-demo-open`),{id:'ticket-demo-open',referenceNumber:'HR-20260810-00001',requesterWorkerId:'worker-003',requesterUid:'demo-ops-manager',catalogItemId:'svc-benefits',category:'benefits',subject:'Benefits enrollment question',description:'DEMO DATA — employee requests clarification on the enrollment process.',priority:'normal',status:'assigned',confidentiality:'standard',assignedToUid:uid,firstResponseDueAt:new Date(Date.now()+4*3600_000).toISOString(),resolutionDueAt:new Date(Date.now()+48*3600_000).toISOString(),firstRespondedAt:timestamp,slaFirstResponseBreached:false,slaResolutionBreached:false,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/hrServiceTickets/ticket-demo-resolved`),{id:'ticket-demo-resolved',referenceNumber:'HR-20260801-00002',requesterWorkerId:'worker-002',requesterUid:'demo-hr-manager',catalogItemId:'svc-letter',category:'employee_documents',subject:'Employment confirmation letter',description:'DEMO DATA — standard employment-letter request.',priority:'normal',status:'resolved',confidentiality:'standard',assignedToUid:uid,firstResponseDueAt:'2026-08-01T18:00:00.000Z',resolutionDueAt:'2026-08-03T18:00:00.000Z',firstRespondedAt:'2026-08-01T15:00:00.000Z',resolvedAt:'2026-08-02T14:00:00.000Z',resolutionSummary:'DEMO DATA — confirmation letter prepared and provided through the governed document process.',slaFirstResponseBreached:false,slaResolutionBreached:false,createdAt:'2026-08-01T12:00:00.000Z',updatedAt:'2026-08-02T14:00:00.000Z'},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/serviceSatisfaction/ticket-demo-resolved`),{id:'ticket-demo-resolved',ticketId:'ticket-demo-resolved',requesterWorkerId:'worker-002',rating:5,comment:'DEMO DATA — quick and clear response.',createdAt:'2026-08-02T15:00:00.000Z'},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/knowledgeArticles/article-employment-letter`),{id:'article-employment-letter',slug:'request-employment-letter',title:'How to request an employment letter',summary:'Use the HR Service Center to request a standard employment confirmation letter.',body:'Open Employee Experience & HR Help, choose Employment Letter, describe any required recipient or purpose, and submit the request. HR will confirm whether additional information is needed.',category:'employee_documents',keywords:['employment','letter','verification'],status:'published',helpfulCount:0,notHelpfulCount:0,createdBy:uid,createdAt:timestamp,updatedBy:uid,updatedAt:timestamp,publishedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/recognitions/recognition-demo-001`),{id:'recognition-demo-001',senderWorkerId:'worker-002',recipientWorkerId:'worker-003',value:'Collaboration',message:'DEMO DATA — thanks for partnering across teams to resolve the onboarding handoff.',visibility:'organization',createdBy:'demo-hr-manager',createdAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/employeeIdeas/idea-demo-001`),{id:'idea-demo-001',title:'Monthly cross-team improvement huddle',description:'DEMO DATA — create a short monthly forum for employees to surface workflow blockers and improvement ideas.',category:'workplace_improvement',anonymous:true,status:'under_review',createdAt:timestamp,updatedAt:timestamp},{merge:true});
  const experienceWorkflow={id:'wf-service-sla-breach',name:'HR Service SLA Escalation',description:'Escalate configured HR Service Center response/resolution breaches without exposing ticket content outside authorized HR service roles.',trigger:'service.ticket_sla_breached',enabled:true,version:1,steps:[{id:'review',name:'Review service request and restore service level',type:'task',ownerRole:'hr_admin',dueInDays:0,escalationOwnerRole:'org_admin',escalateAfterHours:4,dependsOn:[]}],createdAt:timestamp,updatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${experienceWorkflow.id}`),experienceWorkflow,{merge:true});

  // Phase 4 v1.8 — Workforce Planning, People Analytics & Scenario Modelling demo data.
  const workforcePlanId='workforce-plan-2027';
  const workforceSnapshotId='workforce-snapshot-demo-2026-08-10';
  const workforceAssumptions={currency:'CAD',annualInflationPct:2,employerOnCostPct:15,vacancyCostPct:0,defaultSalaryGrowthPct:3,note:'DEMO planning assumptions only. Finance/HR must review actual on-cost, vacancy, compensation and budget assumptions before decision use.'};
  batch.set(db.doc(`organizations/${orgId}/workforcePlans/${workforcePlanId}`),{id:workforcePlanId,code:'WF_2027',name:'2027 Workforce Plan',description:'DEMO DATA — integrated workforce planning horizon.',planningStart:'2027-01-01',planningEnd:'2027-12-31',status:'active',assumptions:workforceAssumptions,createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/workforcePlanCodeIndex/WF_2027`),{planId:workforcePlanId,code:'WF_2027',createdAt:timestamp},{merge:true});
  const workforceBaseline={id:workforceSnapshotId,planId:workforcePlanId,snapshotDate:'2026-08-10',currency:'CAD',headcount:3,activeFte:3,occupiedPositions:3,vacantPositions:2,openRequisitions:1,annualBasePay:349000,estimatedEmployerCost:401350,verifiedSkillGaps:2,criticalPositions:2,uncoveredCriticalPositions:1,activeSeparations:0,sourceCounts:{workers:3,activeEmployments:3,activeAssignments:3,positions:5,positionOccupancy:5,requisitions:1,currentCompensation:3,separations:0,criticalPositions:2,positionSkillRequirements:4,skills:4,workerSkills:6},generatedBy:uid,generatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/workforceSnapshots/${workforceSnapshotId}`),workforceBaseline,{merge:true});
  const scenarioActions=[{id:'wf-action-growth-1',type:'hire',positionId:'pos-hrc',orgUnitId:'unit-people',headcountDelta:1,fteDelta:1,annualBasePayDelta:65000,effectiveDate:'2027-03-01',rationale:'DEMO assumption — fill approved HR Coordinator capacity to support service growth.'},{id:'wf-action-growth-2',type:'hire',positionId:'pos-hrd',orgUnitId:'unit-people',headcountDelta:1,fteDelta:1,annualBasePayDelta:115000,effectiveDate:'2027-07-01',rationale:'DEMO assumption — add HR leadership capacity if growth milestones are confirmed.'}];
  const projectedBasePay=529000,projectedCost=Math.round(projectedBasePay*1.15*100)/100;
  batch.set(db.doc(`organizations/${orgId}/workforceScenarios/scenario-demo-growth`),{id:'scenario-demo-growth',planId:workforcePlanId,name:'Service Growth Scenario',type:'growth',description:'DEMO DATA — model two planned hires against current capacity and compensation assumptions.',status:'modelled',baselineSnapshotId:workforceSnapshotId,assumptions:workforceAssumptions,actions:scenarioActions,projection:{headcount:5,activeFte:5,occupiedPositions:5,vacantPositions:0,annualBasePay:projectedBasePay,estimatedEmployerCost:projectedCost,netHeadcountChange:2,netFteChange:2,netAnnualBasePayChange:180000,netEmployerCostChange:projectedCost-401350},budgetLimit:620000,budgetVariance:projectedCost-620000,createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/workforceDemand/demand-demo-hr`),{id:'demand-demo-hr',planId:workforcePlanId,positionId:'pos-hrc',orgUnitId:'unit-people',title:'People & Culture service capacity',targetHeadcount:1,targetFte:1,targetDate:'2027-03-01',priority:'high',status:'approved',rationale:'DEMO DATA — approved demand based on planned employee-service and compliance workload growth.',requiredSkillIds:['skill-people-analytics'],createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
  const workforceWorkflow={id:'wf-workforce-scenario-approved',name:'Approved Workforce Scenario Handoff',description:'Route an approved workforce scenario to HR/Finance operating-plan review without executing employment changes automatically.',trigger:'workforce.scenario_approved',enabled:true,version:1,steps:[{id:'finance-review',name:'Confirm workforce cost and budget assumptions',type:'approval',ownerRole:'org_admin',dueInDays:5,escalationOwnerRole:'super_admin',escalateAfterHours:48,dependsOn:[]},{id:'execution-plan',name:'Translate approved scenario into governed workforce actions',type:'task',ownerRole:'hr_admin',dueInDays:10,escalationOwnerRole:'org_admin',escalateAfterHours:48,dependsOn:['finance-review']}],createdAt:timestamp,updatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${workforceWorkflow.id}`),workforceWorkflow,{merge:true});

  // Phase 4 v1.9 governed People Analytics demo data.
  for(const base of STANDARD_ANALYTICS_METRICS){
    const metricId=createHash('sha256').update(base.code).digest('hex').slice(0,32);
    const indexId=createHash('sha256').update(base.code).digest('hex');
    batch.set(db.doc(`organizations/${orgId}/analyticsMetrics/${metricId}`),{...base,id:metricId,status:'active',createdBy:uid,createdAt:timestamp,updatedAt:timestamp},{merge:true});
    batch.set(db.doc(`organizations/${orgId}/analyticsMetricCodeIndex/${indexId}`),{metricId,code:base.code,createdAt:timestamp},{merge:true});
  }
  const history=[
    ['2025-09-30',2,2,220000,1,1,0],['2025-10-31',2,2,220000,1,1,0],['2025-11-30',2,2,225000,1,1,0],['2025-12-31',2,2,225000,1,1,0],
    ['2026-01-31',2,2,228000,1,1,0],['2026-02-28',2,2,228000,1,1,0],['2026-03-31',2,2,232000,1,1,0],['2026-04-30',3,3,349000,1,2,0],
    ['2026-05-31',3,3,349000,1,2,0],['2026-06-30',3,3,349000,1,2,0],['2026-07-31',3,3,349000,1,2,0],['2026-08-10',3,3,349000,1,2,0],
  ] as const;
  for(const [date,headcount,fte,basePay,vacancies,skillGaps,sepsYtd] of history){
    const employerCost=Math.round(basePay*1.15*100)/100;
    const metrics={
      'workforce.headcount':headcount,'workforce.fte':fte,'workforce.vacancies':vacancies,'workforce.base_pay':basePay,'workforce.employer_cost':employerCost,
      'recruiting.open_requisitions':vacancies,'talent.verified_skill_gaps':skillGaps,'succession.uncovered_critical_positions':1,'lifecycle.active_separations':0,
      'lifecycle.separations_ytd':sepsYtd,'lifecycle.turnover_ytd_pct':sepsYtd?Math.round(sepsYtd/(headcount+sepsYtd)*10000)/100:0,
      'service.open_tickets':date>='2026-06-01'?1:0,'safety.open_incidents':0,'performance.open_reviews':date>='2026-07-01'?3:0,'learning.overdue_assignments':0,'experience.active_surveys':date>='2026-07-01'?1:0,
    };
    batch.set(db.doc(`organizations/${orgId}/analyticsSnapshots/daily_${date}`),{id:`daily_${date}`,snapshotDate:date,period:'daily',currency:'CAD',metricVersion:1,metrics,segments:[{dimensionType:'org_unit',dimensionId:'unit-people',label:'People & Culture',population:1,suppressed:true,metrics:{}},{dimensionType:'org_unit',dimensionId:'unit-operations',label:'Operations',population:1,suppressed:true,metrics:{}}],sourceCounts:{workers:headcount,activeAssignments:headcount,positions:3},generatedBy:'seed:synthetic-demo',generatedAt:timestamp,methodologyNotice:'DEMO SYNTHETIC HISTORY — supplied only to exercise v1.9 trend and forecast controls. Never treat this seeded history as production workforce evidence.'},{merge:true});
  }
  const forecastModelCode='HC_LINEAR_DEMO',forecastModelId='forecast-model-hc-demo';
  batch.set(db.doc(`organizations/${orgId}/analyticsForecastModels/${forecastModelId}`),{id:forecastModelId,code:forecastModelCode,name:'Demo headcount linear trend',metricCode:'workforce.headcount',modelType:'linear_trend',horizonPeriods:6,confidenceLevel:0.95,minimumHistoryPoints:6,assumptions:'DEMO ONLY — exploratory aggregate linear trend based on monthly OPSIQO snapshots. Business plans, structural changes, seasonality and external conditions are not automatically modelled.',version:1,status:'active',createdBy:uid,createdAt:timestamp,updatedAt:timestamp,approvedBy:uid,approvedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/analyticsForecastModelCodeIndex/${createHash('sha256').update(forecastModelCode).digest('hex')}`),{modelId:forecastModelId,code:forecastModelCode,createdAt:timestamp},{merge:true});
  const analyticsWorkflow={id:'wf-analytics-forecast-approved',name:'Approved People Forecast Review',description:'Route an approved aggregate people forecast into executive planning review without executing workforce actions.',trigger:'analytics.forecast_approved',enabled:true,version:1,steps:[{id:'planning-review',name:'Review forecast assumptions against business plan',type:'task',ownerRole:'hr_admin',dueInDays:5,escalationOwnerRole:'org_admin',escalateAfterHours:48,dependsOn:[]}],createdAt:timestamp,updatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${analyticsWorkflow.id}`),analyticsWorkflow,{merge:true});


  // Phase 4 v2.0 AI HR Copilot governance demo records.
  const aiPromptId='ai-prompt-hr-copilot-v1';
  batch.set(db.doc(`organizations/${orgId}/aiPromptTemplates/${aiPromptId}`),{id:aiPromptId,code:'HR_COPILOT',name:'HR Copilot evidence-first system prompt',version:1,status:'active',systemInstruction:'You are OPSIQO HR Copilot. Answer only from supplied OPSIQO evidence. Cite evidence IDs for material claims. Distinguish facts, forecasts, assumptions and recommendations. Never make or recommend an individual hiring, firing, promotion, compensation, discipline, accommodation, leave-eligibility, or succession decision. Suggest only investigation, review, analysis, communication, planning or monitoring actions. State limitations and data-quality concerns. Consequential decisions require authorized human review.',prohibitedUses:['Autonomous consequential employment decisions','Protected-characteristic inference','Invented evidence or citations'],createdBy:uid,createdAt:timestamp,updatedAt:timestamp,activatedBy:uid,activatedAt:timestamp},{merge:true});
  batch.set(db.doc(`organizations/${orgId}/aiModelProfiles/ai-model-demo-v1`),{id:'ai-model-demo-v1',code:'HR_COPILOT_MODEL',provider:'demo',model:'opsiqo-evidence-demo-v1',purpose:'Demo evidence-grounded HR Copilot model profile for local validation without a remote provider.',dataHandlingNote:'No remote provider call is made by the demo adapter.',version:1,status:'active',createdBy:uid,createdAt:timestamp,updatedAt:timestamp,approvedBy:uid,approvedAt:timestamp},{merge:true});
  const aiWorkflow={id:'wf-ai-action-plan-approved',name:'AI Recommendation Human Action Plan',description:'Route a human-approved AI recommendation into governed work without granting the model direct execution authority.',trigger:'ai.action_plan_approved',enabled:true,version:1,steps:[{id:'evidence-review',name:'Verify cited OPSIQO evidence and action scope',type:'approval',ownerRole:'hr_admin',dueInDays:3,escalationOwnerRole:'org_admin',escalateAfterHours:24,dependsOn:[]},{id:'execute-plan',name:'Execute approved non-consequential action plan',type:'task',ownerRole:'hr_admin',dueInDays:10,escalationOwnerRole:'org_admin',escalateAfterHours:48,dependsOn:['evidence-review']}],createdAt:timestamp,updatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${aiWorkflow.id}`),aiWorkflow,{merge:true});
  const diagnosticWorkflow={id:'wf-diagnostic-finding-created',name:'HR Diagnostic Gap Remediation',description:'Route a newly evidenced HR diagnostic gap to human remediation planning.',trigger:'diagnostic.finding_created',enabled:true,version:1,steps:[{id:'diagnostic-review',name:'Review diagnostic evidence and applicability',type:'approval',ownerRole:'hr_admin',dueInDays:5,escalationOwnerRole:'org_admin',escalateAfterHours:48,dependsOn:[]},{id:'remediation-plan',name:'Create governed remediation plan',type:'task',ownerRole:'hr_partner',dueInDays:10,escalationOwnerRole:'hr_admin',escalateAfterHours:48,dependsOn:['diagnostic-review']}],createdAt:timestamp,updatedAt:timestamp};
  batch.set(db.doc(`organizations/${orgId}/workflowDefinitions/${diagnosticWorkflow.id}`),diagnosticWorkflow,{merge:true});

  await batch.commit();

  // Phase 4 v2.1 HR Diagnostic demo: bootstrap the governed Ontario reference pack and a reusable in-progress evidence snapshot.
  const diagnosticActor={uid,orgId,role:'org_admin' as const,workerId:'worker-001',permissions:permissionsForRole('org_admin'),demo:true};
  await bootstrapOntarioDiagnostic(diagnosticActor);
  let diagnostic=await diagnosticDashboard(diagnosticActor);
  let demoAssessment=diagnostic.assessments.find(a=>a.name==='DEMO · 2026 HR Governance Diagnostic');
  if(!demoAssessment){
    const framework=diagnostic.frameworks.find(f=>f.status==='active');
    if(framework){
      demoAssessment=await createDiagnosticAssessment(diagnosticActor,{frameworkId:framework.id,name:'DEMO · 2026 HR Governance Diagnostic',scopeNote:'DEMO DATA — organization-wide HR maturity and Ontario compliance-reference evidence review.',profile:{jurisdiction:'Ontario, Canada',currentEmployeeCount:25,ontarioEmployeesJan1:25,organizationType:'business',isProvinciallyRegulated:true,isPublicSector:false,notes:'DEMO applicability facts only; legal applicability requires qualified review.'}});
      diagnostic=await diagnosticDashboard(diagnosticActor);
      const controlsByCode=new Map(diagnostic.controls.map(c=>[c.code,c]));
      const assessments=[
        ['GOV-001','met','Governance responsibility matrix approved by leadership.'],
        ['GOV-002','partially_met','Core policy lifecycle exists; annual review completion evidence requires consolidation.'],
        ['ON-OHSA-WVH-001','met','Current workplace violence/harassment policies and annual review evidence available.'],
        ['ON-OHSA-WVH-003','partially_met','Program exists; worker instruction evidence is incomplete for one cohort.'],
        ['ON-ESA-EM-001','not_met','Demo employer meets the January 1 threshold but no current electronic-monitoring policy evidence is linked.'],
        ['ON-PAYEQ-001','partially_met','Applicability screening indicates review is required; job-class maintenance evidence remains incomplete.'],
        ['SEC-001','met','Server-side RBAC and audit logging are enabled.'],
        ['INT-001','partially_met','Diagnostic capability is live; repeat reassessment evidence has not yet accumulated.'],
      ] as const;
      for(const [code,status,note] of assessments){const c=controlsByCode.get(code);if(!c)continue;await assessDiagnosticControl(diagnosticActor,demoAssessment.id,c.id,{applicability:'applicable',status,evidenceRefs:status==='not_met'?[]:[{sourceType:'external_reference',sourceId:`demo-${code.toLowerCase()}`,label:`DEMO evidence for ${code}`,note:'Synthetic demo evidence used only to exercise diagnostic workflow.'}],assessorNote:note});}
    }
  }
  console.log(`Seeded OPSIQO HCM Phase 4 HR Diagnostic & Compliance Intelligence v2.1: ${orgId}`);
}

seed().catch((error) => { console.error(error); process.exit(1); });
