import { z } from 'zod';
const id=z.string().trim().min(1).max(160), money=z.number().finite().min(0).max(100_000_000), date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
export const jobFamilySchema=z.object({code:z.string().trim().min(2).max(30).transform(v=>v.toUpperCase()),name:z.string().trim().min(2).max(140),description:z.string().trim().max(2000).optional(),status:z.enum(['active','inactive']).default('active')});
export const jobLevelSchema=z.object({code:z.string().trim().min(1).max(30).transform(v=>v.toUpperCase()),name:z.string().trim().min(1).max(120),rank:z.number().int().min(1).max(100),description:z.string().trim().max(2000).optional(),status:z.enum(['active','inactive']).default('active')});
export const salaryBandSchema=z.object({code:z.string().trim().min(2).max(40).transform(v=>v.toUpperCase()),name:z.string().trim().min(2).max(140),jobFamilyId:id.optional(),levelId:id.optional(),currency:z.string().trim().length(3).transform(v=>v.toUpperCase()),payBasis:z.enum(['annual_salary','hourly']).default('annual_salary'),min:money,midpoint:money,max:money,location:z.string().trim().max(140).optional(),effectiveDate:date,status:z.enum(['active','inactive']).default('active')}).refine(v=>v.min<=v.midpoint&&v.midpoint<=v.max,{message:'Salary band must satisfy minimum ≤ midpoint ≤ maximum.'});
export const positionCompProfileSchema=z.object({positionId:id,jobFamilyId:id.optional(),levelId:id.optional(),salaryBandId:id.optional(),marketBenchmarkId:id.optional(),exemptionNote:z.string().trim().max(2000).optional()});
export const workerCompensationSchema=z.object({workerId:id,effectiveDate:date,currency:z.string().trim().length(3).transform(v=>v.toUpperCase()),payBasis:z.enum(['annual_salary','hourly']).default('annual_salary'),basePay:money,annualizedBasePay:money.optional(),variableTargetPct:z.number().min(0).max(500).default(0),allowancesAnnual:money.default(0),changeReason:z.enum(['hire','merit','promotion','market','equity','adjustment','demotion','other']),note:z.string().trim().max(2000).optional()});
export const benchmarkSchema=z.object({code:z.string().trim().min(2).max(50).transform(v=>v.toUpperCase()),title:z.string().trim().min(2).max(180),source:z.string().trim().min(2).max(300),sourceDate:date,currency:z.string().trim().length(3).transform(v=>v.toUpperCase()),location:z.string().trim().max(140).optional(),jobFamilyId:id.optional(),levelId:id.optional(),positionId:id.optional(),p25:money,p50:money,p75:money,p90:money.optional(),note:z.string().trim().max(2000).optional()}).refine(v=>v.p25<=v.p50&&v.p50<=v.p75&&(!v.p90||v.p75<=v.p90),{message:'Market percentiles must be ordered P25 ≤ P50 ≤ P75 ≤ P90.'});
export const compensationCycleSchema=z.object({name:z.string().trim().min(3).max(180),cycleYear:z.number().int().min(2000).max(2200),effectiveDate:date,currency:z.string().trim().length(3).transform(v=>v.toUpperCase()),budgetPct:z.number().min(0).max(100).optional(),budgetAmount:money.optional(),eligibilityNote:z.string().trim().max(2000).optional()});
export const recommendationSchema=z.object({cycleId:id,workerId:id,type:z.enum(['merit','promotion','market','equity','lump_sum','other']),proposedIncreasePct:z.number().min(0).max(100).default(0),lumpSumAmount:money.default(0),rationale:z.string().trim().min(10).max(3000),evidenceRefs:z.array(z.string().trim().min(1).max(300)).max(20).default([])});
export const recommendationActionSchema=z.object({action:z.enum(['submit','approve','reject','apply']),decisionNote:z.string().trim().max(2000).optional()});
export const cycleActionSchema=z.object({action:z.enum(['open','send_to_hr','approve','apply','close','cancel']),decisionNote:z.string().trim().max(2000).optional()});
export const rewardsInputSchema=z.object({workerId:id,asOfDate:date,employerBenefitsValue:money.default(0),employerRetirementValue:money.default(0),otherRewardsValue:money.default(0)});
export const payEquityJobClassSchema=z.object({code:z.string().trim().min(2).max(50).transform(v=>v.toUpperCase()),name:z.string().trim().min(2).max(180),establishmentId:z.string().trim().min(1).max(160),bargainingUnit:z.string().trim().max(160).optional(),genderPredominance:z.enum(['female','male','neutral','unknown']),jobRate:money,currency:z.string().trim().length(3).transform(v=>v.toUpperCase()),skillPoints:z.number().min(0).max(10000),effortPoints:z.number().min(0).max(10000),responsibilityPoints:z.number().min(0).max(10000),workingConditionsPoints:z.number().min(0).max(10000),comparatorMethod:z.enum(['job_to_job','proportional_value','proxy','not_assessed']).default('not_assessed'),comparatorJobClassIds:z.array(id).max(25).default([]),reviewStatus:z.enum(['draft','review_required','reviewed','action_required','closed']).default('draft'),legalBasisNote:z.string().trim().max(4000).optional()});

export const payTransparencyPolicySchema=z.object({jurisdiction:z.string().trim().min(2).max(30),effectiveDate:date,employerEmployeeThreshold:z.number().int().min(0).max(100000),rangeMaxSpreadAnnual:money,exceptionAboveAnnual:money,postingRetentionYears:z.number().int().min(1).max(20),interviewDecisionNoticeDays:z.number().int().min(1).max(365),enabled:z.boolean()});
export const requisitionDisclosureSchema=z.object({requisitionId:id,publiclyAdvertised:z.boolean().default(false),currency:z.string().trim().length(3).transform(v=>v.toUpperCase()),expectedMin:money,expectedMax:money,annualized:z.boolean().default(true),vacancyExists:z.enum(['yes','no','unknown']).default('unknown'),aiUsedInScreening:z.boolean().default(false),aiDisclosureText:z.string().trim().max(1000).optional()}).refine(v=>v.expectedMin<=v.expectedMax,{message:'Expected compensation minimum cannot exceed maximum.'});

export const letterActionSchema=z.object({action:z.literal('release')});
export const compensationFxRateSchema=z.object({fromCurrency:z.string().trim().length(3).transform(v=>v.toUpperCase()),toCurrency:z.string().trim().length(3).transform(v=>v.toUpperCase()),rate:z.number().finite().positive().max(1000000),asOfDate:date,source:z.string().trim().min(3).max(300),sourceReference:z.string().trim().min(3).max(500),methodologyNote:z.string().trim().min(3).max(2000)});
export const benchmarkProvenanceSchema=z.object({benchmarkId:id,sourceReference:z.string().trim().min(3).max(500),sourceRetrievedAt:date,methodology:z.string().trim().min(3).max(2000),sampleSize:z.number().int().min(1).max(10000000).optional(),currencyBasis:z.string().trim().min(3).max(300),geographyBasis:z.string().trim().min(2).max(300),evidenceRefs:z.array(z.string().trim().min(1).max(300)).max(20).default([])});
export const compensationCorrectionSchema=z.object({workerId:id,effectiveDate:date,currency:z.string().trim().length(3).transform(v=>v.toUpperCase()),payBasis:z.enum(['annual_salary','hourly']),basePay:money,annualizedBasePay:money,variableTargetPct:z.number().min(0).max(500).default(0),allowancesAnnual:money.default(0),reason:z.string().trim().min(10).max(3000),evidenceRefs:z.array(z.string().trim().min(1).max(300)).max(20).default([]),fxRateId:id.optional(),retroPayAmount:money.default(0),retroPayDate:date.optional()}).refine(v=>v.retroPayAmount===0||Boolean(v.retroPayDate),{message:'Retro pay requires a target pay date.'});
export const compensationCorrectionActionSchema=z.object({action:z.enum(['approve','reject']),note:z.string().trim().max(2000).optional()});
export const letterSupersedeSchema=z.object({reason:z.string().trim().min(10).max(2000)});
