import { z } from 'zod';
const isoDate=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
export const assumptionsSchema=z.object({currency:z.string().length(3).default('CAD'),annualInflationPct:z.number().min(-20).max(100).default(2),employerOnCostPct:z.number().min(0).max(200).default(15),vacancyCostPct:z.number().min(0).max(200).default(0),defaultSalaryGrowthPct:z.number().min(-20).max(100).default(3),note:z.string().min(10).max(5000)});
export const workforcePlanSchema=z.object({code:z.string().regex(/^[A-Z0-9_-]{2,40}$/),name:z.string().min(3).max(180),description:z.string().max(4000).optional(),planningStart:isoDate,planningEnd:isoDate,assumptions:assumptionsSchema}).refine(v=>v.planningEnd>=v.planningStart,{message:'Planning end must be on or after planning start.'});
export const workforcePlanActionSchema=z.object({action:z.enum(['activate','approve','archive'])});
const action=z.object({id:z.string().min(1).max(80).optional(),type:z.enum(['hire','remove_position','vacancy_fill','planned_exit','transfer_in','transfer_out','compensation_adjustment']),positionId:z.string().optional(),orgUnitId:z.string().optional(),headcountDelta:z.number().int().min(-100000).max(100000).default(0),fteDelta:z.number().min(-100000).max(100000).default(0),annualBasePayDelta:z.number().min(-1_000_000_000).max(1_000_000_000).default(0),effectiveDate:isoDate,rationale:z.string().min(5).max(4000)}).superRefine((v,ctx)=>{if(v.headcountDelta===0&&v.fteDelta===0&&v.annualBasePayDelta===0)ctx.addIssue({code:'custom',message:'Scenario action must change headcount, FTE, or annual base pay.'});const reductions=['planned_exit','remove_position','transfer_out'];const growth=['hire','vacancy_fill','transfer_in'];if(reductions.includes(v.type)&&(v.headcountDelta>0||v.fteDelta>0))ctx.addIssue({code:'custom',message:'Reduction/transfer-out actions cannot increase headcount or FTE.'});if(growth.includes(v.type)&&(v.headcountDelta<0||v.fteDelta<0))ctx.addIssue({code:'custom',message:'Hire/fill/transfer-in actions cannot reduce headcount or FTE.'});if(v.type==='compensation_adjustment'&&(v.headcountDelta!==0||v.fteDelta!==0))ctx.addIssue({code:'custom',message:'Compensation-adjustment actions may change pay cost only.'});});
export const workforceScenarioSchema=z.object({planId:z.string().min(1),name:z.string().min(3).max(180),type:z.enum(['baseline','growth','reduction','restructure','budget']),description:z.string().max(4000).optional(),actions:z.array(action).max(250).default([]),budgetLimit:z.number().nonnegative().optional()});
export const workforceScenarioActionSchema=z.object({action:z.enum(['model','approve','archive']),actions:z.array(action).max(250).optional(),budgetLimit:z.number().nonnegative().optional()});
export const workforceDemandSchema=z.object({planId:z.string().min(1),positionId:z.string().optional(),orgUnitId:z.string().optional(),title:z.string().min(3).max(180),targetHeadcount:z.number().int().min(0).max(100000),targetFte:z.number().min(0).max(100000),targetDate:isoDate,priority:z.enum(['low','normal','high','critical']).default('normal'),status:z.enum(['planned','approved','fulfilled','cancelled']).default('planned'),rationale:z.string().min(10).max(5000),requiredSkillIds:z.array(z.string().min(1)).max(100).default([])}).refine(v=>v.targetHeadcount>0||v.targetFte>0,{message:'Demand must include target headcount or FTE.'});

export const workforceDemandActionSchema=z.object({action:z.enum(['approve','fulfill','cancel'])});
